### ISSUE TITLE
Builds on iOS9, but not on iOS10/11 (arm64)

### ISSUE THREAD

**Issue by jet082** [libretro/libretro-uae#100]
See title.

Errors are:

```
sources/src/main.c:981:2: error: implicit declaration of function 'pause_select' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
2 warnings and 1 error generated.
make: *** [sources/src/main.o] Error 1

```

**Comment by rsn8887** [comment]
-Werror should probably be disabled in the Makefile I can try it later.

**Comment by rsn8887** [comment]
By the way it is not enough to test that it build you also have to check that it actually works because the cpu emulation relies on some pointer arithmetic that might break on 64bit iOS, not sure.

**Comment by jet082** [comment]
Currently, I am just running ``libretro-build-ios-arm64.sh puae`` in libretro-super. If I run ``libretro-build-ios9.sh puae`` it works, however (but this is not useable in the iOS10+ retroarch).

**Comment by rsn8887** [comment]
I could reproduce this locally and think I fixed this via https://github.com/libretro/libretro-uae/commit/1c7996958d5db669094c83f2a4b9a5b928ebcb4d

**Comment by jet082** [comment]
I can confirm this compiles now!
