### ISSUE TITLE
Android IPF support

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#102]
I noticed that the emulator UAE4Arm has IPF support. It's not a single library file though. Could this be made to work for this core ?

https://github.com/lubomyr/uae4arm/tree/master/plugins/capsimage

**Comment by rsn8887** [comment]
Yup this works! Thanks!

I compiled these .so files, and made a zip archive that includes the compiled Android capsimg files.

The zip archive is here:
https://github.com/rsn8887/capsimg/releases/latest

I tested by loading Giana Sisters ipf on my Nvidia Shield Portable running Android Kitkat, using the armeabi-v7a version of capsimg.so from my archive. I just copied it to my Retroarch/system folder.

**Comment by MajorWilly** [comment]
Awesome !
