### ISSUE TITLE
Bug if show_leds is set to false

### ISSUE THREAD

**Issue by DamsRoxxx** [libretro/libretro-uae#105]
If show_leds parameter is set to false or not specified (default false) some games hang at a moment or another.

For example Rick Dangerous 2 (adf or whd version) hang when selecting level.

**Comment by sonninnos** [comment]
This is fixed soon, because the row omission is only possible with custom configs, and in the new PR that is no longer possible.

The show_leds was left as a FIXME state in the code and it is merely forced in at the config autogeneration. It should've been forced elsewhere to begin with.
