### ISSUE TITLE
Minor Status line issue & centering issue

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#110]
Nothing major, I just thought i'd report it. I loaded up the game Dynablaster and had the status bar on. It looks like the screen changes resolution or goes into NTSC and this happened, double status bar -

![Screenshot_2019-09-05-23-11-05](https://user-images.githubusercontent.com/52862903/64387433-dfe8db80-d033-11e9-9c95-20e46a8208b9.png)

Also, with the game Banshee it has trouble centering the screen -

![Screenshot_2019-09-05-23-14-58](https://user-images.githubusercontent.com/52862903/64387485-060e7b80-d034-11e9-9de9-db9d915d2b86.png)

**Comment by sonninnos** [comment]
Indeed the statusbar does not redraw properly when PAL switches to NTSC and the statusbar is at the bottom. There is a version of Dyna Blaster which stays at PAL though.

Do the centering core options do anything with Banshee?

**Comment by MajorWilly** [comment]
Yeah, it's weird. I've never noticed a PAL game change to NTSC in game. I remember the music being this speed back in the day on a real Amiga, I think PAL would sound too slow. No biggie. Just don't use the status bar on this game !

Regarding Banshee, I tried simple, smart and off but it looked the same as above on all (in game). Is there a manual x,y offset that could be put in the Quickmenu or something similar ?

**Comment by sonninnos** [comment]
Hmm, WinUAE does the same thing but only with gfx_center_horizontal=smart..

There exists a gfx_center_horizontal_position, so looks like it can be finetuned.

**Comment by MajorWilly** [comment]
Instead of opening another issue, i'll quickly ask here. I've tried about 30 games and actually found 1 that doesn't work! `Skidmarks`. I've tried the ADF, IPF and WHDLoad versions but it just doesn't do anything when you click the Skidmarks icon. It works in WinUAE even with basic settings. Do you guys have any ideas why it doesn't work ?

**Comment by rsn8887** [comment]
I just tried Banshee with both centering options = OFF and it works for me. If I use centering Inalso get the shifted screen. Maybe you forgot to restart the core after changing the centering option?

Here’s a screenshot with centering OFF (WHDLoad version):
[![2019090707255500-D0-B9-AC9357-A3561-F8-D041-C64209-A70-F0.jpg](https://i.postimg.cc/g04vSGtH/2019090707255500-D0-B9-AC9357-A3561-F8-D041-C64209-A70-F0.jpg)](https://postimg.cc/kV66DPm2)

**Comment by MajorWilly** [comment]
So I tried lots of options and finally figured it out. For some reason I had the option 'Crop Overscan' ON. I had to turn this OFF and also turn off 'Horizontal Centering'. It now displays correctly.

I find the emulation compatibility on this core to be much better than UAE4Arm and Amiberry. I've yet to find something that doesn't work. Has anyone else found anything that doesn't work ?

I can live with the Dynablaster statusbar glitch. I just won't have the statusbar on in this game.

**Comment by rsn8887** [comment]
I found something that doesn’t work it seems:
Second Samurai

But that’s a bit unfair because almost no emulator can play that game correctly.

Btw I added a 24 bit color mode today. It can improve some AGA color gradients. It might not be supported on all platforms.

Example using WBVerlauf tool in A1200 Workbench:
Using default setting “16bit”:
[![2019090710103600-d0b9ac9357a3561f8d041c64209a70f0.jpg](https://i.postimg.cc/ZKVtNgx1/2019090710103600-d0b9ac9357a3561f8d041c64209a70f0.jpg)](https://postimg.cc/VdrVQKTR)

Using new setting “24bit”:
[![2019090711015300-d0b9ac9357a3561f8d041c64209a70f0.jpg](https://i.postimg.cc/kXML7sPw/2019090711015300-d0b9ac9357a3561f8d041c64209a70f0.jpg)](https://postimg.cc/yW5LPFdS)

The effect is quite subtle but the WBVerlauf color gradient is smoother using 24 bit colors.

**Comment by MajorWilly** [comment]
The OCS/ECS version of Second Samurai works (I tried the ADF version). It has a flickering menu screen but can be fixed with Cycle Exact, although the actual game works fine without Cycle Exact. I only had a quick go, great game. I haven't tried the AGA version.

**Comment by MajorWilly** [comment]
@rsn8887 The OCS/ECS version of Second Samurai works (I tried the ADF version). It has a flickering menu screen but can be fixed with Cycle Exact, although the actual game works fine without Cycle Exact. I only had a quick go, great game.

I tried Second Samurai AGA on WinUAE and it only works with Cycle Exact and 2MB Chip only. @sonninnos Is there any chance we could have another preset of an Unexpanded A1200 (2mb Chip, no Fast) ?

**Comment by sonninnos** [comment]
> I tried Second Samurai AGA on WinUAE (ADF version) and it only works with Cycle Exact and 2MB Chip only. @sonninnos Is there any chance we could have another preset of an Unexpanded A1200 (2mb Chip, no Fast) ?

Sure it can be added easily. The WHDLoad version works on WinUAE with Fast though.

**Comment by MajorWilly** [comment]
@sonninnos  If you do decide to add a Unexpanded A1200 preset would it be best to use a 3.0 ROM ? I was looking through the WinUAE presets and the only A1200 one that uses a 3.1 ROM is for Blizzard PPC. I guess 3.1 is only for graphics cards and OS3.5+ (WHDLoad etc.) ?

**Comment by sonninnos** [comment]
I've always used 3.1 with WinUAE, and remembering what happened last time I had my way with the kickstarts I hope it isn't necessary.

But looks like setting fastmem_size=0 does not help with this core. Maybe because even with value 0 it does not say 0 in WB etc..

**Comment by MajorWilly** [comment]
I just tried the IPF of Second Samurai AGA (with Fast mem) and WinUAE crashed at the Loading screen after inserting Disk 2. Not sure how you ran it ?

**Comment by sonninnos** [comment]
Oh okay, I didn't go that far because it always meditated before that with this core. But indeed the whole emulator crashes after disk 2..

**Comment by MajorWilly** [comment]
So fast memory cannot be disabled on A1200 with this core ? Not much use for a preset :-) Oh well.

**Comment by sonninnos** [comment]
Fast can be disabled, and the bogo which is lurking, but it won't do any good in this case, because it meditates before getting to the disk change.

**Comment by MajorWilly** [comment]
3.1 and 3.0 work for this game in WinUAE.

**Comment by MajorWilly** [comment]
> Fast can be disabled, and the bogo which is lurking, but it won't do any good in this case, because it meditates before getting to the disk change.
> 
Do you have Cycle Exact On in PUAE ? This game needs it.

**Comment by sonninnos** [comment]
Aarrg, I thought I did, but I had it disabled for some testing reason.

With setting fastmem_size=0 AND bogomem_size=0 this is the result:
![retroarch_2019_09_08_17_23_32_890](https://user-images.githubusercontent.com/45124675/64489564-8237d780-d25d-11e9-8a2d-63a70514e2f8.png)

**Comment by rsn8887** [comment]
Awesome! Thanks for getting Second Samurai to work! I had almost given up on the game.
