### ISSUE TITLE
Filename question

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#111]
Some ADF games I have from the Gamebase set have `(OCS & AGA)` in the filename.
e.g. `Seek & Destroy (OCS & AGA) (MD).m3u`
 I assume this will not be detected as a model preset and it will just use what is set in the QuickMenu ?

If I renamed it to -
`Seek & Destroy (OCS) (AGA) (MD).m3u`
which preset will it set ? OCS ?

**Comment by sonninnos** [comment]
Look at the verbose log and it will tell.

But if it works on either one then just pick either one.

**Comment by MajorWilly** [comment]
I'll rename the games that say `(OCS & AGA)`. Just wondered which one would take priority if there were two in the filename.

**Comment by sonninnos** [comment]
At the moment the order is: 
A500+/A500PLUS, A500OG/512K, A500/OCS, A600/ECS, A1200/AGA, default
