### ISSUE TITLE
Crop overscan + statusbar at bottom = no statusbar

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#117]
If you have 'Crop Overscan' ON and the statusbar at the bottom then you can no longer see the statusbar. It's OK at the top though.

NTSC screen is also cut off at the bottom. (Tested with Dynablaster). Is it stretching the screen and not centering ?

**Comment by sonninnos** [comment]
I'm voting for removing the whole crop option, because it brings so much misery and needs more and more exceptions on top of heap of exceptions..

**Comment by DamsRoxxx** [comment]
> I'm voting for removing the whole crop option, because it brings so much misery and needs more and more exceptions on top of heap of exceptions..

Some peoples claimed for it on the forum last year for rendering their games "fullscreen". Now that there is a zoom option maybe it isn't necessary anymore.

Never have been fond of it...

**Comment by sonninnos** [comment]
Plus zoomings can be done in RA and/or shaders.

But I'll see if I can replace those unprecise centering options with custom values.

**Comment by MajorWilly** [comment]
Now rsn8887 has added zooming I suppose it is redundant. But you'll have to select the correct amount of zooming on a per-game basis which will probably need a UAE config for all games #hassle. The only reason I liked the crop is because it gave all games the maximum amount of screen with least amount of black borders.

Why does NTSC mode stretch the screen (on Dynablaster) ?

**Comment by sonninnos** [comment]
Because NTSC aspect ratio is different. It does that on a real Amiga.

**Comment by MajorWilly** [comment]
I just thought it looked stretched/wrong aspect. If you look at the bombs on the Dynablaster title screen they are circular on PAL but oval on NTSC.

EDIT. You posted before I finished typing. :)
