### ISSUE TITLE
x86_64 build fail

### ISSUE THREAD

**Issue by paradadf** [libretro/libretro-uae#125]
Hi! Thanks for improving the core in the last weeks!
I'm trying to integrate this into recalbox and I can build the core (with some adjustments) everywhere but on x86_64. This is the building log:  
https://pastebin.com/CUtPA1mQ

Any hints how I could fix it?

**Comment by sonninnos** [comment]
The end has a libco related whine:

> /tmp/ccV4Anpj.ltrans0.ltrans.o: relocation R_X86_64_PC32 against undefined symbol `co_active_handle' can not be used when making a shared object; recompile with -fPIC

**Comment by rsn8887** [comment]
I wonder if it is something that has since been fixed in latest libco version from libretro-common? 

Can you try to use https://github.com/rsn8887/libretro-uae master branch for testing compilation on x86_64? I updated libco there on that branch.

**Comment by rsn8887** [comment]
Latest Linux x86_64 build works fine on buildbot:
```
[Status: done] [recipes/linux/cores-linux-x64-generic] [Finished: 2020-01-03 22:23:09.142491+00:00] []
```
, so it must be either something wrong on your end or it was fixed. Either way, I am closing this issue. If you still find a problem, please re-open.
