### ISSUE TITLE
Very minor "issue" with VKeyboard CapsLock key

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#126]
On the Virtual Keyboard when pressing the Caps Lock key it doesn't change the case to UpperCase. I noticed it when entering my name in the game 'Wings'. I double checked it with a Workbench Shell window.

**Comment by sonninnos** [comment]
Oops, yep, now it only works on the actual keyboard. It doesn't actually press the capslock, but only forces a keypress to be pressed with shift down. Simply forgot to add it on the VKBD too. Will try to fix soon.
