### ISSUE TITLE
Questions and Minor Issues

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#137]
- Is there any info on what the 'CPU vs. chipset timing ratio' does ? I tried changing it in-game and Retroarch locked up.

- Sometimes when using Retroarch Fast Forward, the drive sounds get louder.

- The game Skidmarks (Floppy and WHDLoad versions) doesn't start when you need to click on the Skidmarks logo. This can be fixed by deleting the file `serial.device` from the games `devs` directory. What's missing from PUAE that's preventing this from working ?

**Comment by rsn8887** [comment]
Timing ratio is the slider from old WinUAE versions:
[![Timing.png](https://i.postimg.cc/mr7f1x5D/Timing.png)](https://postimg.cc/FfFnw6m5)

It works on Switch, but seems to be broken on Windows, no clue why. Just leave it at "real" for now.

**Comment by sonninnos** [comment]
@rsn8887 can answer about the need for the timing setting

I've noticed that fastforwarding sometimes makes drive spin sound disappear, but not any volume differences yet.

Let's hope that serial device is easy to fix, since Skidmarks is a great game. I haven't yet managed to reach letter S in my collection.

**Comment by MajorWilly** [comment]
I'll leave the 'CPU vs. chipset timing ratio' on Default and steer clear for now then, it sounds complicated.

All these 'minor issues' where using Android so maybe the Drive Sounds react differently (and get louder instead of disappear on Android) ?

I've been reading a few threads on EAB and also tried 'Super Skidmarks' WHDLoad. There is only a WHDLoad CD32 version for some reason but it doesn't work on PUAE because it requires 26mb to run ! LOL. 26mb !

**Comment by sonninnos** [comment]
But CD32 only has 2MB Chip.. Skidmarks 2 is HD installable so no WHDLoad is required.

**Comment by MajorWilly** [comment]
I'm using Retroplays WHDLoad lha's. The Super Skidmarks CD32 WHDLoad doesn't work for me with 2mb & 8mb Fast ram. It says 'couldn't allocate memory' or something like that. You have to add some Z3 ram. I think the slave author increased the memory requirements so more car types can be used for multiplayer. There is also a Low Memory slave but that also requires 26mb ! But like you said, there is a HD version anyway.

**Comment by MajorWilly** [comment]
Apparently it's already reported, but i'm losing faith with WHDLoad anyway. It requires too much memory (whereas the original doesn't). I was playing Monkey Island 2 and nearly got to Act 2 then suddenly got a black screen. Don't know if it was memory related. Darkseed also keeps flashing the screen when loading because 10mb is not enough for preload apparently. I'll stick with floppies unless it's a swapfest !

**Comment by sonninnos** [comment]
Well that is just retarded. The 1.1 lowmem indeed does the same as 1.1.

The version 1.0 from whdownload does work and serves all purposes needed here.

**Comment by MajorWilly** [comment]
Yeah, the Amiga version of Monkey 2 is almost silent. I'll stick with SCUMMVM for the Point'n'clickers and proper HD installed versions if available.
