### ISSUE TITLE
Joystick 2nd Button Issue

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#143]
With games that have support for 2 button joysticks (Banshee, Bubble & Squeak etc.), the second button only works once then it doesn't do anything. If you switch the Controls to CD32 Pad then it works fine. If you switch back to Retropad the second button works once and then stops again.

**Comment by rsn8887** [comment]
Can you make sure nothing is mapped to B in quickmenu->options? If something is mapped there, just set both A and B to "----" and try that way.

**Comment by sonninnos** [comment]
No such thing in Turrican. So problem lies somewhere in UAE and not in this core per se, which makes fixing not so fun..

**Comment by MajorWilly** [comment]
I can't test at the moment because i'm re-installing Windows. If it also happens on WinUAE then i'll close this. We can set it to CD32 Pad.
