### ISSUE TITLE
Black bars at the top- and bottom of the screen (making some pixels not visible when zoomed in)

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#147]
I'm in the process of migrating from FS-UAE to this libretro core, and thereby making the overall setup mimic the config files I had in FS-UAE. I have however encountered issues when it comes to viewing all of the image in games that uses the 320x256 resolution on the Amiga (notable Pinball Dreams and Pinball Fantasies) while fitting the image to my 1080p screen while preserving the original aspect ratio.

I'm using Core Provided in Aspect Ratio in RetroArch, making this libretro core handle the Aspect Ratio itself. If we take the game Pinball Fantasies (PAL, the non AGA version, course Disk 1), and choose the Party Land board, having Vertical Centering set to None, Crop Overscan False, Vertical Position 10, and Zoom Mode Small, we can see all the top pixels of the board, but we miss some pixels on the bottom of the image.

If I then set Zoom Mode to None, suddenly all the pixels of this Pinball board are visible, although the image is a bit to small for my liking. Setting Zoom to Small again and adjusting the values in the Vertical Position slider, I can choose if I want to view all of the pixels on the top- or the bottom of the game's image. There seems to be black borders at the very top- and bottom of the screen in this libretro core, hiding the full image of games running in 320x256 screen resolution while zoomed in.

This also applies on Amiga games running in different screen resolutions. If we take the game Blues Brothers, while setting Vertical Centering to None, I can move the picture up- and down with the Vertical Position slider to my liking, and if I move the picture way up or way down, the infamous black borders on the top- and bottom of this libretro core eats away the pixels before the image travels away from my computer screen.

**Comment by rsn8887** [comment]
Pinball Dreams uses 262 lines as far as I know.
The current zoom modes are:
None: 284 lines
Small: 256 lines
Medium: 240 lines
Large: 224 lines
Larger: 216 lines
Maximum: 200 lines

So I will simply add a 262 lines mode, called "Smaller". That should fix your problem hopefully :)

**Comment by rsn8887** [comment]
I think this issue should be fixed by a commit I just made https://github.com/libretro/libretro-uae/commit/3ce7c35f480f6cadfb0d823152c856c5525c68b5

Just select "Zoom Mode: Smaller" for Pinball Dreams.

**Comment by Gagert** [comment]
Hi again; I have just now tested this commit by downloading the newest libretro core in the Online Updater of RetroArch.

The new minimum Zoom mode, combined with Crop Overscan False, Vertical Centering set to None and Vertical Position 10 did the trick for all the games I had issues with regarding the game's height.

Thanks a lot; I can now close this issue in the Issue-tracker.
