### ISSUE TITLE
No kicks seem to be loading without error on windows, linux, or android

### ISSUE THREAD

**Issue by ChronoStriker1** [libretro/libretro-uae#149]
Im getting errors just loading the core with no hdf files, granted those seem to crash as well but I believe the issue is happening before it even tries to load the hdf files.

So far the only kick that seems to be loading is for the A500+

This pastebin has me loading each of the kicks individually without any additional rom files.  Only A500+ actually loads anything.  A600 if I dont menu out quickly enough will crash retroarch (and it has a super annoying buzzing sound with green and purple flashing background.  All others only show black and are silent)
[https://pastebin.com/rd8zRmQ3](url)

I can attempt to get the same logs for linux but not android but all show the same symptoms so Im assuming the issue is the same in all.

**Comment by sonninnos** [comment]
Something wrong with your Kicks, because this:
`Unknown ROM 'C:\Users\chronostriker1\AppData\Roaming\RetroArch\system\kick40068.A1200' loaded`

should read:
`Known ROM 'KS ROM v3.1 (A1200)' loaded`

Are you sure the hash is correct?

**Comment by ChronoStriker1** [comment]
Thank you for that, I was ignoring that because a few weeks back I made sure I had gotten the correct ones when I created my whdload file, I must have over written the correct ones at that time...  Double checked and the only one that worked was the one with the correct hash (who would have guessed.)
