### ISSUE TITLE
The very first time I press the left- or the right direction in-game, the character moves without stopping

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#150]
I've encountered a strange bug in this libretro core that's very easy to replicate; the first time you start any Amiga 2D platform game, are in-game, and press either the left- or the right directional button, the character walks in that direction without stopping. I'm using the wireless Xbox One gamepad (the one with bluetooth, although I'm using the wireless gaming receiver).

If you take James Pond 2, press the right directional button a single time in the very start outside the castle, and the character will walk through the first door, and he will not stop until he reached the invisible barrier on the far right on the first level. If you  then press the left directional button, the character will walk as far left as he can without stopping. Pressing left- or right afterwards and the directional buttons on the gamepad will behave as they should.

**Comment by sonninnos** [comment]
Indeed it does. Confirmed with JoyPortTest. Very odd that the same does not happen with up/down..
