### ISSUE TITLE
Player 2 character walks forever to the left- or right direction on the first button press (after the Controller Fixes #151 Pull Request)

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#152]
I just got the 67fc6c6 update of this libretro core from the Online Updater in RetroArch, and I tested it out. The Issue #150 that I wrote in the Issue tracker is mostly fixed during my quick testing, and by mostly it seems like Player 1 right- and left directional keys behaves OK now.

The Player 2 gamepad however acts like it just recently did; the first single press in the left- or right directional button causes the character to run all the way in that direction (tested with Blues Brothers and RodLand).

**Comment by sonninnos** [comment]
It is caused by the fact that the other joyport is a mouse port by default. And that won't be changed. But I'll try to see if it could be overcome without creating another problem.
