### ISSUE TITLE
[Enhancement] Support for disks in zip

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-uae#158]
This core can already load zip files.  When I load a zip file the core automatically seems to load the correct 'Disk 1' or 'Disk A'.  A common format for these zip files is to include all the associated disks in one zip (no-intro for example).  Append disk doesn't work in this case because the additional disks are within the zip file, so they can't be selected.

The request is to automatically handle all disks in the zip without the user having to unarchive the zip. 

Example what the current core does with the file `1869 - Erlebte Geschichte Teil I (Germany) (AGA).zip`

```
xxx$ /Applications/RetroArch.app/Contents/MacOS/RetroArch -L "/Users/xxx/Documents/RetroArch/cores/puae_libretro.dylib" "/Users/xxx/Downloads/1869 - Erlebte Geschichte Teil I (Germany) (AGA).zip"
...
[INFO] CRC32: 0x2e7951d5 .
Game '/var/folders/1f/xrx2xy955356grtv7mf2v6600000gn/T/1869 - Erlebte Geschichte Teil I (Germany) (AGA) (Disk A).ipf' is a disk, a hard drive image or a m3u file.
Generating temporary uae config file '/Users/xxx/Documents/RetroArch/saves/puae_libretro.uae'.
Found '(A1200)' or '(AGA)' in filename '/var/folders/1f/xrx2xy955356grtv7mf2v6600000gn/T/1869 - Erlebte Geschichte Teil I (Germany) (AGA) (Disk A).ipf'. Booting A1200 with Kickstart 3.1 r40.068 rom.
Disk (1) inserted into drive DF0: /var/folders/1f/xrx2xy955356grtv7mf2v6600000gn/T/1869 - Erlebte Geschichte Teil I (Germany) (AGA) (Disk A).ipf
...
```

While the zip file contains Disks A-D

**Comment by sonninnos** [comment]
RA does the unzipping, not the core. And because of that, I have no idea if anything can be done about it in the core.

**Comment by escalade** [comment]
This is easily scripted though, just unzip and put the files in a .m3u. Even if someone did bother to implement this, it should probably be in the frontend and not in the core.

**Comment by zach-morris** [comment]
OK, I'll close this and then maybe open an enhancement for Retroarch.  Thanks for looking into it

**Comment by sonninnos** [comment]
This PR should cover this issue, so please do test once it is merged and ready: https://github.com/libretro/libretro-uae/pull/253
