### ISSUE TITLE
Use of line_doubling=0 or low_resolution=1 result in only partial fullscreen

### ISSUE THREAD

**Issue by Enverex** [libretro/libretro-uae#16]
Normally these two options are used in FS-UAE to stop it trying to scale internally, so that scaling shaders work better.

In this core, if you enable either of these options, the output will end up being limited to a smaller part of the display.

low_resolution=1 results in only the left hand side of the display being used.
line_doubling=0 results in only the top half of the screen being used.

**Comment by DamsRoxxx** [comment]
Fixed in #46
