### ISSUE TITLE
Libretro uae crashes after selecting "Fastest possible CPU, but maintain chipset timing" in RetroArch

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#160]
I'm playing around with various settings/options in this libretro core to see it's effect on the emulated Amiga games. It seems like going from "Approximate real timing" to "Fastest possible CPU, but maintain chipset timing" in "CPU vs. chipset timing ratio" within RetroArch crashes both the core and RetroArch itself (PUAE 2,6,1 ad05971 combined with RetroArch 1.7.9 [v2]).

I've tested with various different games, same result.

**Comment by rsn8887** [comment]
Yes, treat this feature as experimental (I should have labeled it that way). It works on Switch it seems, but not on Windows.

**Comment by Gagert** [comment]
I suppose I don't have any valid reasons to be using this feature (I have a high spec PC); I was just curious if this feature had any benefits whatsoever.

**Comment by sonninnos** [comment]
Is the max-option still necessary to have and are the other options confirmed to actually have a benefit in any scenario?

**Comment by rsn8887** [comment]
I tested again, they do something, but not what I expected. I removed the option for now.
