### ISSUE TITLE
Floppy sound emulation doesn't seem to work

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#161]
It seems like the slider for floppy sound doesn't do anything at all as of now.

**Comment by sonninnos** [comment]
Works fine here.

**Comment by Gagert** [comment]
Aah; I would need some specific files for floppy sound emulation? I could not find any references to that in the readme-file provided here, but anyway that would explain a lot.

**Comment by sonninnos** [comment]
These: https://github.com/libretro/libretro-uae/tree/master/sources/uae_data
To: 'RA/system/uae_data', as said in the core options sublabel.

**Comment by Gagert** [comment]
The small tutorial describing in which folder you should place the sound-files for floppy-drive sounds is still mentioned in the ReadMe.

Now that the actual sounds are baked-in with the core itself, I suppose the small tutorial can be deleted from the ReadMe file?
