### ISSUE TITLE
Horizontal Position

### ISSUE THREAD

**Issue by Papermanzero** [libretro/libretro-uae#164]
Same as Vertical Position only for horizontal.
Games like north and south are left aligned for which such a feature would be perfect.

**Comment by sonninnos** [comment]
![retroarch_2019_10_22_23_17_51_589](https://user-images.githubusercontent.com/45124675/67328588-55e0cd80-f522-11e9-9bb4-b75ed36a7597.png)

![retroarch_2019_10_22_23_18_13_111](https://user-images.githubusercontent.com/45124675/67328605-5c6f4500-f522-11e9-887e-8600ea5959d1.png)

Does not look uncentered.

**Comment by Papermanzero** [comment]
Strange. In my case it is left aligned. But i can make a screenshot

**Comment by sonninnos** [comment]
Let me guess: You use a custom uae conf with a custom width? In that case just add the `gfx_center_horizontal=` (simple or smart) manually, if you must do it like that.

I removed those options for a reason, which is the screen always shifts when toggling vkbd or statusbar, and that they are not necessary anymore with the current zoom feature.

**Comment by Papermanzero** [comment]
No i am not using it

**Comment by Papermanzero** [comment]
![North   South-191023-131303](https://user-images.githubusercontent.com/10263536/67387423-1f916580-f597-11e9-9fb8-293ec8954fc1.png)
![North   South-191023-131412](https://user-images.githubusercontent.com/10263536/67387426-20c29280-f597-11e9-9b0e-f190f2ba81a0.png)


Here you can see screenshots. On the second one you see that the symbol on the top left is cut off. On the first screenshot you see on the right a blue border.

**Comment by sonninnos** [comment]
The core is not doing any cropping, so looks like the blame is in your RA video/shader settings.

And holy smokes does that scaler look awful.

**Comment by Papermanzero** [comment]
Every game is centered. Beside North and South.
I can now start a loooong discussion why my screen is more accurate compared to yours. But the question is just to add an horizontal position.

**Comment by sonninnos** [comment]
No thanks.

**Comment by Papermanzero** [comment]
Why did u add the vertical position then? 🙄

**Comment by sonninnos** [comment]
You just can't seem to stay at one subject. I've already added the horizontal position option to my todo list, but thanks to your attitude I'm saving it for last. Better start hoping that someone else joins to help with this core then.

That article says nothing new to me nor does it help with the core. Try some European fullscreen games like Stardust, The Settlers and Elfmania and see how great your aspect shenanigans work then. American made games are a different matter and that has been acknowledged. Those screenshots were made for showing the horizontal position (and not for a dick measuring contest of who has the most correct pixel size down to a negligible millimeter) and they are not American games.

The vertical position here is for keeping the zoomed modes centered. Using the knobs on the monitor for every single game is very annoying, especially when the knobs are on the back, like in the Idek I still have. Even that 1084S does not have size knobs on the front, and does it even have them in the back? Many people used a A520 adapter with TVs which have very little leg room, so they were stuck with whatever the developers decided. That is not "accurate" now either..?

Claiming what Amiga should have done and what it actually does are totally different things. And regarding accuracy the latter is most important. And using zoom to maximize screen estate is not accurate to begin with.

The real solution is to make the core's aspect calculation as accurate as possible, and not try to solve it with outside tweaking. That is what I am using, so it is not in fact "my" screen, but the core's screen. So either point where the error is and propose a more correct way of achieving it or you can shut it and stop wasting my time.

**Comment by Papermanzero** [comment]
The vertical position here is for keeping the zoomed modes centered. Using the knobs on the monitor for every single game is very annoying, especially when the knobs are on the back, like in the Idek I still have.

This is the reason why I asked for horizontal position..
Except that it is for the centred mode „simple“ or „smart“ to adjust the image to the centre.

**Comment by sonninnos** [comment]
Fine, have fun.

**Comment by Papermanzero** [comment]
Sorry, I did not want to piss you off. It was just a feature request, which I figured out when I tested video modes with the core.
