### ISSUE TITLE
4-player adapter / parallel joystick support

### ISSUE THREAD

**Issue by mleopold** [libretro/libretro-uae#169]
Hi,
I'm wondering what the chances are to see support for the 4-player adaptors that existed for the Amiga? It emulated 2 joysticks using the parallel port. As far as I can tell the emulator code is there, so I imagine this might simply be a matter of exposing the configuration?

In inputdevice.c the 2 additional joysticks are mentioned:
```
	case 3: /* ->Parallel port joystick adapter port #1 */
	case 4: /* ->Parallel port joystick adapter port #2 */
```

WinUAE (that I think libretro-uae shares some ancestry with) has the configuration option "Emulated parallel port joystick adapter". I could not find anything similar for libretro-uae.

Br,
Martin

**Comment by rsn8887** [comment]
Already supported, always on. Please test next time before you make an issue.

**Comment by mleopold** [comment]
Hi,
Great news! I'll definitely try it out.A bit of documentation would have helped me out - would a PR for a note somewhere be appreciated?

Br,
Martin

**Comment by rsn8887** [comment]
You mean list all the hundreds of features added by @sonninnos in the last few months? Sure. I started a feature list https://github.com/libretro/libretro-uae/commit/084aa229332ae51eedbeb9eea423b6a4952d926f

**Comment by mleopold** [comment]
Hi,
First, I tested the 4-player adapter with Dynablaster on my setup (which was my favorite way back when) - and it worked on my Nvidia Shield with 4 BT controllers. Great work! Much appreciated. As a first time user of RetroArch I found it a bit confusing to set up, so I was considering to collect notes in a "Quick Start Guide".

Second, I was concerned with the feature mentioned above. I was simply unaware that you were spewing out new and awesome features - I think drawing attention to that would be a great idea. In my case, the list you added would have sufficed for me, thank you. What I could do, if you are interested, is make an abbreviated version of the commit-log, but since I've not been a part of it it would be best effort.

Br,
Martin

**Comment by rsn8887** [comment]
I have a better list, one second

**Comment by rsn8887** [comment]
By the way there was an announcement on the official Retroarch blog about some of these new features:
https://www.libretro.com/index.php/core-news-puae-amiga-emulator-and-vice-commodore-64/

I also tried to alert people on my patreon and twitter accounts. I am not sure, but sonninnos might have also posted about this stuff somewhere.

**Comment by sonninnos** [comment]
Nah, I haven't advertised anything. Maybe eab could use some news spam as soon as the prime time is right.
