### ISSUE TITLE
Not available in buildbot for macosx

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/libretro-uae#17]

**Comment by twinaphex** [comment]
Honestly we still have numerous organizational issues getting that buildbot up and running. I apologize. I hope the nonsense is over soon.

**Comment by meepingsnesroms** [comment]
Its ok I fixed it and am about to submit a patch.

**Comment by meepingsnesroms** [comment]
Fixed

**Comment by meepingsnesroms** [comment]
It compiles now but still is not available for download.

**Comment by RetroUp** [comment]
FYI. Same is true or Win x86.
