### ISSUE TITLE
Flashback - Switching disks doesn't work

### ISSUE THREAD

**Issue by turboboy215** [libretro/libretro-uae#186]
I understand there's a separate core for this game specifically, but when I try to play this game, it runs well right up to the point where it says to insert disk 2 after the title screen. No matter what I try, it simply just doesn't work - it flashes black for a second and then says insert disk 2 again. Tried pressing every button and nothing happens. On WinUAE for PC, switching to disk 2 causes the screen to go black for a while and then goes to the first cutscene as it should. Other multi-disk games I've tried work. What's the problem here?

**Comment by sonninnos** [comment]
I've had similar problems only with PushOver, and it needs multiple times of ejecting and inserting for it to work, but not always. No idea why. I'll test Flashback soonish.

**Comment by sonninnos** [comment]
I tried the IPF version (SPS 1885) and it worked just fine. Too bad this game does not support multiple drives though.

**Comment by MajorWilly** [comment]
Just for clarification, the ADF version from Gamebase Amiga also works fine.

**Comment by turboboy215** [comment]
Mine is from a TOSEC set. The names for the ADF images are as follows:
Flashback v1.0 (1993-04-22)(Delphine - U.S. Gold)(Disk 1 of 4)[cr DCD].zip
Flashback v1.0 (1993-04-22)(Delphine - U.S. Gold)(Disk 2 of 4).zip
Flashback v1.0 (1993-04-22)(Delphine - U.S. Gold)(Disk 3 of 4).zip
Flashback v1.0 (1993-04-22)(Delphine - U.S. Gold)(Disk 4 of 4).zip

As said so far, these images work on WinUAE for PC but not when I try it on RetroArch for Android. How do you guys swap disks? I do mine the following:

Go to Disc Controls -->Disk Cycle Tray Status
Change Disk Index to 2
Select Disk Cycle Tray Status again

But this doesn't work.

**Comment by turboboy215** [comment]
I tried another version and it still doesn't work.

**Comment by turboboy215** [comment]
I'm also using an M3U file.

**Comment by sonninnos** [comment]
I also used M3U and did nothing else.

**Comment by turboboy215** [comment]
Did you try swapping the disks the same way I did? Otherwise, I don't know what the issue is.

**Comment by sonninnos** [comment]
Of course, how else would you swap them? Also using hotkeys work too. Try cycling the tray again.

**Comment by sonninnos** [comment]
Found a simple cure for this particular problem. Which is that a software won't know a disk has changed, since it checks for an empty state in between the changes. And that was already tried to force before, but it did not what it was supposed to.
