### ISSUE TITLE
[Switch] .uae file doesn't work to load multi disk games

### ISSUE THREAD

**Issue by cucholix** [libretro/libretro-uae#192]
Using latest build of the core, I'm trying to play Banshee, which is a 4 disk game, I'm booting the .adf disk through an .uae file:

```
floppy0=/roms/Commodore - Amiga/floppies/Banshee (Europe) (En,Fr,De,Da) (AGA) (Disk 1).adf
floppy1=/roms/Commodore - Amiga/floppies/Banshee (Europe) (En,Fr,De,Da) (AGA) (Disk 2).adf
floppy2=/roms/Commodore - Amiga/floppies/Banshee (Europe) (En,Fr,De,Da) (AGA) (Disk 3).adf
floppy3=/roms/Commodore - Amiga/floppies/Banshee (Europe) (En,Fr,De,Da) (AGA) (Disk 4).adf
```

The game launches just fine, but after the language select screen it ask to insert the disk 2, which shouldn't since I already indicate the path to that .adf in the .uae.

I've used this core since its launch on Swicth, and at that time everything worked fine (old UI).

No problems with single disk games like Turrican.

**Comment by sonninnos** [comment]
All the external floppy drives need enabling with that method, by adding:
```
floppy1type=0
floppy2type=0
floppy3type=0
```

But why not use the M3U method with "(MD)" added in the filename to achieve the same result automatically.

**Comment by cucholix** [comment]
> floppy1type=0
> floppy2type=0
> floppy3type=0

That fixed the issue, thanks!
