### ISSUE TITLE
"Please insert volume system in any drive" after .hdf load (switch version)

### ISSUE THREAD

**Issue by tomjramsden** [libretro/libretro-uae#194]
This is linked to 4ea45cc. I am now getting the error "please insert volume system in any drive" error after attempting to load .hdf on switch, again these work fine on windows version.

![2019122907023500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13732780/71553655-198e8980-2a0b-11ea-8947-9333617ce2d1.jpg)

Thanks,

**Comment by MajorWilly** [comment]
May also be related (but with Android), in the Readme it says that it will copy the Kickstarts if they are not found in the WHDLoad.hdf. If they are not there it crashes. If you copy the kickstarts to the WHDLoad.hdf then everything is fine. Maybe related to the Retroarch 'System' directory.

**Comment by tomjramsden** [comment]
Yes, still the same behaviour with the kickstart ROMs both inside whdload.hdf and in the system directory. You're right though, the switch version of retroarch system directory is inside the 'cores' directory.

**Comment by sonninnos** [comment]
For the time being please just remove these lines from the WHDLoad.hdf S:Startup-Sequence:
```
if not exists DH0:Devs/Kickstarts/kick34005.A500
   if exists System:kick34005.A500
      copy System:kick34005.A500 DH0:Devs/Kickstarts/
   endif
endif

if not exists DH0:Devs/Kickstarts/kick40068.A1200
   if exists System:kick40068.A1200
      copy System:kick40068.A1200 DH0:Devs/Kickstarts/
   endif
endif

if not exists DH0:L/WHDLoad.key
   if exists System:WHDLoad.key
      copy System:WHDLoad.key DH0:L/
   endif
endif

if exists System:WHDLoad.prefs
   copy System:WHDLoad.prefs DH0:S/
endif
```

Then it will stop assuming there is a volume named System, so you only need to copy the files in question by hand (Mainly just the Kicks, since WHDLoad.key and WHDLoad.prefs are just icing on the cake, and the prefs inside the hdf is the same file). And of course it will stop the "WHDLoad.prefs"-core option from doing anything.

For some reason the directory filesystem is not working on Switch then. But did it work before RA 1.82 or not? Directory location should play no part, since it is the very same directory where the required Kickstarts are, and there are no guesses of what directory is used, as in the RA system is used, whatever it is.

I'll revise a better way of fault tolerance once I feel better and get around to it.

**Comment by tomjramsden** [comment]
Thank you. I tried altering the WHDLoad.hdf S:Startup-Sequence, but the workaround was not successful, unfortunately. This is what the file now looks like:
```
failat 21
clicknot
devs:monitors/ntsc
devs:monitors/pal

path C:
makedir RAM:ENV RAM:T >NIL:
assign ENV: RAM:ENV >NIL:
assign T: RAM:T >NIL:

cd DH1:

if exists s/startup-sequence
   path DH1:C
   execute s/startup-sequence
endif

if exists custom
   setenv custom `type custom`
else
   setenv custom ""
endif

if exists System:WHDLoad.prefs
   copy System:WHDLoad.prefs DH0:S/
endif

if exists load
   execute load
else
   list #?.slave quick nohead to ENV:slave
   whdload preload $slave $custom
endif
```

**Comment by sonninnos** [comment]
You did not remove all instances of System volume.

**Comment by rsn8887** [comment]
I don’t think the directory filesystem ever worked on Switch. But it would be good to test this with logs etc.

If you use .hdf on Switch, please keep in mind that you can disable usage of WHDLoad.hdf in the core options. You can then use a collection with separate hdf, one per game, where all system files are included with every game in the same hdf, such as Ransom’s collection for example.

**Comment by rsn8887** [comment]
Hy the way, this issue here is not related to https://github.com/libretro/libretro-uae/commit/4ea45cc9d52c16d268474999e653873a647c2fc8 please remove that reference in OP, thanks.

**Comment by MajorWilly** [comment]
> a collection with separate hdf, one per game, where all system files are included with every game in the same hdf

In the Readme for 'New WHDLoad.hdf features' it says -
`'Use WHDLoad.hdf' core option does not need to be disabled when launching a non-WHDLoad HDF which has its own startup-sequence.` This doesn't seem to work. You have to disable the WHDLoad.hdf opton.

**Comment by sonninnos** [comment]
Care to share or point to a hdf that does not work with the core option enabled, because I haven't found one yet?

**Comment by MajorWilly** [comment]
[Barbarian+ AGA.zip](https://github.com/libretro/libretro-uae/files/4008516/Barbarian%2B.AGA.zip)

**Comment by sonninnos** [comment]
Looks like it just has some libs that need to be copied to Libs:

Very unplayable and clunky remake btw.

**Comment by MajorWilly** [comment]
Yeah, it was the only one that was Freeware. I can't find one that works with the option turned on.
