### ISSUE TITLE
HDF files don't load with the latest build (Dec 2)

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/libretro-uae#197]
I'm getting this:

![1d11a71018dbe07ee2c11dcdb1413e8e01b9dbf6_2_625x500](https://user-images.githubusercontent.com/12124465/71675109-c196b080-2d85-11ea-8785-c899ac5a5fb2.png)

It was working fine with a few days older build. That's on Windows 7.

**Comment by sonninnos** [comment]
There is a new WHDLoad.hdf version in the repo which solves that problem. And soon there will be yet another one with new features and fixes.

**Comment by Tasosgemah** [comment]
Thanks, that fixed it. I updated the whdload a few days ago and didn't realise i have to update that too for every core build.

The custom made (for retroarch) whdload games do work now. Any chance the oldre versions with the "gamename.slave" files will ever work?

**Comment by sonninnos** [comment]
No not for every build, this is just a special occasion of straightening out old shortcomings. 

Sorry for not getting all of these updates in a single bunch, but as I said, you'll soon need to update just one more time, then hopefully it (the relationship between the core and the HDF) can be left alone for a while.

What older versions? The name of the `.slave` does not matter anymore, so everything should work.

**Comment by Tasosgemah** [comment]
Could you try this file and see if it loads for you? It never did for me, i had to use a different set but i would prefer it if this worked:

https://www12.zippyshare.com/v/dMdhyPDV/file.html

**Comment by sonninnos** [comment]
No, ZIPs arent likely to be working for a while, since there is no way the core can work with all use cases, as in most likely a ZIP will include a single ADF.

UAE should know how to handle ZIPs, but the core would need to block ZIP extraction to get the actual archive that far, and that would break the ADF use case. So it needs some planning.

But same kind of LHAs will be working after the next PR. Still doing some last tests.

**Comment by Tasosgemah** [comment]
Thanks for the info. I will keep the zipped archive in case it works someday.

**Comment by TyroneSlothrop** [comment]
As of Jan 3: first of all thank you for your work on this core, if RetroArch can nail Amiga it would certainly improve its offering.

I am on 2.6.1 bb8782b on Mac - previously it was touch and go between hdfs loading and completely crashing. Then as of latest RetroArch 1.8.2 release (which comes with latest cores in Mac version), I had the above 'please insert volume system in any drive'... now I am getting 'Volume ADFView disk is full' after using the latest WHDLoad.hdf (note that I also used the new prefs and saves hdf too).

Any help you can offer pls?

![hdf issue](https://user-images.githubusercontent.com/1816777/71697938-32f45480-2dc2-11ea-90ff-a22041c968ac.png)

**Comment by tomjramsden** [comment]
> As of Jan 3: first of all thank you for your work on this core, if RetroArch can nail Amiga it would certainly improve its offering.
> 
> I am on 2.6.1 [bb8782b](https://github.com/libretro/libretro-uae/commit/bb8782b89bdc92fe26d16b9257d9102fa368de4f) on Mac - previously it was touch and go between hdfs loading and completely crashing. Then as of latest RetroArch 1.8.2 release (which comes with latest cores in Mac version), I had the above 'please insert volume system in any drive'... now I am getting 'Volume ADFView disk is full' after using the latest WHDLoad.hdf (note that I also used the new prefs and saves hdf too).
> 
> Any help you can offer pls?
> 
> ![hdf issue](https://user-images.githubusercontent.com/1816777/71697938-32f45480-2dc2-11ea-90ff-a22041c968ac.png)

I am getting the same error with certain games... SWOS 2020 being one of them...

**Comment by sonninnos** [comment]
SWOS 2020 is not a WHDLoad game, and I can't guarantee that every random HDF installation works with the "WHDLoad.hdf" core option enabled.

I will try to continue the never-ending whack-a-mole, but in the meantime just disable the core option in those cases.

**Comment by MajorWilly** [comment]
SWOS 2020 (non WHDLoad HDF) works fine for me on Android, no errors. Must be a Mac only problem. @tomjramsden There has been a new WHDLoad.hdf since #195 . Have you tried the updated WHDLoad.hdf ?

**Comment by sonninnos** [comment]
It is happening here too with all the latest thingamagicks.

**Comment by MajorWilly** [comment]
Oh, mine is custom made from a game pack, not from the website. Probably why I didn't get this error.

**Comment by tomjramsden** [comment]
> SWOS 2020 (non WHDLoad HDF) works fine for me on Android, no errors. Must be a Mac only problem. @tomjramsden There has been a new WHDLoad.hdf since #195 . Have you tried the updated WHDLoad.hdf ?

I have indeed, it's working well for most games, but I can also replicate the error on windows version of RA (using latest build and WHDLoad.hdf)

**Comment by tomjramsden** [comment]
> Oh, mine is custom made from a game pack, not from the website. Probably why I didn't get this error.

You built a custom .hdf? I just tried that and failed :( - any chance of sharing please? (as it's freeware!)

**Comment by MajorWilly** [comment]
I got it from EAB. He's deleted the single download now though so here you go -

[Sensible World of Soccer 2020.zip](https://github.com/libretro/libretro-uae/files/4020944/Sensible.World.of.Soccer.2020.zip)

**Comment by tomjramsden** [comment]
> I got it from EAB. He's deleted the single download now though so here you go -
> 
> [Sensible World of Soccer 2020.zip](https://github.com/libretro/libretro-uae/files/4020944/Sensible.World.of.Soccer.2020.zip)

Thanks very much, appreciated! :)

**Comment by sonninnos** [comment]
Please try updating to the current WHDLoad.hdf.

**Comment by TyroneSlothrop** [comment]
Yes I confirm all good now for me, thank you very much.
