### ISSUE TITLE
Sound output

### ISSUE THREAD

**Issue by pawelomega** [libretro/libretro-uae#20]
Hello. Thanks for good project. Emulation works much better than UAE4ARM but problem is in audio output. I think isn't properly playing with stereo. Left channel playing much louder then right and i'm not see stereo seperation. Thanks and waiting for next releases >>>

**Comment by sonninnos** [comment]
Amiga natively pans all sounds either hard left or hard right. Please try if the recently added stereo separation option helps out.

**Comment by rsn8887** [comment]
Try stereo option: mixed or stereo

Try mixed with separation less than 100%, like 70%. There was a bug report that said separation should be muliplied by 2/3 or some such e.g. 70% should be the maximum.

**Comment by sonninnos** [comment]
The sound channel option does nothing, it is forced to stereo.

**Comment by sonninnos** [comment]
I'm pretty sure this can be closed.
