### ISSUE TITLE
WHDLoad kickstarts & XPK compressor libraries

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#202]
I just noticed on this page -
http://www.whdload.de/docs/en/need.html

There are a couple more Kickstarts mentioned -
```
kick33180.A500
kick40068.A4000
```

I don't know what requires the A4000 one but I do know that the Arcadia WHDLoad games require the `kick33180.A500` kickstart.

Also, inside the XPK libraries package that it mentions (from Aminet) there is a 'compressors' folder with the xpkmaster.library. Not sure if they are needed ? I assume it's the ones in the regular 'Libs' folder that are needed.

**Comment by MajorWilly** [comment]
Yes, I think the compressors are needed. The game Dungeon Master gives an error about them.

**Comment by sonninnos** [comment]
Nothing prevents anyone from copying manually the Kickstart 1.2 and RTB if needed. I don't see it important enough to be required by the core/whdload.hdf. But sure, why not include it to be autocopied too if found in system.

I'm pretty sure no install requires the A4000 Kickstart, but that WHDLoad can use either A1200 or A4000, like it says in a readme snippet:
> The kickstart image must be located in the directory "Devs:Kickstarts" and
 must be named "kick40068.A1200" or "kick40068.A4000".


Regarding XPK I gathered from the readme, that only the main library is required for normal use, and those sublibraries are the same libs separated.

> XPK consists of one xpkmaster.library, which does all
the work you need to do to support packing (data handling, file format
creation, parameter checking, ...) and a lot of sub libraries, which are
equal to the XPR libraries. They have an standardized interface and are
stored in LIBS:compressors directory. Normally you call the master library
when you need to pack or unpack something. You also may use the sub
libraries directly (like for XPR). The sub libraries all implement
different packing or encrypting algorithms.

**Comment by sonninnos** [comment]
Dungeon Master + Arcadia installs working automatically, have a spin:
[WHDLoad.zip](https://github.com/libretro/libretro-uae/files/4027254/WHDLoad.zip)

**Comment by MajorWilly** [comment]
Yep, all working, thanks.

**Comment by MajorWilly** [comment]
I've never actually played an Arcadia game but it seems that Player 1 always uses port 0 which is the Mouse in PUAE. Is there anyway that i've missed that changes it to Joystick ?

**Comment by sonninnos** [comment]
I tried Ninja Mission Arcadia and it controlled very regularly, just had to find the insert coin and start buttons in the function keys.

The joyport part could use some renovations anyway since at the moment 3 player Dyna Blaster with the 4 player adapter is not possible, because 3&4 become 1&2 and 1&2 become 3&4, and the ports in the Controls menu go hardcoded in tandem. Which means that the second controller will control the unexisting 4th player.

**Comment by MajorWilly** [comment]
I actually played Ninja Mission in the Arcade back in the day. It's a decent improvement over the Amiga version which is weird because the Arcadia is just an Amiga 500 in a cabinet !

When I tried a few of these I used F3 for coins and F1 for 1 player but it would only work from the mouse. The readme says something like 2nd player (joystick port) and 1st player (mouse port).
