### ISSUE TITLE
"Volume whdload is not validated"

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/libretro-uae#204]
If i have a fresh WHDLoad file in the system directory, the games load fine. But after a few games i randomly get this error:

![AllNewWorldOfLemmings_v1 0_AGA_0625-200107-052735](https://user-images.githubusercontent.com/12124465/71866578-52b3b180-310f-11ea-8c6f-f23fc8c57828.png)

This error means my WHDLoad file is screwed and i can't load any games anymore unless i manually replace it with a fresh one or a backup.

Making the file read-only doesn't work, it makes the core crash. But letting it be modified means it will eventually bust it again. So how can i prevent this?

**Comment by MajorWilly** [comment]
The WHDLoad.hdf has been updated several times recently and I think @sonninnos fixed this issue (there's also another update waiting to be pulled). Have you tried updating the file and still get this issue ?

**Comment by Tasosgemah** [comment]
> 
> 
> The WHDLoad.hdf has been updated several times recently and I think @sonninnos fixed this issue (there's also another update waiting to be pulled). Have you tried updating the file and still get this issue ?

Yeah, i updated both the core and WHDLoad a few minutes before the post

**Comment by sonninnos** [comment]
So far the only solution I have is not quitting the core while the HD is loading.

**Comment by Tasosgemah** [comment]
How do i know the HD is loading? Is it only at the startup? Can i load a state or do i have to wait until i see the first screen of a game?

**Comment by sonninnos** [comment]
The statusbar has a LED. Mostly it only happens at startup, since the Preload option is the default with WHDLoad installs. That option copies as much game data as the configured RAM can fit. 

Powering off whenever won't be good for a real Amiga either, but I'm looking into it. It is just so hard to reproduce on command, that it won't be easy to be sure it never happens again.

If you can make it happen like clockwork, could you try increasing the `ReadDelay` option in `WHDLoad.prefs` to something like 50 for starters?

**Comment by Tasosgemah** [comment]
Ok, i will test this readdelay option and report.

I could very easily reproduce the issue by loading New World of Lemmings and quitting early. After about 4-5 attempts i get this error.

**Comment by sonninnos** [comment]
Thanks for the tip, I managed to recreate it with just a few attempts with that game.

Please try to break this one, I haven't yet:
[WHDLoad.zip](https://github.com/libretro/libretro-uae/files/4031511/WHDLoad.zip)

**Comment by Tasosgemah** [comment]
Looks stable so far after a couple of minutes trying to break it with early quits and load states.

I'm going to test more games (in case it's a game dependable issue) since i'm sorting out my favorites right now. I'll report if i manage to break it again or not.

**Comment by sonninnos** [comment]
Looking good. I've tried and I've tried but haven't got the corruption yet. I'll be pushing some updates soon if there is no objection.

**Comment by Tasosgemah** [comment]
Yeah, i havent got home yet for further testing.
