### ISSUE TITLE
Some WHDLoad LHA games crash the core (due to 0 byte files etc.)

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#207]
These WHDLoad LHA games crash the core/Retroarch.

Cadaver&ThePayoff_v2.4_0900
CannonFodder2_v1.12_0104
CaptainBlood_v1.1_0443
DefenderOfTheCrown_v3.1_CDTV

I've noticed that all 4 of these games have a 0 byte file inside. WinUAE uses a UAEFSDB file for dealing with illegal characters/files etc. Is that what PUAE uses ?

http://eab.abime.net/showthread.php?t=5126

(Just copied these posts from the WHDLoad.hdf thread as it wasn't related). There will be more that crash but I stopped after it was confirmed what the cause was.

SimCity_v1.0_2193
Zool_v2.0_CD32

**Comment by sonninnos** [comment]
Nothing to do with UAEFSDB and illegal characters/filenames.
