### ISSUE TITLE
Pressing R1 button on 24 bit color mode crashes

### ISSUE THREAD

**Issue by Panderner** [libretro/libretro-uae#210]
When I press r1 button on 24 bit color mode it crashes

**Comment by sonninnos** [comment]
Please be more precise. What platform and what video resolution?

I can't reproduce on 64bit Windows 10.

**Comment by rsn8887** [comment]
Can’t reproduce on Switch either using latest build b533286

**Comment by Panderner** [comment]
> Please be more precise. What platform and what video resolution?
> 
> I can't reproduce on 64bit Windows 10.

I'm using 64 bit Android

**Comment by sonninnos** [comment]
Does the same thing happen if you change the Statusbar core option from "Bottom Full" to "Bottom Basic"?

**Comment by Panderner** [comment]
> Does the same thing happen if you change the Statusbar core option from "Bottom Full" to "Bottom Basic"?

Buttom basic works but buttom full crashes

**Comment by sonninnos** [comment]
That narrows it down nicely. Could you try updating the core and see if it still happens? I did some small changes yesterday on that regard, but they probably won't help anything. Would have to get the crash happen here too to actually fix it..

**Comment by sonninnos** [comment]
Does it crash even with the current version?

**Comment by Panderner** [comment]
> Does it crash even with the current version?

No. It fixed on latest version

**Comment by sonninnos** [comment]
Excellent!
