### ISSUE TITLE
HDF Files not booting (workbench screen) - Switch version

### ISSUE THREAD

**Issue by tomjramsden** [libretro/libretro-uae#212]
Hello I recently updated to build 2.6.1 b533286 (retroarch 1.8.3) with the latest whdload.hdf, kickstarts, etc.

When attempting to load hdf games using whdload.hdf I get the following workbench screens
![workbench_error_apidya](https://user-images.githubusercontent.com/13732780/72206151-5a15ea80-3482-11ea-8ef1-b6b564ffde2b.jpg)
![workbench_error_gods](https://user-images.githubusercontent.com/13732780/72206152-5a15ea80-3482-11ea-84d3-ed04b546b493.jpg)

Any help greatly appreciated!

**Comment by sonninnos** [comment]
Oops, looks like I broke the ancient `game.slave` renamed launching.

That selector should only come up if either you hold down fire button at boot or if the game you are launching does not have an exactly named icon with the slave, like in this case.

Could you rename the slaves back to their real name and/or get fresh LHA installs instead?

I tried `Apidya_v2.05_Kaiko_0764.lha` and `Gods_v2.3.1_0666.lha` and they work fine.

**Comment by tomjramsden** [comment]
> Could you rename the slaves back to their real name and/or get fresh LHA installs instead?

That's unfortunate, my whole collection have renamed to game.slave :/
https://archive.org/details/amigaromset

I suppose I could look at straight .lha files - out of interest are their advantages of lha over hdf?
I haven't tried launching lha directly from retroarch before, last time I tried I didnt think it worked.

Any advice appreciated.

Thanks,
T

**Comment by sonninnos** [comment]
I can restore the renamed support soonish, but the downside will be that the `custom` file creator can't differentiate between slaves, so that can't be used.

The advantage is that all those HDFs were created from those LHAs, so that is the original form. Disadvantage is that LHAs are read only, but that is not a real problem anymore since saves are redirected elsewhere. LHA support is a pretty fresh inclusion, so do try again.

**Comment by tomjramsden** [comment]
Okay, makes sense thanks. I just tried to load a .lha directly from 'load content' on switch and got a 'failed to load content' error. 

I don't have a strong preference of hdf over lha, so happy to switch over, once supported. I guess the lha's are updated more regularly which is a bonus.

**Comment by MajorWilly** [comment]
LHA's can't be loaded from 'Load Content' as Retroarch doesn't recognize the LHA filetype. I think the CoreInfoFiles need updating but I don't know who's responsible for this. They work great with a playlist.

**Comment by sonninnos** [comment]
Core info is already updated, and Load Content works fine here.

**Comment by MajorWilly** [comment]
@sonninnos You can load LHA files from the 'Load Content' option ? The core info file here https://github.com/libretro/libretro-core-info/blob/master/puae_libretro.info (if this is the right one ?) has no LHA as a supported extension.

@tomjramsden I recommend using Retroplay's LHAs. Most of the HDF's from that link you listed are seriously out of date.

**Comment by sonninnos** [comment]
Hmm, I thought this was the place: https://github.com/libretro/libretro-super/blob/master/dist/info/puae_libretro.info

I just updated the info files in RA and LHA is there.

**Comment by tomjramsden** [comment]
> @tomjramsden I recommend using Retroplay's LHAs. Most of the HDF's from that link you listed are seriously out of date.

Thanks, is best up to date source on EAB FTP?

**Comment by MajorWilly** [comment]
Yeah. Retroplay also has a link to his MEGA account (on EAB) which gives full speed downloads.

**Comment by sonninnos** [comment]
Presumably buildbot has the new version ready, so those renamed HDFs should start working after deleting the old `WHDLoad.hdf` and running any HDF.

**Comment by tomjramsden** [comment]
> Presumably buildbot has the new version ready, so those renamed HDFs should start working after deleting the old `WHDLoad.hdf` and running any HDF.

Thanks very much, i'll test soon.

**Comment by tomjramsden** [comment]
> Yeah. Retroplay also has a link to his MEGA account (on EAB) which gives full speed downloads.

I've managed to pull down a good selection of LHA's from retroplay. I'm having a bit of mixed success now I am testing properly. I think some it might the right combination of config.
Out of interest have you ever got Chaos engine 2 working?
I am working through this switch compatibility list I created, if you're interested..

https://docs.google.com/spreadsheets/d/1rudk_fh_2GY7vD1DJLYgsnshVTKEpqrCG3DVxMf3je4/edit?usp=sharing

**Comment by MajorWilly** [comment]
I tested the first 5 red entries in your list and they all work fine !

Alien Breed 2 (ECS and AGA)
Another World
Cadaver & The Payoff
Curse of Enchantia
Fightin Spirit CD32

For the CD32 ones you'll need to set your controls to CD32 Pad.

**Comment by tomjramsden** [comment]
> I tested the first 5 red entries in your list and they all work fine !
> 
> Alien Breed 2 (ECS and AGA)
> Another World
> Cadaver & The Payoff
> Curse of Enchantia
> Fightin Spirit CD32
> 
> For the CD32 ones you'll need to set your controls to CD32 Pad.
> 
> EDIT: I may have found your problem. Are you trying to run all these games in NTSC mode ? Only games with NTSC in the filename are true NTSC versions.

Good Man! Yes, spot on, as soon as I adjusted to PAL they were working...I suspect the rest of my testing will be successful!

**Comment by tomjramsden** [comment]
> I tested the first 5 red entries in your list and they all work fine !

I still can't get Chaos engine 2 to run, did it work for you?

**Comment by MajorWilly** [comment]
Both versions work fine -

ChaosEngine2_v2.1_0172
ChaosEngine2_v2.2_AGA_0173

Not really sure why it doesn't work for you. Does the non-AGA version work for you ?

**Comment by tomjramsden** [comment]
> Both versions work fine -
> 
> ChaosEngine2_v2.1_0172
> ChaosEngine2_v2.2_AGA_0173
> 
> Not really sure why it doesn't work for you. Does the non-AGA version work for you ?

Hmmm redownloaded both versions, the non-AGA works but the AGA still doesn't. 
Out of interest which version of RA and core are you running?

**Comment by MajorWilly** [comment]
Retroarch 1.8.3, PUAE 7abc7f1

Do other AGA games work for you ? Do you have the correct A1200 ROM for WHDLoad ? Other than that, I'm not sure. They work fine for me. Maybe @rsn8887 might know, I think he has a Switch.

**Comment by sonninnos** [comment]
`ChaosEngine2_v2.2_AGA_0173.lha` crashes here when the actual gameplay should start.
> Warning: Bad playfield pointer
Exception code=0xc0000005 flags=0x0 at 0x00007FF947A74AE4. Access violation - attempting to write data at address 0x000000000DFCA000

**Comment by MajorWilly** [comment]
I just updated to154ccbc and Chaos Engine 2 AGA still works for me (Android).

**Comment by sonninnos** [comment]
"Works" as in goes further than just the menu..?

**Comment by MajorWilly** [comment]
Yeah, I can play the game.

**Comment by sonninnos** [comment]
Wot, this is the last screen I see before the crash, no matter what:
![retroarch_2020_01_12_21_59_02_239](https://user-images.githubusercontent.com/45124675/72224804-2670b880-3587-11ea-9374-7f26bd2f1415.png)

**Comment by MajorWilly** [comment]
I can play the game -

![ChaosEngine2_v2 2_AGA_0173-200112-200944](https://user-images.githubusercontent.com/52862903/72224946-ab53d600-3577-11ea-8ae1-7f709afea66d.png)

But if I pull down my Android bar it crashes.

**Comment by MajorWilly** [comment]
Pulling down the top Android bar seems to crash on all cores so not related. Weird how this game works on Android but not on Windows/Switch.

**Comment by sonninnos** [comment]
I'm trying to wrap my head around it. Even tried a much earlier build (before CD32 support) and still all game versions crash on the same spot.

**Comment by Tasosgemah** [comment]
> 
> 
> Yeah. Retroplay also has a link to his MEGA account (on EAB) which gives full speed downloads.

Full speed is a stretch. I can only get like 300 kb/sec max from that MEGA link. Maybe too many people downloading?
