### ISSUE TITLE
HDF Usage (again)

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-uae#216]
Hello,

First, I just wanted to say thanks for all the work put into this core.  I've been watching the improvements in the commit history and they've been coming fast and furious.

This may not be an issue, but more of a question, and possibly usage could be clarified in the readme.  Previously, a whdload game would load with no additional setup required.  This seems to have recently changed.

I can load an hdf file with the new WHDLoad.hdf directions (where it's auto loaded and then copies the kickstarts directly).  Seems to work without an issue.  When the emulator starts (using RickDangerous_v1.2_0776.hdf as a standard example) I'm presented with this screen:
<img src="https://i.imgur.com/mDH6bud.png" width="650">

From what I gather, I get this screen because my game hdf doesn't have the slave file in the root.  So I browse up and find the game.slave file and select it:
<img src="https://i.imgur.com/vPYqM2Y.png" width="650">

But then I'm given an error screen and it automatically loads a readme file instead.  I'm left with the following error:
<img src="https://i.imgur.com/eaBKdtu.png" width="650">

I'm assuming this is because I don't fully understand how to load the game now, or is this a bug? 
 Could this be clarified in the readme?

**Comment by zach-morris** [comment]
I guess I spoke too soon.  I see the readme was recently updated and I just deleted WHDLoad files, and restarted.  The core automagically generated the files needed and the game autostarted again.

<img src="https://i.imgur.com/sKL3k1K.png" width="650">

**Comment by sonninnos** [comment]
Yeah, I accidentally didn't make sure that the slave renamed HDF versions still work too. But good that it seems to be sorted then.
