### ISSUE TITLE
Is runahead implementation plausible?

### ISSUE THREAD

**Issue by aboutafter** [libretro/libretro-uae#217]
The core has about 4 to 6 frames of input lag on the games that I tested. The possibility of removing that input lag with runahead would be marvelous. 

Is it something that can be implemented?

**Comment by sonninnos** [comment]
Not with the current savestate implementation and probably not even if/when they are properly memory based.

The core reacts on the next frame, so that amount of input lag is a game and/or configuration issue. But then again run-ahead is meant to affect game lag, not core lag.

**Comment by rsn8887** [comment]
I learned the following from Sonninnos: You can check the inherent lag due to the core  and game by pausing the core, holding your controller button and stepping single frames forward until you see a reaction.

**Comment by rsn8887** [comment]
You can always precisely check the lag due to game by pausing the core, holding your controller input down, and advancing single frames until you see the reaction.

**Comment by realnc** [comment]
The core-induced 1 frame of lag was removed a while ago. The core now has no lag at all, actually. An easy way to verify this is to run Monkey Island 1. Press 'k' while moving the mouse. The game's mouse cursor should react immediately.

Runahead would be nice of course to get rid of the lag that the games themselves have even on actual Amiga hardware. But as sonninnos said, it's not something that can be added easily.

**Comment by rlnilsen** [comment]
Is runahead supposed to be practical with commit 146a71025d6427017cd2bc3ee7ab139bb427839b, or are there still other issues in the way (like savestate implementation)?

**Comment by sonninnos** [comment]
No, it only helps the core to not crash if runahead happens to be enabled at start, as the title suggests. The savestate handling in PUAE itself requires who knows how much changes for it to work properly, because the savestate load initialization isn't happening at the next frame.

**Comment by sonninnos** [comment]
Closing due to being a pipe dream.

**Comment by bidinou** [comment]
Hi ! I'm reviving this thread to ask whether the situation has changed now that the new "Preemptive frames" system has superseded "RunAhead" ?

Cheers & thank you so much for maintaining the core !

**Comment by sonninnos** [comment]
No, since it depends on savestates just as much, therefore nothing is going to change.

**Comment by benjis8888** [comment]
> The core has about 4 to 6 frames of input lag on the games that I tested. The possibility of removing that input lag with runahead would be marvelous.
> 
> Is it something that can be implemented?

I don't know if this typical but on Rat Trap I am even getting up to 8 frames delay when in the first section where you choose a level door to go into
