### ISSUE TITLE
RA 'Online Updater' (Switch version) broken

### ISSUE THREAD

**Issue by tomjramsden** [libretro/libretro-uae#221]
I just updated to the latest build (I can't verify which as it crashes) and it crashes retroarch on every game I am tried to launch.

It also crashes when I try and load the core.

I can launch other cores/content with no issue

Can anyone else replicate? 
I have attached logfile for what it's worth (although it doesn't seem to explain much.)
[retroarch__2020_01_14__21_34_00.log](https://github.com/libretro/libretro-uae/files/4061687/retroarch__2020_01_14__21_34_00.log)

**Comment by tomjramsden** [comment]
I have isolated the issue. When attempting to use the online updater to pull down the latest version it adding this to the core directory:

![image](https://user-images.githubusercontent.com/13732780/72385738-03294300-3718-11ea-9980-32a39ba14c44.png)

An empty zip file?? - I have never seen this before.

**Comment by tomjramsden** [comment]
**Workaround**
I have manually restored the .nro core from the last release and removed the empty zip file, and it's working again.

Probably needs investigating why the online updater is pulling down only an empty zip file..

**Comment by rsn8887** [comment]
Can you double check that your main retroarch executable is 1.8.3? If not, download
"Retroarch_Loader_Update.zip"
from here
http://buildbot.libretro.com/nightly/nintendo/switch/libnx/
and copy it to /switch

The file was recently renamed.

**Comment by rsn8887** [comment]
I can’t reproduce this. I just used the online updater to get the latest puae core, loaded it, verified it is the correct latest commit and started the core. No problem.

**Comment by tomjramsden** [comment]
> I can’t reproduce this on my Switch. I just used the online updater to get the latest puae core, loaded it, verified it is the correct latest commit and started the core. It started without problem.
> 
> Please update Retroarch to latest nightly version (including the loader .nro) from buildbot.libretro.com and test again. If it still doesn’t work, delete or rename your config and core config and try again with default config.
> 
> If it still doesn’t work, we need to find out what’s different between your setup and mine, because it works for me.

Thank you, I updated to the nightly and seemed to resolve it.
