### ISSUE TITLE
[For Reference] WHDLoad games that don't work.

### ISSUE THREAD

**Issue by ghost** [libretro/libretro-uae#229]
Firstly, awesome work on this emulator @sonninnos ! You've literally breathed new life into it. This is really only for reference. I've been trying a few WHDLoad games and have kept a record of the ones I couldn't get to work. If this core ever gets updated to a newer PUAE version in the future then these could be the ones to test. I matched the settings on WinUAE using the same WHDLoad.hdf and they all work, even without cycle-exact. If anyone want's to add anything i'll put it in this first post.

-------------------------------------------------------------------------------------------------------

![Clockwiser](https://user-images.githubusercontent.com/60177795/74045629-0b963600-49c5-11ea-9db5-4bd9ac34ccc5.png)
**_Clockwiser_v1.1_**
**_Clockwiser_v1.1_AGA_1900_**
Amiga crash. (Floppy versions work).
![Clockwiser_v1 1_AGA_1900-200210-165731](https://user-images.githubusercontent.com/60177795/74172445-2d432780-4c28-11ea-8c82-6309c9fde03e.png)

-------------------------------------------------------------------------------------------------------------
![Deep, The](https://user-images.githubusercontent.com/60177795/74045652-1781f800-49c5-11ea-92ac-b83bbca1de05.png)
**_Deep_v1.0_**
Black screen.

------------------------------------------------------------------------------------------------------------
![DynamiteDux_v1 0_1183](https://user-images.githubusercontent.com/60177795/87255912-bb953100-c486-11ea-8dda-bc09dd5a3939.png)
**_DynamiteDux_v1.0_1183_**
Crashes Retroarch. (Floppy version works).

-----------------------------------------------------------------------------------------------------------
![Fatman - The Caped Consumer (AGA) (MD)](https://user-images.githubusercontent.com/60177795/74045779-44360f80-49c5-11ea-9c27-1c2ac836dba1.png)
**_FatmanTheCapedConsumer_v1.1_AGA_0480_**
Locks up/black screen after intro. (Floppy version works).

-------------------------------------------------------------------------------------------------------------
![c7342d67-34f2-46b3-995a-7b6e09d35d61](https://user-images.githubusercontent.com/60177795/74089416-ed9a0580-4a98-11ea-915d-3b5b34b668dd.png)
**_GadgetLostInTime_v1.0_**
Black screen.

-------------------------------------------------------------------------------------------------------------
![12012c26-7a65-4c5c-889e-9ffabc392054](https://user-images.githubusercontent.com/60177795/74172590-6a0f1e80-4c28-11ea-9f9a-500a9453c81f.png)
**_HoundOfShadow_v1.0_0338_**
Amiga crash.
![HoundOfShadow_v1 0_0338-200210-170224](https://user-images.githubusercontent.com/60177795/74172653-84e19300-4c28-11ea-8c1f-b67f9b87ce38.png)

--------------------------------------------------------------------------------------------------------------
**_PulsatorDemo_v1.1_AGA_**
Needs 68030 to run.

--------------------------------------------------------------------------------------------------------------
![super skid](https://user-images.githubusercontent.com/60177795/74045794-4bf5b400-49c5-11ea-889b-f32ecd3ec27e.png)
**_SuperSkidmarks_v1.1_CD32_**
Needs 26mb to run. (v1.0 works).

--------------------------------------------------------------------------------------------------------------
![TensaiDemo_v1 0](https://user-images.githubusercontent.com/60177795/87330453-81806980-c530-11ea-8074-695618b20d59.png)
**_TensaiDemo_v1.0_**
Black screen.

-------------------------------

**Other**

**_BeneathASteelSky_v2.1_CD32_**
Speech sounds corrupted or has interference.

**_APB_v1.1_*_**
There is a custom option to brighten the screen (`CUSTOM2=$111` etc.) but when entering it in MkCustom it says 'bad number' in the DOS screen.

Thanks !!!

**Comment by sonninnos** [comment]
Thanks for the kind words. There only exists PUAE 2.8.1b6, which is not so different from this 2.6.1, and since this core already is a Frankenstein with lots of code from WinUAE 4.x, I don't see it worth the effort to ever completely change the source to anything else than FS-UAE or WinUAE.

The compatibility is already pretty good, as in nearly all games I care to play do work, but nevertheless and of course getting it to the same level as the latest WinUAE is worth pursuing.


But here are my findings:

_**Executioner_v1.1**_
Black screen, but works when forced to A1200 AND when "CPU Compatibility" is anything else than "Cycle-exact".

_**GrandPrixCircuit_v1.0_0008**_
Black screen, no known cure, same thing with the floppy version.

_**SensibleGolf_v1.2_0200**_
Going to the options will crash WHDLoad unless forced to A1200. Same thing with WinUAE, so the slave is to blame.


Super Skidmarks 1.0 slave will boot up, but locks up when pressing "Select Cars" on the menu and/or when loading the actual race. Audio and video will continue, but game logic does not. Fun to debug, eh? Same thing with the HD install and the CD32 version. Only the floppy version goes to the game part, but will also lock up on "Select Cars".

Ninja Mission Arcadia does control on the regular joyport. Is it really worth the effort to implement a joyport switch for those other handful of games, when you could just use/map a second controller..?

Heh, nice call on the APB slave to use the same character that does variables in scripts.. Maybe it can be escaped. Midnight Resistance does the same kind of color correction with just `CUSTOM1=1`.

**Comment by WindyWinston** [comment]
The accuracy is top notch on this core. All the classics that I used to play are working. I'd rate it above Amibian/Amiberry (a hackfest!) because PUAE has cycle-exact as well which allows games like Came from the Desert to work correctly. I think the only real gem on this list is the Skidmarks games. I haven't tried yet but there is also a CD version called Ultimate Skidmarks.

The Arcadia games are not worth the bother as most of them have official Amiga versions anyway.

The black screen seems to occur on a few of these listed. I wonder if it's all related ? Overall :+1:

**Comment by sonninnos** [comment]
Ultimate Skidmarks is just Super Skidmarks in disguise, so the same error applies. And yes, getting that to run properly is on the priority list, even though I like the first one better, and it works fine.

**Comment by WindyWinston** [comment]
A few more added -

**_BeneathASteelSky_v2.1_CD32_AGA_**
After intro it says 'Please insert disk 0' ?!

**_ValhallaBeforeTheWar_v1.2_0756_**
**_ValhallaLordOfInfinity_v1.1_**

**Comment by WindyWinston** [comment]
A weird thing I found that happens with 'Apidya'. The top part of the screen makes the sprites invisible so makes it unplayable unless you stay at the bottom of the screen ! :smile:  Also found another -

**_Apidya_v2.05_*_**
**_ApidyaSpecialEdition_v1.1_Hack_by_Earok_**

**_Clockwiser_v1.1_**
**_Clockwiser_v1.1_AGA_1900_**
Amiga crash.

**Comment by sonninnos** [comment]
Apidya works fine when forced to A1200 or "CPU Cycle-exact Speed" is 4x or higher.

Please also test around with the settings when listing these.

**Comment by WindyWinston** [comment]
Indeed it does work. I've been testing all of these with A1200 and if it doesn't work I try with cycle-exact. Not sure why I changed the model. I think i've overdosed on Amiga the last few days and i'm surprised nobody else has found anything. I'll give up.

**Comment by WindyWinston** [comment]
I tried the floppy version of a couple of these games (Clockwiser ECS & AGA, Fatman AGA) and they worked so not sure what WHDLoad is up to.

**Comment by sonninnos** [comment]
Yep, no idea why, but maybe some WHDLoad parameters/tooltypes help. The CD32 version works also on the AmigaJay's Puzzle Collection.

And indeed GrandPrixCircuit_v1.0_0008 can be removed from the list now.

**Comment by WindyWinston** [comment]
Will do. I'll have a little test when the buildbots ready and add a note about SuperSkidmarks 1.0.

**Comment by WindyWinston** [comment]
**DragonsLair2_v1.0_0059** & **SpaceAce2_v1.1_0931** now work as well because of that commit ! 3.5 Games off the list (until anymore maybe added!).

**Comment by sonninnos** [comment]
Found something interesting while finding a solution for **DeluxeStripPoker2&DataDisks_v1.0**:
- If the files are extracted and the directory is used as a filesystem, it works
- If the files are converted into a HDF, it also does not work

I bet it has something to do with that high number of files in `data/sounds/`. It does not happen with WinUAE, so whatever it is, it is curable. For some reason the crash is not identical between LHA and HDF, but it clearly is a filesystem issue, and luckily not emulation accuracy.

**Comment by WindyWinston** [comment]
I thought **PulsatorDemo_v1.1_AGA** would work now that there is an 030 option but it doesn't. Must be an added emulation thing.

So is it having trouble reading all the files from LHA's ? Could that also be why **BeneathASteelSky_v2.1_CD32** and **EyeOfTheBeholder_v0.2_AGA** ask for a disk to be inserted ?

**Comment by WindyWinston** [comment]
Found another different Amiga crash.
**HoundOfShadow_v1.0_0338**
See first post.

**Comment by WindyWinston** [comment]
Following up on the Strip Poker thing, I just converted the LHA to HDF and it worked !? I used a program that I found on EAB. 

[DeluxeStripPoker2&DataDisks_v1.0.zip](https://github.com/libretro/libretro-uae/files/4185261/DeluxeStripPoker2.DataDisks_v1.0.zip)

So it must be something to do with the LHA reading ?

**Comment by sonninnos** [comment]
Nope, both CD32 versions (normal + NoVoice) do the same "Insert disk 0" thing no matter what.

**Comment by WindyWinston** [comment]
**BeneathASteelSky_v2.1_CD32.lha** works if the files are copied to a HDF. I just tried it and no 'insert disk 0' message. Maybe your fix will fix it also. **EyeOfTheBeholder_v0.2_AGA** also asks for a disk but doesn't if copied to a HDF.

**Comment by WindyWinston** [comment]
You had to force A1200 for DuluxeStrip2 ? When I copied it to HDF it worked on Automatic.

So what was the problem in the end ?

**Comment by sonninnos** [comment]
I also tried that HDF you posted and it does not work with Automatic either.

**Comment by WindyWinston** [comment]
That is very weird. It's working for me and mine is set to Automatic. Also works with Cycle-Exact on or off.

**Comment by sonninnos** [comment]
Heh, figured it out. I always used fastforward on the loading parts, but when I don't keep my currently mapped key (Backspace) down, I also do not get guru meditation on the automatic A600 model.

**Comment by WindyWinston** [comment]
-4 !!

On **BeneathASteelSky_v2.1_CD32** there seems to be some kind of scratchy audio interference when the speech plays sometimes. You can hear it at the very beginning in-game. Is that accuracy related or something different ?

There's four left that all produce black screens so don't know if that's a related problem. Clockwiser ECS/AGA seems a weird one as well because the floppy versions work fine (and Fatman AGA).

**Comment by WindyWinston** [comment]
Latest version of **TestDrive2&DataDisks_v1.3_0588&0589&0590&0591&0818** seems to crash Retroarch after the Porsche intro. Bit weird.

**Comment by sonninnos** [comment]
Here are some updates for those notes about Arcadia and APB:
- There is now a core option for joystick port reordering which should deal with Arcadia.
- The only way to change that APB palette seems to be modifying the icon tooltype, which is not convenient at all if wanting to keep it as LHA, and especially since modifying tooltypes requires running Workbench. So as long as the slave requires that `$` char in the parameter, it can't be done via CLI.

**Comment by WindyWinston** [comment]
Cool, I'll check these out tomorrow. I haven't actually used this core for about a month! Been on the 64 a lot. That APB core option was a bad decision by the slave maker. I'll have to update my slaves too.

**Comment by WindyWinston** [comment]
Test Drive 2 still crashes after the Porsche intro but if you press 'Fire' when you see the Porsche you can skip the crash.

**Comment by sonninnos** [comment]
Ah, stupid me rushing with the fire button. Luckily that is a good kind of crash, and I found the reason: The Automatic Horizontal Position calculation goes ballistic in the animation, which slows it down a huge amount and eventually crashes. It gives negative starting values to line filling function.

So with the option at 0 it does not crash. And the crude method of skipping the function when the value is negative makes it not crash with Automatic, but I'll hunt down a better one once I fix that ZIP issue first.

**Comment by WindyWinston** [comment]
Hey man, it's been a while. Found another one for the list, **Dynamite Dux**. You get an error when running with default settings (which also happens on WinUAE) but if you force A1200 it crashes Retroarch. It works on WinUAE with A1200.

**Comment by sonninnos** [comment]
Crap, it does the same kind of crash that ***FatmanTheCapedConsumer_v1.1_AGA_0480*** does, which is still a mystery:
```
Your Amiga program just did something terribly stupid CCCCCCCC PC=009F3FB0
CCCCCCAC  0000 0000 0000 0000 0000 0000 0000 0000
CCCCCCBC  0000 0000 0000 0000 0000 0000 0000 0000
CCCCCCCC  0000 0000 0000 0000 0000 0000 0000 0000
CCCCCCDC  0000 0000 0000 0000 0000 0000 0000 0000
CCCCCCEC  0000 0000 0000 0000 0000 0000 0000 0000
009F3F90  EF24 4290 51EC 0DF5 70FF 4E75 4E71 4E71
009F3FA0  2F38 0070 4E75 2F38 0074 4E75 2F38 0078
009F3FB0  4E75 4E71 4E71 4E71 4E71 4E71 4E71 4E71
009F3FC0  514F 40D7 007C 0700 48E7 80C0 7007 C079
009F3FD0  00DF F01C C079 00DF F01E 6600 0110 7001
CPU halted: reason = 3
```

**Comment by Enkak** [comment]
SensibleWorldOfSoccer9697_v1.7_0842 crashes with a very similar error when in career mode after you pick the team.
Tried other settings but always crashes there. Same file works in FS-UAE standalone, for example.

**Comment by gabberhead** [comment]
i have testet a lot of games. 3 of them are not working as whdload and also as adf files.

Moonwalker_v1.0.lha
whdload: game not working
adf: cracktro working, but not the game
in winuae both are working

RunningMan_v1.0_0382.lha
whdload: game starts till menu, but not the game after that
adf: the same as whdload
in winuae both are working

Vigilante_v1.1_1188.lha
whdload: game not working
adf: cracktro working, but not the game
in winuae both are working

and the game as whdload file:
HudsonHawk_v1.5_1035.lha

i get only to work with the AROS Bios. With official bioses the game is not working. The Workbench Screen starts where u can set unlimited lives, but the game dont start. the screen stays black.

as adf file the game is working

**Comment by sonninnos** [comment]
Sadly even after the major update some of these do not work, but since the original poster has left the building, a new issue for all the remaining ones is for the best.

**Comment by zzedmore** [comment]
Thanks for this update. Did a quick check and these from the list now seem to work -

Clockwiser_v1.1
Clockwiser_v1.1_AGA_1900
DynamiteDux_v1.0_1183
FatmanTheCapedConsumer_v1.1_AGA_0480
HudsonHawk_v1.5_1035

The rest still don't work for unknown reasons ? (Apart from 'SuperSkidmarks_v1.1_CD32' and 'PulsatorDemo_v1.1_AGA' which are known reasons). I also found another non-working game -

PinballDreams

It just gives a black screen. Floppy version works though.

**Comment by zzedmore** [comment]
Regarding the 'Pinball Dreams' thing, it crashes when 'WHDLoad Support' is set to files. When set to HDFs it just gives a black screen. The log says this -

```
starting..
[libretro INFO] Illegal instruction: 4e7a at 002346C0 -> 002346D0
[libretro INFO] B-Trap F200 at 002346EA -> 0023470E
[libretro INFO] B-Trap F017 at 00234738 -> 0023476A
```

**Comment by gabberhead** [comment]
Since the New update, Hudson hawk is working now. But 3 games which I also testet, moonwalker, vigilante and running man are still not working. The problems for those 3 games are discribed above in my other Post.

**Comment by sonninnos** [comment]
I was able to fix the Pinball Dreams problem, but unfortunately HDFs are completely broken and I'm running out of ideas.. Those log outputs are normal and do not cause the current thing.

**Comment by zzedmore** [comment]
May as well just remove the 'HDFs' option as 'Files' is recommended anyway. No great loss!

**Comment by sonninnos** [comment]
I meant ALL HDFs, so that won't do anything..
