### ISSUE TITLE
build error   info->library_version  = "2.6.1" GIT_VERSION;

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/libretro-uae#232]
cc -fPIC -O2 -mtune=atom -O2 -DCPUEMU_0 -DCPUEMU_11 -DCPUEMU_12 -DCPUEMU_20 -DCPUEMU_21 -DCPUEMU_22 -DCPUEMU_31 -DCPUEMU_32 -DCPUEMU_33 -DMMUEMU -DFULLMMU -DFPUEMU -DUNALIGNED_PROFITABLE -DAMAX -DAGA -DAUTOCONFIG -DFILESYS -DSUPPORT_THREADS -DFDI2RAW -DDEBUGGER -DSAVESTATE -DACTION_REPLAY -DDRIVESOUND -DGAYLE -DNCR -DCD32 -DCDTV -DA2091 -D__LIBRETRO__ -DRETRO=1 -DINLINE="inline" -std=gnu99 -DLIBRETRO_PUAE -DCAPS -DA_DMS -DA_LHA   -I./sources/src -I./sources/src/include -I./libretro -I./libretro-include -I./sources/utils -I. -I./deps/zlib -c -o libretro/libretro.o libretro/libretro.c
libretro/libretro.c: In function 'retro_get_system_info':
libretro/libretro.c:2739:37: error: expected ';' before 'GIT_VERSION'
    info->library_version  = "2.6.1" GIT_VERSION;
                                     ^
make: *** [Makefile:288: libretro/libretro.o] Error 1

**Comment by sonninnos** [comment]
That happens when GIT_VERSION is not set, so according to the makefile something is preventing git from getting the value. Git not installed?

Remove/comment the ifneq and endif rows from this section, so it is always included, even when it is " unknown":
```
GIT_VERSION := " $(shell git rev-parse --short HEAD || echo unknown)"
ifneq ($(GIT_VERSION)," unknown")
    CFLAGS += -DGIT_VERSION=\"$(GIT_VERSION)\"
endif
```

**Comment by Zombie-Ryushu** [comment]
Git is installed.

**Comment by sonninnos** [comment]
..So what happens when you run that command `git rev-parse --short HEAD`?

**Comment by Zombie-Ryushu** [comment]
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by sonninnos** [comment]
You made a clone with `git clone https://github.com/libretro/libretro-uae.git` and you ran that rev-parse command in the same created directory where you ran make?

Where did you get that `-mtune=atom` since the makefile does not have it?

Please try being more helpful.

**Comment by Zombie-Ryushu** [comment]
Its actually a download of master.zip from github, not a proper git checkout. The -mtune=atom is passed by my RPM Spec due to the fact I am compiling for Intel Atom hardware.
