### ISSUE TITLE
[Request] Show selected model in status bar

### ISSUE THREAD

**Issue by WindyWinston** [libretro/libretro-uae#235]
This may be pointless but I notice that there is a lot of blank space in the status bar and wondered if it would be good to show the currently selected model. So when running a game you don't have to check the core options to see what model was set or if it's on automatic you can see what model it chose. And some ECS games have AGA enhancements. (Maybe this could also be done for vice). You could use the same naming as in the readme so you would also know how much memory is set (A500OG, A500+, CD32FR etc.) Just an idea.

Slightly off topic, in the PUAE status bar there are 4 joysticks even though I only have 1 user set in Retroarch ?

**Comment by sonninnos** [comment]
I'm kinda satisfied already with those differently colored LEDs, but I'll think about it.

Disconnect (Device Type = None) controllers 3 & 4 in Quick Menu -> Controls and they won't show anymore.

**Comment by WindyWinston** [comment]
That would rely on people knowing what color LEDs are what model (I couldn't remember to be honest) and you would also know the memory config. Completely up to you though.

I had to re-enable the other 3 users and set the Device Type to none, even though I had Max Users set to 1.
