### ISSUE TITLE
IPF disk support broken

### ISSUE THREAD

**Issue by mors-gotha** [libretro/libretro-uae#241]
Hi!
In latest PUAE bilds IPF disks don't work (retroarch linux (centos 7) crashes when a IPF disk is loaded).
IPF disks load correctly in 2020-02-09 build, PUAE (2.6.1 7506965).

Thanks for the incredible work you're doing!

**Comment by sonninnos** [comment]
Works fine with Windows, and I don't see any apparent reason why any change after that commit would affect IPFs. Can any Linux guru confirm?

**Comment by jdgleaver** [comment]
Just tested on openSUSE Leap 15.1, using the latest release of the core + `capsimg.so` v5.1 from here: https://github.com/rsn8887/capsimg/releases

Verified good IPF files load and run just fine (no crashes) - is it possible you might have bad files...?

**Comment by mors-gotha** [comment]
I confirm it doesn't work.
I use the same capsimg.so 5.1 and the IPF disks are an official realease of Team17 (i tried Alien Breed SE, overdrive and superfrog).
Retroarch crashes as soon as i load a IPF disk with the lastest build.
With the 2020-02-09 build it works perfectly

**Comment by sonninnos** [comment]
Sorry I should've been clearer that I need stdout/stderr log, since UAE outputs everything there for the time being. Searching for:
```
capsimg.dll opened
CAPS: library version 5.1
CAPS: type:1 date:24.6.2003 5:57:26 rel:615 rev:1
```

**Comment by mors-gotha** [comment]
How do i create a stdout/stderr log?

**Comment by sonninnos** [comment]
Just run RA in a console with --verbose.

**Comment by mors-gotha** [comment]
Here's the new log ;-)
[retroarch.log](https://github.com/libretro/libretro-uae/files/4188817/retroarch.log)

**Comment by sonninnos** [comment]
OK, looks like it has nothing to do with IPF, and instead you should get a crash with any other image file too. It crashes right at the point of displaying the image name in the statusbar.

**Comment by mors-gotha** [comment]
You're right. Retroarch/PUAE crashes even with ADF disks but it works with lha games.

**Comment by sonninnos** [comment]
Fix will be coming as soon as I get the next PR ready. I'll try to be quick and postpone a few things.

**Comment by mors-gotha** [comment]
Thank you again for your hard work. 
PUAE is one of the best Amiga emulator i've had the luck to try!

**Comment by sonninnos** [comment]
Please confirm if it worked, when possible.

**Comment by mors-gotha** [comment]
It works perfectly! Many thanks!
