### ISSUE TITLE
How compile.....

### ISSUE THREAD

**Issue by crystalct** [libretro/libretro-uae#254]
Could you indicate which is the latest compilable version for PS3? It is bizarre that a project started from a PS3 port is not usable for PS3.....

**Comment by KMFDManic** [comment]
@crystalct You still stuck with this?  Depending on your set-up, I can probably compile one for you.  It is an amazing Core, and one of my absolute favorite go tos.  RSN8887 and Sonninnos have done an exceptional job with the Commodore stuff:)

**Comment by crystalct** [comment]
Please, try to compile it for PS3 and let me know your deductions about it.

**Comment by crystalct** [comment]
Still waiting.....

**Comment by KMFDManic** [comment]
@crystalct was taken a little off guard by the lockdown.  It added to my workload.  I will try to compile a version for u by tomorrow am and post link here.  Remember, you will still need to handle BIOS.  I'd suggest testing with an .adf to get a quick verification.  But, you can still load/start Core to see if it at least opens.  Thanks for being patient.

**Comment by crystalct** [comment]
Just tested again after many weeks....
$ make platform=ps3
CFLAGS: -DSDL_BYTEORDER=SDL_BIG_ENDIAN -DMSB_FIRST -DBYTE_ORDER=BIG_ENDIAN -D__CELLOS_LV2__ -DHAVE_MEMALIGN -DHAVE_ASPRINTF -I./sources/utils/zlib/ -O3 -DRETRO=1 -DINLINE="inline" -std=gnu99 -DGIT_VERSION=\"" d973ea9"\" -D__LIBRETRO__
-------
/usr/local/cell/host-win32/ppu/bin/ppu-lv2-gcc.exe  -DSDL_BYTEORDER=SDL_BIG_ENDIAN -DMSB_FIRST -DBYTE_ORDER=BIG_ENDIAN -D__CELLOS_LV2__ -DHAVE_MEMALIGN -DHAVE_ASPRINTF -I./sources/utils/zlib/ -O3 -DRETRO=1 -DINLINE="inline" -std=gnu99 -DGIT_VERSION=\"" d973ea9"\" -D__LIBRETRO__   -I./sources/src -I./sources/src/include -I./libretro -I./libretro-include -I./retrodep -I./sources/utils -I. -I./deps/zlib -c -o sources/src/main.o sources/src/main.c
In file included from ./retrodep/machdep/maccess.h:9,
                 from ./sources/src/include/memory_uae.h:65,
                 from sources/src/main.c:23:
./libretro-include/retro_endianness.h:70:4: warning: #warning Defining MSB_FIRST and LSB_FIRST in compile options is deprecated
./libretro-include/retro_endianness.h:99:4: error: #error "Unknown platform"
./libretro-include/retro_endianness.h:107:4: error: #error "Bug in LSB_FIRST/MSB_FIRST definition"
make: *** [sources/src/main.o] Error 1

or.....

$ make platform=psl1ght
CFLAGS: -DSDL_BYTEORDER=SDL_BIG_ENDIAN -DMSB_FIRST -DBYTE_ORDER=BIG_ENDIAN -D__CELLOS_LV2__ -DHAVE_MEMALIGN -DHAVE_ASPRINTF -I./sources/utils/zlib/ -O3 -DRETRO=1 -DINLINE="inline" -std=gnu99 -DGIT_VERSION=\"" d973ea9"\" -D__LIBRETRO__
-------
/c/PSDK3v2/ps3dev/ppu/bin/ppu-gcc  -DSDL_BYTEORDER=SDL_BIG_ENDIAN -DMSB_FIRST -DBYTE_ORDER=BIG_ENDIAN -D__CELLOS_LV2__ -DHAVE_MEMALIGN -DHAVE_ASPRINTF -I./sources/utils/zlib/ -O3 -DRETRO=1 -DINLINE="inline" -std=gnu99 -DGIT_VERSION=\"" d973ea9"\" -D__LIBRETRO__   -I./sources/src -I./sources/src/include -I./libretro -I./libretro-include -I./retrodep -I./sources/utils -I. -I./deps/zlib -c -o sources/src/main.o sources/src/main.c
In file included from sources/src/main.c:17:0:
./retrodep/threaddep/thread.h:157:23: fatal error: semaphore.h: No such file or directory
compilation terminated.
make: *** [sources/src/main.o] Error 1

**Comment by KMFDManic** [comment]
@crystalct For the moment, see how this standalone works on your PS3.  Confirm how this runs.  I will try to adjust my compiler so it can do a proper PS3 compile for you, for P-UAE.

https://ufile.io/9dswm4n2

**Comment by crystalct** [comment]
I know it.... it isn't libretro compliant.... i would add a Amiga libretro core for my project: https://www.psx-place.com/threads/final-burn-neo-plus.28110/page-3#post-237391

**Comment by crystalct** [comment]
Contributors never replied to me (@twinaphex, @sonninnos, @rsn8887, @zeromus, @DamsRoxxx, @Alcaro, @jdgleaver, @r-type, @phcoder, @webgeek1234, @repojohnray, @loganmc10, @diablodiab, etc etc). A question to them, why do you not remove the PS3 platform from Makefile?
In this way no one will bore you with a request for compatibility with the PS3.

**Comment by KMFDManic** [comment]
@crystalct a lot of the people who have contributed generally have established compiler setups, such as for PC.  The ps3 compile likely works fine. You have to fix errors as they arise.  I, myself, want to avoid screwing my compilers up since I usually do the compiles for PC/Mini Classics.  I will still try to see if I can reasonably get it working for PS3.  Whatever you get as your current errors, refresh my memory on.

**Comment by rsn8887** [comment]
PS3 is not officially supported last time I looked.

**Comment by rsn8887** [comment]
If you look on https://retroarch.com/?page=platforms or on buildbot.libretro.com, you will see that PS3 is not officially supported by Retroarch (yet). If you can fix PS3 compilation and verify it works, please make a PR to fix the makefile.

**Comment by KMFDManic** [comment]
@rsn8887 good to know. Was not entirely sure.  By the way, props to you and Sonninnos for your continued efforts with Amiga and Commodore and all else! Stay Safe!  Ive been getting my ass kicked in Xenon 2, when I have had a free moment from work.

**Comment by rsn8887** [comment]
Ha I tried playing that on the weekend and I managed to get to level three (beat the Nautilus and Spider bosses) but that was it.

**Comment by crystalct** [comment]
Cause presence of PS3 target inside Mekefile, i thought that in the past it was compilable for PS3. But i was wrong, since commit 01 isn't. I donwloaded many commit since first. That presence is only incidental and makes the makefile more "cool".  The right word isn't "fixed" but "rewritten". 
Issue closed.
