### ISSUE TITLE
Feature request: Support for compressed CHD images

### ISSUE THREAD

**Issue by Shoegzer** [libretro/libretro-uae#257]
This would support the use of [libchdr](https://github.com/rtissera/libchdr) as other cores have done, to permit loading compressed CHD images, and permit more people to test libretro-puae against CD-based titles in particular such as Amiga CD32.

Thanks to @jdgleaver who indicated [here](https://github.com/libretro/libretro-uae/issues/246) that he will look into this time permitting.

**Comment by ToniBC** [comment]
It would be great if they implemented it, but hey, we'll see if someone gets on.

**Comment by Darknior** [comment]
Same for me, now i use CHD for all my systems and win a lot of hard drive space ...
Please if some one can add it it will be great :)
Thanks

**Comment by Shoegzer** [comment]
First, thanks @sonninnos for this great feature! 

Question, normally to load CHDs, the user would select "Load Content" from the RA main menu, browse to the CHD, and a menu of cores supporting the CHD format appears.  However, in this case PUAE doesn't appear on the list.  Understanding this method may not be supported yet, I started the core (as CD32) without content and tried "Load New Disc" afterwards, but that doesn't seem to work either.  So, how can I take advantage of the new feature?

**Comment by sonninnos** [comment]
At the moment only by launching via command line or by manually adding `chd` to `info/puae_libretro.info` extensions list, since using the online info update won't help, because the PR that updates the info has been waiting for a week now..

**Comment by Shoegzer** [comment]
That explains it, thanks.  I'll edit the info for now and otherwise await the update.
