### ISSUE TITLE
Mouse sensitivity too high

### ISSUE THREAD

**Issue by Papermanzero** [libretro/libretro-uae#26]
You cannot control the menu due to the high sensitivity.

**Comment by 777sha** [comment]
_**Reposting my similar issue that I wrote in the wrong repository:**_

OS: Windows 10 x64
RetroArch 1.7.2
OpenGL driver
AMD Rx 480
Latest version of P-UAE

I found the following issues:

The mouse is way too fast in the menu, almost impossible to use
After hitting "OK" RetroArch freezes

**Log:**
https://pastebin.com/fc42cJNj

**Console output:**
P-UAE 2.6.1
Git Commit: 0186c1b16f7181ffa02d73e6920d3180ce457c46
Build date: Mar 24 2015 22:46:15

Copyright 1995-2002 Bernd Schmidt
          1999-2013 Toni Wilen
          2003-2007 Richard Drummond
          2006-2013 Mustafa 'GnoStiC' Tufan

See the source for a full list of contributors.
This is free software; see the file COPYING for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Enumerating display devices..
Sorting devices and modes..
done
load config './././.uaerc':0
Opening cfgfile './././.uaerc': failed
load failed
failed to load config './././.uaerc'
setup_soundEntered action_replay_load ()
ROM loader.. (<none>)
Failed to open 'kick.rom'
gui message: Could not load system ROM, trying system ROM replacement.

ROM loader end
memory init end
No disk in drive 0.
Building CPU table for configuration: 68000 prefetch 24-bit
1883 CPU functions
Building CPU, 44316 opcodes (0 1 1)
CPU=68000, FPU=0, MMU=0, JIT=CPU=0.
INIT SOUND
driveclick: can't open './uae_data/drive_click_LOUD' (or './uae_data/drive_click_LOUD.wav')
driveclick: can't open './uae_data/drive_spin_LOUD' (or './uae_data/drive_spin_LOUD.wav')
driveclick: can't open './uae_data/drive_spinnd_LOUD' (or './uae_data/drive_spinnd_LOUD.wav')
driveclick: can't open './uae_data/drive_startup_LOUD' (or './uae_data/drive_startup_LOUD.wav')
driveclick: can't open './uae_data/drive_snatch_LOUD' (or './uae_data/drive_snatch_LOUD.wav')
driveclick: can't open './uae_data/drive_click_LOUD' (or './uae_data/drive_click_LOUD.wav')
driveclick: can't open './uae_data/drive_spin_LOUD' (or './uae_data/drive_spin_LOUD.wav')
driveclick: can't open './uae_data/drive_spinnd_LOUD' (or './uae_data/drive_spinnd_LOUD.wav')
driveclick: can't open './uae_data/drive_startup_LOUD' (or './uae_data/drive_startup_LOUD.wav')
driveclick: can't open './uae_data/drive_snatch_LOUD' (or './uae_data/drive_snatch_LOUD.wav')
driveclick: can't open './uae_data/drive_click_LOUD' (or './uae_data/drive_click_LOUD.wav')
driveclick: can't open './uae_data/drive_spin_LOUD' (or './uae_data/drive_spin_LOUD.wav')
driveclick: can't open './uae_data/drive_spinnd_LOUD' (or './uae_data/drive_spinnd_LOUD.wav')
driveclick: can't open './uae_data/drive_startup_LOUD' (or './uae_data/drive_startup_LOUD.wav')
driveclick: can't open './uae_data/drive_snatch_LOUD' (or './uae_data/drive_snatch_LOUD.wav')
driveclick: can't open './uae_data/drive_click_LOUD' (or './uae_data/drive_click_LOUD.wav')
driveclick: can't open './uae_data/drive_spin_LOUD' (or './uae_data/drive_spin_LOUD.wav')
driveclick: can't open './uae_data/drive_spinnd_LOUD' (or './uae_data/drive_spinnd_LOUD.wav')
driveclick: can't open './uae_data/drive_startup_LOUD' (or './uae_data/drive_startup_LOUD.wav')
driveclick: can't open './uae_data/drive_snatch_LOUD' (or './uae_data/drive_snatch_LOUD.wav')
RETRO:ROM NOT FOUND
memory init end
Reset at 00000000. Chipset mask = 00000001
00000000    2048K/4 =     512K Chip memory
00200000   10176K/0 =   10176K <none>
00BF0000      64K/0 =      64K CIA
00C00000     512K/1 =     512K Slow memory
00C80000    1024K/0 =    1024K Custom chipset
00D80000     256K/0 =     256K <none>
00DC0000      64K/0 =      64K Battery backed up clock (none)
00DD0000      64K/0 =      64K <none>
00DE0000     128K/0 =     128K Custom chipset
00E00000     512K/1 =     512K Extended Kickstart ROM (7000C2B4)
00E80000      64K/0 =      64K Autoconfig
00E90000     960K/0 =     960K <none>
00F80000     512K/1 =     512K Kickstart ROM (B2161EDB)
PAL mode V=49.9201Hz H=15625.0881Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
hardreset, memory cleared
inputdevice change 'retro pad0':0->1
Illegal instruction: 4e7a at 00F8042C -> 00F804BC
B-Trap f280 at f80410 (000000001C29F6A0)

**Comment by goedzo** [comment]
Fixed with #34

**Comment by Papermanzero** [comment]
https://github.com/libretro/libretro-uae/pull/34

This pull request fixes the bug.
