### ISSUE TITLE
WHDLoad Raspberry Pi

### ISSUE THREAD

**Issue by pawkon** [libretro/libretro-uae#265]
I'm very new to this subject and I'm having problems to run any game. I've prepared the whdload.hdf as it was described but when I'm starting the game I'm getting black AmigaDOS screen with information of "Unknown Command FAILAT" I was tying to switch between A500 and A1200 but no success. I'm using Libreelec with IAGL launcher. Without the whdload.hdv I'm only getting blue AmigaDOS screen without any info. Please tell me how to get this running. I'm not sure if it's the right place but I couldn't find any answer over the internet.

**Comment by sonninnos** [comment]
Do not prepare any HDFs manually. The new default WHDLoad is Files-mode anyway. Delete them all and let the core do them automatically.

Also make sure that the core version is new enough, that those changes are in.

**Comment by pawkon** [comment]
Here is what I did till now.

Kodi shows plugin: Comodore - Amiga (P-UAE) - Libretro 2.6.1.5.1

When trying with clean install, after copying every needed kickrom to resources/system (MD5 checked and correct)
and wav files to resources/system/uae_data and files WHDLoad.hdf, WHDLoad.prefs and WHDSaves.hdf 
from here https://github.com/libretro/libretro-uae/tree/master/whdload to the directory resources/system
after running any game with IAGL launcher I'm getting Blue AmigaDOS screen with error : "Not a DOS disk in unit 0"

After preparing the WHDLoad.hdf, which in my words means that I open it with ADFOpus and insert into it
kick34005.A500 and kick40068.A1200 into Devs/Kickstarts/ i get tge same message. I think this is because
when opening in ADFOpus there is a warning at the begining like this : ADFLib Warning adfReadBootBlock : incorrect checksum

So I tried to create my own WHDLoad.hdf simply by going back in history of GitHub to 3c78c27 commit of WHDLoad.hdf 
which doesn't have this adfReadBootBlock warning. Then I deleted everything from this file with ADFOpus
and then copied everything from newest file from master github to it. By doing that I'm getting black screen 
AmigaDOS release 1.3 showing Unknown command FAILAT. Typing DIR in AmigaDOS shows nothing.

I have also downloaded and checked files in hdf file which is providing IAGL and it seems its is everything fine.
 
here is the puae_libretro.uae file which resides in save dir of the addon:

cpu_type=68000
chipmem_size=1
bogomem_size=2
chipset_compatible=A500
chipset=ocs
ntsc=false
cpu_compatible=true
cycle_exact=true
cpu_throttle=0.0
cpu_multiplier=0
sound_output=exact
sound_stereo_separation=10
sound_interpol=anti
sound_filter=emulated
sound_filter_type=standard
floppy_speed=100
floppy_volume=100
floppy0sound=1
floppy1sound=1
floppy2sound=1
floppy3sound=1
input.mouse_speed=100
immediate_blits=false
waiting_blits=false
collision_level=playfields
gfx_center_horizontal=
gfx_center_vertical=
gfx_lores=false
gfx_linemode=double
kickstart_rom_file=/storage/.kodi/userdata/addon_data/game.libretro.uae/resources/system/kick34005.A500
hardfile=read-write,32,1,2,512,/storage/.kodi/userdata/addon_data/game.libretro.uae/resources/system/WHDLoad.hdf
hardfile=read-write,32,1,2,512,/storage/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/SuperfrogDemo_v1.1_TheOne.hdf


Changing addon settings from A500 to A1200 doesn't seem to change anything. File puae_libretro.uae from Save dir is not changing
and running the addon stand alone shows Amiga Workbench V 1.3. When trying to run the game same error with 
Unknown command FAILAT.

Trying to change manualy puae_libretro.uae from A500 to A600 also doesn't change anything because after 
trying to run the game settings are getting back to A500 while in kodi plugin settings there is still A1200 chosen

I have no idea how to get this working ...

**Comment by sonninnos** [comment]
Simply put you are using an ancient version of the core, therefore everything is futile. For instance there should not be these rows:
```
gfx_center_horizontal=
gfx_center_vertical=
```
and many more are missing. Only thing you could do is to hunt down an earlier HDF version that would work with the core version, but I do not recommend doing so, since there are too many downsides to it, for example that block error probability is too high in regular use.

FailAt is a built-in Kickstart command not included in the classic v1.3 but only in later ones which will have HD interface support, so that is a clear indicator that the Kickstart is wrong for this particular use.

If this version is the latest one you can get for the distro you are using, please inform the maintainers that it is high time to update the core. With the current version the user does not have to do anything else except make sure the Kickstarts are in "system". No manual hassling with HDFs or other files.

**Comment by pawkon** [comment]
Please tell me if the buildbot is a kind of "tree" from libretro? I've seen the buildbot releases and they are working for example in Linux/Windows but there is no repo for RPi. Well, there is but without Amiga support. There is only this: http://buildbot.libretro.com/ and I don't know how to contact them for example to ask them if they could add rpi support.

**Comment by sonninnos** [comment]
Yes, buildbot is the official libretro place.

I do have a RPI but haven't used it in years, so it will take a while for me to try to get it updated and to see first hand what is up. 

But what I remember from using it is that the cores are installable from source, as in they can be compiled manually. And that should be doing regular `git clone <this_repo_url>`, as in should get the latest version.

**Comment by pawkon** [comment]
Libreelec and probably Openelec too does not have the git and compilation options. And this is the problem. I would really appreciated if You could somehow get this working. Last time I played Amiga was more than 25 years ago and now I would like to play it with my kid :)

**Comment by pawkon** [comment]
I did that but without any answer. So here is my only hope. 
I'm also trying to do something not just sitting back and waiting and I just prepared ubuntu for cross compilation. I have compiled toolchain etc and I'm ready to try to compile p-uae. I need a little assistance. I've found config file package.mk in libreelec sources but it is also downloading some historic version so please tell me how to modifie it to get the newest version. Here is the code:

PKG_NAME="libretro-uae"
PKG_VERSION="d38f5176ad76eb62010e3ca2e51632e116e860f4"
PKG_SHA256="c7358d95d6dd7c89d50cf154f16e901e3b4d5524b510cba6b2e351dbec89f01d"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/libretro/libretro-uae"
PKG_URL="https://github.com/libretro/libretro-uae/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain kodi-platform"
PKG_LONGDESC="libretro wrapper for UAE emulator."
PKG_BUILD_FLAGS="-lto"

PKG_LIBNAME="puae_libretro.so"
PKG_LIBPATH="$PKG_LIBNAME"
PKG_LIBVAR="UAE_LIB"

pre_configure_target() {
  if [ "$TARGET_ARCH" = "arm" ]; then
    CFLAGS="$CFLAGS -DARM -marm"
  fi
}

makeinstall_target() {
  mkdir -p $SYSROOT_PREFIX/usr/lib/cmake/$PKG_NAME
  cp $PKG_LIBPATH $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME
  echo "set($PKG_LIBVAR $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME)" > $SYSROOT_PREFI$
}

**Comment by sonninnos** [comment]
Should be enough to just change the `PKG_VERSION` from that `d38f5176ad76eb62010e3ca2e51632e116e860f4` which points to Nov 22, 2019 (crikey) to the latest commit `987251c661e1fc55035cf08ddae8e6fd1cc81bfc`.

**Comment by pawkon** [comment]
There is something wrong with this file because I'm getting

PROJECT=RPi DEVICE=RPi2 ARCH=arm scripts/create_addon libretro.uae
ERROR: no addons matched for filter libretro.uae
For more information type: ./scripts/create_addon --help

and the file now is:

PKG_NAME="libretro-uae"
PKG_VERSION="10.0.1"
PKG_SHA256="2b7b4724d72adb998bededbee118d494e3da2dd8f03fa39dac8804c169947d74"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/libretro/libretro-uae"
PKG_URL="https://github.com/libretro/libretro-uae/archive/987251c661e1fc55035cf08ddae8e6f$
PKG_DEPENDS_TARGET="toolchain kodi-platform"
PKG_LONGDESC="libretro wrapper for UAE emulator."
PKG_BUILD_FLAGS="-lto"

PKG_LIBNAME="puae_libretro.so"
PKG_LIBPATH="$PKG_LIBNAME"
PKG_LIBVAR="UAE_LIB"

pre_configure_target() {
  if [ "$TARGET_ARCH" = "arm" ]; then
    CFLAGS="$CFLAGS -DARM -marm"
  fi
}

makeinstall_target() {
  mkdir -p $SYSROOT_PREFIX/usr/lib/cmake/$PKG_NAME
  cp $PKG_LIBPATH $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME
  echo "set($PKG_LIBVAR $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME)" > $SYSROOT_PREFIX/usr/lib/$
}

**Comment by sonninnos** [comment]
I don't get it, why is the `PKG_VERSION` now "10.0.1", where does that come from? Does something create that script or did you just replace the string in the wrong place? As in not in the `PKG_URL`, but just the `PKG_VERSION` variable.

**Comment by pawkon** [comment]
I was experimenting :)
At the begining it was like this below but error was the same:

PKG_NAME="libretro-uae"
PKG_VERSION="987251c661e1fc55035cf08ddae8e6fd1cc81bfc"
PKG_SHA256="2b7b4724d72adb998bededbee118d494e3da2dd8f03fa39dac8804c169947d74"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/libretro/libretro-uae"
PKG_URL="https://github.com/libretro/libretro-uae/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain kodi-platform"
PKG_LONGDESC="libretro wrapper for UAE emulator."
PKG_BUILD_FLAGS="-lto"

PKG_LIBNAME="puae_libretro.so"
PKG_LIBPATH="$PKG_LIBNAME"
PKG_LIBVAR="UAE_LIB"

pre_configure_target() {
if [ "$TARGET_ARCH" = "arm" ]; then
CFLAGS="$CFLAGS -DARM -marm"
fi
}

makeinstall_target() {
mkdir -p $SYSROOT_PREFIX/usr/lib/cmake/$PKG_NAME
cp $PKG_LIBPATH $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME
echo "set($PKG_LIBVAR $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME)" > $SYSROOT_PREFI$
}

After getting this error I've tried to compile another version available in the repo like game.libretro.uae which was compiled just fine so I changed this file too. After trying to compile 
 game.libretro.uae again got the same error :/

**Comment by sonninnos** [comment]
Same error as in: `ERROR: no addons matched for filter libretro.uae`? Shouldn't it be "libretro-uae", as in the PKG_NAME?

Maybe also that SHA256 is checked somewhere, so that should also be calculated from whatever it is calculated from. I'm afraid I don't have the knowhow to help you any further.

**Comment by pawkon** [comment]
nope ... still nothing and now the file looks like this

PKG_NAME="libretro-uae"
PKG_VERSION="987251c661e1fc55035cf08ddae8e6fd1cc81bfc"
PKG_SHA256="c7358d95d6dd7c89d50cf154f16e901e3b4d5524b510cba6b2e351dbec89f01d"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/libretro/libretro-uae"
PKG_URL="https://github.com/libretro/libretro-uae/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain kodi-platform"
PKG_LONGDESC="libretro wrapper for UAE emulator."
PKG_BUILD_FLAGS="-lto"

PKG_LIBNAME="puae_libretro.so"
PKG_LIBPATH="$PKG_LIBNAME"
PKG_LIBVAR="UAE_LIB"

pre_configure_target() {
  if [ "$TARGET_ARCH" = "arm" ]; then
    CFLAGS="$CFLAGS -DARM -marm"
  fi
}

makeinstall_target() {
  mkdir -p $SYSROOT_PREFIX/usr/lib/cmake/$PKG_NAME
  cp $PKG_LIBPATH $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME
  echo "set($PKG_LIBVAR $SYSROOT_PREFIX/usr/lib/$PKG_LIBNAME)" > $SYSROOT_PREFIX/usr/lib/cmake/$PKG_NAME/$PKG_NAME-config.cmake
}

**Comment by sonninnos** [comment]
Looks like you need to find an expert then. Just for kicks why not also try if the buildbot's linux arm builds work with rpi.

**Comment by pawkon** [comment]
But there is no buildbot's linux arm builds for linux arm. puae-librelec should be in here http://buildbot.libretro.com/nightly/linux/armhf/latest/ as it is in here http://buildbot.libretro.com/nightly/linux/x86_64/latest/ for Linux x64. This is why I asked if there is someone here who could add this to the buildbot's repo :)

**Comment by sonninnos** [comment]
Oh right. It actually should be there but the building fails. It just needs to be fixed, so let's hope it is something so easy that I can figure it out.

**Comment by pawkon** [comment]
:) fingers crossed :)

**Comment by pawkon** [comment]
I've made it :) I was able, with a help from Libreelec forum (with a special thanks to HiassofT), to compile latest available version of p-uae for RPI Libreelec.  I'm attaching it to this post if someone will need it. It was made for RPi 2 and 3 arm Libreelec and it is working flawlessly.
[game.libretro.uae-2.6.1.6.1.zip](https://github.com/libretro/libretro-uae/files/4455388/game.libretro.uae-2.6.1.6.1.zip)

**Comment by sonninnos** [comment]
Great! Sounds like there is not enough horsepower. Changing the default CPU compatibility option from "Cycle-exact" to "Normal" should give a performance boost at the expense of compatibility, of course.

**Comment by pawkon** [comment]
Changing that didn't helped :/ The weird thing is that the same problem I'm experiencing with my Ubuntu Intel Core i5 ...

**Comment by sonninnos** [comment]
Some RA settings may be to blame then, since I don't have any sound problems with i5-9600K.

Happens on all games/images and in the same way?

**Comment by pawkon** [comment]
hmm... it seams that some games are working just fine and the others not. I know that AGA games are more demanding so I will do some more testing. I have 2 more questions if it's not a problem ... while loading a game there is no disk drive sounds and what is more important there is no reaction for controller and keyboard. Do I have to do any configuration? I have a dualshock3 which is working in Kodi menu and in for example SNES just fine.

**Comment by sonninnos** [comment]
There is a core option for disk drive sounds with volume control hidden under another core option (Show Audio Options).

That input thing is totally a frontend (RetroArch) issue. I haven't tested DS3 directly as I only use it wireless with ScpToolkit which makes it visible as a regular X360 controller and thus naturally works without tinkering.

**Comment by pawkon** [comment]
Maybe I'm wrong but it seems that there is a problem in a core because there is no profile for DS3. To be more precise, when the game was loaded I was able to enter quick settings menu of the core (with a tv remote) and under control setting there were only profiles for Kodi, Computer Mouse and Keyboard and while I was in the settings I was able to use my ds3 controller. After returning to the game I couldn't use it again. I've also checked my kodi controll profiles and there is a DS3 profile installed. Moreover while trying tu run Amiga games with pc keyboard is also not working. I'm able to press only Esc to see black Amiga screen with info that there is no action for this key and I'm unable to get back to the game after that. On the PC i have a version from buildoot.

**Comment by sonninnos** [comment]
Yes you are wrong, the core does not, can not and should not have anything to do with any physical controllers.

Having profiles for controllers is the job of the frontend, not the core. The core only deals with virtual "RetroPads", and the frontend dictates what physical controller that is.

And F10 is not supposed to do anything else except press Amiga F10. Please read the current readme: https://github.com/libretro/libretro-uae/blob/master/README.md

Also delete the old configs which the old core made. Depending on the RA settings it is either conveniently on a separate file under `config/PUAE` or not so conveniently in a shared global file `retroarch-core-options.cfg` in RA root dir.

**Comment by pawkon** [comment]
Thanks for the correction, now I understand. 
But getting back to DS3 problem, I don't have the file You have mentioned. I have Libreelec as the OS and a IAGL as a starter for games which runs libretro-puae. So what I see is that the IAGL under Libreelec is starting a hdf game in libretro-puae. There is nothing more between, like retroplayer. So in this case is it a problem in IAGL or Kodi? As I mentioned before in Kodi everything works fine and also running in IAGL games from for example SNES also works fine. I'm sorry but I'm feeling confused and don't know where to look for a solution. I'm so close to play a game but very far to controll it :)

**Comment by sonninnos** [comment]
Sure it is confusing, because you basically have two frontends. Kodi launches RetroArch which launches the core. All core related settings would be wherever RetroArch is. If that SNES is also running on RetroArch and there the controls work, there is no reason why it would not work with this core with the exact same settings. It would be best to start with a clean slate, since you have already started the old version of the core, which will have different defaults, but should not really cause any havoc.

And more confusingly there are 2 different Input menus while in RetroArch, one for the frontend where you would bind the actual controllers, and one for the core where you can change a different controller which the core sees.

For example in this core there are the regular RetroPad which is a normal joystick with all the extra buttons remappable to keyboard keys, the CD32 pad, the analog joystick, and the keyboard, useful for pinballs and the likes. Do not change that option unless you need to, so keep the first port as RetroPad.

If you can control the RA menu where those options are with the same controller, and then suddenly it stops working while using the core, then I have no idea what causes that, and if I can't reproduce it, there is nothing I can do about it.

Also: What games are you trying and does the statusbar joyport indicators show any life at all?

**Comment by pawkon** [comment]
I'm trying to run Superfrog, Street Fighter, S.D.I and few more. 
I have no idea what is statusbar joyport indicator. Where to check it?
I will make one more test. If I understand it correctly keyboard should work out of the box in RA and games. I have an extra (clean) Ubuntu VMWare so I will install there a Kodi, IAGL and p-uae from buildboot repo as I did before. I will see if it will work from a scratch. If not then this will be a way to reproduce the problem

**Comment by sonninnos** [comment]
The statusbar opens by default with F12, and also via the "STBR"-key in the virtual keyboard, which opens with F11 or RetroPad Select.

**Comment by pawkon** [comment]
F11 and F12 are not working. Here is a full debug : https://pastebin.com/6JwnjKnd
I pressed almost every key on keyboard but nothing happens in the game

**Comment by sonninnos** [comment]
Does the keyboard work in any other computer core, like dosbox? That log clearly shows that buttons are pressed, but indeed that is a Kodi log (which I know nothing of, but I do use Kodi for watching videos), and there are few things I find suspicious:

```
2020-04-10 11:07:03.536 T:140061383809152   DEBUG: AddOnLog: Commodore - Amiga (P-UAE): Loading libretro buttonmap /home/pilot/.kodi/addons/game.libretro.puae_libretro_buildbot/resources/buttonmap.xml
2020-04-10 11:07:03.536 T:140061383809152   DEBUG: AddOnLog: Commodore - Amiga (P-UAE): Detected buttonmap version 2
2020-04-10 11:07:03.537 T:140061383809152   DEBUG: AddOnLog: Commodore - Amiga (P-UAE): Loaded buttonmap at version 2
2020-04-10 11:07:03.537 T:140061383809152   DEBUG: AddOnLog: Commodore - Amiga (P-UAE): Loading controller topology "/home/pilot/.kodi/addons/game.libretro.puae_libretro_buildbot/resources/topology.xml"
```
What are these buttonmaps?

```
2020-04-10 11:07:03.546 T:140061383809152    INFO: Loading controller layout: /home/pilot/.kodi/addons/game.controller.keyboard/resources/layout.xml
2020-04-10 11:07:03.548 T:140061383809152    INFO: Loading controller layout: /home/pilot/.kodi/addons/game.controller.mouse/resources/layout.xml
2020-04-10 11:07:03.548 T:140061383809152    INFO: Loading controller layout: /usr/share/kodi/addons/game.controller.default/resources/layout.xml
```
And what are these layouts? None of these are dictated by the core.

Also with a huge bunch of these you won't be having proper fun even if you get it working: 
```
2020-04-10 11:09:17.010 T:140058816411392   DEBUG: RetroPlayer[AUDIO]: Audio delay (300.25 ms) is too high - flushing
2020-04-10 11:09:17.351 T:140058816411392   DEBUG: RetroPlayer[AUDIO]: Audio delay (310.03 ms) is too high - flushing
2020-04-10 11:09:17.506 T:140058816411392   DEBUG: RetroPlayer[AUDIO]: Audio delay (305.42 ms) is too high - flushing
2020-04-10 11:09:18.048 T:140058816411392   DEBUG: RetroPlayer[AUDIO]: Audio delay (308.63 ms) is too high - flushing
2020-04-10 11:09:18.300 T:140058816411392   DEBUG: RetroPlayer[AUDIO]: Audio delay (300.60 ms) is too high - flushing
2020-04-10 11:09:18.451 T:140058816411392   DEBUG: RetroPlayer[AUDIO]: Audio delay (304.61 ms) is too high - flushing
2020-04-10 11:09:18.755 T:140058816411392   DEBUG: RetroPlayer[AUDIO]: Audio delay (300.30 ms) is too high - flushing
```

Also you said:
> There is nothing more between, like retroplayer

But the log clearly says RetroPlayer in a bunch of things. I don't understand much of this, but I'm pretty sure the core is not to blame for these problems.

**Comment by pawkon** [comment]
These are the 2 files from /home/pilot/.kodi/addons/game.libretro.puae_libretro_buildbot/resources/
[buttonmapANDtopology.zip](https://github.com/libretro/libretro-uae/files/4464788/buttonmapANDtopology.zip)
This is the keyboard layout from /home/pilot/.kodi/addons/game.controller.keyboard/resources/layout.xml : 
[layout.zip](https://github.com/libretro/libretro-uae/files/4464789/layout.zip)
This is the mouse layout from /home/pilot/.kodi/addons/game.controller.mouse/resources/layout.xml: 
[mouselayout.zip](https://github.com/libretro/libretro-uae/files/4464791/mouselayout.zip)
This is the default layout /usr/share/kodi/addons/game.controller.default/resources/layout.xml: 
[defaultlayout.zip](https://github.com/libretro/libretro-uae/files/4464792/defaultlayout.zip)

The first 2 files in my opinion are the virtual controller from p-uae settings and the rest 3 files are addons of profiles installed in kodi. There is also 3 other addons of the controller for SNES games and in SNES everything is working.

Don't bother "Audio delay (300.25 ms) is too high - flushing" because as I told earlier I have installed everything from the scratch on a virtual machine with a minimum of ram an processors. On a real hardware there is nothing lik that.

**Comment by sonninnos** [comment]
I can't see anything odd about those either. I guess I have to try to install a virtual machine and try it out then.

But thanks to @phcoder the buildbot now has the missing linux-arm-builds if you can test those too.

And good, I assumed that audio delay was with RPI, phew.

**Comment by pawkon** [comment]
I have tested the new version from buildbot. The good thing is that it doesn't need WHDLoad.hdf which is very good. There are only kickstart roms needed. BUT unfortunatelly problem with controllers still persist :( I gave my version to another person with RPi to test and he got the same problem. I don't know what controller he uses but I can ask him if it changes anything. So if it's not a problem for You could You please try to reproduce this problem in a few simple steps as I wrote here https://github.com/libretro/libretro-uae/issues/265#issuecomment-612153280

**Comment by pawkon** [comment]
Hi, did You manage to reproduce the problem ? Need any help with Ubuntu?

**Comment by sonninnos** [comment]
Sorry, I haven't had the time to do help desk, I've been busy with other stuff.

**Comment by pawkon** [comment]
Sure! If You will find any free time please remember about me :)

**Comment by sonninnos** [comment]
Okay, I finally had some examination, and there sure are plenty of things wrong, but not in this core. All of these problems are frontend problems:

1. No place to plug controllers in, and by default it only outputs to the log that Port 1 is unplugged. With RetroArch as frontend all 4 ports are plugged in as RetroPads. The Controls menu under Select+X/Guide is very gimped and does not allow proper configuration of the ports and the device types. Without the device type all CD32 games are out of the question, even if the default RetroPad could be somehow made to work, but even that is not happening.

Luckily wireless X360 works through the virtual machine, and I can control Kodi with the controller no problem. Also there does not seem to be a way to access those shortcuts (Select+X/Guide & Select+Start) with the keyboard at all.

Installing the emu-addon does install a mouse & keyboard addons, and they do work fine in the emu, but of course only when running software that responds to mouse & keyboard. The keyboard is not triggering any of the core functions like it should. So the frontend bypasses that part also somehow.

2. Rewind is enabled by default, and I can't find where it can be disabled. It causes heavy slowdown on this core.
3. The core options are forcefully alphabetized, option labels and sublabels are not visible, making them much more cumbersome to use.
4. Aspect ratio is by default stretched beyond belief, and it can be changed, but none of the options are the real default "Core provided".
5. The "Libretro Compatibility" addon only has one option, which is useless and even typoed: "Crop overscap"..


So without any place to configure the controllers to do what they are programmed to do in the core, as in be plugged to a certain port and also to emulate the mouse in the other port, it looks like with this method for now you are stuck to games that can be really controlled with keyboard+mouse (Cannon Fodder, Syndicate, etc).

Maybe the only thing missing is just some other controller addon..? I've spent way too much time on this already to dig deeper.

I suggest you close the issue and redirect the findings to those who dev the RetroPlayer addon. It clearly is not ready for primetime yet, but the concept sure is promising though, even if IAGL downloads are extremely slow. There is nothing to be done on this end, like the crystal ball said.

**Comment by sonninnos** [comment]
This can be closed then, because the issue no longer has anything to do with the title, and also because it is also not really our problem.

**Comment by pawkon** [comment]
Yes, thank You very much for Your time and I'm sorry for not responding but few days ago my child was born :) I'm closing this thread and thanks again!

**Comment by sonninnos** [comment]
No sweat, first things first and congrats!

**Comment by mmarodin** [comment]
I'm using a Raspberry 4B with LibreELEC, using kickstart ROM of Amiga500.
I have the "Unknown Command FAILAT" error when a game try to start.

I have just read all the thread ... I understood that FailAt could not be used with 1.3 release ok kickstart.
But if I try to set A1200 in the AddOn configuration, it does not work.

Do you have any other news from May? :)
Please let me know, thanks.
Bye

**Comment by sonninnos** [comment]
It does not work how? Please post the verbose log. And make sure you are not running some ancient core version.

**Comment by mmarodin** [comment]
Sorry, I was using a wrong version of kickstart files.
Now games load correctly ... but I have to undestand how to use my bluetooth controller :(
