### ISSUE TITLE
[Android] Zipped floppies & Whdload 'Files' mode not loading content

### ISSUE THREAD

**Issue by WindyWinston** [libretro/libretro-uae#269]
I just tried to load a single ADF (zipped) and the Whdload file requester keeps appearing ?!?

**Comment by sonninnos** [comment]
Works fine here. Are there any other files inside the zip and is the core version fresh? I fixed it pretty recently to not care if there are other files, but maybe I missed something.

Before that if there was anything extra, like a text file, it would go into directory mode, as in treat it as a WHDLoad-zip.

**Comment by WindyWinston** [comment]
Sorry for the late reply. Weird things are happening. It must just be Android. I tried deleting all the files in the 'Saves' directory and now the WHDLoad LHA's don't boot. If I switch the 'WHDLoad Support' option to 'HDFs' then they work. Are there any other Android users that can confirm this ? @jdgleaver

**Comment by sonninnos** [comment]
Files-mode still works fine under Windows at least.

**Comment by WindyWinston** [comment]
Everything seems to work fine on Windows (but the buildbot is still at https://github.com/libretro/libretro-uae/commit/31c02626049e91cceb13ea38b0d5629c2061bc90)

On Android it's https://github.com/libretro/libretro-uae/commit/d88daed0dc49e9b9b63548b365332fb21ed0e393 . Hope someone else can confirm.

**Comment by jdgleaver** [comment]
Yes, I can confirm that the current Android build is broken.

It creates the `WHDLoad` directory structure, but it's empty. It does indeed seem that `ZLIB` isn't working any more. I don't know if anything else is broken... (that commit diff is too long to go through, and I don't know assembly...)

**Comment by WindyWinston** [comment]
Great, but that's not good to hear. Is that because of phcoder's recent 'cleanup' ?

**Comment by sonninnos** [comment]
I'm sure the reason is found and dealt with soon, no biggie using the previous version in the meantime.

**Comment by WindyWinston** [comment]
All seems to work again now, thanks.
