### ISSUE TITLE
Xenon 2 CDTV failure to load, except when model is CD32

### ISSUE THREAD

**Issue by KMFDManic** [libretro/libretro-uae#272]
Xenon 2 CDTV Version seems to get stuck on Black Screen with a little red dot displaying at top left.  Most other games loaded absolutely fine for me!  And, Space Wars did not seem to allow me any controls, aside from the Xenon 2 Test.  Curious if you guys get the same results on your end on these 2 specific games.  Xenon 2 is quite possibly the best game on CDTV, bar none.  So, would be cool if there is a conflict, we can figure out what causes it!

**Comment by sonninnos** [comment]
I just recently tried Space Wars and it worked fine. Gameplay is pretty bad though compared to Star Control.

That red dot seems to be the mouse cursor, and any keys do nothing. No idea what causes it to get stuck there, but it does not happen in CD32 mode.

**Comment by KMFDManic** [comment]
@sonninnos thanks for the quick reply. I will try Space Wars again.  I've opted for Amiga Xenon 2.  But, it would be beautiful if we could sort the CDTV Version out so we can enjoy the amazing soundtrack!  

Prehistorik and Town With No Name also worked fantastic.

**Comment by sonninnos** [comment]
I'll see what I can do, but since the same version works fine with CD32, it is not high on the list.

**Comment by KMFDManic** [comment]
@sonninnos if forcing it to CD32 works, then definitely don't make it a priority.  I was just curious about what conflict might prevent it from working.  I believe same issue was present in the PC Emulator, too.

**Comment by Gravity-Grave** [comment]
I am also having this same problem with Xenon 2. I used to be able to boot it successfully with the CD32 bios, before the CDTV bios was introduced. But now, when I select to load with either of the two CD32 model options, the system still seems to default back to the black CDTV loading screen. If I try deleting the CDTV kickstart file from the system folder, all CDTV games then refuse to load, giving me a 'Failed to load content' notification. I have also tried toggling through the Cycle-exact, Normal and More Compatible CPU options, but they don’t appear to make a difference.
I can’t find a way to force CD32 anymore. Is there something I am doing wrong?
I am on a Windows PC, Retroarch 1.8.5, PUAE (2.6.1 bd2b98f)

I have noticed that WinUAE will also get stuck on this same black screen with red cursor dot, but if I press reset, the game always seems to boot up successfully on the second attempt. This rebooting technique doesn't appear to working for me in Retroarch. I’ve also noticed that WinUAE is using a different CDTV bios (MD5: 82A21C1890CAE844B3DF741F2762D48D.) WinUAE refuses to load the CDTV bios file used by Retroarch.

**Comment by sonninnos** [comment]
Filename matching will override everything, so if the filename has "CDTV" in it, just remove it and it will go to CD32.

I also tried some other CDTV version 2.3 I found, but the CDTV boot screen is red tinted with it, so I let it be 1.0 for now.

**Comment by Gravity-Grave** [comment]
I don’t have CDTV in the names of any of my files. Most of my CDTV set are from the TOSEC collection and they all retain their original file naming conversion. However, I believe my copy of Xenon 2 comes from Redump collection and my files are named:

Xenon 2 - Megablast (Europe) (En,Fr,De,It).cue
Xenon 2 - Megablast (Europe) (En,Fr,De,It).bin

Please ignore the last part of my previous comments regarding WinUAE using a different bios file. I am not a regular WinUAE user and was mistakenly looking at ‘Main ROM file’ options when I should have been concentrating on the ‘Extended ROM file section. WinUAE is also using CDTV v1.00.

P.S. Thanks for all the excellent work you’ve put into this core over the last 8 months, or so. It’s been a real pleasure to watch something which was essentially broken, be transformed into such a polished piece of software. Much respect!

**Comment by sonninnos** [comment]
Now that is odd.. The only way I can make it CDTV is either the core option or the filename tag. As in Model at Automatic picks CD32 and the CD32 models pick CD32, on start and on core restart.

Thanks-a-bunch! The version before the intervention sure didn't "make it possible", so something had to be done, heh.

**Comment by Gravity-Grave** [comment]
Correct!! Yes, CDTV was in the name of the root folder where all my games were stored! As soon as I altered the folder name, the games successfully booted. I didn’t realise the core was checking folder names too!
I think we should have some kind of way around this. I rarely use the system naming on the roms files, other then AGA, but I think it could be useful to have a File/Folder Name toggle option, or as you say, when automatic is selected.

**Comment by KMFDManic** [comment]
Having a folder name automatically load game types is actually a nice little hidden gem, if you think about it.  Wonder if AGA folder would also trigger that type.  I don't mind that at all.

**Comment by sonninnos** [comment]
Yes all file tags do the search from the whole path.

I have the above mentioned model hierarchy change ready and looking good, but I'll be testing some more before pushing.

**Comment by KMFDManic** [comment]
The folder thing is excellent, as some platforms have issues with parenthesis for name types.

**Comment by Gravity-Grave** [comment]
I have no coding knowledge, so don’t know how simple or complex such a thing would be. But how about a menu toggle which allowed for systems to be selected under the following naming conventions.

Files Names Only / Folders Names Only / Either / Off

Would this be a practical solution?

**Comment by sonninnos** [comment]
I don't see all that worth the trouble now after this smallish change. It does look simple on the surface, but will complexify and uglify the actual matching parts of the code by a lot.

**Comment by KMFDManic** [comment]
Did some retesting and folder names working flawlessly.  Being that the core has a fairly steep learning curve to begin with, it should be easy enough to relate this information to those who do utilize it.

**Comment by sonninnos** [comment]
Sure, I'll add it to the Readme and rephrase the verbose log output.

**Comment by Gravity-Grave** [comment]
I look forward to seeing your changes. Thanks again!

**Comment by KMFDManic** [comment]
@sonninnos excellent way of handling things.  You are welcome to close this issue anytime you want.  Thanks so much:)

**Comment by sonninnos** [comment]
Much obliged! I say there is no harm keeping the issue open until Xenon 2 is running on CDTV. Maybe change the title a little.

**Comment by Gravity-Grave** [comment]
I’ve done a little bit more experimenting with this and have found that, although Xenon 2 is a PAL game, if you force NTSC mode the game will boot up using the CDTV bios. Very strange!

I’ve seen somebody suggest that the disc insert timings are a little different with the NTSC bios and if you want the game to boot in PAL mode, a slight delay needs to be added to the disc insert for this particular game to boot.

**Comment by WindyWinston** [comment]
Yes, if you boot the core in CDTV mode, wait for the CDTV logo to appear, then mount the Xenon 2 image it boots fine. There are a couple of games like this that will only boot after the logo/workbench hand is shown.

**Comment by Gravity-Grave** [comment]
I hear that Total Carnage on CD32 is also fails to boot if no disc delay command is implemented. I can confirm after quickly testing that Total Carnage doesn’t appear to load past the bios screen when in either ‘Automatic’ or ‘CD32 (2MB Chip)’ mode. However, it will boot successfully when forced into ‘CD32 (2MB Chip + 8MB Fast)’ mode.

**Comment by sonninnos** [comment]
Interesting. If that insert delay does not cause annoyances with other games, I'll increase the default. If yes, then I guess it is core option time.

Sounds very odd that FastRAM would be helping with anything like this. It shouldn't have any other difference.

**Comment by Gravity-Grave** [comment]
Perhaps doubling the CDTV’s system RAM to 2MB and having CD32 default to the 8MB Fast RAM model would be enough to fix these problems without needing to bring in a disc delay feature? I’ve just tried boosting the system RAM of CDTV to 2MB within WinUAE. Once that's done, Xenon 2 then seems to load without issue when in PAL mode.

**Comment by sonninnos** [comment]
I'm afraid that would cause more problems than it would solve. But all kinds of tests are welcome. At least I remember that there are CD32 games that do not like Fast at all, but could be wrong.

I've also been planning to add a feature that would allow replacing those predefined models there currently are with custom conf files, like the recently added global conf file. For cases where someone would rather run A500+ with more Chip or more Bogo, or A1200 with only 4MB Fast. Maybe not so much needed, but it would be simple to add. Currently it almost could be done with .uae-files, but they would have to be created for every single instance.

Exposing a memory core option may be nice to have, but ugly to pull off, since there are so many configurations that only work with certain models, and currently RA menu system does not allow a clear and realtime way of hiding options depending on some other option.

**Comment by WindyWinston** [comment]
Is there really much point to this just for one game (Xenon 2) ? It does the same thing on WinUAE so it's probably correct behaviour. Just put 'CD32' in the filename and it will boot fine.

**Comment by Gravity-Grave** [comment]
> Is there really much point to this just for one game (Xenon 2) ? It does the same thing on WinUAE so it's probably correct behaviour. Just put 'CD32' in the filename and it will boot fine.

This is very true! It is what I am now doing to launch the game. I was just wondering if there was perhaps a more elegant solution that would fix this issue, as other people will likely to run into this problem in the future.

**Comment by sonninnos** [comment]
As it turned out it is not the only game that requires the delayed insert, I'll add the option for it, since it would be the most user friendly and general solution.
