### ISSUE TITLE
Feature Request Idea: Variable Frame Skip PER Model Type

### ISSUE THREAD

**Issue by KMFDManic** [libretro/libretro-uae#285]
Everything has been absolutely fantastic, bar none.  But, I got to thinking of one thing that would really be a nice addition.  On lower spec platforms, AGA games clearly won't run well unless frame skip is applied.  But, if you do a "universal" frame skip, it will affect games that do not need it.  Maybe, just maybe, if it doesn't complicate the code set all too much, Core Options for Variable Frame Skips Per Model Type, such as AGA = 0, 1, 2, and so on.  With Model Detection already in place automatically or recursively, this would be beautiful indeed to be able to run Aladdin AGA with frame skip and Giana Sisters without, without needing to muck about with anything that can create a flustercluck or sorts.

Thanks as always, both of you @sonninnos and @rsn8887 for taking into account any of my feedback and ideas!  It has truly made the entire Amiga/Commodore 64 thing all that much cooler!  I am still absolutely glad that @fr500 entertained my keyboard to controller mapping idea a few years back!  That is still, by far, one of the absolute best additions ever added for many of the PC Cores that don't have keyboard accessibility!

Thanks again, as always!  No complaints otherwise.  Just trying to think of anything that can be enjoyed by others on EVERY platform:)

And, of course, anything needing tested, I can compile immediately and verify on my end.

**Comment by KMFDManic** [comment]
Additionally, a friend of mine who had personally been testing out additions, as well as anything I change for lower spec, had this little bit of feedback to give.  Just a few observations that could be interesting to read.  Feedback is always a good thing:)

""When it comes to the Amiga though then there's no basic standard of resolution for games due to the way the Amiga works which meant programmers could (and did) write games with all sort of different screen resolutions that varied from game to game (well for many of them anyway)...

So to get the best out an Amiga game on a modern day screen and the SNES native resolution of 720, then you really have to change each games x, y resolution and postion for each individual game so that it fills the biggest part of the screen and you don't have huge black borders surrounding a game and a tiny visible play area (especially true for NTSC games)...

So there's not really any general presets you could include that would cover each and every possible individual game people may use. It's easy enough using RetroArch's menus to edit them to suit each game the only issue is as I explained is it not saving all of the settings you made in the .cfg file for each game and then having to edit them manually and add the missing options in...

Not sure what the cause of that is or why it varies each time you save a .cfg file for a game as it can be any of the options you've changed that can be missing from the .cfg file and there's no consistency to which ones might be missing, it's pretty random at times...

One thing I hope you can add/hard code would be a "50.000000" hz setting as most Amiga games are PAL and there's only a "60.000000" hz setting in the options and to change the setting to 50hz you currently have use the 2048 samples part to try and register something as 50Hz, that would be a handy and time saving feature to add if possible...

Main issue for me with PUAE has been a long standing one which I've not be able to find a way to resolve (perhaps it's there and I've missed it) and that's not being able to set the mouse as default when you boot up an Amiga game as quite a number of games require mouse input for their use and not a joystick...

I know you can set up a joypad button (the method I currently use) or now even use the virtual keypad to toggle between the mouse or joystick but that means having one less button available on the joypad to toggle the mouse or bring up the virtual keypad and with many Amiga games often requiring numerous key presses to play them and with the limited buttons a joypad has then that's one less button available that could be used for one of those often much needed key presses...

It would really great and very handy if there was an option to set the mouse or joystick as default which could be picked in RetroArch and saved in a games .cfg file (or even a command line/ argument that could be added while installing the game in HakChi) if that would be possible... :-)

One other thing I've often wondered/ am curious about when it comes to emulating the Amiga (I can write anything for the Amiga or C64 in Assembly language or machine code but when it comes to emulators then that is way beyond my scope)...

The Amiga's native audio output is only on average 22,050 kHz for the majority of games up to a maximum of 29kHz (that was rarely used in games) but emulators seem to insist on converting that up to 48 kHz or 44.1 kHz and as often in lot of Amiga games the audio and the amount of processing power it takes (especially on something not exactly that powerful as far as processing power goes like the SNES Mini) then that means for a lot of games to get audio without judder or hiccups then you have to skip a frame to get the audio play smoothly (though that has improved a lot with the most recent versions of RetroArch and PUAE)...

So would it not save a some or perhaps a lot of processing power if the audio was set to the Amigas native (most used when it comes to games output) of 22.050 kHz as converting it up to 44.1 or 48 kHz doesn't actually improve the sound quality and if by not converting it up would that therefore save on processing power which could then be used for other parts of the emulation and mean that there'd be no need for any frame skipping on most games that currently need at least one frame dropped for the audio to be glitch free ???

As said I am clueless when it comes to actual emulators and the very clever coding involved in such a task as writing them but have often wondered about the audio side of things which has always been an issue when using hardware with limited processing power and wondered if you could throw some light on that subject for me... :-)

Thanks as always for all your work and especially you taking the time to reply to people with questions/ suggestions as it's much appreciated and is something that I find is quite rare these days with many coders... :-)"

**Comment by sonninnos** [comment]
Actually I already have been pondering on a feature that would almost make that possible. As in allow replacing the current model presets with files like `puae_libretro_A1200.uae`. The downside of course is that all options added there will be replaced by the realtime core options. All options update at once when any unrelated is changed.

It is always worth trying if lowering the CPU speed helps with performance issues. The default for 68020 is for some reason faster and more resource hungry than needed. I had a jab at it a while back, but reverted, because I noticed some odd downsides after all. I'll look at it again sometimes.



And regarding that great wall of chi^H^H^Htext:
1. The core already has a zoom option with many presets + a very well performing automatic option. It could use a horizontal cropping bonus option though.
2. The core already delivers the exact Hz straight from UAE. Not getting the smooth 50Hz is a frontend configuration and/or hardware issue.
3. The core has supported mouse control on both analog sticks, and button mappings to RetroPad for ages. But indeed, the option to have D-Pad as mouse by default is missing, so perhaps it should be added for those who use minimal controllers.
4. The core outputs at 44100Hz, because it also supports CD audio, and changing that serves no benefits, only drawbacks.

**Comment by KMFDManic** [comment]
@sonninnos I actually thought he might have a conflict on his end, as I believe he is still even using the oldschool method of manual .uae files, rather than automatic, which I am greatly loving!  I will have to tell him, for now, how to run Analog on D Pad.  It can be done easily with the revised RetroArch Settings, Input, Player Port 1, remapping Analog to D Pad.  DOSBox works same way.  

And, I have also been careful about sound timing.  With MAME 2003 Xtreme, we had to add a smart recalculation of sound samples, since many games won't work if above 22000 Audio Rate.  For a few years, Midway Games wouldn't properly work due to trying to run at higher Sound Rate.  This even affected the timing in a game you wouldn't expect it to, RoboCop.  

I definitely try to listen to any and all suggestions.  But, sometimes, what might seem like a good change for one might end up being a bad change for many others.

I look forward to seeing how you might incorporate Frame Skipping Per Model.  I think that would be an amazing addition.

**Comment by sonninnos** [comment]
Okey dokey, with the changes in the latest PR the requested result can be achieved simply by:
- Create a file in `saves` named `puae_libretro_A1200.uae` with the contents:
 ```
cpu_model=68020
chipmem_size=4
fastmem_size=8
bogomem_size=0
chipset_compatible=A1200
chipset=aga
gfx_framerate=2
```

For now it replaces the preset, therefore all rows need to be there, not just the new option. The frameskip option won't be overriden by the core option if defined in a customized conf.

I also added the option to start D-Pad in mouse mode. I'll look at the horizontal zoom cropping nextish.

**Comment by KMFDManic** [comment]
@sonninnos Looks great!  I will test things out:)  

By the way, not sure if it is an ARM issue or not.  But, I have been testing latest commits for VICE, and Autostart seems to not be functioning reliably.  What is even a little stranger is that games load more reliably if uncompressed, than if 7zipped or zipped.  But, in previous one, I was able to load 7z and zip fine.  I am going to try another Compile, to confirm, as well as ensure I am running "defaults" all across the board.  I retested the last Compile I did, and every game loaded fine.  Just some weird thing with latest, hopefully just on my end!

Thanks again for looking into the Model Presets:)

**Comment by sonninnos** [comment]
Yep, unfortunately 7zs are broken after the core started handling ZIPs internally for M3U generation. RA only has a global extraction blocking, which means 7z support would also need to be done by the core.. Same thing with both VICE and PUAE. And it is currently not a priority for me, since ZIPs are more common and work well.
