### ISSUE TITLE
WHDLoad Demo unsupported filename character ?

### ISSUE THREAD

**Issue by WindyWinston** [libretro/libretro-uae#289]
Hey good buddy. I haven't used these cores for quite some time but decided to get back into them again. I tried a WHDLoad Demo called '`100MostRememberedGamesOnThe64_v1.01_PerhåkanSundell&RonBirk`'. It doesn't seem to boot because of the accent above the letter 'a'. If you replace it with a normal 'a' then it boots (but it seems to be in slow motion, must be a emulation accuracy issue).

Not really an issue because I found the solution but I thought i'd let you know anyway !

**Comment by sonninnos** [comment]
The `å` got translated to `%E5` here on download, and it worked fine. But if renamed back to the original form it indeed fails to be seen as a proper path, and looks like it is changed to `├Ñ` already in `info->path`, which is where the core gets the path from, so I don't know (yet) if anything can be done in the core to convert it or something..

**Comment by WindyWinston** [comment]
I'll close this because the file has to be manually renamed anyway because the Retroarch playlist doesn't like that accented character either. Most of the playlist disappeared after a second run !

**Comment by sonninnos** [comment]
Perhaps the issue should be opened in RA repo then. Most likely there are more similar chars that cause the same problems.

**Comment by sonninnos** [comment]
Score! I managed to fix this character issue with a simple `libretro-common` function after all.

**Comment by WindyWinston** [comment]
Good job as usual! This saves having to rename it.
