### ISSUE TITLE
[IOS] close content crashes retroarch

### ISSUE THREAD

**Issue by QcSamuel** [libretro/libretro-uae#294]
on ios devices when you select close content it will crash retroarch so because of this ios users can't change the core options that need a core restart

retroarch 1.8.8
uae 2.6.1 987251c
iphone 7 13.5 jailbroken

**Comment by sonninnos** [comment]
Why the old build? A fix for static build core reloading has been included later on, and hopefully it fixes that too.

**Comment by QcSamuel** [comment]
cores need to be code sign on ios so there no auto buildbot to build the latest cores so i'm using this repo the cores are not updated yet https://forums.libretro.com/t/ios-tvos-retroarch-1-8-5-and-other-emulators-download-cydia-repo/27503/18

**Comment by QcSamuel** [comment]
> Why the old build? A fix for static build core reloading has been included later on, and hopefully it fixes that too.

ok so now it's at 2.6.1 638bf34 now it's freezing retroarch

**Comment by sonninnos** [comment]
An improvement of some kind at least. Does that happen with any other core?

**Comment by QcSamuel** [comment]
only have this problem with this core
the freezing happen on restart too

**Comment by sonninnos** [comment]
That is interesting.. But the VKBD/hotkey reset works, right? And is the VICE C64 (or any VICE) core one of those you've tested?

**Comment by QcSamuel** [comment]
vice cores restart and exit are working fine
and yes the amiga  onscreen keyboard reset works

**Comment by sonninnos** [comment]
Too bad it takes a while to confirm, but I have some cleanup operations ready regarding `uae_restart` in the next PR.

**Comment by sonninnos** [comment]
I don't expect the changes to actually help with anything other than maybe narrowing it down, but in the meantime:
- Does the same thing happen with all medias = ADF/IPF, HDF, LHA and CD images?
- Can you get the stdout verbose log somehow? On Windows the RA log will not show the UAE output, so it has to be run in the console, but I don't know if that is universal on all platforms. That should give at least some useful info about where the fun stops.

**Comment by QcSamuel** [comment]
logs are not working on ios 
and i can only find .adf files right now
will keep searching for the others

**Comment by i30817** [comment]
IOS dislikes JIT (aka dynamic recompilation) so if there is something doing that on close it might very well crash.

Source ppsspp: https://github.com/hrydgard/ppsspp/issues/13255

**Comment by sonninnos** [comment]
JIT is not enabled, and I haven't figured out how to get it to compile..

**Comment by sonninnos** [comment]
Does this still happen after these recent changes? At least now all logging goes to frontend log, so that should help narrowing it down a little.

**Comment by QcSamuel** [comment]
@yoshisuga hi could you test the core with the recent changes :)

**Comment by QcSamuel** [comment]
@WeedyWeedSmoker

**Comment by QcSamuel** [comment]
same freeze on abb1353

**Comment by sonninnos** [comment]
I can't go shooting in the dark without a log..

**Comment by QcSamuel** [comment]
logs don't work on ios so i'm going to close this issue i guess
