### ISSUE TITLE
Shadow of the beast III crash on loading level 2

### ISSUE THREAD

**Issue by bigly2001** [libretro/libretro-uae#296]
Hi
I noticed that the game Shadow of the beast III crashes on loading in level2
I tested any configuration and release for this game and the problem persists.

**Comment by sonninnos** [comment]
WHDLoad version loads fine. I tried Skidrow cracked disk version and it did not work even with WinUAE.

**Comment by WindyWinston** [comment]
Level 2 works on the floppy version if you use A600 & Normal Compatibility.

**Comment by bigly2001** [comment]
Hi Winston

Which floppy version do you use in detail please?
because for mine non of amiga models worked.

**Comment by bigly2001** [comment]
Hi  Tony
I tried skidrow version with winuae 4.1 without problem.

**Comment by bigly2001** [comment]
> WHDLoad version loads fine. I tried Skidrow cracked disk version and it did not work even with WinUAE. IPF also loads fine.

Hi
how to load ipf file ?
I put capsimg.so for armv7a to system folder of retroarch but when i load ipf file nothing happened and bios screen (the hand and diskette) was shown
my hardware asus tinker board on android 7 and retroarch 1.8.8

**Comment by WindyWinston** [comment]
This is the floppy version I use -

```
Shadow of the Beast III (1992)(Psygnosis)(Disk 1 of 2)[cr SR][t +8 ATX][a]
Shadow of the Beast III (1992)(Psygnosis)(Disk 2 of 2)[cr SR]
```

Level 2 doesn't lockup and crash if you force the model to `A600` and leave the compatibility on `Normal`. The WHDLoad version `ShadowOfTheBeast3_v1.6_0016.lha` works with default settings (Model Automatic, Compatibility Normal).

**Comment by sonninnos** [comment]
> I tried skidrow version with winuae 4.1 without problem.

4.1 here also and I can't get any of the cracked floppy versions to work with the most compatible A500 setup..

> how to load ipf file ?
>I put capsimg.so for armv7a to system folder of retroarch but when i load ipf file nothing happened and bios screen (the hand and diskette) was shown

That should do it, so the library version is most likely not correct.

The best option naturally is the WHDLoad version (no floppy swapping, trainers included, intro skip included).

**Comment by bigly2001** [comment]
> This is the floppy version I use -
> 
> ```
> Shadow of the Beast III (1992)(Psygnosis)(Disk 1 of 2)[cr SR][t +8 ATX][a]
> Shadow of the Beast III (1992)(Psygnosis)(Disk 2 of 2)[cr SR]
> ```
> 
> Level 2 doesn't lockup and crash if you force the model to `A600` and leave the compatibility on `Normal`. The WHDLoad version `ShadowOfTheBeast3_v1.6_0016.lha` works with default settings (Model Automatic, Compatibility Normal).

I had a bad checksum with a600 bios when i replaced it with new bios file it runs perfect
thanks WindyWinston

**Comment by sonninnos** [comment]
Please close this issue, since the "fix" is as good as it gets.
