### ISSUE TITLE
CORE PUAE x WAV FILES

### ISSUE THREAD

**Issue by AlanRibas** [libretro/libretro-uae#299]
I was configuring the PUAE core. And I saw some files with the ".wav" extension missing.
I was very curious.
Can anyone tell me what the purpose and importance of these files are for the AMIGA emulation?

<img width="960" alt="A" src="https://user-images.githubusercontent.com/16063712/84972895-383a2700-b0f6-11ea-8a5d-358cb781f91d.png">

Whatever the purpose of these files, I downloaded them and placed them in the same directory as the other bios in the AMIGA system (D:\Jogos\RetroArch\system). However, they were not recognized by RetroArch.

<img width="960" alt="A2" src="https://user-images.githubusercontent.com/16063712/84974117-fc549100-b0f8-11ea-9462-1813e9411a6b.png">

Is it necessary to place them in a specific directory?

**Comment by sonninnos** [comment]
They are completely optional. Readme says it all: https://github.com/libretro/libretro-uae#floppy-drive-sound

**Comment by AlanRibas** [comment]
I found this information here on the link you gave me:

"Floppy drive sound
For external floppy drive sounds to work, copy the files from https://github.com/libretro/libretro-uae/tree/master/sources/uae_data into a subdirectory called uae_data in RetroArch system directory."

Correct me if I got it wrong. But are these .wav files needed only if I want to use a real floppy drive with the emulator?

**Comment by sonninnos** [comment]
The external files are there simply to provide an alternate to the internal default samples. And naturally floppy drive sounds are emulated only when a floppy drive is used.
