### ISSUE TITLE
Vita port broken

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-uae#302]
Hi there @rsn8887 and @sonninnos ,

would you guys happen to know why compilation fails now on Vita (statically linked target), and whether you guys can fix it?

http://paste.libretro.com/218202

It looks like some symbols (of functions) are named identically in two source files and they should be uniquely named.

**Comment by sonninnos** [comment]
Hmm, those can't possibly be caused by the latest changes or can it..?

**Comment by rsn8887** [comment]
Looks like someone changed the buildbot

**Comment by twinaphex** [comment]
Nothing changed on the buildbot, only that we fixed space running out and reflushed the ccache -

http://paste.libretro.com/218274

These are the errors.

**Comment by twinaphex** [comment]
I'll try to let it forcibly rebuild from a fresh git clone to see if that can help on the buildbot.

**Comment by rsn8887** [comment]
I think someone updated gcc to 10?

I think I fixed it here:
https://github.com/libretro/libretro-uae/commit/135c9644d5676ae5d1ffd44c888ae4afe4fcc382

**Comment by rsn8887** [comment]
Look like that commit indeed fixed it:
```
retroarch: [Status: done] [recipes/playstation/vita] [Finished: 2020-07-24 02:25:43.952443+00:00]
```
