### ISSUE TITLE
[Android] Loading content crashes retroarch

### ISSUE THREAD

**Issue by Frakatchoo** [libretro/libretro-uae#307]
Hi !

I can't load any .lha games, I can start the core, but if I try to load content, Retroarch crashes.
Any solution ?

Retroarch 1.8.9
P-UAE 2.6.1
Retroid Pocket 2 (Android 6)

**Comment by sonninnos** [comment]
Not enough information to proceed really, sorry.

So all other file formats (floppies/CDs/harddisks) do work then? Can you test the same LHA files with some other platform?

Is there are debug build of RA for Android, for getting some log output of the crash? Also regular RA verbose log would give some hints, except all the really helpful information goes to stdout, and not the log..

**Comment by sonninnos** [comment]
I tried with emulated Android (MEmu), no crash..

![MEmu_2020_09_05_02_01_01_216](https://user-images.githubusercontent.com/45124675/92290181-d8e0fb80-ef1b-11ea-9e51-546a6c18a042.png)

**Comment by WindyWinston** [comment]
For what it's worth, I use Android,

Firestick 4K - Android 7
GPDXD Handheld - Android 4.4.4

LHA's load fine on both devices.

**Comment by Frakatchoo** [comment]
> For what it's worth, I use Android,
> 
> Firestick 4K - Android 7
> GPDXD Handheld - Android 4.4.4
> 
> LHA's load fine on both devices.

Interestingly, I also have a GPD XD, and i still have the same problem, retroarch crash when i want to load a .LHA file!

I am using the latest versions:
- Retroarch 1.8.9
- PUAE 2.6.1

Can you check which versions you are using?
No reason for it to crash with me, and not with you on the same machine.

**Comment by sonninnos** [comment]
BTW that "2.6.1" will not matter, since it has been that since the beginning and also will stay that way. What matters is the github commit hash, as in the latest version is `84a7e2b` (full: `84a7e2bafdf0a4c5d438265b756ab510d5090b33`)

**Comment by Frakatchoo** [comment]
OK I solved the problem. I checked the kickstart roms (bad md5). Replaced by the good ones, and now it works! Thanks for the help.

**Comment by sonninnos** [comment]
Phew, awesome!
