### ISSUE TITLE
[Switch]  games don't work properly 

### ISSUE THREAD

**Issue by RetroMarioBros** [libretro/libretro-uae#316]
puae core has regressed on this platform, causing the games to not work properly, some do not start and others, and crash after a few seconds
[01601666045_01003a400c3da000.log](https://github.com/libretro/libretro-uae/files/5319903/01601666045_01003a400c3da000.log)
this is crash_reports that is obtained when trying to play prince of persia 
(this game for example does not start actually)

**Comment by rsn8887** [comment]
Maybe it is the missing -fcommon compiler option. I need to find time to test.

**Comment by RetroMarioBros** [comment]
ok, when the .nro is built I test it and tell you 😃

**Comment by RetroMarioBros** [comment]
there are no crashes, the core is working again!!
😃😃😃
Thanks you!
