### ISSUE TITLE
[Bug] Cannot move the mouse cursor to the right or down

### ISSUE THREAD

**Issue by masaklaw** [libretro/libretro-uae#321]
## Use case

In some (probably all?) games that use the mouse (e.g. <q>Cannon Fodder</q>, <q>North & South</q> or <q>Beneath a Steel Sky</q>), at some point during runtime, the mouse cursor can no longer be moved to the right or down (including both at once). It seems that there is an invisible boundary in the middle of the screen.

The boundary appears at runtime and changes position (the available mouse movement area shrinks progresively). Trying to move the mouse cursor beyon the left or up screen boundary (which are correct) resets mouse movement area to the original/correct one. After some time the problem repeats itself.

The problem is much more easily reproduced at lower mous speed, e.g. `10%`, but appears at all mouse speed settings.

## Ideas

These are purely _shots in the dark_, but there may be something wrong either with the:
- calculation of the mouse movement boundary,
- mouse movement tracking in regard to the boundary (maybe a rounding error accumulation?).

## Environment

**PUAE core version**: 1a17c1e3, but this is not the first version when the problem appears - it also appears in core version as old as the beggining of 2019, maybe even older ones.

Tested on _Ubuntu 20.04_. Retroarch version (although t probably does not matter):

    RetroArch: Frontend for libretro -- v1.8.5 Compiler: GCC (9.3.0) 64-bit

**Comment by sonninnos** [comment]
Huh, never had that happen on Windows, so does not really look like a core problem..

**Comment by masaklaw** [comment]
Only happens with real mouse. Analog stick and d-pad mouse work without any issues.

It seems to happen regardless of input driver, tried: `x`, `sdl2` and `linuxraw`.

**Comment by sonninnos** [comment]
Ok, then it should happen with other cores too, like dosbox.

All mouse methods go through the same pipe, so nothing to be done here I'm afraid. Please create the issue in RetroArch repo.

**Comment by masaklaw** [comment]
OK - thank you.

It really seems like it's a RetroArch's problem, because I tired the last one availble input driver under linux: `udev` and it actually works correctly! It didn't work for me previously, because it requires some additional permissions.

**Comment by masaklaw** [comment]
The problem seems to already be reported in RetroArch. I linked this issue in a comment to the RetroArch's one, as seen above.

**Comment by sonninnos** [comment]
Nice. Let's hope someone picks it up then. No reason to keep this issue open though.
