### ISSUE TITLE
Cloanto  / amiga forever roms rejected when loading whd load game

### ISSUE THREAD

**Issue by fejtonx** [libretro/libretro-uae#329]
Hello,

I am owner of amiga forever plus edtion since april.
If I take forever roms, rename according to the documentation, place them into system directory and then load compressed whd load game (lha) I get an error that rom can not be copeid due to incorrect file size.
My rom file sizes are 256 155 or 524 299 bytes.
Any advice?

Thanks in advance

**Comment by sonninnos** [comment]
Those sure are very odd sizes, and I have no idea how UAE can even accept those.. They really should be `262 144` and `524 288`.

But since you can get that far with them, simply try copying the files manually to the right place in the helper image, `WHDLoad/Devs/Kickstarts/` in `saves`.
