### ISSUE TITLE
SWIV game doesn't work

### ISSUE THREAD

**Issue by toniosj** [libretro/libretro-uae#332]
Libretro-uae can't run SWIV game. After game loads, black screen.

**Comment by sonninnos** [comment]
No problems here with the default settings, IPF and WHDLoad both. Bad cracked version perhaps?

![retroarch_2020_11_02_19_59_52_199](https://user-images.githubusercontent.com/45124675/97902575-7a32d500-1d46-11eb-9feb-8d092517ef38.png)
![retroarch_2020_11_02_20_00_58_374](https://user-images.githubusercontent.com/45124675/97902597-7e5ef280-1d46-11eb-9fc3-40beebe48ac9.png)

**Comment by toniosj** [comment]
I've tested on Retroarch Windows and it works fine. The problem is on Recalbox compilation. Sorry.

**Comment by sonninnos** [comment]
No worries, you may close this issue.
