### ISSUE TITLE
Custom Controls

### ISSUE THREAD

**Issue by yolkfolk1** [libretro/libretro-uae#334]
Hi. The auto .uae file is great, is there a way to ammend what is created by default.
I'd like to have controls mapped to a gamepad I use by default. Is there a way I can define them?
like this for example...
input_a_btn = "48"
input_b_btn = "30"
many thanks

**Comment by sonninnos** [comment]
Sorry, I don't understand. Those example rows are RA rows, not UAE rows. UAE does not handle button remaps, the frontend does. Which means anything added to uae conf regarding input will do nothing. What is it that you are trying to achieve exactly?

- If you want to add/assign keyboard keys to the joypad, use the mapping options under `Quick Menu -> Options`
- If you want to replace all joypad buttons with keyboard keys (pinball setup, no joystick starting point), change the device type to "Keyboard" under `Quick Menu -> controls`
- If you want to move the buttons around to match a specific controller layout, use `Quick Menu -> Controls`

The labels used under core options will not match the whatever layout is in the frontend, so you need to memorize which RetroPad button is which. Ergo, the mapping stuff under core options are for creating a fantasy joystick, not configuring the actual used controller.
