### ISSUE TITLE
Compilation error about #include "memory.h"  inside blkdev_cdimage.c

### ISSUE THREAD

**Issue by crystalct** [libretro/libretro-uae#349]
I suppose it should be removed......

**Comment by crystalct** [comment]
Same thing inside libretro-glue.c

**Comment by sonninnos** [comment]
Weird, I'm not getting any errors, but indeed there is no such file anywhere, so I guess it should be "memory_uae.h"..

**Comment by crystalct** [comment]
![image](https://user-images.githubusercontent.com/1675181/100245169-098f6a80-2f38-11eb-94e3-cde617cbc7be.png)
