### ISSUE TITLE
[Switch] loading .adf from inside .zip does not work

### ISSUE THREAD

**Issue by ms2048** [libretro/libretro-uae#358]
I'm on RetroArch 1.9.0 on Nintendo Switch with newest core available from Core Updater (PUAE 2.6.1 e187a61). Trying to open contents from inside a zip like this:

Load Contents -> ... -> (zip file) -> Browse Archive -> (adf file)

does not work. The Amiga starts but without a disk inserted into a drive.

This worked ok in an older build (bundled within RetroArch 1.9.0 for Switch). On the other hand, opening uncompressed .adf files works:

Load Contents -> ... -> (adf file)

and also opening a zip as a whole like this:

Load Contents -> ... -> (zip file) -> Load Archive -> Commodore - Amiga (P-UAE)

just the first way stopped working.

**Comment by sonninnos** [comment]
On a desktop setup this seems to be working fine after the core is running. If the core is only loaded (or not), the Browse Archive list will be just "No Items", and I don't think that can be fixed as long as the core is handling the archive extraction.

**Comment by ms2048** [comment]
Confirmed fixed, thank you!
