### ISSUE TITLE
Diskswapping with Analog stick on DPad

### ISSUE THREAD

**Issue by goedzo** [libretro/libretro-uae#37]
Since m3u playlists are now supported, it would be great to allow diskswapping with the left analog stick. So pressing right on the stick, ejects the current disk, swaps to the next disk and then inserts it again. Left, does the same but then towards the previous disk.

This allows easy diskswapping without the need to enter the main menu or getting out of full-screen mode to use the menu's. And it saves a lot of clicks :). 

I don't think this must be a generic retro-arch function, since the diskswapping is mostly relevant for disk based systems, and other systems actually need the analog stick to play games. So I suggest to solve this only for this core.

**Comment by qclart** [comment]
Analog stick is used to emulate mouse movement without the need for an actual mouse and some people, myself included, use the analog stick instead of dpad to play certain games. Implementing your suggestion would break this functionality.

**Comment by DamsRoxxx** [comment]
Disk control function is a retroarch thing. I think it would be better to add the capacity to map this function within RetroArch to be standard for each core (IMHO, It's a "frontend" function).

In the meantime you can map a hotkey combination on your controller to bring the retroarch menu and switch disk very easily (it's what I do).

**Comment by goedzo** [comment]
@qclart in this core, mouse emulation is actually being done by the DPAD while using the start key to switch from joystick to mouse. The analog stick is not attached to anything. Also there are two analog sticks, so one stick can even be used for the mouse, whilst the other can be used for disk swapping.

**Comment by goedzo** [comment]
@DamsRoxxx it would also help a lot, of I can use the retroarch key mapping feature to map it to the dpad. However from the retro-arch frontend menu I cannot select diskswapping if I try to map the analog stick to anything. Also using the frontend menu is a lot of switched especially when you have to swap almost every 10 seconds or so. Doesn't bring a very good experience.

**Comment by goedzo** [comment]
Solved this issue, by binding my hot-key. Found that you can then see diskswapping options.
