### ISSUE TITLE
RetroArch WHDload won't start game, only kickstart rom

### ISSUE THREAD

**Issue by GordonWesside** [libretro/libretro-uae#381]
So guys, i'm new here with a frustrating issue. In RetroArch on Nvidia Shield Pro i can get single disk/adf files to run without issue but when it comes to whdload i can't get any game to run wether it be an .lha/.hdf or zipped .hdf file.

Running latest versions of Retroarch and PUAE.
Kickstart is set to: A1200 2mb/8mb for WHDload as suggested everywhere
Files are placed in: \\SHIELD\internal\RetroArch\Amiga\Games\WHDload\
Kickstart roms work (as .adf files work fine) i have placed these kickstart files in above mentioned directory as well as the: \RetroArch\system\ directory (to be sure.. old situation i believe that was needed).

I have attached the logfile where i tried to load 'Elfmania'  which at the very end states:
FS: BootHD (flags=00000002,E=0,ED=1,EF=0,native='/storage/emulated/0/RetroArch/saves/BootHD') starting..
FS: WHDLoad (flags=00000002,E=0,ED=1,EF=0,native='/storage/emulated/0/RetroArch/saves/WHDLoad') starting..
FS: WHDSaves (flags=00000002,E=0,ED=1,EF=0,native='/storage/emulated/0/RetroArch/saves/WHDSaves') starting..
FS: Elfmania (flags=00000002,E=0,ED=1,EF=0,native='/storage/emulated/0/RetroArch/saves/TEMP/Elfmania') starting..
But all it ends up with is booting the kickstart and that's it?

Elfmania zipfile contents:
-Elfmania (folder)
-Elfmania.info

Elfmania folder contents:
-Disk.1
-Disk.2
-Elfmania.info
-Elfmania.slave
-Manual
-Manual.info
-ReadMe
-Readme.info

[retroarch__2021_02_14__17_59_35.log](https://github.com/libretro/libretro-uae/files/5978097/retroarch__2021_02_14__17_59_35.log)

**Comment by sonninnos** [comment]
Do not enable "Global Boot HD" option (seen there as the first filesystem BootHD). It is meant for installing Workbench from floppies and it will take priority when launching hard drives, because it would be totally useless otherwise.

Also there is no need to force A1200 (except with specific games). Trust the current Automatic defaults and forget ancient tutorials.

**Comment by GordonWesside** [comment]
Wow.. that simple *facepalm*   worked! thanks man!
