### ISSUE TITLE
[Android] Double inputs/Unintended clicking. Request for option to disable touch mouse input

### ISSUE THREAD

**Issue by demodanza** [libretro/libretro-uae#387]
First, thanks for your work on this great emulator/core. I got to experience Amiga games for the first time with it, and features like the on-screen keyboard make it a breeze.

As the title says, an option to disable touchscreen mouse input in Android would be much ppreciated. As it is now, when using a gamepad overlay to press, for example, up, it also registers as a mouse click or movement, which makes almost impossible to play some games when every button press is also a mouse click.

Dragging the mouse and clicking small in game buttons with the fingers is impressice. With a dungeon crawler for example, in dosbox pure, one can disable touch mouse and emulate the mouse with the dpad/analog stick (virtual), and maneuver the game's interface without a second input in the way.

**Comment by sonninnos** [comment]
Cheers! Indeed looks like that thing should be ultimately handled in the frontend, but in the meantime sure I'll soon change the current multi-mouse core-option to "physical mouse" with disable.

**Comment by demodanza** [comment]
Yeah, for sure seems like it should be a universal toggle at frontend level. There is a disable touch input on the interface menu, but it does not relate to android touch input or it doesn't work properly.
Good to know it's gonna be taken a look at core level, thank you!

**Comment by Denshadego** [comment]
Hi! Thanks for taking a look into the issue, however, the virtual keyboard still receives touch input when touching anywhere close on the screen, no matter the mouse option selected. An option for the Virtual Keyboard to be only interacted through the retropad/gamepad would be ideal, as in the core Dosbox Pure.
