### ISSUE TITLE
Non native resolution / Not Pixel accurate

### ISSUE THREAD

**Issue by Papermanzero** [libretro/libretro-uae#39]
It seems P-UAE doubles the pixles. For some reason it is not the original resolution which is why shaders like scalefx cannot be applied.

![turrican-180915-180126](https://user-images.githubusercontent.com/10263536/45588227-b2ca8700-b911-11e8-851e-eda9c5d4bae2.png)

**Comment by Papermanzero** [comment]
I found the root cause why scaling filters do not work.

The core provides two internal scaling methods. gfx_lores= (default = true) gfx_linemode= (default = double)

If both are activated p-uae doubles the size of the image horizontally as well as vertically. If both settings are deactivated the frame because pretty slow (however pixel perfect). So the rendering of the core has to be changed to output the frame always in fullscreen.

**Comment by Papermanzero** [comment]
Related to that issue:
https://github.com/libretro/libretro-uae/issues/16

**Comment by DamsRoxxx** [comment]
Very good job. Just tried it and it seems to work with scalfx:

![turrican-180916-005833](https://user-images.githubusercontent.com/14038573/45591249-a7954c80-b94d-11e8-8a5f-f7c8244222e7.png)

Will fix this as soon as possible.

**Comment by DamsRoxxx** [comment]
Patch is ready in my repo.

I will wait till #34 is merged to submit it.

**Comment by DamsRoxxx** [comment]
Fixed in #46
