### ISSUE TITLE
Game+Core Options not saving

### ISSUE THREAD

**Issue by riggles1** [libretro/libretro-uae#401]
Game or core .opt option files are never created, all other cores I use have no issues in this regard. But with PUAE I've had to manually create an .opt manually for each new individual game I want to play and edit the settings through notepad++.

**Comment by sonninnos** [comment]
Never had that happen on Windows, and the core is not even responsible for loading/saving those opt files..

**Comment by riggles1** [comment]
> Never had that happen on Windows, and the core is not even responsible for loading/saving those opt files..

Strange, wonder what is up, unrelated I've been having issues with First Samurai, with it causing RA to crash (tried loading the core, then disk as well, crashes as soon as you load disk2 after the intro disk1, and loading disk1 directly causes RA to crash). Maybe it's related, been trying to create an opt file with different settings as maybe that game requires some specific hardware configuration.

RA, win64, never had issues with other cores for PC98, DOS etc, I'm very used to using RA, however I'm new to the Amiga core.

Appreciate the reply!

**Comment by sonninnos** [comment]
Good you got it working, but what was wrong with the files? Weird path/characters or something?

I'll close this then.

**Comment by riggles1** [comment]
> Good you got it working, but what was wrong with the files? Weird path/characters or something?
> 
> I'll close this then.

No idea actually, not related to the name, if you want to try it, try the .adf and .ipf files for First Samurai to see if that is acting up. Otherwise all hdf I've tried worked perfectly, no crashing, .opt's everything (though .opt's were saving when I was trying again so who knows, but either way First Samurai will crash either on the intro splash or when you switch to disk 2 which is before the actual game starts).

Hopefully I don't run into that again since I have a bunch of music .adf's,

**Comment by sonninnos** [comment]
Just tried the No-Intro IPF and indeed no problems with opt files, but there is graphic corruption without Cycle-exact.

And for some reason Ctrl-A-A boot is not enough after changing the CPU compatibility option, but instead requires either full restart or restart via the menu..
