### ISSUE TITLE
Issues on iOS 14.4.2 with whdload games

### ISSUE THREAD

**Issue by mnpst** [libretro/libretro-uae#402]
First of all, thanks for giving me a chance to live once again these magic moments from my early teenage youth - I am really grateful for all the efforts put into this work!

I am attempting to use lr-puae on my first RetroArch install on iOS - my .lha files, which work on Android and RetroPie, do not load here (black or yellow screen) - and the same happens for  for dhf files.

I have all required kickstarts in place, and also attempted to force A1200 (2+8mb) but still no success.
Same result if whdload support is set to files or archive.

I can successfully launch afd files, and load the core without any content.
However, the entire retroarch freezes if I try to restart the core or close the content.

Any hints appreciated!

**Comment by sonninnos** [comment]
Thanks!

I have no idea what could cause that. Also no reports from other platforms. Please post the verbose log, specifically after this block:
```
[libretro INFO] --------------------------------------------------------------------------------
[libretro INFO] PUAE 2.6.1 (0186c1b16f7181ffa02d73e6920d3180ce457c46)
[libretro INFO] Git commit: 43fd84b
[libretro INFO] Build date: Mar 31 2021 23:18:16
[libretro INFO] 
[libretro INFO] See the source for a full list of contributors.
[libretro INFO] This is free software; see the file COPYING for copying conditions. There is NO
[libretro INFO] warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[libretro INFO] --------------------------------------------------------------------------------
```

**Comment by fatoune** [comment]
Thanks for the attention!
..unfortunately, retroarch logging does not seem to work on my end on iOS - despite logging verbosity being enabled (and set to debug for both retroarch and cores), all retroarch logs created are simply empty files (0 bytes).

Looks like not that many people are using lr-puae on iOS, I have not found anyone else reporting similar issues or even mentioning running WHDload games on this platform.. 

lr-puae works perfectly on my other systems (including andorid tv, fiestick, retropie).
Cheers!

**Comment by fatoune** [comment]
..nevermind, I managed to peek into the logs by running RetroArch attached to xcode and looking at its console output.

The log seems to get constantly flooded by this:
```
Apr  1 14:42:53  RetroArch[25021] <Notice>: [WARN]
2021-04-01 14:42:53.468390+0200 RetroArch[25021:7738985] [GL]: FBO textures exceeded maximum size of GPU (4096x4096). Resizing to fit.
```

**Comment by sonninnos** [comment]
That is indeed weird and can't actually have anything to do with the core..

**Comment by fatoune** [comment]
Alright, I managed to gather a few more info - rebuilt retroarch and got rid of that error polluting the logs.

This is what I get running the puae core standalone (which boots as amiga 500 by default): 
```
Apr  1 20:12:02  RetroArch[2854] <Notice>: Illegal instruction: 4e7b at 00FC0564 -> 00FC0582
2021-04-01 20:13:33.987415+0200 RetroArch[2854:77515] [INFO]
Apr  1 20:13:33  RetroArch[2854] <Notice>: [INFO]
2021-04-01 20:13:33.987475+0200 RetroArch[2854:77515] [Core]: Paused.
Apr  1 20:13:33  RetroArch[2854] <Notice>: [Core]: Paused.

```
If I load a .lha file instead, I get a "Thread 1: bad access" error in the xcode debugger - see [screenshot..[](url)](url
<img width="1548" alt="Screenshot 2021-04-01 at 20 27 42" src="https://user-images.githubusercontent.com/32594252/113338931-1418a100-932a-11eb-9b51-f076407e623f.png">
)

To be clear: I am reporting just for the sake of helping out in case others run into the same issue, but do not expect any support so ignore unless it's useful..

Best,
M.

**Comment by sonninnos** [comment]
Any difference with the latest changes?

**Comment by TyroneSlothrop** [comment]
Hi sonninnos - really appreciate you looking at this at it is a major remaining issue with RetroArch on iOS. 
On my side I get a 'flickering' black screen with version 2.6.1 b0c3cd4 on using WHDs (doesn't even get to the splash) and crashes. The exact same settings for a given drive work on Mac OSX and Android.

fatoune - I also have the 0 kb log file issues (I only have a random game launch count stat tracking json file in the puae file which is useless), is there a guide or are their tips on attaching xcode (I'm using the prebuilt ipa file though)?

**Comment by TyroneSlothrop** [comment]
Last roll of the dice, this is where I think it goes wrong on iOS: 
`RetroArch	Exception 20 3 (f02004) at f02004 -> f80b0e!`

This is following comparing Mac and iOS with same KS, hdf, settings etc - logs comparing the 2 start-ups attached and even on OSX on a working hdf I see an 'illegal instruction' so that could just be a red herring.

Hopefully that means something - the log command is buried in MC68000 emulation newcpu.c

I was hoping to _not_ return to this issue and live my life, so I also tried the .uae configuration file with a directory structure as a workaround, but that's a no go for the **same reason** of flickering screen / soft looping resets (so it may not be hdf related but how A1200 emulated instructions may be skewed on iOS somehow?).

In any case I am available to test things if someone can suggest anything (I just don't know C well enough to be able to do it myself at this stage).

[mac vs ipad.txt](https://github.com/libretro/libretro-uae/files/6314380/mac.vs.ipad.txt)

**Comment by esgie** [comment]
Same behaviour here.
(Non-jailbroken) iPad Pro running iOS 14.7.1 and iPhone 11 running iOS 14.3…
(i have tried both official retroarch build and the one by Weed Smoker, including the most recent build availabre from Cydia only and repacked on my own to a form usable for non-jailbroken devices, as well as some older builds of both; I have also tested with both JIT disabled and enabled via Jutterbug..).

Screen is flickering between gray and black or yellow and black (depending on chosen model) in an infinite bootloop if I tend to boot Amiga using hard drive (or CD, but I believe that under the hood it’s mounted on-the-fly as a hard disk anyway) - no matter if it’s a global boot hd, slave/info files inside a dir, hdf image, lha archive or zip containing any of the above, both directly or via m3u... Not mentioning spending some significant time on trying to load them via .uae file…

On the other hand, if Amiga is configured to use hard drive, but not to boot from it, whole retroArch crashes immediately (well, the app just disappears without any message).

No way to run any hard-drive related stuff at all.

I’d like to provide some logs but I can’t as they are 0 kb just like folks above mentioned.

And I do not own a Mac so I doubt if I can get them in any other trivial way (or maybe I should get more familiar with Linux’ libimobiledevice?)

I can only think of problems with some iOS restrictions, like the one for running unsigned code. It may kick in if some executable native code is downloaded or created on-the-fly, then it will more likely fail to execute. (Btw that seems to be the reason why RetroArch for iOS fails to run cores installed through Updater; cores has to be in fact bundled inside and sideloaded along with the app so they got signed…). Or maybe a problem with file permissions. As far as I can see, hard drive directories are generated/placed inside saves directory, in „external” RetroArch documents folder (the one which is easily accessible through the Files app, not the one which is accessible via iTunes only!), I guess files permissions isn’t anyway supported for this location.., but that’s only my random thoughs.

it’ll be great news to have fully-working Amiga station working on the go on ipad - and not being limited to floppy…

Thank you for your time and effort.

**Comment by sonninnos** [comment]
Looks like this issue should be sorted with the latest change, since it seems like a dupe anyway, so I'm closing this, but please do confirm that it worked.

**Comment by TyroneSlothrop** [comment]
Yes! This has made my date - just doing a few initial tests but seems to work (launching a few hdfs, save/load state, keyboard/mouse input...). Thanks so much for this.... was it literally just the compiler flags to share memory across processes the issues?

Screenshot from iPhone 11, RA 1.14 - iOS 16.2.

Only one note: latest version I have doesn't seem to recognise the older frozen 2021 core in the list available when picking the hdf - so it's using the non-2021 frozen version.

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/1816777/211406248-77eff3a4-57e5-4e7f-8950-1f0eae3c7f29.png">

**Comment by sonninnos** [comment]
Mac stuff apparently wants named semaphores yes.

I did add the same change to 2021 too. There is only one 2021 and it is not frozen in regards of features, but only the CPU emulation which makes it faster. I did change the `library_name` to `PUAE 2021` a while back to separate it properly from the current one. And it is available for core association and working fine here.
