### ISSUE TITLE
Image is squished vertically when Aspect Ratio is set to 1:1 PAR

### ISSUE THREAD

**Issue by oldghost83** [libretro/libretro-uae#403]
Hi! 
Thank you for your effort in bringing Amiga core to Retroarch! Works great, though I couldn't figure out how to run the games until today. Turned out the path to BIOS shouldn't have any characters except latin symbols, I guess. Or maybe there's a path length limitation. I placed Retroarch into root folder of my ssd and both PUAE and Mesen's FDS part started to work. Before that I constantly got "Failed to load content" message. And I didn't find any info about this anywhere for some reason, even though I searched somewhat thoroughly.
Another thing with PUAE is it doesn't want to delete through "Information -> Core Information -> Delete Core". It just always stays ) Need to manually delete core and info files. Though it's not major, please, take that into consideration. Maybe it's not concerned with your core.

Now for the issue. I might not understand something, maybe didnt't read properly again, but the first thing I was greeted with upon loading a game (my collection is in .ipf and .adf formats) was a squished image. 
When I change Aspect Ratio to core provided or 4:3, I think I see something close, but it's not what we aim for, right? Shouldn't option "1:1 PAR" show us just how it was intended?
Is it a bug or I don't know something? I'm not much familiar with Amiga's technical stuff. But I haven't seen this behavior with any other core I use. I keep "Integer Scale" set to ON and turning it OFF doesn't help either, of course. Can you confirm this, please? Something may be off with my settings. I tried my previous setup with Retroarch 1.9.0 and it's exactly the same.

**Comment by sonninnos** [comment]
Cheers! Delete core is working fine here, and the issues with the characters seem to be frontend related, not 
core..

PAL is 1:1 PAR on Amiga, and the default settings both on frontend and core will display the aspect properly. As you may have noticed, Amiga resolution height natively is squished compared to width, which means actual 1:1 is out of the question. Which means you must use "Core provided" aspect in the frontend. Integer scale indeed has nothing to do with it.

Raw screenshots taken from the frontend will illustrate the "Single Line" issue. Screenshots will be correct if either Resolution is set to "Low", or Line Mode to "Double Line".

**Comment by oldghost83** [comment]
Thanks for your quick reply!
Deleting core works for you? Why not for me? ) 
I'll be watching this, could be ssd-related, I suppose. It's a new machine. Maybe something else.

Will check into this path to BIOS thing with frontend developers, thanks! I'm sure it's been discussed somewhere.

And thank you for your explanation! Didn't know any of that. 
I'm new on github, so how do we put it? Do we close this issue, which wasn't an issue? I think your explanation would be very helpful for people like me.

**Comment by sonninnos** [comment]
No worries. Since I don't think there is anything to be done core-wise, we can close this.

The hard drive type surely has nothing to do with it, but odd characters maybe. Then again there shouldn't be any if RetroArch is in the root. But maybe there is some kind of permission thing in that case, who knows.
