### ISSUE TITLE
WHDLoad error 'disk is write-protected'

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#407]
Hi, great work on this my man. I was trying to play the WHDLoad game 'F117A Nighthawk' but when selecting a pilot or creating a new one it crashes saying `(disk is write-protected) on deleting "Roster.Fil"`. I also encountered a similar write protect error on a different game but can't remember what it was !

**Comment by sonninnos** [comment]
Thanks. Some slaves are simply faulty when it comes to honoring `SavePath`. There is nothing else to be done except either extract the LHA and launch it as a directory (.info & .slave & directory can be used as content), or convert it to HDF that has enough space for the saves.

**Comment by zzedmore** [comment]
OK thanks. I tried the LHA in WinUAE and when selecting a pilot it says (in game) `"Unable to write to disk in drive. Roster file will not be saved."` You can click OK and the game continues. No crash.

**Comment by sonninnos** [comment]
Hmm, in WinUAE with the exact same config that this core generates I get the exact same WHDLoad error with  only "Quit", "Restart" and "Make coredump", as in no option to continue.

Also found something interesting: After launching the extracted version once and going through the error phase, it will delete `Roster.Fil` from the game data directory, and then it will create the file under `saves/WHDSaves/F-117ANighthawkStealthFighter2.0` like it should. And after that the LHA archive launch works as usual, so the extracted one can be deleted.

**Comment by zzedmore** [comment]
Yeah, in WinUAE using the core WHDLoad.hdf and the game LHA I get the same crash as Retroarch. If I use ClassicWB and the LHA (in WinUAE) then I get the ingame error I mentioned but it then lets you continue to play the game. I suppose it doesn't like the WHDLoad.hdf (or files) ?

**Comment by sonninnos** [comment]
I assume there is no `SavePath` set in `WHDLoad.prefs` in ClassicWB installation then, since by default it is not set. Also `NoWriteCache` is not set by default, which means write operations happen only after quitting WHDLoad cleanly, so maybe it also has a role in this.

Both of those settings are absolutely required in our scope, but the user is still free to edit that file as they please under `system`, as it will be copied to the helper image on launch.

**Comment by zzedmore** [comment]
Yes! If I comment out `NoWriteCache` in the WHDLoad.prefs in Retroarch/system then the game doesn't even display a write error (that WinUAE does) and goes straight to the game. What is this option for and is it safe to leave like this `;NoWriteCache` ?

**Comment by sonninnos** [comment]
But I just explained what it does.. and the prefs file says:
> disable the disk write cache

Without it no saves will be written unless WHDLoad is closed with `QuitKey`. So go right ahead if you don't need in-game saves, or are willing to quit WHDLoad always before quitting RA. Still it only postpones the writing, so it will most likely crash then too without that trick I meantioned earlier.
