### ISSUE TITLE
.ipf  stop working 

### ISSUE THREAD

**Issue by ZzackKbin** [libretro/libretro-uae#408]
I cant run ipf files now with capsimg.so.
 What  happens? lr-puae does not mount img files in DF0.

**Comment by sonninnos** [comment]
Working fine here on Windows and Linux. Log will say what is wrong.

**Comment by ZzackKbin** [comment]
I use Retropie and RPi4: Runcommand looks fine but games wont start:
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-puae/puae_libretro.so --config /opt/retropie/configs/amiga/retroarch.cfg "/home/pi/RetroPie/roms/amiga/5th Gear (Europe).zip" --appendconfig /dev/shm/retroarch.cfg
Unzip: /home/pi/RetroPie/roms/amiga//TEMP/example.ipf
Clean: /home/pi/RetroPie/roms/amiga//TEMP/example.ipf
Clean: /home/pi/RetroPie/roms/amiga//TEMP/example.m3u

**Comment by sonninnos** [comment]
That is console output, not RetroArch log. It will show stuff such as:
```
[libretro INFO] capsimg.dll opened
[libretro INFO] CAPS: library version 5.1
[libretro INFO] CAPS: type:1 date:6.2.2008 21:41:36 rel:2796 rev:1
```

When were you able to run them if suddenly "now" you can't? There hasn't been changes regarding this functionality in a long time, and I'm not witnessing anything out of order.

I also recently built and used caps library with RPi2 without any problems. Perhaps you simply have the wrong library version for the platform.

**Comment by ZzackKbin** [comment]
Where I fing log for retroarch in retropie? 
I've checked /dev/shm/runcommand.log

**Comment by sonninnos** [comment]
Looks like `~/.config/retroarch/logs/` once they are enabled. And `capsimg.so` should be in `~/RetroPie/BIOS/`.

But anyway, Retropie related issues have nothing to do with this core, so I'm closing this. If the library is in the correct place etc, it will work.
