### ISSUE TITLE
Running *ipf files through RetroArch on Android using capsimg.so

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#418]
I'm having no problems whatsoever running *ipf files on my Windows 10 PC using RetroArch 64 bit, this libretro core and having the proper capsimg file installed in the RetroArch system folder.

The same can't be said when running this libretro core on my old Samsung Galaxy S7 with aarch64.apk install of RetroArch downloaded from the RetroArch official download page itself (the "Download (64bit)" link under the Android banner on the download page of retroarch.com).

I'm just wondering if the fault may be within either the Android release of libretro-uae, or of the capsimg project itself (I've already created [an Issue on that GitHub page there some time ago](https://github.com/rsn8887/capsimg/issues/4))?

It's no big deal in my case; I suppose it's wiser to just use either the adf- or whdload versions of the same games instead of the *ipf released on my Galaxy S7, but I just thought that this may be worth noting nonetheless.

**Comment by sonninnos** [comment]
Android isn't allowed to load external libraries from any other than the executable directory, so it should work, if the file is not in `system` but instead in wherever `retroarch` is. But as far as I know that requires rooting. Readme already says that the library is searched from those 2 locations, but maybe it could be clearer that it is required for Android.

So I don't think this will ever change as long as we can't include CAPS library in the core itself..

**Comment by Gagert** [comment]
Thanks for the heads-up. My device is not rooted, it's using standard factory settings.

I didn't know about that regarding how Android works with external libraries. I'll just stick with adf- and whdloads from now on.
