### ISSUE TITLE
Improvement of IPF Support

### ISSUE THREAD

**Issue by Papermanzero** [libretro/libretro-uae#43]
IPF are original copies from amiga games. However it seems there are several issues when loading an ipf with puae. Either there is not enough memory or there is a software issue. Normally IPFs should behave like the ADF file.

**Comment by DamsRoxxx** [comment]
It seems that this core is currently not build with IPF support (CAPS not defined in makefile).

To use IPF support a third party library is needed and you have to be conform with a third party licence “SPS Freeware License Agreement” (see http://www.softpres.org/download).

Don't know if this is compatible with RetroArch licence and distribution.

And if it is, the buildbot of libretro should be updated to build it for release.

**Comment by DamsRoxxx** [comment]
There is a lot of interesting talks concerning ipf implementation and license in fuse core:

https://github.com/libretro/fuse-libretro/issues/30

I'm not an expert but it seems that there are a lot of problems with the library (license, building, distribution).

**Comment by escalade** [comment]
Here you go: https://github.com/libretro/libretro-uae/pull/61

Enjoy ;)

**Comment by DamsRoxxx** [comment]
IPF support added by #61 and #62

To enable it you have to put a dynamic library called capsimg.dll (Windows) or capsimg.so (Linux, macOS) in your retroarch root directory (where retroarch executable is located).

Compatible CAPSIMG libraries for Windows, macOS and Linux can be found at https://fs-uae.net/download#plugins

Please be aware that there are 32-bits and 64-bits versions of the library. Choose the one corresponding to your RetroArch executable.
