### ISSUE TITLE
Correct refresh rates (game speed)

### ISSUE THREAD

**Issue by Zarkovian** [libretro/libretro-uae#431]
Hi sonninnos,

Thank you for the work on the PUAE libretro implementation, it's great to use and very user friendly.

Below is a request to implement the proper switching between progressive and interlaced refresh rates in the libretro core, plus some background how a similar issue was solved/implemented in the psx_beetle core.

Description of issue:

The hard-coded refresh rate of 49.92Hz leads to incorrect game speed with libretro's default time-stretch settings when interlaced content is run. Solution is to have multiple refresh rates, akin this:

#define FPS_PAL_INTERLACED     50.000
#define FPS_PAL_NONINTERLACED  49.92

In PUAE the incorrect refresh rate for interlaced content is most noticable as audio crackling when interlaced content is played, or when it switches back from interlace to progressive but ends up in short field mode (312 line mode). Both make the audio go out of sync. This can also be seen if you run the "statistics" overlay which shows audio buffer saturation going in underrun/overrun. 

Additional information:

The PAL Amiga can run in three rates:

Long field mode (313 lines) is approx 49.92Hz
Short field mode (312 lines) is approx 50.08Hz
Interlaced mode (alternating long/short field mode, 312.5 lines average) is 50.00Hz

The exact rates for these modes can be found in the WinUAE log when running content that switches between progressive and interlace mode. 

Quote from Toni Wilen _"PAL non-laced can be 312 or 313 (LOF bit set = 313, not set = 312, KS sets it to 313 by default), in interlaced mode number of lines alternates between 312 and 313."_ http://eab.abime.net/showthread.php?t=51883

Interlace is enabled with BPLCON0 LACE bit.  http://amigadev.elowar.com/read/ADCD_2.1/Hardware_Manual_guide/node0022.html

The PUAE libretro core could be improved if above refresh rates are correctly set when these modes switch during runtime.

I'm referencing a similar (fixed) issue for the PSX core here, as PSX runs also both pogressive and interlace modes, maybe it can be of help.

https://github.com/libretro/beetle-psx-libretro/issues/509
https://github.com/libretro/beetle-psx-libretro/blob/cd79168f58df84c36e78abba726b913ae5378524/rsx/rsx_intf.h

One of the challenges could be that not all software with interlaced mode on Amiga is set up properly (setting the LACE bit properly), meaning possibly LACE bit is not set but LOF bit is toggled manuallly every other frame. 

An additional caveat is that apparently the 3.1 ROM resets the LOF bit to 313 line mode each frame. This can cause weird interlace behaviour even in real Amigas for some software that have setup interlace incorrectly.

Best thing is to use a 3.0 kickstart with testing AND test games/demos that switch from progressive to interlaced and back in a proper manner. 

It would be really nice if the proper refresh rates for the different modes could be added to the PUAE core for libretro.

**Comment by Zarkovian** [comment]
That's great.

I see the below are the long and short field rates. When interlace is active the real hardware is toggling between these two rates every other frame.  Do you expect to follow it likewise (a lot of switching?), or switch to the average rate of 50.00hz for interlace content like it is done in the PSX core? 

From what I understand on real hardware lace can be ended on both the long field or short field, thus it can return to a progressive rate of 50.08hz (short field) during runtime after exiting interlace. Do you expect to accomodate for this situation also?


```
[libretro INFO] PAL mode lace V=49.9201Hz H=15625.0881Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
[libretro INFO] PAL mode lace V=50.0801Hz H=15625.0881Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0

```

**Comment by sonninnos** [comment]
Give me an example demo that plays sound while doing lace switching, so that I can test a bit more before I push what I have fixed now.

**Comment by Zarkovian** [comment]
[Tint by TBL](https://www.pouet.net/prod.php?which=701)  --  expect this to behave nicely
[Wild by Anadune & Nah-Kolor](https://www.pouet.net/prod.php?which=3715)  -- A lot of switching I think, not sure how system friendly this is done

Hollywood Poker Pro also does quite a bit of switching back and forth.

**Comment by sonninnos** [comment]
Ok, I got the lace switch to change speed, and also made it work without Automatic Line Mode.

Though only way for my setup to not get any audio crackles at those moments is to toggle "Allow PAL/NTSC Hz Change" off, and also of course it helps to force either Single or Double Line, so that RA geometry won't change.

Naturally that "PAL/NTSC" should be removed from the core option label now, since it means all Hz changes.

**Comment by Zarkovian** [comment]
That's great 👍 

Would love to test it a bit  :)

**Comment by sonninnos** [comment]
There is no need to include anything, since as I said, the Hz that libretro uses comes straight from UAE. If UAE tells the wrong rate, then that is another thing entirely. This is about libretro rate being the same rate.

Windows build of the current state:
[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6718700/puae_libretro.zip)

**Comment by Zarkovian** [comment]
Thanks I gave it a quick spin, it works but not yet results in desired behaviour. 

The issue is that during initerlace it is either switching to 50.08 OR 49.92 once. Which is not aligned with the average 50Hz rate of interlaced mode (which is alternating field mode 50.08/49.92/50.08/49.92 etc.., averaging thus at 50.00hz). It results in permanent audio buffer over or underrun.

You can check this by enabling real time statistics in RA settings:

On-Screen Display->On-Screen Notifications -> Notification Visability -> Display statistics ENABLE

Here you can see various statistics like frame rate. Average Audio buffer saturation, time spent close to over and underrun etc.

When you set audio buffer to 72ms in RA, with the PUAE you should get a stable ~50.00% buffer saturation and 0.00% over or underrun.

With the switching ti correct rates this should again stabilize or otherwise the RA frontend and the core are misaligned.

I think a solution could be if possible that you count whether the core reports alternating refresh per field. So normally it is 49.92Hz all good.

But then comes interlace and the fields start to alternate long and short field 49.92/50.08/39.92/50.08 etc. If you count 4 successive field changes like this youcan be sure interlace is active, then set the frontend to report 50.00hz.  Until your algo report 4 successive fields of same rate (either 49.92 for four successive fields or 50.08 for four successive) then you switch back to that rate.

Or count 2 or 3 successive depending on what works, I think with 2 you'll get false positives.

**Comment by sonninnos** [comment]
I think I finally got it, but unfortunately even with 50.0001 laced mode will make "saturation" and "close to blocking" increase like mad compared to nonlaced..

**Comment by Zarkovian** [comment]
Could you share your current build? I think I may help in diagnosing the issue.

**Comment by sonninnos** [comment]
Phew, took a while to get out of a backport whack-a-mole rabbit hole, but seems to be better now. Updated a bunch of code to get the same calculations as current WinUAE, among other things, so hopefully everything else still works.

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6720443/puae_libretro.zip)

**Comment by Zarkovian** [comment]
Thanks for diving into the rabbithole, large improvement over the previous version.

Two issues come to front:
1. when switching out of interlace back to progressive it is updating CORE GEOMETRY correct but  the "CORE TIMING: FPS" is not updating with the value that the log reports. 
2. There's a peculiar audio buffer increasing saturation when interlace is active. Probably best to try to tackle this when issue 1 is resolved?

Additional info on issue 1:

- Updating of both CORE GEOMETRY and CORE TIMING FPS works correctly when switching from progressive to interlace 
- But the other way around, i.e. switching from interlace back to progressive, only CORE GEOMETRY is updated but -not- CORE TIMING FPS. Even though the latter value is reported in the log.

Below are the libretro logs for the game Lionheart starting at wen you push the button and it loads the interlaced menu and ending with pressing the button to start the game (progressive). I've added my comments in between.

```
**Game Menu**
[libretro INFO] PAL mode lace V=50.0003Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
Press button to start game:
ISSUE: --> "Core Timing: FPS" IS NOT updated with this value: 
[libretro INFO] PAL mode V=50.0804Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0  
While the geometry DOES get updated. 
CORRECT [INFO] [Environ]: SET_GEOMETRY: 720x288, aspect: 1.250.   
```
As an example the same happens in the demo Tint by TBL. On switch to interlace it correctly updates core geometry and refresh rate, but when interlace ends it only updates geometry but not the refresh rate. 

Since the log does report the progressive refresh rate, I guess this should be straightforward to fix?

```
switch to interlace
[libretro INFO] PAL mode lace V=50.0003Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
switch back to progressive:
ISSUE: -->  "CORE TIMING: FPS" IS NOT updated with this value: 
[libretro INFO] PAL mode V=50.0804Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
While the geometry DOES get updated. 
```

**Comment by Zarkovian** [comment]
With regards to point 2 in the previous comment, when I launch Lionheart in WInUAE, the WinUAE log also reports a change in soundrate when switching to interlace. I don't see that switch in soundrate (see calculation from log below) reported in the libretro log. Is this updated soundrate calculation also backported from WinUAE? 

```
26-163 [6422 000-000]: SNDRATE 312.5*227.0*50.000282=3546895.024776
26-163 [6422 000-000]: PAL mode lace V=50.0003Hz H=15625.0879Hz (227x312+1) IDX=10 (PAL) D=1 RTG=0/0
```

**Comment by sonninnos** [comment]
It was simply a leftover from the earlier internal offerings, and it ended up ignoring 50.08 always, even non-laced. Now the current code won't even offer wrong lace rates, so no need for such ignores. 

And yes the calculations are current, I have simply skipped the SNDRATE log output, because the useful information is in the next row anyway.

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6721597/puae_libretro.zip)

**Comment by Zarkovian** [comment]
Nice, another improvement, Tint for example works better now

The remaining issue is that in situations where it switches to 50.00hz the audio buffer starts increasing and time spent close to overrun increases continually. 

Do you have an idea what's causing this?

Obviously when the audio buffer increases and time spent close to blocking increases, it means the buffer gets filled faster than it's "eaten" / played at. Based on this my hunch would be the front-end -audio- time stretch rate is not adjusted on the switch to 50.00Hz, , but stays in the rate that correlates with 49.92Hz while the buffer is filling at a rate that corresponds with 50.00hz.

Is there a way to log the audio time stretch adjustments that are done?  One would expect this to show it's not adjusting properly when the switch to 50.00hz is done?

**Comment by sonninnos** [comment]
Hmm, looks like that only happens when "Line Mode" is Automatic, as in when the vertical resolution changes at the same time. Forcing either mode seems to be solid, but since both the core option and the auto switcher does the exact same thing UAE wise (we change a var that UAE reads when it wants), this might get tricky to get them separated and make them happen at different frames..

Single line lace:
![retroarch_2021_06_27_17_26_57_969](https://user-images.githubusercontent.com/45124675/123549235-ca94f200-d770-11eb-9266-ea600a7f6090.png)

Double line lace:
![retroarch_2021_06_27_17_42_42_815](https://user-images.githubusercontent.com/45124675/123549248-d54f8700-d770-11eb-9b39-ec0faf4a53ba.png)

Auto line lace:
![retroarch_2021_06_27_17_28_32_001](https://user-images.githubusercontent.com/45124675/123549260-dd0f2b80-d770-11eb-9d07-1c61eb4c1b95.png)

The display is pretty exact:
![retroarch_2021_06_27_17_32_15_245](https://user-images.githubusercontent.com/45124675/123549275-ec8e7480-d770-11eb-8f7b-ed0345bfcdba.png)

**Comment by Zarkovian** [comment]
That's a nice find. The audio input rates look correct for all three rates, so it must in that automatic line mode.
Hopefully there's a solution to it as for (CRT) shaders in RA the progressive output (input to the shader) needs to be single line and interlaced needs to be double line for their shading ouput to work correct, so automatic line mode is a sort of must have for their features to work correct. 

I see in newer WinUAE the double line mode has an added "interlaced line mode" submenu (it's under the display TAB) where for double line mode the interlaced setting can be:
- Double, frames
- Double, fields
- Double, fields+

But I don't know exactly what those settings do. Maybe it's of relevance, maybe not. (If it aint broke...)

**Comment by sonninnos** [comment]
This PUAE didn't even have any other than double frame mode, so I backported the double field mode, and saw no reason to add the option for the rest. Because double frame is horrible half frame rate 25fps, double fields + is a dark mess, and double field suits pinballs that have lace mode (Pinball Illusions + Slamtilt).

Personally I like to stick with single line, because the blockiness does not bother me that much from the couch distance. Except of course when lace is used with text, like in Darkseed.

**Comment by Zarkovian** [comment]
Very nice that you backported the double field mode, it's indeed great for the pinballs, slamtilt being one of my favourite pinballs. 

I like to watch the occasional demoscene productions also, and they contain quite a bit of mixed content, which makes the automatic line mode perfect to use when you're also applying some shader. Either way PUAE libretro in general is great to use :-D

Not really related to this topic, but it seems to small to open an issue for. Did you consider adding 48Khz as the highest output mode? I was thinking it could be nice if it would be there, as now the core outputs 44100 max which RA or soundcard resamples to 48000 (as most soundcards only have 48000hz). Maybe audio quality would be improved if the core could output 48Khz natively, such that the intermediate conversion step 44.1->48Khz by RA or audio card is skipped? I guess this would only make a difference for Gsync users where core rate is alsways equal to frame rate (such that there's no time stgretch resampling).

**Comment by sonninnos** [comment]
[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6722254/puae_libretro.zip)

Looking pretty good now with auto line.

I can't yet say how audio sample rate would help and if it is worth the effort if it is resampled already by the core instead of frontend. Audio CDs are all in 44100 too, and RA resampler also has options regarding quality.

**Comment by Zarkovian** [comment]
Hmm, it doesn't seem to work for me. With the Workbench test I now get audio buffer saturation depletion in interlace (it goes to 25% quickly) and time spent close to underrun increasing.

For the the demo Tint it's about the same, audio buffer saturation goes to 20% quite quickly when in interlace and time spent close to underrun keeps increasing with auto line.  So it's sort of the opposite of the version of this morning.

**Comment by sonninnos** [comment]
Oops, indeed I was only paying attention to "close to blocking" and not underrun..

Took some dynamite and sweat again to pinpoint the mystery and to cover all bases, but this time I'm feeling lucky.
[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6728444/puae_libretro.zip)

**Comment by sonninnos** [comment]
More improvements, especially the rubbish that shows for a frame after lace auto line switches is now cleared.

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6736086/puae_libretro.zip)

**Comment by Zarkovian** [comment]
SWEEEETT!! Great job! Everything I throw at it switches and syncs quickly.  Thanks a great deal for putting in the sweat, and the dynamite :-D

With the testing I did I encountered only one side-effect, which is surprisingly a graphics bug occuring on first level in Lionheart. The dark green water is flashing bright green occasionally. This is with A1200 14Mhz setup. It gets worse if the CPU speed is increased.

The most recent version I had before the current changes does not have this glitch occuring.  See the snap below.  Any idea if this is related to the recent changes, or possibly something you had updated in your development build before that? 

![lionheart_glitch_with_new_version](https://user-images.githubusercontent.com/27620077/123869855-d7ad0f00-d931-11eb-8a89-617092fa02d9.png)

**Comment by sonninnos** [comment]
No problemo, thanks for pointing the problem out!

And whoops, I've been testing only with non-exact CPU, so didn't notice.

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6737213/puae_libretro.zip)

**Comment by Zarkovian** [comment]
The graphics bug is fixed, but unfortunately the audio overrun issue is back for Lionheart in-game. Just standing at the beginning of the level, audio buffer saturation and time spent to overrun increases to close to 100% levels. Video frame rate at 50.20hz. (?)

Issue happens with any CPU setting > 7.09Mhz.   Using A1200 2MB+8MB Cycle exact 14Mhz shows the issue for example.

Since Lionheart switches to 50.08Hz mode after coming out of the menu, I also tested Tint, but there's no issue there when it switches out of interlace to 50.08Hz.

I'm booting the WHDLoad version of Lionheart btw.

**Comment by sonninnos** [comment]
I don't get it. I tried 3.1 and 3.0 and both give me exact same perfect 0.00% with cycle-exact and non-exact, other core options being defaults..

Also seems to be pure random which rate comes after the lace mode, as in I managed to get 50.08 with 3.1 too, but both work the same here regardless.

3.1:
![retroarch_2021_06_30_14_38_18_302](https://user-images.githubusercontent.com/45124675/123955283-1bdff400-d9b2-11eb-9179-aba9bd2f7a01.png)

3.0:
![retroarch_2021_06_30_14_43_33_913](https://user-images.githubusercontent.com/45124675/123955291-1e424e00-d9b2-11eb-9eae-f38895836931.png)


Here is the SNDRATE logging enabled, if it gives any guidance.

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6740645/puae_libretro.zip)

**Comment by Zarkovian** [comment]
OK I've pinpointed the issue to my Frame Delay setting. When I lower the setting by 1 or 2 notches when running the newer build (with the graphics bug fixed) the earlier reported issue disappears and everything runs great. 

Glad to have that solved!

So I've been doing some more testing and noticed a remaining issue: NTSC laced, it shows the increasing buffer behaviour. 

To replicate: I booted workbench, opened "Storage -> Monitors -> NTSC", then back to "Prefs -> Screenmode -> NTSC: High Res Laced".

Haven't checked this with WinUAE, but I assume this should synchronize as cleanly as the PAL laced mode now does?


With regards to the solved issue an observation (now that I noticed..) You may wonder about the higher fps thing which you never saw, so after comparing my monitor in normal refresh mode versus GSync mode, it seems that when monitor and RA are in fixed refresh rate mode the fps will not fluctuate, not even when Frame Delay is too high (then sound will crackle). But when using Gsync mode (which I was) the FPS will fluctuate when a too high frame delay setting is used (but sound will -not- crackle).  Interesting difference.. :)

With regards to the kick 3.0 and kick 3.1 I think you're right, the line mode / refresh after interlace seems to randomly be 49.92 or 50.08, so not a real difference between using the two kickstarts.

**Comment by Zarkovian** [comment]
Adding to the previous comment, below are the NTSC rates from WinUAE.
```
SNDRATE 262.0*227.5*59.506668=3546894.951553
NTSC mode V=59.5067Hz H=15590.7471Hz (227x262+0) IDX=11 (NTSC) D=1 RTG=0/0

SNDRATE 263.0*227.5*59.280407=3546894.948950
NTSC mode V=59.2804Hz H=15590.7471Hz (227x262+1) IDX=11 (NTSC) D=1 RTG=0/0

SNDRATE 262.5*227.5*59.393322=3546894.947648
NTSC mode lace V=59.3933Hz H=15590.7471Hz (227x262+1) IDX=11 (NTSC) D=1 RTG=0/0
```

**Comment by sonninnos** [comment]
Dangit, always something. And aye, I also noticed it is best to disable frame delay while testing.

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/6744616/puae_libretro.zip)

Final nails to the coffin hopefully.

**Comment by Zarkovian** [comment]
Polished to perfection. Thanks!
