### ISSUE TITLE
WHDLoad LHA Support does not work on my Linux Mint 20.2

### ISSUE THREAD

**Issue by Mitch187** [libretro/libretro-uae#437]
Hi,

i want to switch from amiberry to a 64-Bit computer with Linux Mint. I have install retropie and lt-puae.
But the Program does not start the games in lha format.

What can i do?
How can i analyse the problem?

Best regards,
Mitch

**Comment by Mitch187** [comment]
I found the Problem. I have so many games and i put t to the roms in subfolders (0,A,B,C...) folder from retropie. When i copy the game outside, that it works.

Can you patch it?

**Comment by sonninnos** [comment]
I don't understand. I can have the file in any path in Linux and Windows. Post logs of working and non-working launches.

**Comment by Mitch187** [comment]
> I don't understand. I can have the file in any path in Linux and Windows. Post logs of working and non-working launches.

Which logs?

**Comment by sonninnos** [comment]
RetroArch verbose log which will show all paths etc.

**Comment by Mitch187** [comment]
Here are both verbose logs from retroarch

[runcommand direct in amiga folder.log](https://github.com/libretro/libretro-uae/files/6835804/runcommand.direct.in.amiga.folder.log)
[runcommand in Subfolder T.log](https://github.com/libretro/libretro-uae/files/6835805/runcommand.in.Subfolder.T.log)

On my amiberry installation the games starts in workbench modus for a few seconds. then, i can select a trainer, cheat, etc.. After that the games start. in lr-puae, i don't see that ist it normal? Can i configure it?

**Comment by sonninnos** [comment]
The first log is not a real log, and the second one indeed indicates that RetroPie will use the content dir as save dir, which is annoying since that causes every directory to have the WHDLoad helper images. It shouldn't matter in any other way than little duplicate data and lost space though. That behavior is totally up to the frontend and not the core.

And it even crashes at the end, which is very weird, and also there is an issue with double slashes..

And yes it is normal that by default there is nothing extra at launch. They are accessible by either core option or by holding down certain buttons. README says it all: https://github.com/libretro/libretro-uae#whdload

**Comment by Mitch187** [comment]
Thank for your Help!

The right behaviour ist, that all files are build in the BIOS path, right? And all Games share the created directories?

Is there any way to force this here? With a Parameter?

**Comment by sonninnos** [comment]
`WHDLoad.prefs` is the only file manipulated in where the Kickstarts are, and libretro save path is used for everything else.

Force what exactly..?

**Comment by Mitch187** [comment]
> Force what exactly..?

User one Filder dir all files, that are needed. Expect then lha Files.

**Comment by sonninnos** [comment]
Currently only disabling `savefiles_in_content_dir`.

But good news, I managed to replicate the crash in Linux VM that happens on the first run on a subdirectory when that option is enabled. No solution yet.

**Comment by sonninnos** [comment]
Wohoo, it was the mysterious double slash after all, causing memory corruption..

I'll look at the duplicate data creation prevention next before pushing.

**Comment by Mitch187** [comment]
> But good news, I managed to replicate the crash in Linux VM that happens on the first run on a subdirectory when that option is enabled. No solution yet.

Nice, then i Play the next dass: Copy to root-amuag-folder. And wait dir the Update... No Stress and thank you.

**Comment by sonninnos** [comment]
Both of these problems should be sorted now, so let me know how it goes.

**Comment by Mitch187** [comment]
Awesome, it works. Nice support!
It works great!
