### ISSUE TITLE
Report Git version with Library Version

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-uae#44]
This core doesn't yet appear to report the git version when the core is loaded.  Similar to [this commit](https://github.com/libretro/hatari/commit/911a8cbde60f71c090e07aafbdd8288edd51135d).

This is particularly helpful when trying to discern what version of the core from the buildbot is being used.

Somewhat non-related, it doesn't seem like the buildbot version of this core is being updated for OSX

**Comment by DamsRoxxx** [comment]
Easy and useful fix. 

Patch is ready in my repo.

I will wait till #34 is merged to submit it.

**Comment by DamsRoxxx** [comment]
Fixed in #46
