### ISSUE TITLE
WASAPI low latency audio compatibility

### ISSUE THREAD

**Issue by Zarkovian** [libretro/libretro-uae#446]
Hi sonninnos,

Thank you for the continued work on the PUAE libretro implementation.

I'm trying to use RA's low latency audio driver "WASAPI" with PUAE but I can't get it to work without a lot of audio glitches and frame pacing issues.

The benefit of using WASAPI as the driver for audio is that it allows for audio latency <10ms, which would be a huge improvement over the currently working XAudio driver latency. 

To replicate the issue, set "Drivers -> Audio" to wasapi. Then exit RA and restart. Then go to menu "Audio -> Output" which will now show the wasapi settings "Exclusive Mode",  "Float format" and "Shared buffer length", this last setting is only showing when the setting "User Interface -> Show advanced settings" is enabled.

You will notice that PUAE will experience sound crackling and frame pacing issues with any setting.  Note that you have to have Frame Delay setting OFF / set to "0" as wasapi mode is not compatible with it.

**Some further information**

I noticed many libretro cores have issues when the WASAPI driver is enabled, and only a few seem to actually be compatible with it. Like for example the beetle PC-Engine fast core. It seems to work without issues for me when enabling "Exclusive" and setting the latency to 3 or lower. The log reports 3ms (!) latency when setting the latency to "0" which makes it open the lowest possible driver allowed latency.  Another one that seems to work properly is the mesen (NES) core.

The developer that implemented the WASAPI driver said the following when asked about issue with certain cores:

> Most important stat’s are average input chunk lengths and average blocking times. If input data duration is shorter than device period (reported after client initialization) and intermediate buffer is off, there probably will be issues. The same goes for blocking periods that are longer than device period. Unfortunately audio driver can’t influence either of those two things.
> 
> I tested bsnes-mercury-balanced core and data chunks are too small (below 100 frames) while device period is 480 frames (in shared-mode on my machine). This is why WASAPI driver have problems with this core.

So it seems like a core needs to be properly "tuned" to work with the wasapi low latency audio driver?

Since we have a good reference with WinUAE, which has a working WASAPI implementation I searched for the github commits that implement the WASAPI changes for RA and for WinUAE. Maybe they can be of help.

WinUAE WASAPI implementation was updated with the 3.4.0 release in 2016, see this commit:  [WASAPI sound improvements. ](https://github.com/tonioni/WinUAE/commit/c1d006830b01bf5a0b75332c52b1c242be34235d#diff-f2c36d3ff4f413480b62f708e5ddadb7e6a80181ddc742add858b1b76358886c)

In this I see some buffer related changes, and things like:

> 	// magic adjustment
	sd->sndbufsize = sd->sndbufsize * 2 / 3;

RA's WASAPI implementation was done in 2017 with the 1.6.0 release. See the initial commit here: [add wasapi audio driver](https://github.com/libretro/RetroArch/commit/129151d5fc97449261dfb5939e43634d884494a3)

(single RA wasapi.c here: [retroarch/audio/drivers/wasapi.c](https://github.com/libretro/RetroArch/blob/master/audio/drivers/wasapi.c) )

A quick glance over the commits I see in the WinUAE update things like;

```
 	// wasapi

	IMMDevice *pDevice;
-	IAudioClient *pAudioClient;
+	IAudioClient3 *pAudioClient;

```

Whereas in RA's wasapi commit I don't see any reference to changes from IAudioClient to IAudioClient3.

Which I understand from [https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/low-latency-audio](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/low-latency-audio), if you look further down the page under the header "Windows Audio Session API (WASAPI)" makes quite a difference.  

So maybe this will be as simple as a buffer size change on the PUAE libretro core, but to be honest I doubt it. This of course has the potential to be a rabbithole very deep, since incompatiblity issues could stem from the core side, RA's wasapi implementation or the interaction between them. Nonetheless I hope it has your interest to look into the issue, as the benefit could potentially be a much reduced audio latency for the PUAE core.

**Comment by sonninnos** [comment]
I'm afraid core-wise there is nothing else to change except the buffer size and/or use either `retro_audio_sample_batch_t` or `retro_audio_sample_t`. Batch is used currently, like in the majority of cores AFAIK.

Looking at the stats I noticed that sample count increases a lot more in some cores (like desmume) - meaning the buffer is small -  and I have no idea what is optimal. I have tried changing the size already a bunch of times, and pretty much the only difference it does is start failing when it is too large. So no apparent benefit from going very small. I've tested the delay by finger playing samples from keyboard in Protracker.

Audio sync enabled the audio delay is already minimal enough with xaudio.

And indeed since WASAPI driver in RA seems broken anyway (frame delay like you mentioned), I haven't bothered to test it much.

**Comment by Zarkovian** [comment]
Thanks for looking into this.

Maybe a little progress. I found that Wasapi shared mode can be made to work well enough to not have real noticable glitches.

Could you try the following and see if it's the same for you:

under "Audio -> Output" set "Audio Latency (ms)" to "0" (zero),
set "WASAPI Exclusive mode" to "OFF" (use shared mode)
set "WASAPI shared Buffer Length" to "Auto"

Then check under "Video -> Output"  that the "Vertical Refresh Rate" is set identical to the "Estimated Screen Refresh Rate" . I found that tiny deviations here cause the above test case to be affected. It needs to be the precise refresh rate.

Quit RA, restart and wait a bit for the synchronization to have its effect (frame time deviation on real time statistics will quickly lower until it stabilizes).

With above settings I get very good results, there are only tiny small hickups that you'll probably only notice when you're looking for them.

With this the log reports:

[INFO] [WASAPI]: Initializing client (shared, pcm, 48000Hz, 0ms) ...
[INFO] [WASAPI]: Client initialized (shared, pcm, 48000Hz, 10.0ms).
[INFO] [WASAPI]: Client's buffer length is 1056 frames (22.0ms).
[INFO] [WASAPI]: Device period is 10.0ms (480 frames).
[INFO] [WASAPI]: Intermediate buffer length is 480 frames (10.0ms).

By setting audio latency to "0" it initializes audio with the device period (10ms).  The intermediate buffer length is automatically set to the same size.   If I manually set the intermediate buffer length to anyhing else than 480 frames the glitches appear again quickly.

Could you possibly make a test version where the audio buffer that the core sets can be configured manually trhough the core options?

If possible it would be nice if this buffer could be set as low as 8 and increments with 8. This way it'll always be a size that "fits" the driver set buffer size. For my device RA sets it to either 480 (shared mode)  or 160 (exclusive mode, which doesn't work without crackling audio), so I would like to try some sizes that are an integer fraction of 480 and 160 (480, 360, 240, 160, 120, 80, 40, etc.. )   Maybe we'll find that it can improve things, and maybe not ;-)

**Comment by Zarkovian** [comment]
I found some better info on the desired buffer size. See this link: [Buffer size alignment and the audio period](https://matthewvaneerde.wordpress.com/2013/07/24/buffer-size-alignment-and-the-audio-period/)

It says a common alignment restriction for HD audio hardware is 128 bytes. 

> A while back I talked a bit about the WASAPI exclusive-mode alignment dance. Some audio drivers have a requirement that they deal in buffer sizes which are multiples of a certain byte size – for example, a common alignment restriction for HD Audio hardware is 128 bytes.

> A more general audio requirement is that buffer sizes be a multiple of the size of a PCM audio frame.
For example, suppose the audio format of a stream is stereo 16-bit integer. A single PCM audio frame will be 2 * 2 = 4 bytes. 

Which means the alignment requirement in audio frames is 32. Which is also shown in the table at the bottom of the page.

I don't fully comprehend what else is said but it seems the reasoning is related to audio card wanting to run in cadence of 10ms. Which is also what RA reports in shared mode as the minimum device period (10ms / 480 frames at 48Khz)

It seems if the alignment is set to 32 frames / 128 bytes and the device period and cadence is 480 frames that 480/32 = 15 data chuncks fit into the buffer in wasapi shared mode?

So then the question remains what the optimal size is for exclusive mode, for which RA report for my card in the log a minumum device period of 3.0ms and 3.3ms (160 frames). So here when the PUAE core buffer is set to 128 bytes / 32 frames then only 5 chuncks fit into the exclusive buffer.

Could this imply that for exclusive mode it could be more optimal to set the buffer size to a lower value than 128 bytes / 32 frames, while still being a multiple of 4 bytes, such that also for exclusive mode around 15 chuncks fit the low latency buffer? For example  8 bytes / 2 frames, such that 16 chuncks (closest fit to 15) fit the exclusive buffer?   

Then I tried WinUAE at lowest wasapi shared mode setting and it seems to open a buffer of 1056 bytes on my card. Which isn't an integer multiple of 128 bytes. 1056 equals a buffer of 22.0 ms surprisingly which is mentioned for my card in the RA log, but not set (it sets the minimum device period 10ms for the intermediate buffer length when it's at "auto").

This would suggest it would be worth trying to set the PUAE core buffer as high as 1056 bytes.

**So in conclusion it would seem that 128 bytes would be the safest bet when choosing a single value for the PUAE core to set.

For testing purposes however it would make a lot of sense to create a version that allows for the buffer to be configurable via core options in increments of 4 bytes, such that we can at least try the buffer sizes of 8, 128 and 1056 as our best bets, and probably some in between to see if that makes a difference for the exclusive mode.**

It would be really nice if you can find some time to create this test version.

I understand you already did a lot of testing with various buffer sizes, but hopefully you're interested to create the test version. Now that the shared mode seems to work quite well already when latency setting is at "0" and "Intermediate buffer length is set to "Auto", things can only get better, right? :D

Some thought not related to the buffer setting
With regards to the wasapi driver in RA, it might well be working as it should, at least for wasapi shared mode. I'm not considering it "broken" because it's not compatible with frame delay. That wasapi doesn't work with frame delay may be a consquence of pushing for the lowest latency. Since it works in pull event mode, any delay or better words blocking that is caused on the RA side (Frame delay may be a simple wait in which nothing else (can) occur) will cause the pull events to be missed / discarded, effectively breaking the low latency update need.

So it may be considered as a triangle of video lag, audio lag and input, if you try to squeeze two of them for lower latency that's possible, but if you try to squeeze all three at the same time one has to give (either lower latency audio OR low latency input).  Of course ideally Frame Delay would be non-blocking to the other processes, like the wasapi driver.

**Comment by sonninnos** [comment]
PCE core is using a huge buffer, but it does audio callback right after video callback in `retro_run()`, and this core does audio internally on its own pace, which may not be good.

I need to bump latency to 12 though in PCE to not get crackles, and for solid frametimes 33.

But with this core I get solid audio with 8, and solid frametime with 22.. Does not make much sense..? I'm using 50Hz for PUAE of course and 60Hz for PCE.

```
[INFO] [WASAPI]: Initializing client (exclusive, pcm, 48000Hz, 8ms) ...
[INFO] [WASAPI]: Client initialized (exclusive, pcm, 48000Hz, 8.0ms).
[INFO] [WASAPI]: Client's buffer length is 384 frames (8.0ms).
[INFO] [WASAPI]: Device period is 3.0ms (144 frames).
[INFO] [WASAPI]: Intermediate buffer length is 384 frames (8.0ms).
```

The core sound buffer size is currently 256 bytes and I didn't notice anything different with 128.

Turns out testing this isn't too fun either, because sound breaks completely in exclusive mode after doing fast forward regardless of settings..

**Comment by Zarkovian** [comment]
Yeah so there seem to be too many variables that can be different between cores and their interaction with the wasapi driver.

I get the impression you did quite a bit of buffer testing for the PUAE core already, much appreciated. For me the core option would be only for having a good testing setup to quickly test the numerous combinations of RA wasapi settings and core buffer size. It is never meant as something to in the end incorporate in the core, just for providing thorough feedback. For example using combinations of RA latency size, Wasapi Driver intermediate buffer length and varying the core buffer size leads to too many combinations already to build separate versions for. Let alone when adding testing the combinations with exclusive and adding float enabled/disabled. A core option would be super efficient for testing and retesting and diving a bit deeper, that would be my main interest, to cover a broad spectrum of combinations and possibly get a bit more grip on what are good combinations and what not and provide feedback with it. 

I do appreciate that you've obviously dug deeper into the issue already. The PUAE is already working very well with the XAudio driver, so I also understand it does not have your biggest interest.

It's too bad the original developer of the wasapi driver (casdevel) seemingly abandoned RA / Github, it would've been super helpful if he had could chime in with you as I think he has been working on one side (RA driver) without really knowing the other end (core settings and development). It seems it would need a cooperation on both sides to come up with the real issue at hand. WinUAE obviously has this advantage.

Maybe close this issue for now and or label it as enhancement and reopen once there's active development by someone (@casdevel where are you?) on the wasapi driver again. Just that we'd be there to test the PUAE core and provide the proper feedback.

Thanks again for the insane work on the PUAE core and being there to answer questions etc!

**Comment by sonninnos** [comment]
No problemo.

Sure the temporary option would be handy for confirming what is up, so maybe some time. Point being that core should have zero to do with frontend audio driver, because that is up to the frontend.

I'm even able to push audio latency with xaudio further down than with any other core I've tested.. Every other core crackles heavily with 24, but not this core (frame delay being tuned for each core). Some even require the default 64 (N64, heh) depending on the running software (Excitebike64 vs Doom64).

That means the audio here isn't that bad, but of course it is possible it could be better. Let me know if you find differences with other cores, and possibly a golden standard, since PCE wasn't helping in painting a solid target.

That fastforward issue with WASAPI really needs to get fixed, so I'll try looking at it at some point.

**Comment by sonninnos** [comment]
Oh right, forgot to mention here that I managed to fix WASAPI fast-forwarding in RA.

But should this issue remain open, since there does not seem to be anything wrong or fixable in the way the core handles audio..?

**Comment by sonninnos** [comment]
Any difference with the current situation? Did a small audio buffer change a while back.
