### ISSUE TITLE
Use the left analog stick on a gamepad like dpad

### ISSUE THREAD

**Issue by Mitch187** [libretro/libretro-uae#448]
Hi,

since the last update (i don't know if the retroarch or lr-puae update) the central retroarch config does not work anymore):
input_player1_analog_dpad_mode = "1"
input_player2_analog_dpad_mode = "1"
input_player3_analog_dpad_mode = "1"
input_player4_analog_dpad_mode = "1"

After i realized this, i set the option Mouse Emulation only to right analog stick, because i want to use the left one for dpad emulation, but it does not work anymore. 

In othe retroarch emulators the central config works.

The option is nice to have, because my friends can use dpad or the left analog stick to play games and i don't have to setup this. It works simultaneously.

Have you have an idea, what can i change to use this?

Best Regards,
Mitch

**Comment by sonninnos** [comment]
RA changed recently the way the "Digital to Analog" operates.

Either disable mouse emulation on the left stick and clear all RetroPad mapping bindings, or simply switch ATD mode to "Left Analog (Forced)", as in `input_player1_analog_dpad_mode = "3"`.

Non-forced options only do their job when the core isn't using the particular input at all.

**Comment by sonninnos** [comment]
Oops, indeed it does not work anymore without that force, even when it should.

**Comment by Mitch187** [comment]
Thank you, you are right!
