### ISSUE TITLE
ROM in Readme Checksum

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#453]
Hiya, I was going through the roms in the readme and noticed that there are two listed as `kick40063.A600`. The checksum you have for the one labelled A2000 (v3.1) is actually -

KS ROM v2.04 r37.175 (A500+)(512k).rom (`DC10D7BDD1B6F450773DFB558477C230`)

Not sure what the correct one is for A2000 v3.1.

**Comment by sonninnos** [comment]
Whoops, thanks for notifying, it was some bad copypasta.

It should be `e40a5dfb3d017ba8779faba30cbd1c8e` like above, since it is the same file, also known as:
 `Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000)[!].rom`
