### ISSUE TITLE
Input latency regression

### ISSUE THREAD

**Issue by Zarkovian** [libretro/libretro-uae#454]
Hi Sonninnos,

I updated to the latest PUAE core though the online updater and am noticing that the input latency has become worse.

The input latency in the previous version I have is top notch, very responsive, and I'm able to breeze through for example first levels of Apidya. With the latest version this is no longer possible for me. I can't really describe it, maybe best description is that the input now has a bit of "rubber band" feeling in the response.

I went a few times back and forth between the previous core (9d79df0) and the latest update (9740a00) and it's a repeatable experience, the latest update does not have the top notch responsiveness of the previous core.

Everything else seems the same (sound buffer is stable, fps stable etc..)

Any idea?

**Comment by hizzlekizzle** [comment]
Can you try the frame-advance method to quantify the issue? Using default RetroArch mappings, that's: pause with the 'p' key, then hold a button and press the 'k' key to advance one frame. Keep pressing 'k' until you see a change onscreen. The number of times you press it is the internal latency of the core+game.

**Comment by sonninnos** [comment]
And are you 100% sure that nothing else changed except the core version? I get zero difference between those commits, thus I'll close this now.
