### ISSUE TITLE
Amberstar (German) nonsense dialogue

### ISSUE THREAD

**Issue by DukeSkinny** [libretro/libretro-uae#457]
All regular NPC conversations consist of nonsense strings of random words. This is what happens as soon as I go to speak with Karwain:

![Amberstar_v1 2_De_Fast-210909-213352](https://user-images.githubusercontent.com/22918018/132752612-a994a448-253b-4e1a-9de8-a04651cc9816.png)

I've tried both 68020 & 68000. A600 & A1200. The 'Fast' game version & the regular one. All result in the exact same problem.

[Log](https://pastebin.com/M6wZYK2k) from the latest attempt using A1200 & 68000 with the Fast (1.2) version.
[Core options](https://pastebin.com/krA9G8ND).

**Comment by sonninnos** [comment]
Does the English version suffer from it? Does it happen with any other UAE version? Does it happen with the disk version?

I'm not familiar with the game at all, and thus can't test it without clear steps of how to get to that point.

http://whdload.de/games/Amberstar.html mentions something related:
`- German version exits with dialogue error at certain place (not problem of this patch)`

**Comment by DukeSkinny** [comment]
The English version seems OK. FS-UAE gives me the same result as the core. I tried several sources to no avail, but interestingly enough the folks from which I got one of the copies speak about it as though there's nothing wrong with it.

As I am terribly unfamiliar with anything non-WHDLoad-related, I ran into some troubles testing the disk version. I'll get back to you if I manage to make it run.

In the meantime, if you'd like to try it out, you need only speak to with any random NPC walking about in the first-person mode. Start the game, click through the intro text, move south to enter the town (Numpad controls). Here, walk around until you find any NPC, right right the movement menu as you stand in front of them, click the mouth to initiate dialogue. You should be able to select a conversation topic which will produce the gibberish.

**Comment by sonninnos** [comment]
Well if it happens with FS-UAE too, then the WHDLoad slave is most likely to blame, and there is nothing to be done here.. Or maybe it is just the pre-install and not the slave, meaning that you might want to try creating a fresh install from IPF disks.

"Wenn ist das Nunstück git und Slotermeyer? Ja! Beiherhund das Oder die Flipperwaldt gersput!", heh.
