### ISSUE TITLE
Is there a possibility to support the fmv cd32 device bios in the future?

### ISSUE THREAD

**Issue by gabberhead** [libretro/libretro-uae#463]
for example, cannon fodder has a mpeg video before the game start. it is working on winuae with the needed bios.

it could be named: kick40060.CD32.fmv

CD32 Full Motion Video Cartridge ROM v3.1 r40.030
md5 hash is: 1C8BBF475D1ADF52EF01B24F50BECF37

CD32 Full Motion Video Cartridge ROM v3.1 r40.022
md5 hash is: 76864BE8AC98B7F62688DAC3D8ACD7EE

**Comment by sonninnos** [comment]
I can't get it to work even with WinUAE 4.4.0.. tried quickstart configs and everything.

There are some incomplete code bits here, but it would need a lot of backporting to get it working, and who knows what else video decoding related. And all just for one game intro does not seem worth the effort all..

**Comment by gabberhead** [comment]
It work with Winuae 4.4.0 on my site. Before the game starts the Video is playing. If u tried it with a chd file u are right, it wont work. Why, I dont know. But with a cue/bin file it works without problems. There is also a second game wich uses the fmv wich I know of. It is the dangerous streets / wing commander disc. It is the cd32 advertising on that disc. It also works without cue/bin, but not with a chd file.

Ps. I testet a lot of games in retroarch and 4 games are not working but they work in winuae. They do not work as adf files or whdload. I will make another post for this Issue later.

**Comment by sonninnos** [comment]
Ah, I only tested it as CHD, so no wonder then. Which does not help with motivation one tiny bit.. Of course I won't stop anyone else from doing a PR.

There is already a non-working WHDLoad issue list, so no need to create more issues for them.

**Comment by gabberhead** [comment]
I didn't know about the whdload list, but the same games as adf files are also not working. Can u give me a link to that list, then I can compare if those games are in that list.

**Comment by sonninnos** [comment]
Simply scroll the issue list to the bottom.

**Comment by sonninnos** [comment]
Finally had a serious stab at this, and indeed not impossible:
![retroarch_2023_01_30_00_01_05_398](https://user-images.githubusercontent.com/45124675/215358111-462923e5-3756-49ad-9e8b-964921e1c8fa.png)


Still no sound though, and the image is squished if not forcing double line mode, and also only 16bit depth shows properly , but progress at least!

**Comment by gabberhead** [comment]
Wow. Never thought u will working on it :) Is the progress available on retroarch already or Do u have only a test core which u are working on it?

**Comment by sonninnos** [comment]
Test core for myself of course for now. Not ready for sharing yet.

**Comment by sonninnos** [comment]
Ok, sound and the rest is working now, and usage is extremely simple: Copy the FMV cart ROM to the usual place in `system/uae/` with other carts, and enable it with the core option.

Will push soon after some final testings.

**Comment by gabberhead** [comment]
ok. thanx for the info. is it also working with a chd file or only cue/bin files like on winaue?

**Comment by sonninnos** [comment]
Same restrictions apply.

**Comment by sonninnos** [comment]
Hah, good thing I waited, since I decided to investigate further about the CHD, and the first hunch sorted it out. Just a simple case missing in the CHD reading code.

**Comment by gabberhead** [comment]
the problem with the chd files you discovered is also the same problem as on winuae?

**Comment by sonninnos** [comment]
Naturally, the MAME CHD code is simply missing the mode: https://eab.abime.net/showpost.php?p=1593326&postcount=39

**Comment by gabberhead** [comment]
did u also try the cd32 advetisment vido on the dangerous streets / wing commander disc if it works? but i think, if the cannon fodder video now is playing, then it should also play the cd32 advertisment video without problem, when the missing code is implemented for the videos for the chd files.

**Comment by sonninnos** [comment]
Works fine.

**Comment by gabberhead** [comment]
its working :) one question. 2021 when i tried it with winuae, i had some sound hick ups in the video after ca. 29sek in the video till the end. now with puae i also have the same problem. i testet it with both rom revisions. do u have this also? if yes, is it a possibility to change something in the options to get rid of it?

**Comment by sonninnos** [comment]
If WinUAE does the same then I guess it is how it is then. And the glitches seem to be uniform, and there is no difference between CHD and raw image, as in either the dump is bad, or that is how the source or the decoding just is. Seems well enough though in order to not use much more time with it.

**Comment by gabberhead** [comment]
ok. one quick question. i also have an action replay cardrige rom to use it for a500 games. how can i get in it when a game is running? which keyboard button it is? i cant find a way to get in it :)

**Comment by sonninnos** [comment]
Short press of the power button in the VKBD is the freeze button.

**Comment by gabberhead** [comment]
Is it only accessible via vkbd? Or can be a keyboard or joypad button be mapped to get access?

**Comment by sonninnos** [comment]
Only VKBD for now.

**Comment by zzedmore** [comment]
I did try this for shits & giggles and found the sound starts stuttering after a while. Note, any VCD should work now with this (can find some on Archive. org). I tried it with a German Movie trailers VCD.

**Comment by gabberhead** [comment]
This is the same problem with the Sound stuttering in the cannon fodder video after ca  29sek. But this problem also have winuae, since i testen it in 2021. I also tried a redump verfied image, and the problem is the same for Cue/bin and also chd. It seems it is a generel problem not puae only related.

**Comment by AhayriSG** [comment]
Is PBC (Playback Control) supported for VCD 2.0 or later, enabling menu and navigation functionality? I've read [this forum thread](https://eab.abime.net/showthread.php?t=109233) but remain unsure about its support. According to [this thread](https://forum.amiga.org/index.php?topic=2208.0) VCD2.0 supported by hardware but i'm not sure if it had PBC support.

Just wanted to add a real-world test case to this thread regarding VCD track behavior and potential PBC support. I'm using the PUAE core with a clean, proper multi-bin dump of a VCD title. The disc layout has 5 separate physical .bin tracks: Track 1 is the data/player files, Tracks 2-4 are short intro clips/commercials, and Track 5 is the main feature. If I boot the master .cue file and use the built-in CD32 FMV player interface, I can select and play any individual track manually just fine. However, if I tick multiple checkboxes next to the tracks to queue them up and hit Play, here is what happens:
* It plays the first queued track perfectly.
* The exact moment that track ends, playback just stops.
* It doesn't auto-advance to the next queued track. The emulator doesn't freeze or crash or anything (I can freely look at the VCD player menu and manually start the other tracks again) but the programmed sequence just refuses to continue on its own.

Regarding the accuracy of the CD32 FMV emulation and its VCD 2.0 sequence/PBC (Playback Control) logic, I don't currently know if the original hardware was actually capable of automatically advancing to the next queued track on a multi-track disc, or if stopping and returning to the menu after each clip is the authentic hardware behavior. Sharing this scenario here in case anyone with access to a real CD32 and an FMV module can verify whether the original system natively supports sequential playback when multiple tracks are selected.
