### ISSUE TITLE
No keyboard events passed in "game focus mode" when run-ahead is globally enabled

### ISSUE THREAD

**Issue by bidinou** [libretro/libretro-uae#468]
Hi !

Using the latest RA (snap packages) and puae core, I noticed that the keyboards events are not passed when enabling both "game focus mode" (general settings) and "keyboard pass-through".

HOWEVER, they are passed when using the pass-through without the focus-mode - which is not optimal because one has to unbind all RA events. <-- this bit is actually wrong, see below

Thanks a lot for your commitment in improving the puae core, that is SO much appreciated :-)
cheers

(configuration : Linux, KDE-Neon (based on Ubuntu 20.04 + up to date KDE stack), snap packages of retroarch, Vulkan)

**Comment by sonninnos** [comment]
That core option is pretty much a relic from the time when RetroArch did not block keyboard events when they are used in hotkeys etc, but then again the core did not use frontend key events then either, so there is no wonder it does not work anymore as intended.

Without it for example default keyboard settings would send joystick directions and keyboard arrow keys at the same time when using the keyboard. And currently the frontend blocks it from happening, so the core option can not do anything. And it only applied to keys that are used as RetroPad buttons.

Frontend "game focus" simply allows keyboard events to go to the core uninterrupted. What is it that you are trying to do exactly that you need the core option? How old are the snap packages..?

With "game focus" I can type no problems and the core options does nothing.

**Comment by bidinou** [comment]
Hi ! 
Thanks a lot for taking the time to reply.
I'm actually using the latest snap packages (and I think I doubled checked with the Steam build and the Flatpak ones). 
What happens is, when using "game focus" & "keyboard pass-through", I cannot use my keyboard for Amiga apps using the keyboard.
For instance, interactive fictions.
If I don't use the "game focus" mode but still use "keyboard pass-through", the problem is obviously that some keys trigger RetroArch events (but the other keys are passed to the Amiga program).

**Comment by bidinou** [comment]
Hmm. Actually, I tried again, and the "pass-through" option doesn't actually seem to make a difference. So with or without game focus, I actually cannot send characters to the Amiga app. 

Maybe I'm overlooking something.

**Comment by bidinou** [comment]
AH !

It works with the Flatpak packages but not with the Snap ones !

**Comment by bidinou** [comment]
Oh my, I "backported" all my RA settings into the Flatpak-RetroArch and... Now the keyboard doesn't work anymore ! 
I tried to modify tons of settings but cannot figure out the culprit.

**Comment by bidinou** [comment]
OK ! So, the culprit setting is...
Enabling run-ahead !!

**Comment by bidinou** [comment]
Okay, so, it turned out... It's a general RetroArch issue as it also affects the DOSBOX core !

**Comment by sonninnos** [comment]
The core actually successfully disables runahead at startup, but apparently not when second instance is also enabled.. Same thing applies to changing disks. As in it can't recover to normal state if second instance is enabled at startup, and stays forever broken.
