### ISSUE TITLE
Floppy disks : unable to swap outside of MD mode except, when run-ahead enabled (or otherwise, in a temporary way, after altering an unrelated setting)

### ISSUE THREAD

**Issue by bidinou** [libretro/libretro-uae#469]
Hi ! I am encountering the following floppy disks related issue. 
Configuration : KDE Neon (Ubuntu 20.04 based) + snap packages of Retroarch (up to date).

I cannot swap disks in non Multidisk mode, even if they are in a M3U playlist and even if I eject and select the new disk properly

HOWEVER I did manage to get some MultiDisk games work in MD mode (for example Athanor 2, as this game supports several floppy drivers)

I guess I'm definitely doing something wrong :-) 
Cheers & thank you so much !!

**Comment by bidinou** [comment]
Update to issue 1 : I have to investigate some more regarding the floppy which do not boot when first inserted. I had some strange results -- I managed to boot turbo Tomato on KS 3.1 although this is definitely an A500 game.

However, the issue when trying to swap floppies is still here. 

Example : I made a playlist for the Eon demo. Disabled Multidisk because the demo only supports a single floppy drive. When I am being asked for the 2nd disk, I eject & insert the 2nd disk in the playlist. It not detected.

**Comment by bidinou** [comment]
OK, I'm editing this issue after making quite a few tests. I've figured out something new :  

Swapping floppy disks does NOT work UNLESS changing the "whdload support" settings and closing the current content, restarting the core !!

I can either change from "none" to "files" or from "files" to "none". Close content. Load an ADF, and, tada, I can swap disks !

If I don't do that, after selecting a new disk, it is not detected.

I have to do this once each time I start RetroArch. Then floppy disks swapping works until I quit RA.

(Edit : I also edited my initial post as I had made a mistake regarding some incompatible disks ; there was another problem, it was my fault)

**Comment by sonninnos** [comment]
That makes absolutely no sense, since the value of that core option is only investigated when booting hard drive images, not floppies.

Debug level log output would shine a light.

I can append/insert floppies just fine regardless if booted with floppies or hard drives.

**Comment by bidinou** [comment]
Yep, it indeed makes no sense at all -- but it's 100% reproducible here :) I'll send you a debug log as soon as possible. Thank you :)

**Comment by bidinou** [comment]
I also made a post on the forum, to see if other people encounter the same problem as me :)
I hope you don't mind !
https://forums.libretro.com/t/unable-to-swap-disks-non-md-unless-altering-an-unrelated-setting/35718

**Comment by bidinou** [comment]
AAAH !!!
Figured out !
Yet another bug triggered when the global "run-ahead" setting is enabled ! 
Disk swapping works 100% when it's disabled (without modifying unrelated settings ;)

**Comment by bidinou** [comment]
Here is the debug log in which I start PUAE with SOS1.adf (Shadow of Sergoth, new RPG :) and try to swap with SOS2.adf. It's not inserted / detected.
https://easyupload.io/yhhjat

**Comment by sonninnos** [comment]
I'll close this one too since I think frontend related run-ahead issues should be fixed in the frontend.
