### ISSUE TITLE
Feature Request : run-ahead possible ?

### ISSUE THREAD

**Issue by bidinou** [libretro/libretro-uae#470]
Hi ! 

I realize this is probably a huge undertaking. I was wondering if run-ahead was potentially implementable in the puae core or if there are some major hurdles ?

Best regards

**Comment by sonninnos** [comment]
PRs are welcome, but I have zero motivation: https://github.com/libretro/libretro-uae/issues/217

**Comment by bidinou** [comment]
Ah, I didn't search for closed issues, sorry for the duplicate then. 
Thanks for your reply !
