### ISSUE TITLE
Files .hdf does not work in the new version

### ISSUE THREAD

**Issue by ToniBC** [libretro/libretro-uae#485]
The core was updated to version 244d06b and the .hdf files no longer load, I tried several and none of them work, it keeps loading with a black screen.

With the previous version, the 3ec4903, which is in the 1.9.14 cores, with that yes they load the WHD (hdf) as before.

Thank you.

**Comment by sonninnos** [comment]
I spent all day yesterday trying to figure it out, and still no dice..

**Comment by ToniBC** [comment]
Ok, yes, what I have with hdf and as you say, something happened that stopped working with the last update.

**Comment by sonninnos** [comment]
I decided to revert the update for the time being.

**Comment by ToniBC** [comment]
Ok, hopefully you can find where the error is, because with normal disks it works fine and I thought I read that the core was updated to 4.9 (I guess with respect to WinUAE). which would be great to improve compatibility.

**Comment by sonninnos** [comment]
Phew, looks like I finally found the goof. Now only need to get SCSI CD to also work, and then we are back in business!

The new version is/was 4.5.0 beta17, because 4.9.0 caused extra issues in libretro-side which I wasn't ready to change yet.

**Comment by SultanOfDawn** [comment]
[itsultan]()
[update]()
[Sultan win]()
[19842022]()

**Comment by sonninnos** [comment]
SCSI CD issue remains a mystery, but the old core is available as `puae2021` if that is needed for now, and also for low specs.
