### ISSUE TITLE
All titles after core update run slow and stutters.

### ISSUE THREAD

**Issue by MrSisters** [libretro/libretro-uae#486]
I did a core update and now as the title suggests all titles run slow and stutters. ADF LHA etc. All ran beautifully before (ECS,OCS), unfortunately I do not have a core backup… so no chance to roll back.

I am running Retroarch 32bit on a Android TV system. Core was originally installed in Nov 13 I think.

Any help would be appreciated as I can no longer play any titles.
Happy Holidays

**Comment by sonninnos** [comment]
That is too bad. I did not notice any speed differences on my rig. Might need to make the previous version available for weaker systems then..

**Comment by sonninnos** [comment]
The update is reverted now until this and HDF issue is sorted.

**Comment by zzedmore** [comment]
Thanks for the heads up! I'll lock this core so it can't be updated as I personally haven't noticed any speed difference on Pi 400 and Android. The OP must be using a very slow device ?

**Comment by sonninnos** [comment]
The current 4.5.0 is available under my repo branch "next", so it can be built whenever.

**Comment by christianhaitian** [comment]
Just adding that I got a similar report from a user when I built the 4.5.0 core from source for a rk3326 device (ex. Odroid Go Advance) and was run on Retroarch 1.9.13.  The distro used was ArkOS whoch is based on Ubuntu/Debian.

**Comment by MrSisters** [comment]
Thank you sooo much (that is from the wife as well) for a revert for now, that did the trick and on Christmas Eve no less!
Yes it is a weak system, Philips (55PUS7803) tv with built in Android Tv. The CPU Model is not known to me, ARMv7 architecture with 4 cores.

Again thank you for the fix, the work you all put in to this Core and to the community!
Want me to close this out now or do you need any additional info?

**Comment by sonninnos** [comment]
Nice. The mega update was supposed to be the present, but back to the oven it goes then..

Sure there is no need to keep this open anymore. If and when the new version is ready, it shall not replace this one.
