### ISSUE TITLE
 Controller problem. 

### ISSUE THREAD

**Issue by ZzackKbin** [libretro/libretro-uae#489]
Hi 
In few games I have strange thing with controller. 
Its look like mouse and joystick together working in the same time example in FIFA Int. Soccer but in Sensilbe soccer is everything is ok.
I see this behaviour first time. In past was ok.

**Comment by sonninnos** [comment]
I haven't noticed, and it should be happening everywhere then, not just one game.

Statusbar shows joyport activity.

**Comment by ZzackKbin** [comment]
In most games is ok but in FIFA not. Strange.

**Comment by ZzackKbin** [comment]
Controller in fifa works but I must run game and dont switch any time joy mouse and any time press pad analog (mosue). If broke this rules the controller goes crazy 0_o 

Thx  for help.

**Comment by sonninnos** [comment]
Yep, I've encountered a few that go haywire if mouse is plugged in and moved, especially CD32 games. And since this one requires a joystick with 2 fire buttons anyway, it does not surprise me much.
