### ISSUE TITLE
In menu "Manage Cores Commodore Amiga PUAE" not information about A500 1.2, A2000 1.2, A4000 030 3.1 and 040 3.1 files requirements

### ISSUE THREAD

**Issue by Augusto7743** [libretro/libretro-uae#491]
If selecting the Amiga models A500 1.2, A2000 1.2, A4000 030 3.1 and 040 3.1 is displayed missing files.

A500 1.2 and A2000 1.2
kick33180.a500
A4000 030 3.1 040 3.1
kick40068.A4000

In PUAE core information not have details about the files above.

**Comment by sonninnos** [comment]
Those particular Kickstarts are totally optional and unimportant.

**Comment by Augusto7743** [comment]
I not understand exactly if have any better performance between the models A500 1.2, A2000 1.2, A4000 030 3.1 and 040 3.1.
Have games not starting with an model and start with other model.
The user not understand because the model not start.

**Comment by sonninnos** [comment]
No there will be no "better performance". There is no need to worry about them if you don't know what you are doing.

**Comment by sonninnos** [comment]
Closed by https://github.com/libretro/libretro-super/pull/1650
