### ISSUE TITLE
Crash of Retroarch after using P-UAE (one time crash)

### ISSUE THREAD

**Issue by Marc91360** [libretro/libretro-uae#492]
Hello,
I'm using P-UAE (1.9.10 - PUAE 2.6.1) on Switch, and it works rather good: I can play a lot of games.

But each time I play an Amiga game, the next time I try to play another one (or quit retroarch, and try to go back to it, or try to load another core), I have an error, and I have to re-lauch Retroarch.

Something like "An error has occurred ..."

In summary: If I play an Amiga Game, no way to play another one: P-UAE / Retroarch crashes one time, and I have to reload a second time Retroarch to make it work. Even If I leave Retroarch, or try to load another core, I have a crash (but only one, then everything is fine).

Is there something wrong somewhere ?

Best regards

Marc

**Comment by sonninnos** [comment]
Duplicate https://github.com/libretro/libretro-uae/issues/359

**Comment by JonnyUtah100pc** [comment]
Hi Marc,

Was this ever solved? I am having the same issue on my Switch Retroarch - after play any Amiga ROM on PUAE 2021, Retroarch crashes exactly as above. 

I have researched the web and haven't found a solution.

Any help gratefully received.

Regards 
Lee

**Comment by sonninnos** [comment]
"Duplicate" implied that there is no point discussing twice about the same thing.

**Comment by JonnyUtah100pc** [comment]
Hi
With great respect I know what ‘duplicate’ means :)

I followed the thread and nothing shows how to stop the problem on retroarch for me anyway. How do I use any of the code on the solved section ?

regards
Lee

**Comment by sonninnos** [comment]
But it isn't solved yet, so there is no stopping it without fixing the code.

**Comment by JonnyUtah100pc** [comment]
Hi thanks for getting back. It will stop me trying to search for hours for a solution.

it’s not a massive issue more a niggling quirk :)
