### ISSUE TITLE
Baby Jo in "Going Home" runs too fast in WHDLoad version

### ISSUE THREAD

**Issue by vinxi2** [libretro/libretro-uae#496]
Hello,

first of all thank you for your great work. I'm using the latest RetroArch and PUAE versions, and I'm trying to play Baby Jo in "Going Home" v1.1_2291 and it runs too fast no matter what settings I use. I also tried Cycle Exact option.

The same game in ADF version works perfectly fine.

Thank you!

**Comment by sonninnos** [comment]
Thanks.

If that happens with Cycle-exact, it likely isn't even an emulation issue, as in same things happen with similar actual hardware setups. Try running it in A600 instead of A1200.
