### ISSUE TITLE
WHDLoad Filenames with spaces

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#497]
Hi, when loading WHDLoad files and the requester comes up, it won't load filenames that have spaces in. 

![WHDL-220321-100622](https://user-images.githubusercontent.com/79696530/159241278-b0a2c652-54a8-49ee-af3f-9ff32261f04f.png)

These are Aladin's WHDLoad files.

**Comment by sonninnos** [comment]
Edit `saves/WHDLoad/S/WBSelect` and add quotes to row 10 `$WBRUN#?`, like so:
```
List "$WBRUN#?" QUICK NOHEAD DIRS LFORMAT %F%M TO ENV:WBDIR
```

**Comment by zzedmore** [comment]
Thanks. Will this become a permanent change in PUAE ? Or I'll have to remember to change it if I load a file from a different location.

**Comment by sonninnos** [comment]
Yes yes, I'll update it when I get around to it and after it is confirmed that it won't cause new troubles.

**Comment by sonninnos** [comment]
HDFs and everything else that works now seems to work except SCSI CD..

**Comment by zzedmore** [comment]
Keep up the great work ! I massively prefer your PUAE core over Amiberry (which is what that A500 Mini is using). The guy that put the work into Amiberry didn't even know it was being used ! That's Github I suppose. They think it's a free way to make money off other people's work.

**Comment by zzedmore** [comment]
Could you also update WHDload as well (18.7) ? It's still on 18.5. (Just to be future proof, i've only seen Workbench 1.3/3.1 that need it but maybe more).

http://whdload.de/docs/History.html

**Comment by sonninnos** [comment]
Ok, done.
