### ISSUE TITLE
Carrier Command ADF/IPF Retroarch crash

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#506]
Hi, any idea why Carrier Command completely crashes Retroarch before it even loads to the menu ? I was looking for a cracked ADF version that has the sampled music. I also tried the IPF and that crashes at the same point. I've attached some of the culprits. There is a version that works that doesn't have the sampled music, just wondered why these crash.

[Carrier Command v1.1 (1988-08-03)(Rainbird)[cr PUB].zip](https://github.com/libretro/libretro-uae/files/8381849/Carrier.Command.v1.1.1988-08-03.Rainbird.cr.PUB.zip)
[Carrier Command v1.1 (1988-08-03)(Rainbird)[cr Tristar][h Atrium Commodore Center- ZB].zip](https://github.com/libretro/libretro-uae/files/8381851/Carrier.Command.v1.1.1988-08-03.Rainbird.cr.Tristar.h.Atrium.Commodore.Center-.ZB.zip)
[Carrier Command v1.2 (1988-08-19)(Rainbird)[cr].zip](https://github.com/libretro/libretro-uae/files/8381852/Carrier.Command.v1.2.1988-08-19.Rainbird.cr.zip)

**Comment by sonninnos** [comment]
Both IPF and WHDLoad versions work fine here with default settings.

I tried that cracked 1.2 and it does not crash with the new 4.5.0 version, but crashes with current. Thus zero motivation to investigate further.

**Comment by sonninnos** [comment]
There are a few similar cases which simply crash with the old version.

I'm starting to give up on the final non-working thing, as in postpone it, so maybe soon.

**Comment by zzedmore** [comment]
So is it possible to release 2 versions on Retroarch ? This current 'old' core and the new 4.5.0 core without CD support. Maybe call it a Beta ?

**Comment by sonninnos** [comment]
Of course two separate versions, because the new one is slower.

**Comment by sonninnos** [comment]
New one is live, and old one is separated as `puae2021`, thus closing this.
