### ISSUE TITLE
Keyboard is set to AZERTY (Fr) by default. Additional Shift key problem.

### ISSUE THREAD

**Issue by wronghands** [libretro/libretro-uae#51]
Hello,

The keyboard has an AZERTY layout by by default without an "input.prefs" file and even when one with an English keymap is present. This happens with kickstart 3.1 and 1.3 alike, with or without startup-sequence. 
<img width="657" alt="azerty" src="https://user-images.githubusercontent.com/16123640/48317301-eba77500-e5bd-11e8-988e-397fb779567a.png">
<img width="655" alt="31" src="https://user-images.githubusercontent.com/16123640/48317302-ee09cf00-e5bd-11e8-9b57-90a2d8b40cd1.png">
<img width="670" alt="13" src="https://user-images.githubusercontent.com/16123640/48317305-ef3afc00-e5bd-11e8-8d4f-28751a5af6a6.png">

Image is from wikipedia:
![500px-kb_france svg](https://user-images.githubusercontent.com/16123640/48317298-dd595900-e5bd-11e8-8a7c-99c46ab79c5b.png)

The only temporary workaround is to counterintuitively choose an actual French layout in input settings under workbench. This way the layout switches to English. However it reverts back to French outside that workbench environment ie. when booting without startup sequence. Also this workaround doesn't fix the special characters.

<img width="662" alt="fre" src="https://user-images.githubusercontent.com/16123640/48317311-04178f80-e5be-11e8-98c0-f4d1d46ecea0.png">
<img width="658" alt="ame" src="https://user-images.githubusercontent.com/16123640/48317313-0679e980-e5be-11e8-9610-0ebf3b557232.png">

Windows 10 country preferences were set to Canada when I first encountered this error but changing it to United States and restarting Windows did not resolve the problem. Windows display language was always set to "English (United States)". I haven't encountered this problem with any other software including WinUAE using the same hdf files and kickstart roms. Also, Canada does not use an AZERTY layout even for French.

<img width="362" alt="region" src="https://user-images.githubusercontent.com/16123640/48317349-81430480-e5be-11e8-9230-3c0d3f6a328d.png">

**Shift problem:**
In addition to this, the shift key works as a toggle and not an actual modifier key. It gets stuck once pressed and has to be pressed again to switch back to normal typing similar to a caps lock but different because it also modifies the special characters that way, unlike a caps lock.

Thanks in advance and thank you for developing this core.

**Comment by wronghands** [comment]
Any updates?

**Comment by defcon8** [comment]
Same problem here, makes this core totally unusable for me! Can we override the layout back to QUERTY with a config file option?

**Comment by defcon8** [comment]
@wronghands Already found a workaround for this issue?

**Comment by wronghands** [comment]
@defcon8 I didn't really bother trying to find one since no one responded for months but I built a new PC this week and I'm planning to duplicate the problem now that you confirmed I wasn't imagining things. Thanks. I also noticed that the shift key bit wasn't a separate issue but related to how FR keyboards worked.

**Comment by defcon8** [comment]
@wronghands Thanks for the feedback.

Ps. besides that the keyboard layout is French/Belgium also the letter M seems to be mapped to the key next to it on the right side. Very strange problem.
