### ISSUE TITLE
One of two commits severely impacts performance on recent builds

### ISSUE THREAD

**Issue by rhester72** [libretro/libretro-uae#511]
Somewhere between 28-Mar-2022 and 7-Apr-2022, a commit SEVERELY impaired performance (even on an overclocked RPi 4) and more than doubled the binary size.

I suspect commit https://github.com/libretro/libretro-uae/commit/022c82b63ccb0d76a35803e52fa3458542f7ebf0 due to the apparent addition of esp.c but that is a guess on my part.  *Something* definitely significantly changed, and from what I can tell nothing in the Retropie toolchain was updated in between.

**Comment by zzedmore** [comment]
Probably due to the fact that sonninos updated PUAE to v4.5.1 for more accuracy from WinUAE. The old build is now called puae2021.

**Comment by sonninnos** [comment]
Yes, the new 4.5.0 version is to blame. The old version is kept in `2.6.1` branch for the low-power machines. Accuracy comes at a cost. No way around it I'm afraid.

**Comment by rhester72** [comment]
Understood, will ask the Retropie folks whether they can maintain both.  Thank you!

**Comment by ZzackKbin** [comment]
You killing my dune. Now glitches with normal speed or normal graphics with glitches in audio :(

**Comment by sonninnos** [comment]
It is what it is. Use the old core version.

**Comment by ZzackKbin** [comment]
how? retropie see only newest.

**Comment by sonninnos** [comment]
If `puae2021` core is not yet available to download, you must build the `2.6.1` branch manually.

**Comment by ZzackKbin** [comment]
Is too much for me.

**Comment by rhester72** [comment]
@ZzackKbin I've raised the question of tracking puae2021 as a separate package in RetroPie here:

https://retropie.org.uk/forum/topic/32502/can-retropie-please-track-legacy-lr-puae-now

For the time being, I'm attaching a build of 2.6.1 HEAD here, just replace your existing library with this and you'll be up to date (thus far).

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/8458193/puae_libretro.zip)

(Unzip, copy to your RetroPie box, ssh in and copy it to /opt/retropie/libretrocores/lr-puae)

**Comment by ZzackKbin** [comment]
Thx :)

**Comment by sonninnos** [comment]
Enabling "Immediate Blitter" seems to also fix the graphic glitches without Cycle-exact.

**Comment by ZzackKbin** [comment]
> Enabling "Immediate Blitter" seems to also fix the graphic glitches without Cycle-exact.

works. thx
