### ISSUE TITLE
Fast Copper option 

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#512]
Would it be difficult / much effort on your part to port the 'Fast Copper' option ? It used to be in WinUAE a long time ago but was removed because it was a hack. It still exists in Amiberry and gives a good performance boost on stuff that uses copper (obviously 😄 ). I understand if it's too much work or not motivational.

**Comment by sonninnos** [comment]
Nah. I tried it once already in the old branch and it did not work at all. No speedup and garbage visuals.

**Comment by zzedmore** [comment]
Oh, it gives quite a boost on Amiberry. OK no worries.

**Comment by sonninnos** [comment]
I think I tried to make Lionheart playable with RPi2 and I monkeyed the code from UAE4ARM. Maybe I goofed something or they simply are not compatible.
