### ISSUE TITLE
[RPi] Crash with Puae Libretro core when using Vulkan driver

### ISSUE THREAD

**Issue by amverweij** [libretro/libretro-uae#517]
Using the current master branch of libretro-uae on a RPi4 (aarch64), when selecting the Vulkan driver in retroarch the core cashes on startup.

Doing the same with the puae2021 Libretro core from the 2.6.1 branch starts emulation as expected.

Platform: RPi4, aarch64
Kernel 5.15.27-v8+
Mesa 22.0.1

The crash was produced using Test Drive and Jim Power.

**Comment by sonninnos** [comment]
The frontend video driver should indeed not matter at all since the core is pure software video..

**Comment by amverweij** [comment]
Retroarch log file is here:
[retroarch.log](https://github.com/libretro/libretro-uae/files/8507432/retroarch.log)

Call stack:
[coredumpctl.txt](https://github.com/libretro/libretro-uae/files/8507443/coredumpctl.txt)

**Comment by amverweij** [comment]
I was a bit surprised to see it start initially (that was the first time). Might be because it is compiled in debug now. The stack traces from before compiling it in debug appear similar in the sense that they also crash in libvulkan_broadcom.so.

It occurs to me that the crash in the second try is right where it mentions "[INFO] [Vulkan]: Destroying stale acquire semaphore." in the first try.

**Comment by sonninnos** [comment]
I don't get it, since that video stuff is the frontend's responsibility and thus out of the hands of the core, as the crash log also indicates. So you are positive that the old branch never crashes in the same way?

**Comment by amverweij** [comment]
I never had any problems with the old core. Puae2021 still works fine for me too. I will try with fresh settings, that's a good idea. It could be an upgrade issue.

**Comment by amverweij** [comment]
Well after recompiling mesa in debug, both the puae Libretro core and the puae2021 Libretro core fail with an assertion.
Gdb log is here:
[gdb.txt](https://github.com/libretro/libretro-uae/files/8525126/gdb.txt)
It seems that the assertion  assert(descriptor->image_view); is not satisfied. However since puae2021 survives this when mesa is not compiled with debug on, we can't conclude that this is the reason of the crash.

**Comment by sonninnos** [comment]
Does not make any sense, since again none of the functions in the log are PUAE core functions..

**Comment by amverweij** [comment]
After upgrading RetroArch to 1.10.3, the issue has gone away. 

Maybe it was a duplicate of https://github.com/libretro/RetroArch/issues/13801.
