### ISSUE TITLE
z3mem_size option does not add memory.

### ISSUE THREAD

**Issue by wronghands** [libretro/libretro-uae#53]
Hello,

As the title says z3mem_size option documented in the configuration.txt does not add a recognizable memory add on to the system and it doesn't show up in the early boot menu. 

This is how it looks like:
<img width="671" alt="untitled" src="https://user-images.githubusercontent.com/16123640/48316428-7fbf0f80-e5b1-11e8-9d04-77682bff195a.png">
<img width="654" alt="e" src="https://user-images.githubusercontent.com/16123640/48318028-6a091480-e5c8-11e8-8262-31efa28b10ff.png">

This is how it's supposed to look like (I used winuae for comparison): Please note that the Gayle chip is not detected / missing from P-UAE as well.
<img width="718" alt="w2" src="https://user-images.githubusercontent.com/16123640/48316439-a8470980-e5b1-11e8-885f-57f6cc6ec8e8.png">
<img width="648" alt="wa" src="https://user-images.githubusercontent.com/16123640/48318071-1a771880-e5c9-11e8-8f35-31836afef5c5.png">

My configuration is as follows:
_kickstart_rom_file=amiga/kick.rom
chipmem_size=4
fastmem_size=8
bogomem_size=4
z3mem_size=16
use_gui=no
nr_floppies=1
cpu_type=68020
cpu_speed=real
cpu_compatible=false
ntsc=false
chipset=aga
immediate_blits=false
gfx_linemode=double
gfx_framerate=1
sound_output=normal
sound_frequency=44100
sound_channels=stereo
sound_interpol=none
show_leds=true
floppy_speed=800
gfx_center_vertical=smart
gfx_center_horizontal=smart
hardfile2=rw,DH0:sys.hdf,32,1,2,512,1,
hardfile2=rw,UDH1:2040.hdf,63,4,2,512,0,
hardfile2=rw,UDH2:2040B.hdf,63,4,2,512,0,
hardfile2=rw,UDH3:whdsaves.hdf,63,4,2,512,0,_

This is only my current configuration. Changes to memory and cpu settings do not seem to solve the problem.

Thank you for updating this core.

**Comment by wronghands** [comment]
This was an old report. I learned a little bit more about the status of uae derivatives meanwhile and came to the conclusion that this functionality is disabled in some of the uae cores that had the misfortune to be translated to the android os and then back to linux. I guess the pandora project is to blame? I don't mind if this gets closed because it's too much hassle to fix.

**Comment by sonninnos** [comment]
Yep, looks like it is not worth it. Z3mem depends on NATMEM_OFFSET and that depends on JIT and that depends on all kinds of other stuff.

But out of interest: What would it actually achieve? What would be better with it?
