### ISSUE TITLE
Zool 2 CD32 grapical issues

### ISSUE THREAD

**Issue by Condor-2-4-2** [libretro/libretro-uae#530]
I have noticed extreme graphical glitches and inverted colours in the CD32 version of Zool 2 (see attachment). These graphical issues appear only ingame. The intro, title and menue screens will displayed correct.

I have tested the game with different core settings. E.g. I tried both CD32 models with CPU 'more compatible' and 'immediate blitter' as well as 'cycle exact' and 'wait for blitter' without success. I didn't found any combination of core settings which could solve the graphical issues.

I also tested the game with WinUAE 4.9.1 and had no issues. Here I used the following settings:

CPU 68020 / MMU and FPU none / chipset AGA with cycle exact full and cycle exact DMA/memory access / 2MB chip ram + 8MB fast ram / CD32 KS ROM v3.1 rev 40.60 (512k) + CD32 extended ROM rev 40.60 (512k)

I want to clear up if I'm using the wrong settings in P-UAE (and which one are correct) or if the emulator has a bug.

My system specifications are:

Retroarch 1.10.3 with P-UAE core 4.5.0b17 1849a0c

![Zool 2 (1994)(Gremlin) ! -220523-164735](https://user-images.githubusercontent.com/49206911/170291609-5823b8f5-f9f3-4c5b-bb70-780d78398bbc.png)
![Zool 2 (1994)(Gremlin) ! -220523-164747](https://user-images.githubusercontent.com/49206911/170291614-5ccc632b-71d3-4203-8b96-c069ed18a954.png)
![Zool 2 (1994)(Gremlin) ! -220523-164814](https://user-images.githubusercontent.com/49206911/170291618-6eb170e0-3fb9-488d-bc38-b528b337c916.png)

**Comment by sonninnos** [comment]
Similar but not same glitches happen also with 4.4.0 WinUAE, and indeed does not happen with old 2021 core and also does not happen with 4.9.0 core I made when I made this current 4.5.0 one. I went with the older one since the newer one had other issues that needed resolving, but I guess this is a good enough reason to update.

**Comment by sonninnos** [comment]
Just a little teaser of things looking good:

![retroarch_2022_05_29_14_37_46_374](https://user-images.githubusercontent.com/45124675/170865985-03b2f9ef-d2c2-4663-9caa-3b25be661dbb.png)

**Comment by zzedmore** [comment]
Looking forward to the new update ! Would 'Action Replay 3' rom work on this newer version ? Just for shits and giggles.

**Comment by Condor-2-4-2** [comment]
The image looks promising and I'm glad that there will be an update soon. Thank you for the fast response in this case.

**Comment by sonninnos** [comment]
I was able to enable this one also with the new version, but with 2021 it crashes at the moment..

![retroarch_2022_06_01_04_03_50_881](https://user-images.githubusercontent.com/45124675/171308078-724e567d-dff1-4229-92f4-3bc3de1687f8.png)

Need to set `cart_file` manually in uae conf file and do a short press on the VKBD reset button, just like in VICE.

**Comment by sonninnos** [comment]
Yes, Cycle-exact is what causes it.
