### ISSUE TITLE
Bart vs. The Space Mutants whdload 2 disc version intro don't play

### ISSUE THREAD

**Issue by gabberhead** [libretro/libretro-uae#533]
the game as whdload "BartVsTheSpaceMutants_v1.1_2Disk_0884.lha" starts directly with the game. the intro is not playing. when i unpack the lha file, and start the game with the file "BartVsSpaceMutants2Disk.info" the intro is playing and after that, it starts the game. i don't think, this is the right behavior with the lha file.

**Comment by sonninnos** [comment]
Yes it is the correct behavior. Look inside the archive and you will see that the intro has a separate slave. There is no way to pick the "right" one automatically if there are multiple slaves and the "right" one has a different name than the main directory.

The way to launch it is to hold the fire button while startup and selecting the wanted info. The selector does come up automatically when there are multiple slaves and if none of them are named like the directory, therefore when there is no "default". But with these cases the selector must be summoned manually.

**Comment by gabberhead** [comment]
ok. thanx for the info. didn't know that. but what is with predator 2? there are also 2 disks one of this is the intro, but it has only one slave file. how can i get the intro work before the game starts? holding the fire button don't work for predator 2.
