### ISSUE TITLE
whdload 18.8 was released.

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-uae#534]
Does it fix the problem you had with it that caused the revert from 18.7? Here is the changelog: http://www.whdload.de/docs/History.html

**Comment by sonninnos** [comment]
Unfortunately no.. Floppy sized save file creations like in Portal still fail.

**Comment by sonninnos** [comment]
I'm closing this since this version shall not be included.

**Comment by i30817** [comment]
18.9 was released yesterday coincidentally.

**Comment by sonninnos** [comment]
Unfortunately the same issue still exists. It is related to write cache, since with write cache enabled the disk is created fine with the newer versions.

I really should try to see if WHDLoad quit could somehow be forced on RA quit, so that disabling write cache is not necessary..

**Comment by hatetepe** [comment]
I see a new option for core - nowritecache.
Am I right that the problem has been solved?

**Comment by sonninnos** [comment]
The problem preventing the version update, pretty sure yes it is solved.

**Comment by hatetepe** [comment]
Great job and very good news :)
