### ISSUE TITLE
No option to disable Virtual Keyboard touch input.

### ISSUE THREAD

**Issue by Denshadego** [libretro/libretro-uae#535]
As the title says, with no option for disabling touch input, when using a gamepad overlay in android and opening the virtual keyboard, the touch input for the VK gets in the way and keys get pressed when one is pushing an unrelated button on the gamepad overlay. 
An option for the virtual keyboard to only be interacted through retropad/gamepad (no touch) would be ideal.

**Comment by sonninnos** [comment]
This needs to be solved in the frontend instead. In the meantime use a preset that does not overlap with the emulated image.

**Comment by sonninnos** [comment]
Should be sorted with https://github.com/libretro/RetroArch/pull/14044
