### ISSUE TITLE
Action Replay

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#538]
Thanks for the updates. Unfortunately, the Action Replay III only seems to work when loading the core without content. If you load a game etc. then press the reset button it doesn't seem to do anything.

I made a quick .uae file called 'puae_libretro_A500' (as the Action Replay 3 only works on A500). Although not sure if that's the correct model to add to the filename as that will probably only work with 512 chip 512 slow.

If I just select 'Load Core' then press the reset button, it works.

**Comment by sonninnos** [comment]
That preset replacer file is currently only meant for replacing these critical blocks (debug level logging shows the full generated config):
```
cpu_model=68000
chipset=ocs
chipset_compatible=A500
chipmem_size=1
bogomem_size=2
fastmem_size=0
```
And since the current buffer is currently only 256 bytes, it is not hard to fill it up with a long path, resulting in truncation. I was able to add `cart_file` to that block easily though, and freezing works as expected with or without content, but still I guess I should create a similar core option for selecting carts from a certain directory like in VICE.

**Comment by zzedmore** [comment]
OK thanks.

A heads up on a different issue (without opening another thread), there is a WHDLoad game called 'SevenCitiesOfGold_v2.0_NTSC_0908' which requires a A1000 ROM `kick31340.a1000` CRC32:	ec86dae2.

**Comment by sonninnos** [comment]
Nice to know, but doing yet another KS copying hassle for both modes isn't yet looking worth it if it is used by only one game.. Copying the files (KS + RTB) manually is pretty simple luckily.

**Comment by zzedmore** [comment]
Yeah, I thought that too when I read the EAB thread. A PAL rom for an NTSC game !

**Comment by zzedmore** [comment]
Oh, I get it now. My .uae file was in the 'saves' directory but the game I was running was on the desktop so it needed to go in the `saves\Desktop` directory.

**Comment by zzedmore** [comment]
So I tried loading a file from the Desktop.

This log is with the `puae_libretro_A500.uae` in the saves directory (AR doesn't work when pressing reset) -
[retroarch saves.log](https://github.com/libretro/libretro-uae/files/8993266/retroarch.saves.log)

This log is with `puae_libretro_A500.uae` in the saves/desktop directory (AR works) -
[retroarch saves desktop.log](https://github.com/libretro/libretro-uae/files/8993285/retroarch.saves.desktop.log)

A couple of things I noticed in the log, `AR ROM patched for KS2.0+`. So the AR Mk3 should work on A600 and above as well ?
And it also said 'Action Replay Checksum is INVALID'.

**Comment by sonninnos** [comment]
Well you clearly have `savefile_directory` pointed to `saves\Desktop`, so that is what will be used:

```
[INFO] [Overrides]: No content-dir-specific overrides found at "C:\Games\RetroArch\config\PUAE\\Desktop.cfg".

[INFO] [Overrides]: Redirecting save file to "C:\Games\RetroArch\saves\\Desktop\Tinyus [Arcade conversion].srm".
[INFO] [Overrides]: Redirecting save state to "C:\Games\RetroArch\states\\Desktop\Tinyus [Arcade conversion].state".

[libretro INFO] Unzip: C:\Games\RetroArch\saves\\Desktop\TEMP\Tinyus [Arcade conversion].adf
[libretro INFO] ->M3U: C:\Games\RetroArch\saves\\Desktop\TEMP\Tinyus [Arcade conversion].m3u
[libretro INFO] No model specified in: 'C:\Games\RetroArch\saves\\Desktop\TEMP\Tinyus [Arcade conversion].m3u'
```

As in probably `sort_savefiles_by_content_enable` is enabled then. Nothing to be done here in the core.

**Comment by zzedmore** [comment]
Yes I think I have that option on to keep the saves directory tidy and so I know what saves are for what system. I'll just have to remember to put the .uae file in the directories that I run the games etc. from.

Thanks.

**Comment by zzedmore** [comment]
Did you say something about a core option ? This would make it more user friendly to just enable the option instead of using a .uae file in the correct saves directory. And also make it easy to disable in case a game detects the cart.

The log file said something about it patching to work with kickstart 2+ so maybe the AR Mk3 v3.17 rom would work with all models ?

**Comment by zzedmore** [comment]
Should I close this ? Not sure if you are interested in adding it as a core option. Maybe too many incompatibilities ?

**Comment by sonninnos** [comment]
I'll look into it at some point.
