### ISSUE TITLE
Mouse left  button activates every time move cursor

### ISSUE THREAD

**Issue by maxm79** [libretro/libretro-uae#547]
Using retroarch on Android running workbench from hdf file.  Every time I move the mouse cursor using touchscreen it also clicks the left mouse button at the end of the movement.  Any idea how to fix this please?

**Comment by sonninnos** [comment]
Touchscreen pointer being mouse is a frontend feature. As in the core only reads touch pointer for the VKBD, and mouse comes from mouse. Meaning that there is nothing to be done about that here in the core.

I'm able to move the mouse with a touchscreen without clicking though. Mouse can be disabled with the "Physical Mouse" core option.
