### ISSUE TITLE
Workbench wrong palette

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#549]
Hi,
Loading WB 3.0 hdf from planet emu, I noticed that it boots in black and white, with a red mouse pointer. If you lauch Palette and click "use" for the default, then the palette reverts to what it should be, with blue and grey.
Other emulators, like vAmigaWeb, with the same hdf file and settings, boot the hdf directly in the right palette.
Is it that puae has a default option for grey palette with some screens?
Brgds

**Comment by sonninnos** [comment]
Either disable "WHDLoad Support" option to skip the core included hard drive booting completely (which uses custom `system-configuration`) , or change "WHDLoad Theme" option to "Native".

**Comment by Vweber73** [comment]
Many thanks!
Cheers
