### ISSUE TITLE
[Feature request] Light gun support

### ISSUE THREAD

**Issue by Tovarichtch** [libretro/libretro-uae#554]
Hello devs,

I wonder if it's possible to add the light gun support for the many compatible games of Amiga. I know there were few light guns available like the famous Trojan Light Phazer. I don't know if all games are Phazer-compatible since this one was using db9 connector (joystick), whereas, for example, Loriciel light gun was using db25 connector (serial). Nonetheless, I think the Trojan Light Phazer would be a great addition.

Thanks a lot !

**Comment by sonninnos** [comment]
This is ready for the next batch, which comes soonish.

**Comment by Tovarichtch** [comment]
That is a wonderful news! Very much appreciate!
