### ISSUE TITLE
Is RAW format supported ?

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#556]
Hi, just a quick question. There are some coverdisks etc. on Archive.org that are in .RAW format and don't have an equivalent ADF version in TOSEC. WinUAE supports .RAW format so I wondered if the capability is already in PUAE but Retroarch doesn't recognize the file extension ?

**Comment by sonninnos** [comment]
I'm not seeing WinUAE allowing any ".raw" extension as floppy, and the only rawish one I'm seeing in the code is ".fdi" which is enabled. Other than the extended version of ".adf", which of course is also allowed.

**Comment by zzedmore** [comment]
Here is an example of the file format. They load fine in WinUAE -

[Amiga Power December 1994 Disk 44a [RAW].zip](https://github.com/libretro/libretro-uae/files/9697383/Amiga.Power.December.1994.Disk.44a.RAW.zip)

**Comment by sonninnos** [comment]
Sure, WinUAE floppy dialog accepts wildcards, but we can't do that in the core, otherwise unwanted files will get appended to Disc Control.

Hmm.. that RAW is actually IPF in disguise (extended version), because header says CAPS and it won't work without the library. But if renamed as IPF, the core crashes after a few `corrupted trackspeed value` log lines, yet WinUAE continues after same errors..

**Comment by zzedmore** [comment]
I removed the CAPS library from my WinUAE and yes, when loading the image in WinUAE it says it needs the SPS plugin, so it is related to IPF.

I still can't get the CAPS library to work in Android though. Any ideas? or maybe there just isn't a working library for Android.

**Comment by sonninnos** [comment]
AFAIK Android can only load libraries from the same path with the executable, so it needs rooting to get it there.

**Comment by zzedmore** [comment]
> AFAIK Android can only load libraries from the same path with the executable, so it needs rooting to get it there

That's a shame. I suppose there's no way for you to bypass it to look in the system directory ?

**Comment by zzedmore** [comment]
Thanks !
