### ISSUE TITLE
Slowdown in Settlers 

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#559]
Hi,

I you launch The Settlers with a powerful configuration (68030+, 2mb chip, 4mb+ chip ram, HDD), then you are entitled to max map size = 8.
If you choose 8 for map size then start the game, during the world computation the music gets crappy and slow, until the computation is complete, which does not happen with other Amiga emulators.
Any idea why?

Many thanks and best regards

**Comment by sonninnos** [comment]
Well are all the other settings exactly the same with other emulators? WinUAE should be slowing down just as much, since the code is the same.

I tried 68030 which allowed the map size 8, and generation does not slow down at all even with Cycle-exact. Sure I get 3x faster speed with Normal when fast-forwarding.

**Comment by sonninnos** [comment]
And are the other emulators that don't slow down with the same settings as recent and as accurate? The current 4.9.1 core sure is slow, especially with that hardware, and 68030 of course makes it slower.

How is the performance with the faster old 2.6.1 core (PUAE 2021)?

**Comment by Vweber73** [comment]
The other emulator I'm using is vAmigaWeb (new core compared to winuae). It is cycle-exact (setting that I used here in P-UAE) and has no slowdown.

I tried the old core, and I got something quite strange, see attached. Maybe the snapshots are messed up between the 2 cores? I loaded this from "History", I tried settlers long ago with the old core so I still had an entry, but I had to restart, when I was in the new core and chose the old core settlers history entry it did nothing, as if it thought it was the same that was already running... 
![Screenshot_20221021_174659_RetroArch (AArch64)](https://user-images.githubusercontent.com/92450215/197237506-a7330f58-1b8f-47a7-bb9d-766557662f4e.jpg)

**Comment by sonninnos** [comment]
Yes I get that screen too with the old core with 68030 and Cycle-exact, but Normal works fine. The old core simply is less accurate and not as complete.

**Comment by Vweber73** [comment]
Thanks! So what would be the best setting for Settlers? Old or New core with/without cycle-exact?

**Comment by sonninnos** [comment]
The one that works well enough of course. This game does not require Cycle-exact, so no need to use it.

Too bad Cycle-exact isn't perfect even with the latest version, but I default to that with my hardware, since it is still the most compatible option.

**Comment by Vweber73** [comment]
At least the intro requires cycle-exact, otherwise the animation is messed up.
Thanks!

**Comment by sonninnos** [comment]
I guess this can be closed, since I don't know what could or should be done about this..?

**Comment by Vweber73** [comment]
Well, removing the cycle-exact option makes it work correctly, but that does not explain the slowdown in cycle-exact, which does not occur with vAmigaWeb (cycle exact core)

**Comment by sonninnos** [comment]
Most likely that is because this current Cycle-exact is the most accurate one, and thus requires most horse power. No code magic is going to change that.

**Comment by sonninnos** [comment]
I'll close this since the core isn't going to get any faster.
