### ISSUE TITLE
Request: resolution switching for crt switchres

### ISSUE THREAD

**Issue by retrorepair** [libretro/libretro-uae#56]
Now that retroarch is capable of switching resolution on the fly for crt users, it would be nice if we weren't limited to one resolution on boot when many games and apps switch res mid game.

This would mean either deciding which options are enabled (lores, linemode, pal, ntsc) on the fly based on the current framebuffer or using the framebuffer itself to fill the variables in retro system av info (forget the exact name).

Obviously this should be an option either in the core settings or config file as it won't apply to everyone.

**Comment by retrorepair** [comment]
The benefit is CRT users will then have progressive and interlaced modes and any resolution that the virtual amiga draws will be displayed correctly without scaling issues.

**Comment by retrorepair** [comment]
I should add this option is aimed mainly at CRT TV users so the native resolution is low res

**Comment by retrorepair** [comment]
https://forums.libretro.com/t/15-khz-crt-documentation-wiki/15671/4

This may explain more as I've not worked on this project for over 6 months and it's early in the morning :)

**Comment by rsn8887** [comment]
This should've just been fixed by the merging of PR #113 . If you think there's still some problem with this, please comment here, and I will re-open the issue.
