### ISSUE TITLE
lr-puae2021 mouse jitter over time on interlaced screens fix

### ISSUE THREAD

**Issue by rhester72** [libretro/libretro-uae#560]
I experienced the issue described here:

https://eab.abime.net/showthread.php?t=109446

and found the fix from early this year:

https://github.com/tonioni/WinUAE/commit/0027bcff91ce5a458c77c8cd8b8134f2d0a36240

which I've backported to lr-puae2021 in the attached patch (forgive me, I am not fluent enough in git to do it via pull request).

This does NOT apply to the newer lr-puae branch (with a much more modern WinUAE base) that already includes this patch.

I've tested with no issues and confirmed it resolves the issue,  Please consider applying the patch to the lr-puae2021 branch for future releases.

[inputdevice_mousefix.zip](https://github.com/libretro/libretro-uae/files/9840618/inputdevice_mousefix.zip)

**Comment by sonninnos** [comment]
Thanks, looking good. I'll try to do some tests as soon as possible.

**Comment by rhester72** [comment]
Thank you!

The same issue was identified and corrected (by the same means) in Amiberry here, just for reference:

https://github.com/BlitterStudio/amiberry/issues/624

**Comment by sonninnos** [comment]
Heh, I don't have time to wait 10 hours, so I'll take your word for it. Patch applied and pushed.

**Comment by rhester72** [comment]
Thanks much!  Will provide final confirmation once the binary build updates propagate.

**Comment by rhester72** [comment]
Never mind - compiled from latest source from RetroPie-Setup directly, let it run for 12 hours, and no issues - confirmed good.  Huge thanks for the integration help!
