### ISSUE TITLE
CHD Audio

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#561]
I have been following this thread -

https://eab.abime.net/showthread.php?t=112171

I thought it was normal behaviour to begin with but now it seems it was bugs in WinUAE. The thread now seems to have stopped and Toni released a new Beta but hasn't fixed the slow start time of the music. It looks like he's not bothered and wants to keep it inaccurate ? 

Any chance you could port his "partial" CHD fix ?

**Comment by sonninnos** [comment]
Patience. No reason to "fix" things haphazardly without a proper fix.

**Comment by sonninnos** [comment]
Okeydokey, I finally had time and I think I nailed it. Please test.

**Comment by zzedmore** [comment]
I tested some of the games that were listed in that EAB thread and they are working great ! I also downloaded his Battle Chess audio CHD and the tracks start at 0 seconds like they should. I compared it to the latest WinUAE Beta and the tracks still have a 2 second silence before they start ! I also think you've nailed it. Better than WinUAE !!

You Da Man !!
