### ISSUE TITLE
Saves not In folders ?

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#562]
I have the option 'Sort saves/states in folders by content directory' on. In the 'saves' directory I have the following Amiga files that aren't in it's content directory folder -

Puae_libretro.hdf
.nvr
TEMP directory
WHDLoad directory
WHDSaves directory

All other systems are saving their files to the correct content directory.

Note - 'states' ARE saving to the correct content folder but not 'saves'.

**Comment by sonninnos** [comment]
Weird. The core seems to be using the API save directory like it should be used, but something is definitely wrong when that option is enabled.

Also the frontend assigns the path in the wrong order, as in `[content_path]/[core]` when it should absolutely be the other way around when both sorts are enabled. But even so only those directories are created, and the savefile will be on the root of saves..

Tried simply with a CD32 game which creates `[content].nvr` file on boot.

**Comment by sonninnos** [comment]
Hmm, this appears to be a frontend issue since `RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY` won't get the content dir path appended to it, meaning that every core that does not do saving via the API (which is designed for SRAM stuff only) should suffer from the same thing.

**Comment by sonninnos** [comment]
Ok, I think I got it working now without breaking anything else.

**Comment by Tasosgemah** [comment]
> Ok, I think I got it working now without breaking anything else.

Seems like this is broken again. No matter what the option for the save location is, PUAE will always put the saves (including two WHDLoad subfolders) in the root saves folder, cluttering it. Though it will create a PUAE sub-folder if the option is such, but it won't save any files in it. The core also ignores any custom save location set in the PUAE.cfg.

**Comment by sonninnos** [comment]
Still works here, and there hasn't been any related changes. I have `savefile_directory = ":\saves\amiga"` set with `--appendconfig`.

Core is not responsible for creating core-sorted subfolders.
