### ISSUE TITLE
F3-F5 doesn't work (on-screen keyboard)

### ISSUE THREAD

**Issue by escalade** [libretro/libretro-uae#57]
Tested with Battlesquadron. F1/F2 works fine, F3-F5 doesn't do anything.

**Comment by grant2258** [comment]
try activate gamefocus mode see if that helps

**Comment by escalade** [comment]
No difference. Regular keyboard works fine, this is just the on-screen keyboard.

**Comment by sonninnos** [comment]
They all work fine here. Tested with SetKey.

**Comment by sonninnos** [comment]
Here is a little teaser on the new keyboard layout progress for today to get the saliva going:
![retroarch_2019_08_28_02_02_45_477](https://user-images.githubusercontent.com/45124675/63814742-9107bb80-c93a-11e9-94ab-b325cb50097e.png)

**Comment by escalade** [comment]
@rsn8887 

It's still an issue. Tested using Battlesquadron (love that game), on the main menu you can use F1-F5 to change different aspects of the game. F5 should change from two players to one but it has no effect. F1 and F2 works though. I haven't bound F5 to anything in my config, also I use hotkey for menu toggle so all keys should be available.

@sonninnos 

You're adding stuff faster than I can think about it, great! Once you're done with that, let's get savestates working lol just kidding :D 👯 The keyboard looks great. At this rate, looks like fs-uae will be obsolete soon ;)

**Comment by sonninnos** [comment]
That issue is fixed in the overhaul PR coming soon. The reason indeed was that the keypress will be very short, since it is made on keyup and released immediately on the next input run. Why it didn't affect F1+F2 in that game is anybody's guess..

**Comment by escalade** [comment]
@sonninnos 

Confirmed fixed, and the new keyboard is awesome. This is now in great shape, thanks guys.
