### ISSUE TITLE
kickstart not found

### ISSUE THREAD

**Issue by elessar38** [libretro/libretro-uae#571]
After the latest update, puae does not see kickstarts.
Starting the game, I get the message kickstart rom kick40068.A120 not found. Changing system to another one also doesn't help (A1200 to A500 - same error), CD32 also shows kickstart error.

**Comment by sonninnos** [comment]
Weird, it didn't happen for me, but I'll look into it.

**Comment by sonninnos** [comment]
Ok, should be fixed now when the next version comes out, so please confirm.

**Comment by elessar38** [comment]
@sonninnos thanks for the quick fix. Everything works.
