### ISSUE TITLE
[Feature Request] Per-game WHDLoad.prefs

### ISSUE THREAD

**Issue by redmist77** [libretro/libretro-uae#572]
It's it possible to add a custom WHDLoad.prefs for a particular game?  If not, it would be a useful feature.  e.g. some games like Elfmania require NoWriteCache to be disabled to avoid screen flickering.

**Comment by zzedmore** [comment]
You mean on the coins of Elfmania ? 'Memory Cycle Exact' cleared that up for me.

**Comment by redmist77** [comment]
No, the flashing on the loading/title/character-selection screens.  'Memory Cycle Exact' doesn't fix that.  The only fix is to enable WHDLoad disk write cache.

**Comment by redmist77** [comment]
Ah, it looks like this issue is handled in WHDLoad 18.7.  PUAE currently uses 18.6

Details here -: http://www.mantis.whdload.de/view.php?id=5263

With this fix, it would be possible to create  saves\WHDSaves\custom_Elfmania.slave containing a command "WriteCache" which would override the "NoWriteCache" in the global WHDLoad.prefs

A workaround is to remove NoWriteCache globally and then create a custom_<game>.slave for every other game which contains "NoWriteCache".  😲

**Comment by sonninnos** [comment]
It sure would be nice to able to have the write cache enabled always AND not lose saves when quitting RA instead of WHDLoad.
