### ISSUE TITLE
Image stretching

### ISSUE THREAD

**Issue by elessar38** [libretro/libretro-uae#574]
PUAE image stretching works very strangely on RA. I use 1080p monitor resolution in RA, 4:3 aspect ratio, in PUAE I change the crop option to automatic, but this option works quite poorly. Depending on the game, the image of the game menu, intro, or in a new location is stretched "in our eyes". For example, Fantastic Dizzy - after leaving the first location (Dizzy House) the image stretches and adjusts to the size of the window.
Sometimes setting the crop to Large/Larger/Medium and then adjusting the window size (vertical position) helps. But it's not perfect here either. Often, for example, the menu is cut too high when the main location is set perfectly.
If necessary, I can record a short video on yt to illustrate the problem.
I will add that I have filter settings automatic scaling set on Winuae and everything is nicely stretched there before the image is loaded (menu, intro, main location, etc.), on PUAE everything stretches with a delay that is very noticeable.

**Comment by sonninnos** [comment]
The delay is by design so that animations etc don't change the geometry on every frame, since it degrades performance.

**Comment by elessar38** [comment]
This is what it looks like in Fantastic Dizzy when you enter or leave a location (sorry it shakes, but I record with my phone).
It's similar in every 2-3 games I've tested. Stretching most often occurs when changing images (menu, main location, etc.).
It would be nice if you could improve it and add an option that stretched the image better and faster. It looks very bad to me. Only the default crop = off setting helps, but then the game window is very small.

https://www.youtube.com/watch?v=1GtHw9Tg_ZU

**Comment by sonninnos** [comment]
It is not stretching here, so there is nothing to improve core-wise, other than not doing the cropping. 

You are supposed to be using "Core provided" aspect in the frontend when using core cropping. If not, then of course the scaling changes when the image height changes. Otherwise only "zooming" happens, which isn't looking too great either with that game, but it is what it is, since the game changes the top and bottom drawed lines, and those are used for cropping.

**Comment by elessar38** [comment]
I see it's a waste of my time here because you're closing a ticket without any support or solution.
Core provided I tested as well as many other screen settings. This causes an even worse effect than the one I recorded, because it stretches the image not only vertically but also horizontally.
Automatic crop works just wrong, the image shouldn't stretch and "jump" like that when you look at it.
It remains to go back to Winuae where you can easily set the screen and how the image should stretch.

**Comment by sonninnos** [comment]
But I did offer support and solution. The core does not crop wrong, and the image does not stretch.

That old version did not have "much more" options, but far less, clearly. And the centering options still exist, but with a different name which fits better with the core options and not UAE options.

The problem in this case is not the cropping itself, but "Vertical Position", which apparently adjusts the position too aggressively based on the screen size. Set it to a certain locked value for these kinds of games that change the height constantly.

Maybe I can try to have a look at it if it could behave better as "Automatic", but continue being a dick and I won't.

**Comment by elessar38** [comment]
"But I did offer support and solution. The core does not crop wrong, and the image does not stretch."
-but what kind of support is this when I have the same problem with most games? I have two choices:
-have strangely stretched image
- have no stretched image at all :)

"The problem in this case is not the cropping itself, but "Vertical Position", which apparently adjusts the position too aggressively based on the screen size. Set it to a certain locked value for these kinds of games that change the height constantly"
-I wrote about it myself that this option also does not help very well. Example: sometimes it allows you to adjust the game menu accordingly, but the bottom of the location will be cut off at the bottom or top.

"Maybe I can try to have a look at it if it could behave better as "Automatic", but continue being a dick and I won't."
- I'm sorry buddy, but I'm the one who struggles to fix/improve something and you close my ticket in 10 seconds and you don't even want to look at it and you're surprised that someone might get mad.
I would be happy to describe the problem in more detail, give the exact retro arch settings, or even record more videos (because the pictures do not show it). But you decided that I'm stupid and the core works about 10 seconds we close, I won't bother.

**Comment by sonninnos** [comment]
Ok, I managed to sort out the issue, and will do some more testing to make sure nothing else broke.

Pretty sneaky and dicky way of deleting and editing messages, but whatever..

**Comment by elessar38** [comment]
"Ok, I managed to sort out the issue, and will do some more testing to make sure nothing else broke."

When I asked for help, you closed the issue, you wrote that there is no problem, puae works as it should, and I have something wrong in RA.
Have you noticed the problem now? I'll use your favorite words "that's a very sneaky and dicky way".

"Pretty sneaky and dicky way of deleting and editing messages, but whatever.."

I deleted the last entry because you don't understand anything and you act like a 10-year-old. It's a waste of time to report any problem here.
You don't even want to take a look at the reported problem, you just close everything as it goes. It's not helping, it's making the person reporting a fool.
The post was edited when there was no reply yet. That's what editing a post is for, that I can change something. Not my fault you replied to the edited post.

**Comment by sonninnos** [comment]
You explained the issue so vaguely that it was too easy to misunderstand what you meant. And kept moving the goalposts. The core does absolutely no stretching. 

I already figured out and said what the problem actually is (crop value change triggered unnecessary image centering), and fixed it, so please fuck off with that attitude.

**Comment by elessar38** [comment]
I explained the problem very clearly and recorded a special video. You're just a smelly lazy guy and you can't fix anything.
Good luck offending others and closing issues automatically.

**Comment by sonninnos** [comment]
Projection level 100.

**Comment by elessar38** [comment]
> You explained the issue so vaguely that it was too easy to misunderstand what you meant. And kept moving the goalposts. The core does absolutely no stretching.
> 
> I already figured out and said what the problem actually is (crop value change triggered unnecessary image centering), and fixed it, so please fuck off with that attitude.

Bravo, genius, you broke crop mode = automatic even more than it was in Fanastic Dizzy (AGA).
This only works fine when manually toggling crop = off ---> crop automatic. After restarting the game, for example, the language selection menu is stretched so much that half of it is not visible.
What's more, you "improved" only one game when the same thing happens with tens/hundreds. No one is testing and using this alpha core?

**Comment by sonninnos** [comment]
Good job editing your message history and looking like the innocent victim, you miserable rat.
