### ISSUE TITLE
Savestate creation attempt fails

### ISSUE THREAD

**Issue by Widge-5** [libretro/libretro-uae#581]
I am using a Raspberry Pi4 with RetropIe, using Retroarch 1.10.0.
I installed lr-puae from source today and it appears to be v 4.9.1 (b2c4acb)

Creating a savestate appears to be broken, but I don't know if it's just me.

Whenever I try to create a savestate the creation fails, the toast notifcation in the lower left corner comes up a message to say "Saving state 0%" but then never changes. it remains on screen for the remainder of the session never moving off 0%.  When I then attempt to exit the core with hotkey+start to return to EmulationStation, the whole thing freezes up and the only way I can get out is to pkill the core from an SSH command line.  Exiting the core is usually fine, except for after I attempt to create a savestate.

**Comment by sonninnos** [comment]
I can't reproduce. Post logs. How about other cores?

**Comment by Widge-5** [comment]
Thanks, looking at the logs was great advice.  It made me realise that the rom location where the savestate was to be saved was owned by `root` instead of `pi`, so there were insufficient privileges for the save.  Changed ownership of the folder and the problem is solved!!   Case closed.
