### ISSUE TITLE
Enhancement request: Right Control as Right Amiga

### ISSUE THREAD

**Issue by rhester72** [libretro/libretro-uae#583]
Owing to many keyboards not having a Menu/Right-Windows key (including all Raspberry Pi keyboards and many laptops), I'd like to suggest making Right Control an alternate Right Amiga key as well with the following justifications:

- The Amiga did not have a Right Control key ;)
- By default, the core defines Right Control as a hotkey for "Switch Joystick/Mouse", which will continue to function as expected even with the requested modification
- Keyboards without a Right Control key are unaffected, as this does *not* effect use or function of Left Control

On lr-puae2021 on RetroPie, I have experimentally modified line 446 of libretro/libretro-mapper.h from:

`    AK_CTRL,        /* 305 = RETROK_RCTRL */`

to

`    AK_RAMI,        /* 305 = RETROK_RCTRL */`

without issue, and finally Ctrl-Amiga-Amiga actually feels natural and doesn't require finger gymnastics.  =)

I am not certain as to whether a similar modification needs to be made for SDL or X11 support, but I don't think so, as those appear to be specific to the original underlying source that libretro builds atop.

I would like to ask that if accepted, this modification be made to both lr-puae and lr-puae2021 with the same justification.

I attempted to avoid source modification entirely by exploring various means of doing similar remapping at the RetroPie/Linux level but was unsuccessful.  This may be possible on other platforms, but allow for it at the source level seems to be innocuous and without  unexpected or ill effects elsewhere (again owing to the fact that it's primarily used as a hotkey anyway, and will continue to function as such unless undefined).

**Comment by sonninnos** [comment]
In case you missed it PageUp+Down also operate as Amiga-keys, so hitting that combo is possible with any keyboard.

There is no SDL or X11 input in this core, only libretro.

**Comment by rhester72** [comment]
@sonninnos I'm aware of PgUp/PgDown, which are only accessible as function-shifted keys on the Pi keyboard, hence the 'finger gymnastics' comment and the reason for the enhancement request =)

**Comment by sonninnos** [comment]
Ok, I'll change it since Ctrl isn't required that often anyway to justify having two of them.

**Comment by rhester72** [comment]
Thank you!
