### ISSUE TITLE
[Feature request] Emulate mouse by using device's touchpad

### ISSUE THREAD

**Issue by babosvabo** [libretro/libretro-uae#588]
I don't know if it is already supported, but if not it would be great that a amiga mouse can be controlled by emulating device's touchpad.

I have tried to set the touchpad up on android phone (retroarch 1.9.12) and WiiU (retroarch 1.14.0) and couldn't do it. On android i can move it via overlay analogue stick and on WiiU only via hardware anslogue stick (touchpad doesnt work in retroarch on WiiU at all?)

Just to add info: generally I don't know where is the pinpoint of the problem with using touchpad to control mouse movement in amiga: is the problem in the emulating device support/retroarch or the PUAE core?

**Comment by sonninnos** [comment]
It already does that by default on my phone.

**Comment by babosvabo** [comment]
> It already does that by default on my phone.

Which version of retroarch? By default you mean that you haven't changed any default options that retroarch had when you installed it?

To confirm that you should be able to turn that option off. Please try to turn it off and describe here how and where have you went to manage touchscreen options while emulating with PUAE

**Comment by sonninnos** [comment]
Latest, and every version I've tried so far.

It can't be turned off from the frontend, since mobile touch handles mouse pointer and desktop mouse handles touch pointer. As in touch can be emulated/simulated in desktops with mice, and mobile touch automatically translates to mouse pointer, so it just works.

But it can be disabled via PUAE by the core option "Physical Mouse" which disables all mouse pointer input, which also includes touch, since it is just mouse input.

Overlay does not matter as long as overlay does not overlap with the whole screen. Free unused space goes directly to mouse.

**Comment by babosvabo** [comment]
Have you tried to play games which require mouse and if yes, which game so I can try to compare our experience because for me touch does work in Retroarch menu but it doesn't in games.
For examle, I've tried in Dune 1 and when in game, touch works only to be able to touch overlay controls, but it doesnt work as mouse, so if I want to move ingame pointer, i have to touch overlay analogue button which then moves the ingame pointer.
So, can you move ingame pointer just by touching it (so basically you dont need overlay) or in which way you move ingame pointer by touch?

**Comment by babosvabo** [comment]
Yes, I'm taking about pushing the cursor around by touchpad...

I have freshly reinstalled Retroarch on my android phone and touchpad control doesn't work, only overlay analogue joystick that mimics mouse. 
Here's the video:
https://youtu.be/YHFUyd5NJvo

What I'm doing wrong? How to controll game pointer via touch even without using overlay

**Comment by rsn8887** [comment]
I am pretty sure I tested touch input when I was testing this core on Android.

It might help to update to a current Retroarch version. It looks like you are using the ancient version 1.9. The current version is 1.14. The galaxy store seems to have it.

**Comment by babosvabo** [comment]
It works! It was the old version of retroarch... can't figure why google plays store doesn't update its retroarch to final version...

Anyway, thank you very much for your help!

Also, is there any chance that you understand how touchpad works on WiiU? It would be great that the same control of mouse with touchpad could be implemented on WiiU but it seams that no one knows how to implement it. 
Here's the thread:
https://github.com/libretro/RetroArch/pull/11191
