### ISSUE TITLE
cannon fodder cd32 fmv video is not working as it should

### ISSUE THREAD

**Issue by gabberhead** [libretro/libretro-uae#590]
minutes ago, i load the game, to play a little bit. before the game starts, normaly the fmv video is playing from beginning to the end. but now, the video is starting, but after few seconds the sound is gone, and again after few seconds the video hangs. i dont know since when the problem exists, but i know 1or 2 weeks ago, the video was playing till the end. i have the latest core installed and retroarch 1.9.15. is there a possible bug in the puae libretro core?

**Comment by sonninnos** [comment]
Sigh, of course caused by the hack I recently added that fixed a few other games from launching..
