### ISSUE TITLE
WHDLoad Magazine Black Screen

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#592]
Hi, i've been reliving the glory days by reading a few of these Diskmags. This one may be the only one that I couldn't get to run -

StolenData08_v1.0_Anarchy.lha

It seems to run fine on WinUAE. On PUAE it gets to the part where it gives a choice of picking 'The Magazine Issue 8' or 'The Charts'. Choosing the main Magazine gives a black screen and nothing else.  I only noticed this part in the log -

```
[libretro INFO] FS: mounted virtual unit DH0 (C:\Users\Anyone\Desktop\StolenData08_v1.0_Anarchy.lha)
[libretro INFO] FS: WHDLoad (flags=00000002,E=0,ED=1,EF=0,native='C:\Games\RetroArch\saves\\Desktop\WHDLoad') starting..
[libretro INFO] FS: WHDSaves (flags=00000002,E=0,ED=1,EF=0,native='C:\Games\RetroArch\saves\\Desktop\WHDSaves') starting..
[libretro INFO] FS: StolenData08_v1.0_Anarchy (flags=00000004,E=0,ED=0,EF=1,native='C:\Users\Anyone\Desktop\StolenData08_v1.0_Anarchy.lha') starting..
[libretro INFO] Illegal instruction: 4e7a at 00239C64 -> 00239C74
[libretro INFO] B-Trap F200 at 00239C8E -> 00239CB2
[libretro INFO] B-Trap F017 at 00239CDA -> 00239D0C
```

[StolenData08_v1.0_Anarchy.zip](https://github.com/libretro/libretro-uae/files/11043108/StolenData08_v1.0_Anarchy.zip)
(Zipped so I could upload it here)

**Comment by zzedmore** [comment]
Oh, that would explain it then ! 😄 I'm using WinUAE 4.10.1. I'll close this.

**Comment by sonninnos** [comment]
I'm waiting for 4.10.2 to be non-beta before starting the update process.
