### ISSUE TITLE
PUAE on Retroarch on Nintedo 3DS 

### ISSUE THREAD

**Issue by solarmon** [libretro/libretro-uae#594]
Hi,

I'm not sure whether this is the right place to ask, but I have installed Retroarch on the Nintendo 3DS - as per:

https://docs.libretro.com/guides/install-3ds2ds/

However, the "**Commodore - Amiga (PAUE)**" core seems to be missing from the list of cores that are available to download.

Is there a reason why this core is not available on Retroarch for Nintendo 3DS? Is there a way to add the core?

Thank you.

**Comment by solarmon** [comment]
Hi,

Thanks for the response. I just wanted an alternative and comparison to uae3DS (https://github.com/badda71/uae3DS) which only supports the A500.

I wanted to test on a Nintendo 3DS XL, if that makes any difference in terms of performance.

**Comment by sonninnos** [comment]
Looks like your best bet is trying to build it yourself to see what happens.

**Comment by solarmon** [comment]
Unfortunately, I wouldn't have a clue on where to start with that! Would you have any pointers that will help me in the right direction?

**Comment by sonninnos** [comment]
Sorry, zero idea.

**Comment by solarmon** [comment]
OK, no problem, thank you for taking the time to respond.
