### ISSUE TITLE
Custom Tooltypes maybe broken

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#595]
Hi, I tried setting a custom tooltype (in the MkCustom Cancel/Set/Remove window). I tried CUSTOM1=2 in the game NARC but it didn't seem to do anything. Also tried CUSTOM1=1 for infinite energy but also didn't work.

I checked in WinUAE and it works fine.

**Comment by sonninnos** [comment]
It hasn't been touched in ages and it works fine here. For example I have `custom1=1` in Settlers and it skips the intro. Also tried that game and I got infinite energy by using the script.

Also the Readme says the other cheat is CUSTOM2=1, not CUSTOM1=2.

**Comment by zzedmore** [comment]
That was a typo on my part. Still couldn't get the NARC ones to work. Settlers already has a splash screen option to skip the intro. I'll see if I can find a different game with tooltypes that aren't on the WHDLoad splashscreen.

**Comment by sonninnos** [comment]
In any case if the script can see and edit the custom option, I don't understand how it could not also be offered to the slave as designed.

**Comment by zzedmore** [comment]
That's weird, it doesn't seem to be working for me. I tried 'Pipe Mania' (CUSTOM1=1 to skip intro) didn't work. Also tried ECS 'Zool' (CUSTOM1=1 for CD32 pad). Oh well, not a big deal.

**Comment by sonninnos** [comment]
Like I said, if the script sees the custom file and edits it, nothing makes sense.

**Comment by zzedmore** [comment]
I deleted all the folders in the save directory and the WHDLoad.prefs in the system directory for good measure (no saves worth saving at the moment). It now seems to work but only after I close content and restart the game.

So when you have the splash screen enabled (that has WHDLoad options before the game starts), if you enable some of them, are they supposed to be still on/save if you restart the game ?

**Comment by zzedmore** [comment]
OK, sorry for wasting your time. One last thing. How do you enter more that one thing in the mkCustom box ? For instance -

Custom1=1
Custom2=1

Or can you only have one ?

**Comment by sonninnos** [comment]
Simply use space. `custom1=1 custom2=1`
