### ISSUE TITLE
[Android] Holding Shift twice in Virtual Keyboard crashes the core

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#596]
As in the title. I did this by accident. I held the Left Shift key down for a few seconds in the Virtual Keyboard (to lock it) to type some Capital letters (using joypad). I held Shift again to release it and the core crashes. 

I realise now that you only have to _press_ the Shift key to release it.

**Comment by sonninnos** [comment]
Nothing happens on Windows except it simply holds it down again.

Also no need to even do that since RetroPad Y toggles CapsLock.
