### ISSUE TITLE
XTreme Racing (AGA whdload) crash

### ISSUE THREAD

**Issue by hatetepe** [libretro/libretro-uae#598]
Hi.
I have this error when starting Xtreme Racing:
![Bez tytułu](https://user-images.githubusercontent.com/130509159/231288421-8f1dc9aa-1804-4edf-8955-0d921d59e90d.png)

I tested the latest version of the game (XTremeRacing_v1.1_AGA_0164.lha) on default puae core settings.
I also checked the extended version from data disk and this one works fine.
OS win 11

**Comment by sonninnos** [comment]
Smells like a WHDLoad problem, and not this core problem. Unless it works with WinUAE with the exact same version and exact same settings.

**Comment by hatetepe** [comment]
Thanks for the answer.
I just tested on a configuration with
winuae 4.9.1, whdload 18.6 and amiga 1200 settings.
It seems to be working ok.

![Bez tytułu](https://user-images.githubusercontent.com/130509159/231414030-d35e24d5-52f8-4b0c-b559-5925968a3161.png)

![Bez tyw222tułu](https://user-images.githubusercontent.com/130509159/231414049-787d239d-3550-483d-ae09-5e1a13067b6e.png)

**Comment by sonninnos** [comment]
Uhh, the both Xtreme Racing versions work fine here with default settings..

**Comment by hatetepe** [comment]
I removed puae core and all saved settings (whdload prefs etc.), reinstalled and everything works fine.
Thanks for checking.
