### ISSUE TITLE
cart roms always resets to "none" in the config

### ISSUE THREAD

**Issue by gabberhead** [libretro/libretro-uae#599]
cart roms after enable for a game, and after closing the game and then starting again, are always set to "none" in the config.
testet with:
Action Replay Mk III v3.17.rom on a500 games
CD32 Full Motion Video Cartridge ROM v3.1 r40.030.rom on cannon fodder cd32

**Comment by sonninnos** [comment]
Sigh, of course this change causes it: https://github.com/libretro/libretro-uae/pull/593
