### ISSUE TITLE
Make Retroplay set of WHDLoads in lha's work

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-uae#60]
Whdloads in this set are done to be extracted on a 'real amiga' and won't be correctly extracted on normal unzip utilities. The retroplay set is all lhas. Strangely there are some hdf images, but I *think* they're also compressed with lha, which makes sense if they are supposed to be extracted on a amiga. I'm not certain because there is no real way to verify the lha archive directory structure in linux nowadays.

tl;dr:

1. create a native lha extractor and parse the whdload.slave file inside the lha passed to the core, to figure out the final machine type and other exotic configs it needs (extra memory, cd32 controller added support, things like that). If it's already a hdf inside, extract that as the 'new file' and parse the slave from it, possibly by extracting it from inside emulation with another amiga program.
2. create a sufficiently big hdf image (somehow) to contain the new game if the final file doesn't exist in retroarch/saves yet goto 3, if it does, goto 4.
3. create a native mounter for the hdf file and extractor of lha that preserves amiga file properties and weird amiga names (this might be difficult because the amiga has different forbidden characters and file attributes, so the normal filesystem interfaces - mount, normal cp etc, might not serve) OR create a auto running amiga program that does the extraction into the hdf from inside emulation and run it.
4. finally mount whichever hdf resulted with the properties from step 1.

Then later a prs could be added for libretro-database so the scanner recognizes these lha's as the games they are, and kept uptodate periodically. As the entry points, they'd be read only and the 'real cached game' would be on retroarch/saves or similar, like certain other cores handle writable memory in 'ROMs' from early consoles.

Retroplay warns that it's difficult to make a extractor that works on the native side (because people apparently constantly break the installs trying with some 'standard' unix lha extractor):

https://forums.libretro.com/t/uae-core-for-retroarch/15599/46

So basically two paths; either create a specialized extractor that preserves the extra metadata and names from the amiga created lha (probably by not touching the 'modern' filesystems and using a library that can write hdf files and attributes directly from in-memory bytes) to output a valid amiga filesystem, or create amiga autoboot programs that extract lhas, create hdfs and somehow return to outside emulation the data in the whdload.slave for config, which is basically the same but with less filesystem 'fun' and more amiga 'fun'.

This library: https://github.com/lclevy/ADFlib (literally found by search 'amiga filesystem' on github)

which purports to be a "A free, portable and open implementation of the Amiga filesystem" and specifically says it supports 'UAE hardfiles' (hdf) may help for both.

**Comment by wronghands** [comment]
I'm not sure if anyone is dedicated to this project right now. Nobody responds to any of the issues posted here at all to talk about the fixes, let alone features. Realistically, I wouldn't expect anyone to. Other than that, it would be exciting to see this feature. Great post.

**Comment by lclevy** [comment]
Hi,
Sorry, i do not have time anymore to support this project, but just fork it and improve it. 
I can help understand the code if needed

**Comment by i30817** [comment]
This would also need a way to parse the whdload.Slave inside the lhas and a way to extract the lha files and their properties/attributes. Searching around github some more:

https://github.com/osvaldolove/whdload-slave <-parser apparently
https://github.com/fragglet/lhasa <- lha extractor

**Comment by lclevy** [comment]
To uncompress lha:
http://lclevy.free.fr/amiga/formats.html

**Comment by wronghands** [comment]
Does anyone know if @DamsRoxxx is still interested in this project? Or are you the same person @lclevy?

**Comment by lclevy** [comment]
No i'm not @DamsRoxxx

**Comment by i30817** [comment]
Ok, i checked the WDHLoad slave format, anddd... it's not surprising no emulator actually tries to use them as datafiles to what the amiga game needs, in spite of of them being right there.

Apparently Slave files are literally executables and assembled, so chasing down flags is trouble some. And i don't know if they have the actually interesting ones like 'OSC or AGA', 'Extra memory support' and 'CD32 controller support'.

https://github.com/midwan/amiberry/wiki/WHDLoad-Booter-(WHDBooter)-F.A.Q. has some info

**Comment by i30817** [comment]
So a alternative idea: document a way to download the openretro sqlite database (for whdloads) and use that for 'autoconfig' since perfect is the enemy of the good here because that database is often outdated because new WHDLoads come out often, use this strategy to autoconfig:

1. if the database has a main filename lha exact match use that entry properties.
2. if it does not, use a fuzzy name search that removes the version (of your local file) and find the latest version in the Retroplay version naming scheme in the database and use that).

The rest (extract and creation of hdfs) stays the same.

**Comment by DamsRoxxx** [comment]
Hi, I don't have a lot of time to support this project at the moment.

And, in my opinion, bug should fixed before doing enhancement like this one (I have a pull request pending since several months).

Basically the core work, if it was better known maybe more developpers would come to fix and enhance things ;-)
