### ISSUE TITLE
Pinball Fantasies AGA scores not saving

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#604]
Only a minor thing. Played 'PinballFantasies_v3.2_AGA_0047' and got a high score. When I exited the table I got an error -

DOS-Error 205
(object not found)
on writing "nvram".

And no high score saved. This is on Windows.

EDIT- Same thing happened on 'PinballFantasies_v3.2_CD32'.

Does it have something to do with the small '32' character in the filename (in the 'WHDSaves' directory) ?
I tried on Android and I have a file on there that can't be deleted 'PinballFantasiesCD󲁇A'.

**Comment by sonninnos** [comment]
Not minor by my standards. Yes indeed, those versions use the same save path and file, and yes non-ascii superscripts are the reason. I managed to fix it by forcing the local filename chars to `3` and `2` respectively.

Thanks for catching, I've only been scoring with the actual CD32 of this game, so it went under the radar.
