### ISSUE TITLE
[Linux] Physical mouse and invisible walls in cannon fodder.

### ISSUE THREAD

**Issue by ZzackKbin** [libretro/libretro-uae#608]
Hello 
In Cannon Fodder  when screen is scrolling mouse cursor stop on invisible walls when use physical mouse but when I use Sony pad DS4 everything is ok.  
https://youtu.be/M_CwEI6_2iE
Linux Arch/Steamdeck

Edit
I made test and:
- in windows and the same hardware no problems with physical mouse
- in linux arch normal desktop and only run retroarch physical mouse stop on invisble walls when screen is scrolling

**Comment by sonninnos** [comment]
Not the fault of the core, but the frontend platform driver. Nothing to be done here, so I will close this.

**Comment by ZzackKbin** [comment]
I dont use frontend just run only retraorch in desktop.

**Comment by sonninnos** [comment]
RetroArch is the frontend in this case.
