### ISSUE TITLE
How to edit the core UI?

### ISSUE THREAD

**Issue by ariaththesage** [libretro/libretro-uae#609]
Hi, i would like to edit core menu, for example for changing some options position (like disc control) and for adding the possibility of creating M3U files to the core, without having to create them apart.

What source files must be edited for adding new options, sections, etc...?

**Comment by sonninnos** [comment]
Not by editing this core alone, since disc control stuff is done by the frontend. This core also already creates m3u files when suitable (when launching archives), so what do you mean exactly? What options are missing?

**Comment by ariaththesage** [comment]
Oh, well, i'll try to explain better...

I'm using m3u files to load all my games (floppy and hdf ones). Then i set the appropiate core settings (model, RAM, etc.) bye game.

Actually i create these files by hand (i'm working on a python script to generate them), and i wondered if was possible to create and manage these files in the core...

You say that the core already generales m3u files?
I suppose you mean Zip files, right?

**Comment by sonninnos** [comment]
Indeed why bother since you can simply launch all kinds of content directly. Yes, archives mean zip and 7z.

**Comment by ariaththesage** [comment]
Yes, i know there is solutions like WHDLoad to instant loading all games, but i was searching a A500-style experience...

About the Zips, i have a donde a quick test and yes, when i load a zipped game i have all floppies like when i use a M3U playlist, but there is one thing i don't understand:

> ZIP support
> 
> ZIPs are extracted to a temporary directory in saves, bypassing the default frontend extraction. The temporary directory is emptied but not removed on exit. ZIP is not repacked, which means saves and highscores are lost.
> 
> This allows:
> 
>     Automatic M3U playlist generation of all files
>     The use of zipped images in M3Us
>     If no compatible images are found, the ZIP will be treated as a directory

When i use a M3U, i can add savegame floppies to it, even label them.

Loading a zipped game i only can choose between the game floppies and, as the readme says, the zip contents are lost upon exiting the game, so, even if i include a savegame flopply, it would be useless because the zip don't get updated.

This is why i started using M3U files. I also use them to load installed games because i'm used to use two HDFs: one for booting Workbench and another one for the game.

**Comment by sonninnos** [comment]
Touching and altering the original zip files would be horrible practice. The core does have a save disk creating feature for games that require a separate save disk, and the ability to redirect all disk writes to separate disks under `saves`.

**Comment by ariaththesage** [comment]
Yes, i have seen that using the M3U. The save floppies are generated in the folder (i think FS-UAE does the same thing), but using zips... 
How can i select them if i only see the game floppies available?

I thought then that zip format was more convenient for games that doesn't save progress, or use codes...

**Comment by sonninnos** [comment]
The created save disk is appended to the floppy list.

**Comment by ariaththesage** [comment]
![IMG_20230506_202233](https://user-images.githubusercontent.com/66223151/236640746-7acdad28-4528-45f5-9304-3b653f7639b8.jpg)
![IMG_20230506_202214](https://user-images.githubusercontent.com/66223151/236640749-37dd81a7-e357-402d-97a8-8416c09b1fec.jpg)

🤷🏼‍♂️

**Comment by sonninnos** [comment]
Since there is no "Save Disk 0" at the end, it means you simply have not created the disk via the available methods: VKBD button `SVDS` (seen when CapsLock is down)  or pressing the Toggle Save Disk hotkey after binding it to a key.

**Comment by ariaththesage** [comment]
![imagen](https://user-images.githubusercontent.com/66223151/236644381-eedd8182-a20f-43c5-8031-438c5f48a78f.png)
![imagen](https://user-images.githubusercontent.com/66223151/236644548-ce7e3400-9881-4243-9fec-06758b4d23ac.png)

Oh my...
Well, that was the problem. The key was unbinded, and i didn't know of its existence...

So, there is certainly no need of using M3Us for floppy games... Thanks a lot for the tip.

Now my doubt is with HDFs. I wonder if i zip the two partitions, belonging to Workbench and the game itself, will be mounted as DH0 and DH1 and the modified files recorded in saves folder, although using M3Us i can easily share the Workbench partition among all games...

**Comment by i30817** [comment]
I have a tool that automatically makes m3u's in linux if you're interested:  https://gist.github.com/i30817/ba37fbb2b3c6e34ff926ad833f465055

**Comment by sonninnos** [comment]
I'll close this since the request is out of the core's reach regardless.
