### ISSUE TITLE
Elvira \ Elvira II screen problem

### ISSUE THREAD

**Issue by KamiLordus** [libretro/libretro-uae#616]
Hi @sonninnos I have a small request. Could you improve the aspect ratio for games:
Elvira
Elvira II
The main screen is quite low for both games.

![Bez tytułu](https://github.com/libretro/libretro-uae/assets/123302593/9e0104bd-fb60-4a8d-bc21-45e29b9e5ef5)

I use settings:
![33](https://github.com/libretro/libretro-uae/assets/123302593/5879d155-45d8-4247-899c-8dc511ea1218)

and 4:3 aspect ratio

**Comment by sonninnos** [comment]
Not going to be simple, since the games report that they are drawing that black area. Same happens with WinUAE, since the values come from the same place. So I'd have to change the logic completely to determine what area is empty. I do have done that already in VICE by comparing the colors to border color per line, since that emulator does not have any internal automatic mechanism for getting the values for the used screen area.

So for now manual cropping is the only option.

**Comment by KamiLordus** [comment]
No problem. Manual cropping works fine.
Regarding the playlist counter, it seems to me that it has always been there in the xmb menu. Most of my settings are standard.
I use RA 1.15 stable, Win 11 and DX 11 driver for fronted.
One more question, are there any chances for version 5.0 of Puae?

**Comment by KamiLordus** [comment]
> Here the playlist index is only in playlist pages..
> 

Hmm, I just installed 1.15 nightly and it's the same:
Maybe it's a bug.

> And yes of course 5.0 is coming when I get to it.
> 

Very good news

**Comment by sonninnos** [comment]
Could you try nightly for the playlist index thing? Looking at the XMB code it should be impossible for it to be elsewhere than playlists and explore list, and that is how it behaves here. Is it showing elsewhere too?

And hmm, BFI is only available for certain drivers, and the code says it is hidden only in "mobile" and Steam deck even if the video driver supports it.

**Comment by sonninnos** [comment]
The index vanishes immediately here after entering the playlist item and beyond.

I guess d3d11/12 just miss the flag then if it works. Weird that the flag affects only the menu option and not the actual function.

**Comment by KamiLordus** [comment]
Okay I found it. This playlist option disables this index:
![Bez tytułu](https://github.com/libretro/libretro-uae/assets/123302593/6590da71-ac51-4ede-a413-37ee167245f3)

Regarding BFI, will it be possible to fix this problem?
It's not a big deal, but it would be nice to have this option available on dx11 without editing the files.

**Comment by sonninnos** [comment]
Well since it works with those drivers, it is very easy and trivial to add the missing flag to them.

I have no idea how I could replicate that index thing though, since I've tried all I can think of..

**Comment by KamiLordus** [comment]
I've been testing BFI with dx11 for three weeks now and haven't noticed any issues.
The exception here is the Flycast (Dremcast) core, I use it with the vulcan driver to enable shaders. When BFI is also on, the screen flickers horribly. Dx12 unfortunately I did not check.
Thanks for the advice, I'll report it.

**Comment by sonninnos** [comment]
BTW the Elvira crop issue does not happen with floppy disk version (tried IPF). And it only works in A500 mode, and other models fail in various ways. Elvira 2 also requires disabling external floppy drives, but the empty area seems like a WHDLoad thing then, which makes it even more weird..

**Comment by KamiLordus** [comment]
I also checked the ipf game and you are absolutely right.
It's the same on winuae. So it must be some problem with the whdload version.

**Comment by KamiLordus** [comment]
Thanks a lot for the tips. For both games I added the NTSC tooltip and the screen centering is correct.
