### ISSUE TITLE
No CLI (Command Line) way to load games directly?

### ISSUE THREAD

**Issue by darksgan** [libretro/libretro-uae#619]
I'm posting this question here because I can't find any clue on the internet, and I don't know where exactly to ask it here.

Ok, I'm making some scripts / batch files to load games directly calling them from another software... but I don't want to change disks in the Retroarch menu... so I'm trying to use some .lha files.

Here is the problem, I can load games directly in full screen with no problems from command line.

This is a part of the script, for example:

.\RetroArch-Win64\retroarch.exe -f -L RetroArch-Win64\cores\puae_libretro.dll Games\Amiga500\Game-ROM.7z

Being "Game-Rom", for example, Rod-Land_Amiga500.7z (a one floppy disk game, changing disks is not needed)

It works perfectly, but, if I try the same using a ".lha" file, it doesn't:

.\RetroArch-Win64\retroarch.exe -f -L RetroArch-Win64\cores\puae_libretro.dll Games\AmigaWHDL\PushOver_v1.23_1267.lha 

It doesn't load the game because Retroarch try to load it as a floppy disk

![imagen_2023-08-10_001344355](https://github.com/libretro/libretro-uae/assets/36720431/2d29b6d9-e4d7-4791-87c5-43946b9777a1)

If I load it through the Retroarch menus, it loads perfectly:

![imagen_2023-08-10_001557207](https://github.com/libretro/libretro-uae/assets/36720431/6657b7aa-b78a-4a22-80c5-e6ce1e94f57d)
![imagen_2023-08-10_001657299](https://github.com/libretro/libretro-uae/assets/36720431/404116c1-1ad1-4e09-98d2-cb4a62c37e0a)

Is there any way to tell Retroarch that the file to load is not a floopy but an HDD using command line?

Or is it some kind of issue?

Thanks and regards.

**Comment by sonninnos** [comment]
Beats me, I've always been loading LHAs via CLI just like that. I'd also rather use absolute paths for content.

The core gets the exact same path from CLI as it does when launching via the menu. Without logs hard to say more what could be the problem.

**Comment by darksgan** [comment]
Oh... my... god................... I typed the relative path wrong... I'm blind.

What I typed:
"Games\Amiga500\Game-ROM.7z"

What I should have taped:
".\Games\Amiga500\Game-ROM.7z"

![imagen_2023-08-10_094952449](https://github.com/libretro/libretro-uae/assets/36720431/75d54801-1f08-4642-933b-4e7b474f4d35)

You know ".\" means "the current directory/path"... f*ck :_(


Finally it is:

.\RetroArch-Win64\retroarch.exe -f -L RetroArch-Win64\cores\%LibretroCore%.dll .\Juegos\%Plataforma%\%Juego-ROM%.%File-Extension%

![imagen_2023-08-10_100343052](https://github.com/libretro/libretro-uae/assets/36720431/77310a99-d5e0-47ad-b752-5a4d95c8c15e)



Obviously, I set the variables "Plataforma", "Juego-ROM", "Juego-Extension" previsouly in another place for making a generic "launch command" for all the games/files and platforms/systems which are gonna be emulated.

Thanks a lot, if you wouldn't have said anything about absolute path, I wouldn't have seen that I had typed the relative path wrong.

**Comment by sonninnos** [comment]
Ok, great, let's close this then.

**Comment by darksgan** [comment]
> Ok, great, let's close this then.

Fine... thanks a lot :)
