### ISSUE TITLE
24-bit memory adressing

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#620]
Hi,

Xenon 2 fails to load with anything else than a 68000. This game is known for using the most significant byte of 32-bit adresses for its own purposes, hence failing on 32-bit architectures. 
I thought it would run on the A1200 setting, since the A1200 features a 68EC020 restricted to 24-bit adresses space. But it fails too. Which makes me think that the A1200 presets defaults to 32-bit rather than 24-bit, and no override is provided, like in WinUAE. Am I right?
This is not a big issue, if a program was badly coded, you can just use a 68000 preset, but there might be some cases were such a program would be optimised of the A1200, and hence be forced to use 24-bit adressing. 
Could this be a user setting?

Also, we can't override the Agnus and Denise types (OCS or ECS). Not really an issue as you can always select the A500 for OCS and A500+/A600 for ECS, but still.
As a side note, the A2000 1mb Chip presets has the hybrid OCS/ECS config (ECS Agnus but OCS Denise). Not very useful, I can't see a case where you would want ECS Agnus but downgrade to OCS Denise, but still, this configuration was sold in both A500 and A2000, so it worth mentioning. The doc simply says ECS for this A2000 config, which is partially incorrect.

Best regards

**Comment by sonninnos** [comment]
I don't quite understand. WHDLoad version with A1200 and CDTV version with CD32 work just fine here with default settings.

**Comment by Vweber73** [comment]
I'm not using whdload, I am using the adf.
The Whdload slave is full of fixes, including one to remove the custom usage of the most significant byte in 32-bit adresses, hence it works on anything.
I just used the floppy disk to test adressing in PUAE.
Other amiga emulators with the 24-bit setting checked succeed in loading the game with 68020+ processor, hence my question about this setting - must be hardcoded to 32-bit?
Again, nothing drastic, alternatives exist, just for the sake of completeness...

**Comment by Vweber73** [comment]
I can't find this file in saves... Maybe because I am running Retroarch on Android?
Anyway, the strange thing is that the very same adf runs in vamigaweb with no problem when I change the processor to 68020 (from a standard 512k/512k config with kick 1.3). If I do the same thing in PUAE, loading fails, whereas it works with 68000. So it has to do with the 68020 emulation...

**Comment by sonninnos** [comment]
Nothing to do with platform. It does not exist because it does not exist by default, because why would it: <https://github.com/libretro/libretro-uae#using-configuration-files>

I get the same behavior with WinUAE 5.0, so maybe it is just an accuracy thing, or perhaps some other setting affects it.

**Comment by Vweber73** [comment]
Ok, many thanks!
I have been trying to change the cpu accuracy from cycle-exact to more compatible to normal, with no success...

**Comment by sonninnos** [comment]
I guess we can close this since exposing the option wouldn't even help with this.

**Comment by Vweber73** [comment]
I understand this option is only relevant for the 68020. 68000 and 68010 are 24 bit by nature. 68030+ are 32 bit by nature. Maybe only add a 68EC020 processor type, to distinguish clearly between the 2? Actually the 1200 preset is 68EC020, and you can override it with 68020, so maybe this is not even needed?
