### ISSUE TITLE
Crash upon downgrading memory

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#621]
If I downgrade the memory settings with the provided overrides (like taking a A500+ or A2000 with 1Mb Chip Ram, and then forcing 512K chip / 512K slow), and launch sysinfo from the Adf, it works fine. Values reported by Sysinfo are correct. However, I if close the contents, I have a systematic crash of Retroarch. As if it was still trying to save memory that does not exist (the upper 512k chip ram?) and getting a null pointer...

**Comment by Vweber73** [comment]
You may wonder why on earth I would want to downgrade a machine with an ECS Agnus to 512k chip... Well because such amigas existed! Starting mi-1989 Commodore released the ECS Agnus (1Mb version), and, not wanting to maintain 2 chips while 1 would do, without telling anybody, started to ship A500s and A2000s with the new Agnus. But the 2 machines were treated differently: the A2000 got 1Mb Chip EAM straight from factory, the A500's trapdoor expansion was still recognised as slow RAM, not Chip RAM. Only a hack, implying cutting traced in the motherboard, would give the full 1Mb Chip RAM. Commodore probably did not to get into compatibility problems on the gaming side (some games hardcoded the slow RAM addresses). So you could have a machine with an ECS Agnus, yet the standard 512/512 memory configuration.
In PUAE such an hybrid machine does not exist in the presets. The 2 A500 configs are purely OCS. The only way to get this configuration in PUAE is to downgrade the A2000 1Mb Chip preset (ECS Agnus, OCS Denise) to 512/512. It works fine... Until you close the contents: crash!

You will tell me that this config is completely useless: if you need full OCS compatibility, just use an A500 preset. If you need ECS, just use a A500+ or A600 preset. I can't think of a game or demo or application that would benefit from an hybrid machine... Ok, but, since this is about retrofun, I should be able to use that config if I like it! :)

**Comment by sonninnos** [comment]
Yep, for some reason it actually never allocates the bogomem, but it tries to free it, thus it crashes..

**Comment by sonninnos** [comment]
Ok, I was able to fix it by updating the memory freeing function to use the `ABFLAG_NOALLOC` flag which is used by a different memory freeing function, which is used when `NATMEM_OFFSET` is defined, and this core does not define it, thus it is using a legacy method which is left behind.

I tried a game that uses bogomem, and it seems to work regardless of that "no allocation". Indeed the flag is set in a block with a comment:
```
/* emulate 0.5M+0.5M with 1M Agnus chip ram aliasing */
```

**Comment by Vweber73** [comment]
First, I would like to say a big thank you for your fast and efficient support - quite rare, and really appreciated!
I can't test right now because the latest commit is not available for download yet. Will do as soon as it is.
Something bugs me though - you seem to say that if you downgrade the chip ram to 512k with an ECS agnus, the code then stil allocates 512k bogo mem somewhere, regardless of your override. But what if the override is not 512k bogo mem but more (1mb, 1.5 or 1.8mb)? Will it crash? Again pretty useless, no game uses more than 512k of bogo mem and you are better off with FAST RAM, but still :)

**Comment by Vweber73** [comment]
I finally got the latest commit.

It seems that everything works as it should :) Bogo mem different sizes are recognised, even if 1.8MB is reported as 1.5Mb by Sysinfo... But the 1.5Mb is reported as 1.3Mb, so I guess thus is more linked to Sysinfo computations.

One thing, sometimes I get "Clock not found" in Sysinfo. I think it happens when I accelerate Retroarch with the double right arrows icon. Maybe something to do with timers?

**Comment by sonninnos** [comment]
Well sure, no wonder any calculations based on real time clock will be a bit off while fast-forwarding, since it does not forward the time. As in UAE takes the time from host clock.
