### ISSUE TITLE
Can't get WDHLoad to work at all

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#630]
Hi,
Forgive me is this is trivial, I am new to WHDLoad and would like to give a try. So far no luck.
I tried to load both .lha files from whdload.de for Heart of China and Willy Beamish.
I used the A1200 preset (3.1, 2Mb/8bMb). 
I enabled Whdload in the Core. 
If I choose "files", I get a readme file, then a window with empty "options" parameters, and a choose box with "set", "cancel", "ignore". Whatever I do, I got a recoverable alert, then back to the readme file. 
I  choose "hdf", then in the Workbench window I get repeated error messages about the 600 then 1200 kickstart having a bad signature. 
I am using Cloanto Amiga Forever Kickstart files, legally purchased on the store, could this be the problem ? I have no problem whatsoever with kickstart files on everything non-WHDLoad... 

Thanks in advance and cheers,

**Comment by sonninnos** [comment]
You can't run stuff from whdload.de because those LHAs don't have game data in them. Look at the file size. They are just installers. Only pre-installed Retroplay LHAs can be launched, as stated in the documents.

**Comment by Vweber73** [comment]
Oops, sorry!
Many thanks

**Comment by Vweber73** [comment]
Sorry again, but I tried a proper retroplay lha this time, but I got this. Seems the proper kickstart is not renamed properly? 
![Screenshot_20230831_173451_RetroArch (AArch64)](https://github.com/libretro/libretro-uae/assets/92450215/24c4855e-158e-4f4c-9a6a-895c692c172c)

**Comment by Vweber73** [comment]
Here is my files in the system folder... They all work well under PUE... 
![Screenshot_20230831_180455_My Files](https://github.com/libretro/libretro-uae/assets/92450215/1939a902-9ecf-45ae-a435-adbc2fff78d2)

**Comment by sonninnos** [comment]
And the core is the latest version with this fix included? https://github.com/libretro/libretro-uae/issues/625

I really can't guess anything more without a log of the WHDLoad first run after deleting `saves/WHDLoad`.

**Comment by Vweber73** [comment]
Wow, this issue looks really like mine!
I always download the latest version of the core. I check several times a day. I'm definitely up to date.
/
I delete both whdload files in Saves, started again, here is the log file.
Complaining about size of the KS files...

[Core]: Réinitialisation.
WHDLoad QuitKey triggered..
Model: 'A1200'
Kickstart: 'kick40068.A1200'
WHDLoad not installing Kickstart 'amiga-os-120.rom' due to incorrect size, 524299 != 262144
WHDLoad not installing Kickstart 'amiga-os-130.rom' due to incorrect size, 524299 != 262144
HD (1) inserted in drive DH0: '/storage/emulated/0/Download/AdventuresOfWillyBeamish_v1.2_1814.lha'
SNDRATE 313.0*227.0*49.920410=3546895.000000
PAL mode V=49.9204Hz H=15625.0879Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
KS ver = 40 (0x28)
KS ver = 40 (0x28)
RTAREA located at 00F00000
TRAP_ENTRY = 00f021de
Known ROM 'KS ROM v3.1 (A1200)' loaded
CPU cycleunit: 128 (0.250)
1872 CPU functions
CPU cycleunit: 128 (0.250)
Building CPU, 45912 opcodes (2 -2 1)
CPU=68020, FPU=0, MMU=0, JIT=0. ~cycle-exact 24-bit
Reset at 00F8F7EC. Chipset mask = 00000007
PAL mode V=50.0804Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
Autoconfig board list:
Card 01: 
'<no name>' no autoconfig 00da0000 - 00daffff.
Card 02: 
'<no name>' no autoconfig 00600000 - 00a7ffff.
Card 03: 
'UAE Boot ROM' no autoconfig 00f00000 - 00f0ffff.
Card 04: 
'Z2 Fast RAM'
  e0.51.00.00.07.db.00.00.00.01.00.00.00.00.00.00
  MID 2011 (07db) PID 81 (51) SER 00000001
  Z2 0x00200000 0x00200000 8192K RAM 0
Card 05: 
'UAE FS ROM'
  d1.52.40.00.07.db.00.00.00.03.20.00.00.00.00.00
  MID 2011 (07db) PID 82 (52) SER 00000003
  Z2 0x00e90000 0x00e90000   64K ROM 0
END
Card 0: skipping autoconfig (not autoconfig)
Card 2: skipping autoconfig (not autoconfig)
CPU cycleunit: 128 (0.250)
hardreset, memory cleared
SNDRATE 312.0*227.0*50.080410=3546895.000000
[Environ]: SET_SYSTEM_AV_INFO: 720x288, Aspect: 1.250, FPS: 50.08, Sample rate: 44100.00 Hz.
[Audio]: Set audio input rate to: 44100.00 Hz.
[Video]: Timings deviate too much. Will not adjust. (Target = 60.00 Hz, Game = 50.08 Hz)
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
[Display]: Found display driver: "gl".
[Input]: Game Focus => OFF
SNDRATE 312.0*227.0*50.080410=3546895.000000
PAL mode V=50.0804Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
SERIAL: period=372, baud=9600, hsyncs=14, bits=8, PC=f8018a
B-Trap F201 at 00F80CA0 -> 00F80CC0
Card 4: Z2 0x00200000 8192K RAM Fast memory
Card 5: Z2 0x00e90000   64K ROM Filesystem autoconfig
00000000    2048K/1 =    2048K ID* C32 Chip memory
00200000    8192K/1 =    8192K ID* F32 Fast memory
00A00000     512K/0 =     512K --  F32 <none>
00A80000    1024K/2 =     512K ID* F32 Kickstart ROM (1483A091)
=KS ROM v3.1 (A1200) rev 40.68 (512k)
00B80000     448K/0 =     448K --  F32 <none>
00BF0000      64K/0 =      64K --  CIA CIA
00C00000    1536K/0 =    1536K --  F32 <none>
00D80000     256K/0 =     256K --  C16 Gayle (low)
00DC0000      64K/0 =      64K --  C16 Battery backed up clock (MSM6242B)
00DD0000      64K/0 =      64K --  C16 Gayle (low)
00DE0000      64K/0 =      64K --  C16 Gayle (high)
00DF0000      64K/0 =      64K --  C16 Custom chipset
00E00000     512K/1 =     512K ID* F32 Kickstart ROM (1483A091)
=KS ROM v3.1 (A1200) rev 40.68 (512k)
00E80000      64K/0 =      64K --  F32 Autoconfig Z2
00E90000      64K/1 =      64K --* F32 Filesystem autoconfig
00EA0000     384K/0 =     384K --  F32 <none>
00F00000      64K/1 =      64K --* F32 UAE Boot ROM
00F10000     448K/0 =     448K --  F32 <none>
00F80000     512K/1 =     512K ID* F32 Kickstart ROM (1483A091)
=KS ROM v3.1 (A1200) rev 40.68 (512k)
filesystem: diagentry 00200098 configdev 00000c48
SNDRATE 313.0*227.0*49.920410=3546895.000000
PAL mode V=49.9204Hz H=15625.0879Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
[Environ]: SET_SYSTEM_AV_INFO: 720x288, Aspect: 1.250, FPS: 49.92, Sample rate: 44100.00 Hz.
[Audio]: Set audio input rate to: 44100.00 Hz.
[Video]: Timings deviate too much. Will not adjust. (Target = 60.00 Hz, Game = 49.92 Hz)
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
[Display]: Found display driver: "gl".
[Input]: Game Focus => OFF
Mounting uaehf.device:0 0 (0):
FS: mounted virtual unit WHDLoad (/storage/emulated/0/RetroArch/saves/WHDLoad/)
Mounting uaehf.device:0 1 (0):
FS: mounted virtual unit WHDSaves (/storage/emulated/0/RetroArch/saves/WHDSaves/)
Mounting uaehf.device:0 2 (0):
FS: mounted virtual unit DH0 (/storage/emulated/0/Download/AdventuresOfWillyBeamish_v1.2_1814.lha)
FS: WHDLoad (flags=00000002,E=0,ED=1,EF=0,native='/storage/emulated/0/RetroArch/saves/WHDLoad/') starting..
FS: WHDSaves (flags=00000002,E=0,ED=1,EF=0,native='/storage/emulated/0/RetroArch/saves/WHDSaves/') starting..
FS: AdventuresOfWillyBeamish_v1.2_ (flags=00000004,E=0,ED=0,EF=1,native='/storage/emulated/0/Download/AdventuresOfWillyBeamish_v1.2_1814.lha') starting..
Illegal instruction: 4e7a at 00234340 -> 00234350
B-Trap F200 at 0023436A -> 0023438E
B-Trap F017 at 002343B8 -> 002343EA

**Comment by sonninnos** [comment]
Well how on the earth can those old 256KB Kickstarts be 512KB there..?

**Comment by Vweber73** [comment]
No idea. These are my cloanto files...
I downloaded several others. Every time, now, I get this.... 
![Screenshot_20230831_195329_RetroArch (AArch64)](https://github.com/libretro/libretro-uae/assets/92450215/b7f057e1-ee75-46fb-a7e0-a4fee69d3712)

**Comment by Vweber73** [comment]
If this helps, here is what is said about cloanto roms on Android:

Amiga "Kickstart ROMs" for Android

On Android systems, [Amiga Forever Essentials for Android](https://play.google.com/store/apps/details?id=com.cloanto.amigaforever.essentials) installs official Amiga ROMs and some additional disk images in a way that is autodetected by Amiga emulator apps for Android (e.g. UAE4Droid, AnUAE4All, UAE4All2, Omega 500). These are the 512 KB system ROM files (256 KB ROMs won't work on many mobile emulators) to run Amiga OS versions 1.2, 1.3, 2.04, 3.0 and 3.1 in emulated computers like the Amiga 500 and Amiga 1200. So if you are searching for "Amiga 500 Kickstart 1.3" or "kick.rom" or "kick13.rom", or for a ROM with MD5 hash 192d6d950d0ed3df8040b788502831c2, [Amiga Forever Essentials for Android](https://play.google.com/store/apps/details?id=com.cloanto.amigaforever.essentials) is the answer that is both legal and easy to use, as it requires no manual configuration work.

**Comment by sonninnos** [comment]
Makes absolutely no sense. How many Cloanto ROM versions are there? The user in the above issue provided crcs and file sizes for all, and they only had the 11 byte encryption extra.

I would expect that kind of error message precisely with entirely wrong files, which will eventually result if I'd skip the filesize check. And how can they possibly work with UAE either without warning messages. As in are you 100% sure that those double sized versions work when you boot normal A500 with either 1.2 or 1.3, and the log says 
```[libretro INFO] Known ROM 'KS ROM v1.3 (A500,A1000,A2000)' loaded```

**Comment by Vweber73** [comment]
Sorry, maybe I, wasn't clear, when I said I tried other roms, i didn't mean I tried other Cloanto roms, just that I tried the standard 256k roms that I could find on the net. With those, I get no more size errors, but validity errors as my screenshot shows. I don't know what do you if no kickstart is OK!

I agree with you that platform is irrelevant to kickstart. Very strange!

As requested, I put again the Cloanto 512K 1.3 rom as Amiga-os-130.rom and relaunched the core. It works fine, and here is the end of the log file:

00000000    2048K/4 =     512K ID* F32 Kickstart ROM (543DA404)
00200000    8704K/0 =    8704K --  F32 <none>
00A80000    1024K/2 =     512K ID* F32 Kickstart ROM (543DA404)
00B80000     448K/0 =     448K --  F32 <none>
00BF0000      64K/0 =      64K --  CIA CIA
00C00000    1536K/0 =    1536K --  F32 <none>
00D80000     256K/0 =     256K --  C16 Gayle (low)
00DC0000      64K/0 =      64K --  C16 Battery backed up clock (MSM6242B)
00DD0000      64K/0 =      64K --  C16 Gayle (low)
00DE0000      64K/0 =      64K --  C16 Gayle (high)
00DF0000      64K/0 =      64K --  C16 Custom chipset
00E00000     512K/1 =     512K ID* F32 Kickstart ROM (543DA404)
00E80000      64K/0 =      64K --  F32 Z2Fast
00E90000     960K/0 =     960K --  F32 <none>
00F80000     512K/1 =     512K ID* F32 Kickstart ROM (543DA404)
[Config]: Nouvelle configuration enregistrée vers "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg".
Your Amiga program just did something terribly stupid 4F694E5E PC=4F694E5E
4F694E3E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E4E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E5E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E6E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E7E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E3E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E4E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E5E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E6E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

4F694E7E 
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2
 25F2

00000000    2048K/4 =     512K ID* F32 Kickstart ROM (543DA404)
00200000    8704K/0 =    8704K --  F32 <none>
00A80000    1024K/2 =     512K ID* F32 Kickstart ROM (543DA404)
00B80000     448K/0 =     448K --  F32 <none>
00BF0000      64K/0 =      64K --  CIA CIA
00C00000    1536K/0 =    1536K --  F32 <none>
00D80000     256K/0 =     256K --  C16 Gayle (low)
00DC0000      64K/0 =      64K --  C16 Battery backed up clock (MSM6242B)
00DD0000      64K/0 =      64K --  C16 Gayle (low)
00DE0000      64K/0 =      64K --  C16 Gayle (high)
00DF0000      64K/0 =      64K --  C16 Custom chipset
00E00000     512K/1 =     512K ID* F32 Kickstart ROM (543DA404)
00E80000      64K/0 =      64K --  F32 Z2Fast
00E90000     960K/0 =     960K --  F32 <none>
00F80000     512K/1 =     512K ID* F32 Kickstart ROM (543DA404)
[Core]: Content ran for a total of: 00 hours, 00 minutes, 07 seconds.
[Runtime]: Saving runtime log file: "/storage/emulated/0/RetroArch/playlists/logs/PUAE/PUAE.lrtl".
[Core]: Unloading game..
[Core]: Unloading core..
[Core]: Unloading core symbols..
[Core]: Saved core options file to "/storage/emulated/0/RetroArch/config/PUAE/PUAE.opt".
Threaded video stats: Frames pushed: 324, Frames dropped: 0.

**Comment by sonninnos** [comment]
And that KS ROM checksum matches with the documents? Why did you cut out the part where it says something about recognizing it?

That log seems like the opposite of "It works fine", since it says "Your Amiga program just did something terribly stupid". Those errors are not at all normal.

Do you have the `rom.key` there with the files or not?

**Comment by sonninnos** [comment]
Well that is weird. UAE code says the size for that is 256KB:
```
	{ _T("KS ROM v1.3 (A3000)(SK)"), 1, 3, 34, 5, _T("A3000\0"), 262144, 32, 0, 0, ROMTYPE_KICK, 0, 0, NULL,
	0xe0f37258, 0xC39BD909,0x4D4E5F4E,0x28C1411F,0x30869504,0x06062E87 },
```

No wonder WHDLoad won't like that kind of version either. In any case best to just get the matching Kickstarts, delete the poisoned `WHDLoad` dir from `saves`, and enjoy.

**Comment by Vweber73** [comment]
Thanks! Working know. Your key advice was "delete the poisoned Whdload Dir from saves". I didn't do it at first, so even 256KB roms wouldn't work, which drove me nuts!

I just read that the 512Kb roms are just 2 identical 256Kb roms glued together. It is the way than transom works. So you could support them I think by just something like if (rom13.size == 512) just_take_half_of_it() ; 🙂

**Comment by sonninnos** [comment]
Yep, the copier won't overwrite files, so first one stays, wrong or not.

So weird that there is anything to copy together with that ROM, so what is the other half other than zero? I can understand combining CD32 KS+extended to one file, but this is alien.

**Comment by Vweber73** [comment]
Yes, this is nuts, but this what it is. Thanks again!

One little thing, now that I can play 10-disk games without getting crazy. These games have menus, triggered by the ESC key. So I press Select to activate the VKBD, then press ESC, the menu appears, I want to see it well so I press Select again to remove the VKBD, it does that, but it also triggers an Amiga mouse left click, so that the menu entry the mouse pointer is on is selected, against my will. Most irritating. Any way to change this behaviour?

**Comment by sonninnos** [comment]
Right, I haven't really used it on touchscreen so wasn't aware of it. So basically because touchscreen acts both as a pointer and a mouse, the frontend sends both down at the same. At least the frontend no longer sends RetroPad events and touch events at the same time, which a while ago prevented closing VKBD completely if the overlay Select happened to overlap with the core image.

I can try simulating that behavior somehow and ignore mouse clicks during VKBD toggle.

**Comment by Vweber73** [comment]
That would be great, many thanks!

**Comment by sonninnos** [comment]
How old RetroArch are you running again? This reminded me of a thing that is fixed already: https://github.com/libretro/RetroArch/pull/15346

**Comment by Vweber73** [comment]
Current stable, 1.15.0

**Comment by sonninnos** [comment]
Update to nightly then.

**Comment by Vweber73** [comment]
I did so. This gave me another instance (1.16.0) of Retroarch, which I had to reconfigure.
Unfortunately It doesn't change the behaviour: in rise of the dragon, select/esc/select still triggers the mouse event...?

**Comment by Vweber73** [comment]
I tested more and realize that there is a behaviour difference between version 15 and 16.
Both versions trigger a left click mouse event upon pressing Select, when in the main menu of rise of the dragon, opened with ESC.
But during the very first menu (skip introduction / play introduction), v15 triggers the click and V16 does not!!
Very strange...

**Comment by Vweber73** [comment]
More differences (Rise of the dragon lha, still) :

In both versions, If the VKBD is on before the Rise of the dragon menu appears, the mouse pointer is on Play, pressing Select again triggers the click.

However, if you trigger the menu, move the mouse pointer away (using the mouse keys from the VKBD), then press select, the menu is still there. If now you set the mouse pointer to play (without clicking), on V15 pressing Select triggers the click, but not on V16, which behaves correctly in this situation, but not on the initial situation! Stranger and stranger...

**Comment by Vweber73** [comment]
Hi, 
Any idea why this inconsistant behaviour? Anything that could be fixed are core level rather than Retroarch level?
Many thanks in advance, best regards

**Comment by sonninnos** [comment]
I can't reproduce the issue with my phone. By having the statusbar open there is no mouse clicks going on when toggling the VKBD by pressing Select on the input overlay. Only when hitting some empty area.

**Comment by Vweber73** [comment]
Have you try rise of the dragon?
I'm talking about this menu. Select does not trigger an event if the menu is already there prior to VKBD, but it the VKBD was on screen before the menu was called (by ESC) then the event is triggered... 
![Screenshot_20230903_192829_RetroArch](https://github.com/libretro/libretro-uae/assets/92450215/b76c4107-304e-4be0-a202-a0594f3ec92e)

**Comment by sonninnos** [comment]
I can't see how any game could get any input if the input is not shown in the statusbar, so I did not test the game.

**Comment by sonninnos** [comment]
Hehey, I think I got it. The ghost click happens only if any VKBD key is pressed after toggling.

**Comment by Vweber73** [comment]
I don't get it. The game is getting virtual mouse input, the empy space on the screen acts as a touch mouse. When I touch it the J2 changes to m2 with arrows... When I press on the screen it acts as a left click... This also happens in V15 whenever I press select, and in V16 only if VKBD was there before the menu.

**Comment by Vweber73** [comment]
> Hehey, I think I got it. The ghost click happens only if any VKBD key is pressed after toggling.

Yes that's it! :)

**Comment by sonninnos** [comment]
It definitely is the Android quick tap press, since it won't happen if the press is longer. Don't even have to touch the VKBD, but just any empty area while the pointer input (VKBD) is active.

**Comment by Vweber73** [comment]
Well, I am looking at the Select behaviour, and it's weird. In V15 the behaviour is wrong (send a left mouse click) but at least systematic. In V16 the bahaviour is right under some circonstances, and wrong under other circonstances. I don't understand the logic...

**Comment by sonninnos** [comment]
Obviously the logic isn't intentional. The quick tap prevention gets nulled somehow when pointer input is received between overlay presses. So if you just use the overlay buttons for pressing Esc instead of pressing Esc, there is no ghost click afterwards.

**Comment by Vweber73** [comment]
Yes, confirmed, if you press ESC using the B button instead of ESC on the VKBD, the problem does not occur!
Is it a Retroarch general issue or a PUAE Core specific issue? I also reported it on the general issue you pointed me to.

Many thanks and best regards

**Comment by sonninnos** [comment]
As already stated, the fault is clearly in the Android input driver. The core gets and obeys the input it receives. Since I can't test Android changes easily, I can try adding some circumvention to ignore inputs more aggressively when toggling VKBD. It already waits for joystick input to be released, but ignores mouse.

**Comment by Vweber73** [comment]
Many thanks, great, that would be much appreciated. I think then it would also work on V15, as I prefer to stick with stable versions...
Cheers

**Comment by Vweber73** [comment]
I tried the new core, thanks a lot for trying! But I see no behaviour change, neither in V15 nor in V16...

**Comment by Vweber73** [comment]
Ouch the last core is a catastrophy! On V15 it takes ages to launch, then there is no on screen elements, no select key,... although the game itself seems to work. On V16 Retroarch completely freezes on launch!!

**Comment by Vweber73** [comment]
I tried the latest core. 
Still the same as before... With one small difference. The left click is still registered after Select, but with one second delay. I initially thought the problem was solved... Until the click finally occurred.

**Comment by sonninnos** [comment]
This is getting pretty unbelieveable and insane.. Every time I increase the amount of frames the core skips ALL input after VKBD is toggled off, the ghost mouse click just keeps on getting triggered later, which makes absolutely no sense.

When the quick tap triggers normally, there is a clear delay sure, but not that long.

**Comment by Vweber73** [comment]
Ouch ! So what to do ?
Cheers

**Comment by Vweber73** [comment]
Wow, we are making progress!
With the latest core:
-V16 works fully as expected,
-V15 works well except when using fast forward mode. Pressing the FF key registers a left click, and pressing Select during FF mode registers too.
We are getting there!

**Comment by sonninnos** [comment]
Ok, I believe we are there then, since old versions are bygones..

**Comment by Vweber73** [comment]
Hi,
Just upgraded to V16, which is now official.
Everything works great, save for a very minor issue: when you press the up and down triangles to hide/show the Retroarch control, this triggers a mouse left button event. No big deal as you don't do that very often, but still strange...
Cheers

**Comment by sonninnos** [comment]
But there hasn't been any related changes between the pre-1.16.0 and current..

**Comment by Vweber73** [comment]
Yes, I don't think there was a change, it's just that I took the opportunity of 1.16.0 release to test more touroughly, and I hadn't tried toggling the overlay before.
I'm using rgpad overlay - is it special?

**Comment by sonninnos** [comment]
That overlay behaves just the same, which is that if you don't hit the toggle hitbox precisely, it will be a mouse click like when hitting an empty area. So the only solution for that issue is making the overlay hitbox bigger so that missing it isn't as easy.

**Comment by Vweber73** [comment]
Thanks a lot ! I tried very carefully and was surprised as the button is the same size than the FF button, which never triggers a click. 
Notheless, if you hit very brierfly and precisely with the nail, it indeeds does not trigger the click...

Best regards
