### ISSUE TITLE
Quick question regarding Lakka

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#632]
Hi, just a quick question. Do you happen to know when Lakka does an update ? I'm using the latest dev build for Raspberry Pi 4 64bit which is `Lakka-RPi4.aarch64-devbuild-v5.x-20230813-afdaa47.img.gz`. Only thing is that your PUAE core is v4.9.1 b2c4acb which is from 1st February !!!??!!! Retro in itself !

**Comment by sonninnos** [comment]
I have no idea other than it has been in the works for a while. I assumed you could build your own cores.

**Comment by zzedmore** [comment]
OK thanks. That's it's biggest downfall, you can't download cores. You only get what it comes with. So everyone that's using it has cores from Jan/Feb. Pretty lame. I'll steer clear of Lakka from now on !
