### ISSUE TITLE
Preload for cd32

### ISSUE THREAD

**Issue by PaddeePadoo** [libretro/libretro-uae#633]
Hello there,

when loading games like Beneath a steel sky using WhdLoad, every scene of dialogue is broken by a black flashing screen as the game loads the next track.  

This is described as a problem in WinUAE back in 06 here https://forum.amiga.org/index.php?topic=23446.0

the solution seems to be preloading the CD into ram, but I don’t see an option for that when configuring the core from UI.

Is there a way to set lr-puae up such that it preloads the CD?

Thanks

**Comment by sonninnos** [comment]
Simply enable enough Z3.

**Comment by PaddeePadoo** [comment]
Worked, thanks!
