### ISSUE TITLE
Problem with 2 controllers + moonlight

### ISSUE THREAD

**Issue by daguile** [libretro/libretro-uae#634]
Hello,
I'm having an issue with my controllers in a specific situation. I'm using my home PC as a host for my retrogaming platform and sometimes I'd like to play it on my TV screen with Shield using Moonlight. It works very well for 1 player game but when I connect two controllers, one gamepad controls the two players (and the other controller only acts on one). I tried all the different parameter combinations in Moonlight but without success. It seems that the problem is linked with puae as I don't reproduce the issue with the other RA cores and the same setup. Also, if I connect the same controllers directly to the PC, everything goes well. 
Here's my setup:
RA version: 1.11.1
libretro-puae: 5.0.0 7bdd798
1st controller: Xbox One Bluetooth
2nd controller: 8bitdo NES30
Both controllers are seen as Xbox360 controllers by RA if I go through Moonlight

If you have some ideas but no time for this, I can also have a look if you point me to the right direction

Thanks!
Damien

**Comment by sonninnos** [comment]
I don't have any issues with the joystick ports. Just remember to use the d-pad, since analog sticks by default control the mouse on the other joystick port, since that is how Amiga works. Some games like FIFA go apeshit if mouse is moved even a little, since the game expects gamepads to be connected.

**Comment by daguile** [comment]
Thanks for the tips! With these, I managed to understand what was going on. In fact, it is the D-pad of my second controller that is acting both as Joystick 2 and Mouse. If I change the Core option "Analog stick mouse" from "Both analogs" to "Right analog" the behaviour is back to normal! Thanks again! You made my day!

**Comment by sonninnos** [comment]
Ok great, let's close this then, since the core can't do anything about it if the frontend is so old that it sends duplicate events when "analog to digital" is enabled, like it did some time ago.
