### ISSUE TITLE
T-zer0 with hdf file and cue/bin or chd not working anymore

### ISSUE THREAD

**Issue by gabberhead** [libretro/libretro-uae#639]
i dont know since when this problem exist, but today i tried to play the game, but it dont work anymore. the intro with the trainer options is working, the game also starts till the menu, but when i try ti start the game from the mainmenu, the game crashes to workbench and you see the traumaconsole, this, where it stands movies available, soundtrack available etc. i tried changing some options in retroarch, but nothing helps. this is what i have:

T-zer0.uae
with this in it:
hardfile2=rw,DH0:D:\--=[Spiele]=--\RetroArch\Commodore - Amiga\WHDLoad\T-zer0.hdf,32,1,2,512,0,,uae0
cdimage0=D:\--=[Spiele]=--\RetroArch\Commodore - Amiga\WHDLoad\T-zer0.chd
scsi=true

T-zer0.hdf

and

T-zer0.chd

few months before, it works without problems. and i also didnt changed anything since then.

**Comment by sonninnos** [comment]
The core hasn't had any possible related changes for months, and those paths look like they could have never worked, because the root path `D:` does not even have a backslash.

But as usual, log is the best bet for hinting what might be wrong.

**Comment by gabberhead** [comment]
this i have in the uae file. i dont know why there is no backslash. i did copy/paste linke here :)

hardfile2=rw,DH0:D:\--=[Spiele]=--\RetroArch\Commodore - Amiga\WHDLoad\T-zer0.hdf,32,1,2,512,0,,uae0
cdimage0=D:\--=[Spiele]=--\RetroArch\Commodore - Amiga\WHDLoad\T-zer0.chd
scsi=true

i will try with d:\ only

how can i provide a log?

**Comment by gabberhead** [comment]
but with d:\ only it also not working

the last time i played the game was ca 6 months ago

**Comment by gabberhead** [comment]
here is the debug log
[retroarch__2023_11_04__23_04_20.log](https://github.com/libretro/libretro-uae/files/13257823/retroarch__2023_11_04__23_04_20.log)

**Comment by sonninnos** [comment]
Well does it work with WinUAE 5.0.0 with the same config? Smells like that is the change that could make a difference.

Maybe try with a different setup than A4000 and 68040.

**Comment by gabberhead** [comment]
tried it with a1200 setup and all on automatic. same problem. the last time it did work it was indeed 4.9 if i remember correct.

**Comment by gabberhead** [comment]
sorry. it was my mistake :) somehow escape was bound to fire. thats why the game didnt start after the menu. the game closed because of escape ^^
but there is anyway something wrong in the puae option. because, if i set fpu model to cpu internal in retroarch and when i start t-zer0, math-co processor is listed as none. when i set to 68882, it is listed as internal. when i set it to 68881, it is listed also as internal. if to none, it is listed as none. if to automatic, it is listed as internal. i am not sure, but i think, before it was alsways listed right. when 68882 it was 68882. when 68881 it was 68881. when internal, it was internal. automatic, i think, it was also internal. is this perhaps a bug?

**Comment by sonninnos** [comment]
What else is in the uae conf you use? It appears the order matters when defining `fpu_model=`, as in it has to be after `cpu_model=` or FPU resets to 0 as in none.

For example using the default A1200 preset and setting FPU core option to 68882 it shows as expected:
```
libretro [NFO] CPU=68020, FPU=68882 (host 64b), MMU=0, JIT=0. ~cycle-exact 24-bit
```

But there does seem to be an issue with the "CPU internal" FPU value resulting in 0 instead of the correct one depending on the CPU with 68040 and above..

**Comment by gabberhead** [comment]
in the uae conf file i only have those 3 lines. nothing else.

**Comment by sonninnos** [comment]
Okeydoke, a tiny logic problem sorted regarding the resulting FPU value, which should eliminate impossible and wrong combos.

**Comment by sonninnos** [comment]
So can this be closed then?

**Comment by gabberhead** [comment]
sorry. yes. it works now. thanx :)
