### ISSUE TITLE
Automatic crop delay option problem 

### ISSUE THREAD

**Issue by KamiLordus** [libretro/libretro-uae#640]
Hi
I noticed a new option added in puae video settings - "automatic crop delay". However, by switching this option from off to on, there is no difference in the speed at which the screen geometry changes. For example, the game Ruff 'n Tumble, the first screen (the main character on a black background), or the very beginning of the first level. You can clearly see how slowly the screen geometry changes.

RA 1.16
Puae core latest
tested video driver dx11, gl core, vulcan.

**Comment by sonninnos** [comment]
Try with Bubba N Stix to see that the option does in fact do something. There must be some centering differences which delays the cropping in Ruff n Tumble then, and the screen also twitches horizontally a bit at that moment when cropping is disabled.

**Comment by KamiLordus** [comment]
I tried with Bubba N Stix and it's the same situation.
One of the first pictures (purple tree and yellow mountains), or the next loading text. These screens use geometry change and it is clearly visible.
Games on the Puae core can be divided into three types (when it comes to geometry change).
1. The game does not use geometry change at all
2. The game uses geometry change, but each screen (horizontal and vertical) is the same size. This is where turning off automatic crop and setting the screen manually helps.
3. The game uses geometry change, but different parts of the game (e.g. intro, game map, gameplay etc.) have different sizes.
Manually setting the screen size does not make much sense. When the intro is the right size, the gampelay will have a cropped screen, etc.

**Comment by sonninnos** [comment]
Good news. Finally after some sweat & suffering I have managed to rewrite the cropping and centering stuff to use RA video callback offset instead of modifying UAE internal values, which allows doing resizing and centering immediately on the same frame. So far looking good with all the jumping problem cases, but more testing needs to be done.

**Comment by KamiLordus** [comment]
Great, good job as always.

**Comment by sonninnos** [comment]
Thanks. Let me know if there are setbacks.

**Comment by KamiLordus** [comment]
Hi @sonninnos
After two hours of testing (using dx11 video driver) I think there is huge progress when it comes to geometry change. Unfortunately, this is not enough to check everything. Games like Bubba n Stix, Trap n Treasure, Buggy Boy, Oscar now work perfectly.
However, I have a few comments after preliminary tests:
  - The automatic crop delay option must be disabled, otherwise geometry change has a noticeable delay (it's a bit confusing)
- currently I am using GL Core video driver (for shaders), unfortunately most of the changes made do not work here. For example, Buggy Boy works well, but Bubba n Stix, Trap n Treasure, Oscar do not.

Will it be possible to fix this on GL Core?
As soon as I have more time I will do more tests and let you know.

**Comment by sonninnos** [comment]
Like I said, this is a software core that does not use video drivers, so there is and can't be any difference between video drivers, and there isn't here..

And of course the delay has to be disabled in order to get immediate results, there is no other way.

**Comment by KamiLordus** [comment]
The problem was with shaders, specifically one of the parameters that probably changes the screen settings.
Thanks again, everything works fine now.

**Comment by KamiLordus** [comment]
I found one bug in Super Sturdust on Amiga CD32. When the "Star Wars"-style intro appears (galaxy and yellow subtitles), retroarch minimizes itself in the taskbar and then returns to full screen.
I think the same problem existed in the MAME core, which was described and fixed here:
https://github.com/libretro/mame/issues/399

**Comment by sonninnos** [comment]
Nah not a bug, it is just the video reinit that must happen since max screen size grows due to the super hires mode. The core used to have the maximum size set at startup to the absolute maximum, but too big by default slows down slower machines. Just don't use "Automatic" resolution and it won't happen.

Super Skidmarks is the only other one where it happens too. And in Workbench of course too. So extremely rare.

**Comment by KamiLordus** [comment]
Many thanks for the information. The option to change the resolution solves the problem.
