### ISSUE TITLE
[Features Request] Update Puae to the latest version 5.3.0

### ISSUE THREAD

**Issue by KamiLordus** [libretro/libretro-uae#643]
Hi @sonninnos 
The latest version of winuae 5.1.0 has been released. Can I ask you to move it to the liberto Retroarch platform?

**Comment by sonninnos** [comment]
Let's just wait for 5.2.0 at least.

**Comment by KamiLordus** [comment]
Sure, no problem. However, I still keep my fingers crossed for vice 3.8 :)
Regarding vice, I have a question:
The geometry change for the puae core that you recently made works great in my opinion. Could something similar be done for vice? Geometry change in vice core works quite similarly to puae (the delay is clearly visible). Of course, if it didn't require a lot of time and work.

**Comment by sonninnos** [comment]
Sure I'm planning to add it there too sooner or later.

**Comment by ulihox** [comment]
Hi @sonninnos.
WinUAE 5.2.0 was released yesterday. Thank you for your hard work on this core.

**Comment by mazxim** [comment]
> Let's just wait for 5.2.0 at least.

An updated, Winuae alligned version would be wonderful. Thank you very much by the way for your excellent work and valuable contribution.

**Comment by KamiLordus** [comment]
I think the final version of Winaue 5.3 should be released soon (currently it's beta 7). It's better to wait for the latest version. For now, I will update my request.

**Comment by sonninnos** [comment]
Progress teaser:
![image](https://github.com/user-attachments/assets/bb7093a1-6f52-473b-9ea3-98b6b09177f4)

Just got it to build and link, and seems fine so far, but still need to do actual testing, and with Linux too.

**Comment by KamiLordus** [comment]
Super news!

**Comment by sonninnos** [comment]
Ok, Linux build errors fixed, and overall looking good. The new branch is in my repo if anyone wants to build and help with testing.

**Comment by sonninnos** [comment]
Sorry for the delay. I got stuck trying to sort out the weird and rare savestate issues that have existed for a long time, since they still exist, even though they are gone from WinUAE, meaning that the libretro method is to blame. But it is not looking simple enough to keep trying to force it in this same update, so I'll try to get this over with soon.

**Comment by KamiLordus** [comment]
I would help with testing version 5.3, but my knowledge of building the core is nonexistent :)
