### ISSUE TITLE
CTRL+A+A with 68030 => Retroarch freeze

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#644]
Hi,

Trying the reset keyboard sequence usually works, but if the professor is changed to 68030, the app freezes (On Android). Strange...

Brgds

**Comment by sonninnos** [comment]
I couldn't replicate that particularity, but managed to find something. Reset works fine with AGA setup, but hangs with basic OCS/ECS.. No problem with old 2021 core.

**Comment by Vweber73** [comment]
Thanks. Strange, as I got the problem on A600 setup when upgrading the processor...but solving the AGA stuff might solve the whole thing!

**Comment by sonninnos** [comment]
What I meant is reset hangs with A600 regardless of changing the CPU.

**Comment by Vweber73** [comment]
I have just tried again, A600 preset (3.1/2mb/8mb).
If CPU is overriden to 68030, CTRL A A hangs.
If no override, reset works fine....?

**Comment by sonninnos** [comment]
Oh well, it always hangs here regardless of settings.. But I managed to prevent it with a band-aid, so I'll do some more testing to see that it causes no harm.

**Comment by Vweber73** [comment]
Thanks a lot!

**Comment by sonninnos** [comment]
Ok, please try the change when possible.

**Comment by Vweber73** [comment]
I just got the new version. Reset with 68030 now works fine, thanks!
