### ISSUE TITLE
Shift should be sticky on single press 

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#645]
I noticed that the Amiga (and also C64 and C128) VKBD requires long press on shift for it to be sticky, as any other key, as stated in the doc. This makes it long to type a shifted character... And then it remains sticky, like caps lock. Wouldn't it be more logical to make it sticky immediately but only until the next key press?

**Comment by sonninnos** [comment]
Nah, that would make everything too complicated, and quick access to Caps Lock already exists by default in RetroPad Y.

**Comment by Vweber73** [comment]
Ok, thanks... And what about haptic feedback on Android and ios? :)

**Comment by sonninnos** [comment]
I have no idea if core can trigger such things to the frontend, but I'll close this since I won't force sticky shifts.

**Comment by Vweber73** [comment]
Well, the amstrad caprice32 core does this very well, even if no visual feedback on the vkbd. Press shift once, then the next key press is the shifted character, press this key again, it is the unshifed character. On commodores the shift keys are useless, since you are better off pressing caps lock (but you have to press it once more after the shifted key...)
