### ISSUE TITLE
Retroarch Cheat made Retroarch crash directly.... simply unusable.

### ISSUE THREAD

**Issue by DjDiabolik** [libretro/libretro-uae#649]
I will try to search some Cheat for a WHD Games (in my case Lupo Alberto: The VideoGames) and apparently it's works.
You can found and apply/enable a cheat but when you load the same games next time apparently the memory address it's not the same and the previous cheat it's not works anymore.
When you try to start a new cheat simply retroarch crash..... lol

**Comment by sonninnos** [comment]
Amiga is a computer. Cheats are not guaranteed to "just work" until after the game is loaded.
