### ISSUE TITLE
When alternating to other software or loading state performance drop to less of 50 FPS

### ISSUE THREAD

**Issue by Augusto7743** [libretro/libretro-uae#650]
Thanks for reading my topic.
Randomly when alternating to another software window or loading an save state the performance drop to few less of 50 FPS or less of 75 % original performance.
Also happen crack in sound requiring to reload the core to fix it.

Have an nice day.

**Comment by sonninnos** [comment]
Nothing to do with this core.

**Comment by Augusto7743** [comment]
I have tested with others cores and that slowdown issue only happen in UAE core.
Perhaps because the OS is configured to use 60 HZ and retroarch use vsync in an core emulating an machine using 50 Hz ?

**Comment by sonninnos** [comment]
RA disables vsync automatically when rates mismatch that much, as also seen in the log. Try NTSC in PUAE to see what happens then. I can't replicate any of that with any settings.

**Comment by Augusto7743** [comment]
Thanks very much for your actions and informations in your reply.
I will try with others cores in PAL mode.
Have an nice next week.

**Comment by Augusto7743** [comment]
That issue happen in X68K core too.
I will try another sound or video configuration.
