### ISSUE TITLE
[Feature Request] Diffenent mouse speed for left/right analog-sticks

### ISSUE THREAD

**Issue by Megapit** [libretro/libretro-uae#654]
I'm new to libretro/RetroArch so forgive me if i bother you. Also i'm not an english speaking native and hope you understand what i want! :)

I recently purchasted an Retroid Pocket 4 Pro and would like to emulate my Amiga-childhood. 
Trying to play Zak McKracken feel's a little bit strange, since there is no real mouse. 
Using the Analog-Sticks is also complicated since the mouse speed is to fast or to slow in my opinion. 
I know there is the posibitity to config a "mouse fast/slower" button. But i think there are two analog-sticks doing the same on my device. 
So why do not config one analog stick fast, the other one slow and add both values to control the mouse.

I'm a developer by myself, but only working with VS2022 and not really familiar with creating pull requests. 
But i can read your well developed code and would suggest changes in two files. I will ad them as attachment. Since i'm also to stupid to genate patchfiles i will also add the originals ("*.Gid.c - Extension")

Maybee the developers can include my code to the build. 
Or as an option point me to cross-compile-beginner-guide, so i can compile it myself for my Retroid.

[Amiga.zip](https://github.com/libretro/libretro-uae/files/15062363/Amiga.zip)

**Comment by Megapit** [comment]
OK :(
Any good starting points to compile it myself , for my personal use?

**Comment by sonninnos** [comment]
Sorry, no idea how to compile for that device. But on second thought maybe the separate speeds aren't that bad after all, so I'll think about it.

**Comment by Megapit** [comment]
just for your information: Retroid Pocket 4 Pro is a Android 13 device.
I think using your makefile is worth looking at. I will setup myself an virtual linux machine and play a little bit with it and try to cross-compile myself.

**Comment by sonninnos** [comment]
Finally got around to try this idea out, and it almost worked as-is, so required just one tiny tweak for the sticks to behave properly at the same time. I ended up cleaning and fixing up a few related things while at it. Will do some more testing before pushing, but shouldn't take too long.

**Comment by Megapit** [comment]
Hi
Finally managed to make changes for testing by myself and compile it under a virtual debian environment.
For others finding this by google: [https://docs.libretro.com/development/retroarch/compilation/android/](RetroArch Compile guide)
I allready tested it on my device and it was still not perfect for click and point adventures (Zak McKracken). But it is better useable than both sticks on same speed.
What i did not mangage to programm was adding both sticks, so you have speeds combined each other.
 
I think it's best you implement the feature like you did it allready. Therefore i will not create a pull request.

**Comment by sonninnos** [comment]
The precision is much better now even with single stick, so let me know how it goes.
