### ISSUE TITLE
Save states seem to carry (some?) core options.

### ISSUE THREAD

**Issue by kokoko3k** [libretro/libretro-uae#659]
My core i5-4570 is'n not able to handle Jim Power in Cycle-exact mode at 50fps, so I've se it to "normal", where it have no problems.

However I've had an old savestate done with the "more compatible" setting.

Problem is that if i boot jim power with normal mode and then load that savestate, jim power struggles.

The menu does not reflect anything, it say it is running in normal mode, but reselecting normal again, makes jim power ok again.

I did the opposite (doing a savestate in normal mode and loading from a more compatible mode) and verified that it seems exactly like i wrote.

If fixing the issue is tricky, a quick workaround would be to apply the options when a savestate is loaded.

**Comment by sonninnos** [comment]
Yes, UAE does that by design, and long ago I've tried to force the current core options after state load, but it caused more problems.
