### ISSUE TITLE
Is it possible to boot from floppy with a hard drive attached?

### ISSUE THREAD

**Issue by vadosnaprimer** [libretro/libretro-uae#660]
A generic example of what I need is booting into a workbench floppy and using an HDF file (or at least a mounted folder). The readme says it should be possible to use .uae files for that but I couldn't figure out how.

I put this in the `saves/test.uae` and I don't see what it changes

```
cpu_model=68040
fpu_model=68040
mmu_model=68040
chipset=AGA
chipmem_size=4
bogomem_size=0
fastmem_size=8
floppy0=FloppyDisk.adf
floppy0type=0
hardfile2=rw,DH0:"HardDrive.hdf",32,1,2,512,0,,uae0
```

If I drop an ADF file onto retroarch, it loads only the floppy. And if I drop an HDF file, it only loads the hard drive. I tried putting them both into an m3u but it thinks the HDF file is just another floppy and doesn't load it either. So while they work fine on their own separately, I'd really love to be able to use them both at once.

**Comment by KamiLordus** [comment]
There are several possibilities how to do this:
1. In the Puae core option, you can enable "Global Boot HD" and select the HDF file size (for example 40, 80, 256, 512mb).
This will automatically create a file for your hard drive and you will only need to install Workbench. The only disadvantage of this method is that it cannot divide the disk into partitions.
2. You can use e.g. the Winuae emulator and do everything there. You create an hdf file, install Workbench and then open the file using the Puae core in Retroarch.
3. The same method as point 2. You create everything in Winuae and save it to a .uae file. This method allows Winuae to save options that are disabled by default in Puae (Retroarch).

When you run the HDF file in Retroarch, there is a "Control Disk" option in the "quick menu". It allows you to load or change a floppy disk.

**Comment by vadosnaprimer** [comment]
Thanks! Sorry but I also mean booting from a floppy drive with a hard drive loaded. A generic example is playing AmigaCD Myst without having WB already on the hard drive. So you'd boot only using disk 2 of workbench, the game would be loaded in the CD drive, you install it on the hard drive, and only after that you can play it.

Having WB already installed on the hard drive obviously makes it possible to also boot from HD and install the game without having to use floppies, but ideally I could have a clean HD. Like with various UAE forks I can mount a user folder for maximum simplicity (which libretro UAE is also capable of, just not exposed to user it seems?), load from a WB floppy and install/play the game right away.

**Comment by sonninnos** [comment]
Amiga by default will boot from floppy if a bootable disk is found even if a bootable hard drive exists, and the same happens with this core. M3U is not currently meant for mixing different types, but nothing prevents doing so with a custom uae conf.

**Comment by vadosnaprimer** [comment]
The issue was created because I was unable to figure out how to do this. If there's a way that works, please tell me how.

**Comment by vadosnaprimer** [comment]
Thanks.
