### ISSUE TITLE
Help starting from a custom HDF file

### ISSUE THREAD

**Issue by mario-f-moreira** [libretro/libretro-uae#663]
I'm trying to start puae with my own custom hdf file and I even try it starting it from USB (like shown) but it never lunches it stays at the kickstart screen.
This UAE file works flawlessly on WinUAE.
I have created the "puae_libretro_global.uae" file and I can attest that it is working since I can load any Kickstart from it as shown but it never pick's up the hardfile:

```
hardfile2=rw,DH0::FNK TECH USB CARD READER 1.00 816820090226,0,0,0,512,0,,uae0
uaehf0=hdf,rw,DH0:":FNK TECH USB CARD READER 1.00 816820090226":\\\\?\\usbstor#disk&ven_fnk_tech&prod_usb_card_reader&rev_1.00#816820090226&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b},0,0,0,512,0,,uae0
kickstart_rom_file=C:\hstwb-installer_1.6.3\User-Packages\Kickstart roms\Kickstarts\A1200.47.111.rom
```
On the settings I have tried all possibilities on the "Global Boot HD" menu: 'files', 'hdf20' .... 'hdf512'

What else can I try?

**Comment by sonninnos** [comment]
This is not a help desk, and the log usually always tells what is wrong.

**Comment by mario-f-moreira** [comment]
> This is not a help desk, and the log usually always tells what is wrong.

Top answer there, thank you so much!
