### ISSUE TITLE
Flash Back Amiga 500 Gotek doesn´t swap disks

### ISSUE THREAD

**Issue by JorgeTbr** [libretro/libretro-uae#664]
Hello guys, I have an Amiga 500 with a Gotek drive. I´ve tried a lot of adf´s but it doesn´t work. The first disk, the introduction works fine, but when it asks the second disk, I select the second adf and no matter I press the mouse, or joystick button, some key, it doesn´t read the second one. I have the same problem with Pinball Dreams too, Does someone have any idea to fix it, or adf´s working fine?

**Comment by sonninnos** [comment]
Gotek is a drive meant for real hardware, thus it has nothing to do with this repo and emulation in general.

**Comment by JorgeTbr** [comment]
I am sorry, I didn´t notice this forum is exclusively about emulation. I have a real Amiga hardware with a Gotek. Thank´s
