### ISSUE TITLE
PATCH (attached): Cherry-picked upstream fix for NTSC bitplane DMA edge case (Demo Reel 3)

### ISSUE THREAD

**Issue by rhester72** [libretro/libretro-uae#666]
The DHAM photo in Newtek Demo Reel 3 is corrupted due to a long-standing issue (and the included patch makes lr-puae the only emulator outside WinUAE that gets it right - it doesn't even work properly on FPGA!).

Two fixes were applied in the WinUAE 5.3.0 cycle to correct this:

https://github.com/tonioni/WinUAE/commit/1ba63e427cc47cdc84539bb7fa7a720d4ca107dd

- In NTSC mode if bitplane DMA last fetch "overflowed" to cycle 0 (which is harmless and normal in overscanned modes) when line was short, it was incorrectly kept allocated for bitplane DMA also during long lines. Long line has 1 more cycle = no overflow. (NewTek demo reel 3 dynamic hires image corruption in NTSC mode, CPU didn't have enough time to update all colors quickly enough. Note: corruption at the bottom in PAL mode is demo bug. NTSC mode also has 2 slightly corrupted lines at the bottom, this is also normal.)

https://github.com/tonioni/WinUAE/commit/dbfb0c8cea6d44b5d0d8f342c1c2158b801ce1f1

- b6 NTSC fix corruption fixed. Fix was incomplete.

The latter required slight adjustment to bitplane_dma_access() for the other patches to function properly.

[custom.c.patch.zip](https://github.com/user-attachments/files/16566969/custom.c.patch.zip)

Sorry, still no git (and thus no pull).  :/

Please note this WILL NOT work on lr-puae 2021/2.6.1, only the master branch.

It's worth noting this only works on NTSC and with cycle-exact (just like the real thing).

**Comment by zzedmore** [comment]
Hi, do you happen to have an Android x64 core with this update applied ? Not sure if we'll be getting any more updates for this core as 5.1.0, 5.2.0 and 5.3.0 were never released.

**Comment by sonninnos** [comment]
Give it a rest. I'm not wasting my time with tiny cherry-pickings which are included anyway once I'll update the whole thing when the time is right.

**Comment by rhester72** [comment]
Wow.  You're welcome.  No worries, no further contributions from me.
