### ISSUE TITLE
Pinball Dream it's unplayable.......due Keyboard not fully works! how i can fix....

### ISSUE THREAD

**Issue by DjDiabolik** [libretro/libretro-uae#676]
i'm on UBUNTU... i have a REAL keyboard attached on my PC but keyboard it's not fully works because on libretro it's some buttons it's setted like a joypad (in my case the arrow keys it's up down left etc o it's select enter it's start etc etc).

How i can use lr-PUAE and use my real keyboard only as keyboard ?

**Comment by sonninnos** [comment]
https://docs.libretro.com/guides/input-and-controls/#cores-with-direct-keyboard-input

**Comment by DjDiabolik** [comment]
> https://docs.libretro.com/guides/input-and-controls/#cores-with-direct-keyboard-input

mmmmmmmmmm it's interesting..... my Retroarch it's currently in italian.... can you suggest where and the exact option i need to activate to use full keyboard ? And i suggestion if i can activate this option by default only when i lauch a amiga games ?

**Comment by sonninnos** [comment]
There is no "option" for the toggle, just a hotkey, and of course this:

![retroarch_2024_11_05_23_25_05_046](https://github.com/user-attachments/assets/32ebe309-a920-4d04-88b9-91f6f7819f31)

**Comment by DjDiabolik** [comment]
> There is no "option" for the toggle, just a hotkey, and of course this:
> 
> ![retroarch_2024_11_05_23_25_05_046](https://private-user-images.githubusercontent.com/45124675/383322137-32ebe309-a920-4d04-88b9-91f6f7819f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzNjUsIm5iZiI6MTczMTA2NDA2NSwicGF0aCI6Ii80NTEyNDY3NS8zODMzMjIxMzctMzJlYmUzMDktYTkyMC00ZDA0LTg4YjktOTFmNmY3ODE5ZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZDFlZmYzYWJkMzgyMDlhNDYwZmI5ZTVhZDdjYjQxYzkxMWZlMzRjYmFlYjcyNmI1ZWE3NGMzZWI1YjQwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QObiCCzDUWB8DBL_wf3qGpvMVL_rTVIiKgwDXOmfOtg)

Oh ok... my gui it's in italian but now i can try to detect better whit this screenshot.

I can also try to set retroarch gui in english instead italian and it's better :)

Thanks for current info.

Now it would be interesting to understand if I can activate this specific option only if I am using the lr-puae core.

**Comment by sonninnos** [comment]
The auto-enable-option has a "detect" mode which only enables it with cores that use the keyboard callback, so yes. And overrides will work regardless.

**Comment by DjDiabolik** [comment]
> The auto-enable-option has a "detect" mode which only enables it with cores that use the keyboard callback, so yes. And overrides will work regardless.

problably i can also use the "Bloc Scorr" or "Scrol Lock" on my keyboard. If i press it it's appears a notification say "Game in first floor" or "Game on seconds flor" very similar to game focus enable or not.
Also in this mode if the games in first floor (sorry for bad traslation.. in italiano dice "Gioco in primo piano" "Gioco in secondo piano" this made keyboard full works and whit games in seconds floor all hotkey back to works also from keyboard.
