### ISSUE TITLE
Minimal Prerequisites to get Z3 functional in P-UAE 2021:)?

### ISSUE THREAD

**Issue by KMFDManic** [libretro/libretro-uae#677]
Hello @sonninnos I've been keeping up on all of the amazing changes you have added to this Repo over the years.  Current commits are fantastic for most platforms I build this Core for.  But, P-UAE 2021 circa is still most optimal for the much lower spec platforms.  I have been hoping to have you shed some light from your experience and expertise of the minimum prerequisites to be able to get Z3 functional on P-UAE 2021, be it via "configuration" or "Core Options".  

"z3mem_size=64MB\n"

and

"cpu_24bit_addressing=false\n"

as an example are what seem to be necessary for the preset config perimeters...

Problem is, the Rebase and Exposing of Z3 have a different coding structure than that of 2021.  IE:

mem_size += (float)(currprefs.fastmem[0].size / 0x100000);
mem_size += (float)(currprefs.z3fastmem[0].size / 0x100000);

where, in puae, they would seem to point to 

mem_size += (float)(currprefs.fastmem_size / 0x100000);
mem_size += (float)(currprefs.z3fastmem_size / 0x100000);

I was able to get Z2, CPU, other Options working on P-UAE 2021.  But, there still seems to be a missing linkage to Z3...possibly via
memory.c, glue.c, main.c?  

I did several different compiles, and it is primarily after the Rebase, I am able to actually see Z3 show up in "status bar" confirming Z3 is being utilized.  Something is missing in 2021 code base that allows me to do the same.  So, thanks so very much in advance, if you are able to shed light on this!

**Z3 Expose**

https://github.com/libretro/libretro-uae/commit/ade9032cd8ac001c907b2b689832434d544f07e2

**Rebase 4.5.0**

https://github.com/libretro/libretro-uae/tree/774bb11114993ec9f20a89b46058048f31ee9443

If you need any other information, please let me know:)  

But, primarily hoping to be able to adapt Z3 to P-UAE 2021 code base, to help lower spec.  Thanks again, and keep up the phenomenal work!!!

**Comment by sonninnos** [comment]
I have absolutely no idea what this is about. The Z3 option works just fine here in the 2021 core too.

**Comment by KMFDManic** [comment]
@sonninnos sorry for any confusion. Do you have perhaps a commit point for 2021 where you know it (Z3) would work?  It didnt work for me before the rebase but worked fine after. But after the rebase, the core is too slow for lower spec.

**Comment by KMFDManic** [comment]
![20241103_130415.jpg](https://github.com/user-attachments/assets/9e9faf77-3a5f-4eae-9bb8-795d47baeef0)

I can run Settlers 3 with same Z3 Core Option before and after rebase.  But it only seems to detect the additional Z3 ram after Rebase.  So that is why I made this post to inquire as to what may possibly be missing.

Thank You:)

**Comment by KMFDManic** [comment]
@sonninnos I believe the issue was in Master which includes rebase...and is what threw me off. I see you reverted the rebase for 2021. I apologize for wasting your time and will retest on that coding structure.

**Comment by sonninnos** [comment]
Yes, because the 4.x update caused a big performance impact, and thus the core was split into two branches, which both have mostly the same features libretro-wise.

**Comment by KMFDManic** [comment]
> Yes, because the 4.x update caused a big performance impact, and thus the core was split into two branches, which both have mostly the same features libretro-wise.
> 

I appreciate your feedback on this. And, keep up the fantastic work!:)
