### ISSUE TITLE
68030+ performance 

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#679]
Hi,
I am playing with The Settlers (hdf version), with 2Mb chip ram and 8MB fast ram (the game is hungry for all sounds and music). 
Stupidly, the game also requires 68030+ for maximum World size (8). 
When selecting 68030 or 40, the music starts to slow down, the emulation is struggling.
When reverting back to 68020, everything is fine.
This doesn't change whether you select cycle-exact or normal.

Anything wrong with the 030 emulation (MMU, caches...)?

Many thanks in advance and best regards

**Comment by sonninnos** [comment]
No problems here. Both cycle-exact and normal run at full speed, but cycle-exact clearly needs more juice.

**Comment by Vweber73** [comment]
Thanks.
I'm running puae on Android, but that's a Samsung Z fold 6, quite a powerful device. Yet the intro music has some slowdowns, but only at times, not always, which makes me think that it is not a power issue....?

Best regards

**Comment by Vweber73** [comment]
I see...
Thanks and cheers
