### ISSUE TITLE
PUAE core Steam Deck corrupt graphics

### ISSUE THREAD

**Issue by leemm** [libretro/libretro-uae#681]
For some reason I see corrupt graphics everywhere through retroarch, I can't see why.

I've tried:

- Different AFD files
- different rom images
- They display fine in fs-uae.

Core version 4.9.1

A couple of examples here. Apidya and Captain Dynamo.

Any ideas?

![20241205111202_1](https://github.com/user-attachments/assets/be92bd90-434b-4171-9618-3ca081a3cc86)
![20241205110451_1](https://github.com/user-attachments/assets/336c1650-c50f-4470-bb7f-308102834605)

**Comment by sonninnos** [comment]
First of all why use that ancient 4.9.1. Never remember seeing anything like that even with that version tho.

**Comment by leemm** [comment]
> First of all why use that ancient 4.9.1. Never remember seeing anything like that even with that version tho.

You were right. When I set up Emudeck this is the version of the core that was installed.
I switched to puae2021 and it works absolutely fine now.

**Comment by sonninnos** [comment]
That is 2.6.1 which is even more ancient than current 5.3.0. Only regarding emulation accuracy that is, since libretro features are the same in both branches.
