### ISSUE TITLE
Vsync issues in Linux build.

### ISSUE THREAD

**Issue by modeler** [libretro/libretro-uae#8]
While running under X in Linux, the core achieves perfect vsync in full-screen mode but starts dropping frames after a few seconds while running in a window. Other cores (Genesis Plus GX, FBA and such) do not suffer from this.

**Comment by sonninnos** [comment]
Is this still an issue?

**Comment by rsn8887** [comment]
I will assume this is not an issue anymore. Please feel free to re-open or create a new issue if you still have a problem.
