### ISSUE TITLE
Compatibility Issues with UAE config file

### ISSUE THREAD

**Issue by Papermanzero** [libretro/libretro-uae#85]
Tested following games and they do not boot:
North & South
The great Giana Sisters

**Comment by sonninnos** [comment]
Could you find out on which version of standalone UAE they do work?

**Comment by DamsRoxxx** [comment]
No-Intro version of these games worked for me with the latest version of the core on windows.

```
Great Giana Sisters, The (Europe).ipf
North & South (Europe) (En,Fr,De,Es,It).ipf
```

**Comment by Papermanzero** [comment]
Same verified the games with no-intro
2945_The Great Giana Sister
0194_North and South.

But they dont boot. Well giana boots however it freezes on the level inteo screen

**Comment by rsn8887** [comment]
The ipf 2945_The Great Giana Sister crc 45a44d4e
works just fine here on MacOS, using default core options. I was able to start the game and play just fine.

Are you using default core options? If not please try (just rename or delete your core-options file).

**Comment by rsn8887** [comment]
This goes for all issues: Please always state your system, core version, details of options you tried etc.

**Comment by Papermanzero** [comment]
Always using default options. I will try to update the core. I have here the windows version

**Comment by rsn8887** [comment]
Are you using CapsIMG library from here? That's what worked for me on MacOS:
https://fs-uae.net/download#plugins

**Comment by Papermanzero** [comment]
Yes, I did everything which is in the tutorial.
Kickstart roms with the correct crc are in the sys folder. IPF library in the root of retroarch.
Turrican was i.e. working without issue.

I updated now to the latest version. Now nothing is working anymore.
I only get the Kick 1.3. boot screen.

**Comment by sonninnos** [comment]
> IPF library in the root of retroarch.
rsn8887 just said the new location is system, not root.

**Comment by Papermanzero** [comment]
Yes, I shifted there. So with the latest release, North and South is working.
However The Great Giana Sisters is still freezing at the "Get Ready Giana" screen.
Whole Retroarch is frozen (not even the menu can be opened)

**Comment by Papermanzero** [comment]
Ok. I found the root cause. It is the uae config file.
With following settings the game does not boot:

ntsc=false
gfx_height=256
gfx_width=320
gfx_lores=true
gfx_linemode=none
gfx_center_vertical=simple
gfx_center_horizontal=simple
kickstart_rom_file= \system\kick34005.A500
floppy0= \2945_The Great Giana Sisters.ipf

So. The issue is more related to config handling.
I use the uae config because libretro is missing the gfx_width and gfx_height feature.
It is a useful feature to get the right pixel ratio.

**Comment by sonninnos** [comment]
PAL + lo-res mode + crop overscan is already exactly that, 320x256.

**Comment by Papermanzero** [comment]
Yes, but I am currently using 320x240. Reason: The aspect ratio.

Amiga games were meant to be played in 4:3 in NTSC mode. However the libretro uae core uses 1:1 pixel ratios, which means if you are using 320x256 u are not getting 4:3 screen resolution. 
If you are changing to the NTSC resolution 320x200 (which is NTSC) you are also not getting a 4:3 screen.

So to get to a real Amiga screen I am using 320x240 and I am using to image_Adjusment shader to scale the picture vertical by 40 pixels. In this manner, I am almost getting the perfect amiga picture.

**Comment by sonninnos** [comment]
There are plenty of PAL games that use the whole area though. But those that were crammed to work on all continents tend to be squished on PAL, yes.

Are you sure that particular IPF works in some other emulator?

First IPF I found has CRC eb8995ac and the result is:
![retroarch_2019_09_01_21_11_01_887](https://user-images.githubusercontent.com/45124675/64080491-96c81d00-ccfd-11e9-9427-be125b65414d.png)

**Comment by Papermanzero** [comment]
The aspect ratio is not correct, but i see what u mean. 
To come back to the original issue, i would propose to open another issue for the graphical behavior and to change the title here to uae xonfig file compatibility.
If the uae file does not define certain settings, the default settings from the core should be used.

**Comment by sonninnos** [comment]
I created a conf that has nothing else except the kickstart_rom_file definition, and the kickstart boots. What am I missing here..?

**Comment by rsn8887** [comment]
Thanks for finally figuring out the issue.

Concerning @Papermanzero’s statement about resolution: Amiga games were not “meant to be played in 4:3 NTSC mode” who told you such nonsense? Original 1084 monitors had all kinds of different aspect ratios depending on monitor settings, and often very large black borders on the bottom of the screen and smaller borders on the left and right.

I agree though it would be cool to be able to hide more of the borders in some games that use only a small portion of the screen. Some games only use 320x200 even.

**Comment by Papermanzero** [comment]
Every documentation and discussion explains the 4:3 scenario:

http://www.lemonamiga.com/forum/viewtopic.php?t=14400&sid=4ca93d6e640d92af85554063b429f547

http://coppershade.org/articles/More!/Topics/Correct_Amiga_Aspect_Ratio/

**Comment by rsn8887** [comment]
One link is the same as mine and the other links you posted also explain a 1:1 or 1:04:1 pixel aspect ratio, so that’s the same as what I posted earlier.

Of course you can already force any aspect ratio you want using settings->video->custom aspect.

**Comment by Papermanzero** [comment]
This is what I do. Using the Aspect Ratio correction in the Video Settings + the image adjustment filter corrects the current picture. I can even recognize the correct picture size because circle graphics are real circles (and not oval) and squares are not squashed.

Amigalove explains it the best way, I think. 
It is clear that 320x200 for NTSC are not 4:3 aspect ratio.
So to get the "real" image you have to stretch the picture.
PAL games on the other hand needs to be squashed due to the 320x256 pixel amount which needs to fit to 4:3.

**Comment by Papermanzero** [comment]
Btw I compared your photo with my image settings.
Just have a look.

This is the image with default settings:
![The Great Giana Sisters-190903-161309](https://user-images.githubusercontent.com/10263536/64181051-1a9d1900-ce66-11e9-997e-a676a3564d05.png)

You can recognize that the picture is just to squashed. Moreover the aspect ratio is not correct.
So in the next step I changed the aspect to 4:3
![The Great Giana Sisters-190903-161328](https://user-images.githubusercontent.com/10263536/64181166-4ae4b780-ce66-11e9-91be-de9f35dc3fa9.png)

Now the picture is now even more squashed, but the aspect ratio is right. As next step I used the image adjustment shader with a modifier of 14 for the overscan y percentage and a y shift of -1.
The result is a "real" amiga image which equals your photo.
![The Great Giana Sisters-190903-161449](https://user-images.githubusercontent.com/10263536/64181341-939c7080-ce66-11e9-97d9-e4a5111e8f93.png)

**Comment by zoharxero** [comment]
> Yes, I shifted there. So with the latest release, North and South is working.
> However The Great Giana Sisters is still freezing at the "Get Ready Giana" screen.
> Whole Retroarch is frozen (not even the menu can be opened)

I had the same problem with Giana Sisters  as hdf, using ipf with default settings works fine. By trial an error found that using a .uea config with show_leds=true there are no freeze, If set as false the game freezes again,  and depending the kickstart it can be also at the title screen.

**Comment by sonninnos** [comment]
I've made an edit to the way custom configs are handled, and I'll soon PR it.

The idea is that the launched uae config will be appended to the default config, overriding all default duplicate rows. Since it appears that the duplicate rows don't need to be removed for the later ones to work, it is pretty simple.

**Comment by DamsRoxxx** [comment]
> 
> 
> > Yes, I shifted there. So with the latest release, North and South is working.
> > However The Great Giana Sisters is still freezing at the "Get Ready Giana" screen.
> > Whole Retroarch is frozen (not even the menu can be opened)
> 
> I had the same problem with Giana Sisters as hdf, using ipf with default settings works fine. By trial an error found that using a .uea config with show_leds=true there are no freeze, If set as false the game freezes again, and depending the kickstart it can be also at the title screen.

Effectively, there is a bug with show_leds parameter. I've seen it with Rick Dangerous 2. I wrote a comment about it in libretro.c last year but I've not investigated...

https://github.com/libretro/libretro-uae/blob/943e1f20e04bf690a3ec8f9bae1b333ae4037421/libretro/libretro.c#L1965

```
// FIXME : Bug if show_leds is set to false
// If this parameter is set to false or not specified (default false) Rick Dangerous 2 (adf or whd version) hang when selecting level.
// But no impact since the parameter in RetroArch configuration overload this setting : If Leds is set to none, the led won't be drawn on screen and it works...
```

We should open a new issue
