### ISSUE TITLE
Possibility to load a normal HDF file ?

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#86]
I wondered if it's possible to load a HDF file with ClassicWB on it ? So we can just boot up and choose from several WHDLoad games installed on the Harddrive. At the moment I think it only allows single game HDF's and it looks for the file 'game.slave'.

**Comment by sonninnos** [comment]
rsn8887 already enabled that. You just need to disable the WHDLoad.hdf in core options.

**Comment by MajorWilly** [comment]
Is there anything else i'm missing ? I've turned off the WHDload option and set it to A1200 but I just get the red 'Software Failure' when booting the HDF. It works in UAE4Arm.

Are there any extra kickstarts that I need to put in the System directory apart from the 3 required ones ?

**Comment by sonninnos** [comment]
I didn't do anything else. Try with another hdf maybe?

In the end the temporary uae that is created looked like this:

> cpu_type=68ec020
chipmem_size=4
fastmem_size=8
chipset=aga
ntsc=false
cpu_speed=real
cpu_compatible=true
sound_output=exact
sound_stereo_separation=5
sound_interpol=anti
sound_filter=emulated
sound_filter_type=standard
floppy_speed=100
floppy_volume=80
immediate_blits=false
gfx_center_vertical=none
gfx_center_horizontal=none
cycle_exact=true
gfx_lores=false
gfx_linemode=double
show_leds=true
kickstart_rom_file=c:\tools\retroarch\system\kick40068.A1200
hardfile=read-write,32,1,2,512,s:\emu\amiga\hdf\System.hdf

**Comment by MajorWilly** [comment]
I'll try a fresh one later. I think the problem maybe that mine is formatted to the PFS3 filesystem ?

**Comment by sonninnos** [comment]
The UAE version is pretty old so It would not surprise me.

**Comment by MajorWilly** [comment]
Yep. The PFS3 filesystem was the problem. I've got it working now. Cheers guys.
