### ISSUE TITLE
Changing device type to Joystick/CD32 disables mapped controls + Question

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#88]
I currently have the 'Controls - Device Type' set to RetroPad. All my custom mapped keys (in Options) like Virtual Keyboard, StatusBar, Swap Mouse/Joystick etc. work correctly. If I change the Device Type to Joystick or CD32 then none of those custom control options work.

Do you happen to have a BLANK 2gb HDF (FastFileSystem) that works with this core that you could attach please ? Everytime I create one it either says it's only 1gb or doesn't work at all. That's if it's even possible with this core.

**Comment by sonninnos** [comment]
I guess there are a few buttons to spare, but the point of the CD32 pad was to not be like RetroPad, because in CD32 there are no keyboard and mouse, and the games that support a CD32 pad have no need for the extra mappings.

**Comment by MajorWilly** [comment]
Not sure if my post was clear. For instance, the defaults for L is F10 (Statusbar) and R is F11 (VKeyboard). If you change the Controls menu Device Type to Joystick then L & R don't do anything.

**Comment by sonninnos** [comment]
Just use RetroPad. Joystick is supposed to be a stick with only one button.

**Comment by MajorWilly** [comment]
Yeah, I currently use RetroPad. Just wondered why Joystick was selectable in the Controls. Thanks.

Do you or @rsn8887 have a BLANK 2gb HDF (FastFileSystem) ? I'm not sure if this core can actually use them as i've only been able to create a 1gb compatible HDF.

**Comment by sonninnos** [comment]
I created a 2GB HDF with WinUAE and it seems to work. I didn't try to boot from it or anything.
Only added this to my config:

> hardfile2=rw,DH3:S:\emu\amiga\hdf\temp.hdf,0,0,0,512,0,,uae3

**Comment by MajorWilly** [comment]
Thanks for trying. I'll just use two 1gb HDF's with ClassicWB and games/demos on each one.

I'll close this. Keep up the good work !
