### ISSUE TITLE
[Request] More Model Presets (in QuickMenu) or Seperate Memory Options & Frameskip Option

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#89]
Is it possible to have seperate memory options ? Some A500 games (I think Technocop is one) require only 512K Chip memory.

> Simulate an Amiga 500 with OCS chipset, 1MB of RAM and 1.8MB of slow memory expansion (bogomem).

This seems a strange preset ?

**Comment by sonninnos** [comment]
Oh, forgot to update the README when I changed the A500 memory settings to be 0.5MB Chip + 0.5MB Slow like usual.

But sure if some games do not work with the extra ram then we should add an option to disable it.

**Comment by MajorWilly** [comment]
Would it also be possible to add the Frameskip option to the QuickMenu ? (gfx_framerate=2 ?) So that it reduces it to 25fps. You probably wouldn't notice it as a lot of games are 25fps anyway and it will help people with slow devices.

**Comment by sonninnos** [comment]
Sure, why not.

**Comment by MajorWilly** [comment]
@sonninnos Your updates amaze me ! Thanks a lot ! :+1:

**Comment by sonninnos** [comment]
Frameskip will have some problems with cycle_exact=true, as in it will get reseted on startup, but works afterwards from core options..
