### ISSUE TITLE
Optimization of auto generated .uae files to help stubborn AGA games, etc:)

### ISSUE THREAD

**Issue by KMFDManic** [libretro/libretro-uae#90]
With the lack thereof Dynamic Recompiler, gets truly suffer on especially A1200.  Both of you, @rsn8887 and @sonninnos have done some great commits of recent, for the Core.  I work in the Mini Classic community, for NES/SNES/Playstation Classics.  We touched up P-UAE last year.  Larger keyboard, refined controls, 2 player mode active, and so on.  You guys did a phenomenal job refining things in a much more stable fashion!  With our 2 player mode activate, mouse connectivity would sometimes cut out.  You can see the way we implemented the coding here:

https://github.com/KMFDManic/libretro-uae

qclart and madmonkey are two people I collaborated with in fixing things up.  

In any case, my idea is this:)  The auto generated .uae files for A500, A600, A1200 can certainly use some touching up to be more optimal.  Qclart was great enough to very extensively test and get together some of the ones at the following link.  Analyze and survey the AGA ones, particularly the game specific ones like Agony, Aladdin, etc.  If we can incorporate more optimal .uae auto generations, with better settings, especially for AGA, that would be fantastic.  For the record, Agony and Aladdin are quite a deal more playable with the game specific ones!  

I am thinking of going one of two potential routes with this...Either directly make the .uae configurations more optimal and/or try to implement Core Options to account for the additional .uae configuration settings that are not within the context of said Core Options.  

Here ya go:

https://hakchi.net/KMFDManic/NESC-SNESC-Modifications/KMFDManic-S-NESC-PSC-Cores_7-23-19/_km_Xtras/AMIGA/AMIGA_Template.7z

**Comment by rsn8887** [comment]
The core already supports loading custom .uae files. I don't think anything more is needed.

**Comment by KMFDManic** [comment]
@rsn8887 

I didn't intend to have everyone using the same settings, in the least.  It was more so geared towards the more optimal configuration, via Core Options/Overrides..which is exactly how things played out:)

Essentially, what you guys just added for the latest commits, is what I was going for.  I can now run the AGA games way way way way better.  Some of the options you implemented include the frame skips, such as in the custom .uae files I had linked to above.  Exceptional work.  Glad it worked out:)  Only thing we need now, which might not be an easy task, is dynamic recompiler!  But, glad, as it stands.  

I will continue to test the commits.  But, as of right now, very very impressed and happy with the results of a Core that has needed a bit of TLC for quite some time!  Thanks:)
