### ISSUE TITLE
On-screen drive lights

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#95]
Is there anyway you could remove all the drive lights that don't actually do anything or not in use ? At the moment I can see 3 to the left of the Power LED. I think one is for FPS, don't know what the other 2 are for. There are 2 to the right of the Power which I think are for Harddrive and CD but they are always there even when not in use. Just a thought as it would cut off less screen when using the normal status bar.

@rsn8887 Is the Android build broken again ? It hasn't built since 30th 14:32. Latest commit a8c8053 Maybe they've just slowed the buildbot for Android even more.

**Comment by sonninnos** [comment]
For the time being I'm not going to touch the default UAE OSD. Too much things to worry and too little pay-off in saved screen estate.

**Comment by MajorWilly** [comment]
No worries ! Was only a suggestion.
