### ISSUE TITLE
Android build hasn't built lately

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#96]
Just curious at how long or how many times a day the buildbot normally builds the Android version ?. The Windows version builds constantly. The last time it built was 30th 14:32. Latest commit a8c8053 I just wondered if it might be broken again. Maybe they've just slowed the buildbot for Android even more.

**Comment by rsn8887** [comment]
Once per day.

**Comment by rsn8887** [comment]
You can also always check for yourself, just join https://discord.gg/D6Qzpm and check the #buildbot channel at the top. It says whether a build succeeded or failed.

**Comment by rsn8887** [comment]
I don't see any failed builds for Android recently. It looks like a new release cycle was started which will keep the buildbot from building a new nightly until the stable has been built AFAIK.

**Comment by rsn8887** [comment]
I think it just build now.

**Comment by MajorWilly** [comment]
Yeah, it's there now, 25 hours ! It used to build twice a day. I'll close this now.
