### ISSUE TITLE
A600 WHDLoad support

### ISSUE THREAD

**Issue by DamsRoxxx** [libretro/libretro-uae#98]
Hi @sonninnos 

In #92 the default rom for A600 was changed to Kickstart 2.05 (37.300) :

|Name|Description|System|MD5|
|---|---|---|---|
|kick37300.A600|Kickstart v2.05 (Rev. 37.300)|Amiga 600|fa4acc75b49e880679fe02716af24d71|

It's the original A600 rom but it is incompatible whith WHDLoad.

Could you please re-add a configuration with the Kickstart 3.1 rom for A600 (40.063) :

|Name|Description|System|MD5|
|---|---|---|---|
|kick40063.A600|Kickstart v3.1 (Rev. 40.063)|Amiga 600|e40a5dfb3d017ba8779faba30cbd1c8e|

This configuration could be named 'A60031' for exemple.

Alternatively, the 2.05 configuration could be named 'A600ORIGINAL' and the 3.1 'A600' as before.

Regards

**Comment by MajorWilly** [comment]
I would welcome this as well. On 68020 WHDLoad, a lot of games play way too fast which requires you to use Cycle Exact to play them at the correct speed. But this uses a lot of processing power. Using 68000 A600 the games play at the correct speed and no need for Cycle Accuracy.

**Comment by sonninnos** [comment]
Hmm, I have that Kickstart 2.05 in a real A600 and WHDLoad works just fine, but whatever, let's change it back.

**Comment by MajorWilly** [comment]
I just looked on the ClassicWB site and there are two versions for A600 -

http://classicwb.abime.net/classicweb/requirements.htm

One for 2.0 roms (Original A600) and another for 3.0 roms. I'm not actually sure what the benefit is with the 3.1 ROM expansion because both are ECS only.

**Comment by sonninnos** [comment]
At least the 3.1 boots much quicker.
